### ISSUE TITLE
How to use ZXing.EncodeHintType.ERROR_CORRECTION?

### ISSUE THREAD

**Issue by PeterConchaR** [micjahn/ZXing.Net#1]
Hi Michael, with my colleagues we want to use: 
ZXing.EncodeHintType.ERROR_CORRECTION
But we do not find documentation on this point

Could you help us? :) #ZXing

**Comment by micjahn** [comment]
sample code:
```
var writer = new BarcodeWriter
{
   Options = new ZXing.QrCode.QrCodeEncodingOptions
   {
      ErrorCorrection = ErrorCorrectionLevel.H
   }
};
```
