### ISSUE TITLE
New home?

### ISSUE THREAD

**Issue by Redth** [micjahn/ZXing.Net#10]
I know this was a mirror initially of the subversion repo on codeplex, but given codeplex is shutting down, do you plan on making this repo the actual source home? 

Love that it's here as I can submodule it now for my library!

**Comment by micjahn** [comment]
Probably yes. At least if codeplex is switched to readonly. At the moment I care both like main project pages. Sources are in sync and I look at both sites into the reported issues.

**Comment by micjahn** [comment]
Now it's official. The codeplex page shows "The project has moved..."
