### ISSUE TITLE
Could not load assembly Zxing Version=0.16.2.0

### ISSUE THREAD

**Issue by CHLINDE** [micjahn/ZXing.Net#101]
I permanently get the error message "Could not load assembly 'zxing, Version=0.16.2.0..." on Xamarin Forms.
I installed the package via NuGet-Package administration tool and only added the following:
using ZXing;
and
IBarcodeReader reader = new BarcodeReader();
Is there any solution to fix this problem?

**Comment by micjahn** [comment]
Are you using .Net Standard 2.0?

**Comment by CHLINDE** [comment]
Yes I do. Geht’s auch auf deutsch?

Von: Michael Jahn <notifications@github.com>
Gesendet: Montag, 9. April 2018 19:57
An: micjahn/ZXing.Net <ZXing.Net@noreply.github.com>
Cc: CHLINDE <CHLINDE@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [micjahn/ZXing.Net] Could not load assembly Zxing Version=0.16.2.0 (#101)


Are you using .Net Standard 2.0?

**Comment by micjahn** [comment]
Geht auch auf Deutsch, jedoch können dann einige nicht mehr mitlesen. Deshalb ist Englisch prinzipiell besser.
Ich vermute, es wird das gleiche oder ein ähnliches Problem sein, wie hier:
https://github.com/micjahn/ZXing.Net/issues/100
und hier
https://github.com/Redth/ZXing.Net.Mobile/issues/578
Sobald ich es schaffe, eine neue Version zu bauen, welche .Net Standard 2.0 direkt unterstützt, wird
es wohl funktionieren.
Im Moment kannst Du wohl nur die Worksarounds mit den angepassten Projektdateien, wie in
https://github.com/Redth/ZXing.Net.Mobile/issues/578
beschrieben, probieren.

**Comment by micjahn** [comment]
version 0.16.4.0 with .net standard 2.0 support is out

**Comment by CHLINDE** [comment]
Sorry for reactivating this thread,, but I get the same message with v0.16.4.0.

**Comment by micjahn** [comment]
Can you provide a sample project which I can use to reproduce the problem?

**Comment by wayne-o** [comment]
I am getting this too

**Comment by samhouts** [comment]
FYI: https://github.com/xamarin/Xamarin.Forms/issues/5294

**Comment by akatsukle** [comment]
I'm having the same issue with v0.16.5 on Xamarin.
The workaround in xamarin/Xamarin.Forms#5294 fixes the issue.
(Don't forget to clear bin/obj folders if the issue persists)

@micjahn Did you have the time to try PureWeen solution on the Xamarin thread?
