### ISSUE TITLE
Skia renderer performance

### ISSUE THREAD

**Issue by jackbond** [micjahn/ZXing.Net#103]
After I did the renderer for Magick.Net, I figured I'd look at the performance of the Skia renderer which was quite a bit slower than the others. I tried to simply pass Skia the black and white image format data that the MagickImage constructor accepted, but it didn't recognize the format. I liked the approach, and then I realized that passing Skia a 1 bit grayscale png might work and be really fast. So what I did was write an extension method for the BitMatrix class that returns a byte array of png data. Then in the SKBitmapRenderer I simply called SKBitmap.Decode with that png data. For the 600x600 Qr codes, I saw a 50x performance improvement. I realize this approach may not work for barcode formats which support text, but for Qr, it's great. I tried to create a pull request for this, but I was unable to get the latest code to build on my machine.

I've attached a solution with the code, and a couple unit tests. FYI, all of the code is original, although the Adler32 and Crc32 classes were based on well known algorithms.

[bitmatrixextension.zip](https://github.com/micjahn/ZXing.Net/files/1900642/bitmatrixextension.zip)

**Comment by jackbond** [comment]
One extra note, I did this as an extension method, but I think it would be optimal as a method on the BitMatrix class. Having direct access to BitMatrix's private bits collection might allow for further optimization. Thanks again.

**Comment by micjahn** [comment]
There is an optimization made on March 09, 2020 which improves the rendering speed dramatically. I will close this issue here for now. Please reopen it if you have further optimization.
