### ISSUE TITLE
当图片中有多个barcode时reader.DecodeMultiple的方法好象还是只拿到一个

### ISSUE THREAD

**Issue by windbell2** [micjahn/ZXing.Net#104]
尝试在图片中加入多个的barcode图形
然后使用reader.DecodeMultiple方法，却只能获得1个result,
调整barcodes的位置后，能识别多个，但还是有几个未能识别，
不知我需要怎么做，才能让DecodeMultiple得到精确的结果
--------------------------------------------------------

Try adding multiple barcode graphics to the picture
Then using the reader.DecodeMultiple method, we can only get 1 result.
After adjusting the location of barcodes, we can identify more than one, but there are still several unidentified ones.
I don't know what I need to do to make DecodeMultiple get accurate results.

`

            IBarcodeReader reader = new BarcodeReader();

            var barcodeBitmap = (Bitmap)Image.FromFile("d:\\a.png");

            var result = reader.DecodeMultiple(barcodeBitmap);

            return result;
`

**Comment by micjahn** [comment]
zxing tries but doesn't guarantee to find every barcode inside an image.
If you only want to find QR codes you can try to set the PossibleFormats property to QR_CODE only. In that case inside of DecodeMultiple zxing uses another multi barcode finder implementation. In all other cases you can try to set TryHarder = true or you implement another multi barcode finder which better fits your needs. Current implementations which are used implicit by BarcodeReader are QRCodeMultiReader and ByQuadrantReader.
