### ISSUE TITLE
QR Code + CODE 128

### ISSUE THREAD

**Issue by alb3ric** [micjahn/ZXing.Net#108]
Hello,

I have an image with a QR Code and CODE_128 barcode. If I assign Options.PossibleFormat with  { BarcodeFormat.CODE_128, BarcodeFormat.QR_CODE }, the CODE_128 is found but not the QR. If i set only QR_CODE the QR_CODE is found.

I'm decoding this way : 

```
var reader = new BarcodeReader();
reader.Options.PossibleFormats = new BarcodeFormat[] { BarcodeFormat.CODE_128, BarcodeFormat.QR_CODE };
reader.Options.TryHarder = true;
reader.AutoRotate = true;
reader.TryInverted = true;
var results = reader.DecodeMultiple(bitmap);
```

Do you have any explanation ? Is it because the TryHarder is not apply because it is finding the CODE_128 ?

Thanks for your help.

Best regards,

**Comment by micjahn** [comment]
If only QR code is enabled the barcode reader internally uses the class QRCodeMultiReader. If other formats are set too the reader uses the class GenericMultipleBarcodeReader. Both of them are using different search methods which gives different results.

**Comment by alb3ric** [comment]
Thanks for the answer.

So the solution is that I do a pass with CODE_128 and second one with QR_CODE ?

**Comment by micjahn** [comment]
There is no general solution. It depends on the goals and dependencies of your project.
If you want to make sure that you get the best results and if you have enough cpu cycles left you should do it that way.
If you can get a constantly stream of captured images from a webcam there might be a better way with processing the next image.
