### ISSUE TITLE
NullReferenceException when ByQuadrantReader fails to decode

### ISSUE THREAD

**Issue by kent37** [micjahn/ZXing.Net#11]
`ByQuadrantReader` should check for `result == null` at [line 103](https://github.com/micjahn/ZXing.Net/blob/master/Source/lib/multi/ByQuadrantReader.cs#L103). If the last decode attempt fails, this line throws `NullReferenceException`.

**Comment by micjahn** [comment]
Thanks for reporting. Fix comitted.
