### ISSUE TITLE
QR code decode fails if angle not 0, 90, 180, or 270.

### ISSUE THREAD

**Issue by douglaskbell** [micjahn/ZXing.Net#110]
I implemented ZXing.Net 0.16.4 as of May 2018.
It reads QR code perfectly, but only if at rotational angle of 0, 90, 180, or 270 degrees (plus or minus a 'tad').

Is ZXing QR decode not rotation tolerant, or did I do something wrong?

doug.Bell@Inscripta.com

**Comment by micjahn** [comment]
ZXing isn't perfect and I don't think that you made something teribble wrong.
Please take a look into the black box test cases for QR codes in the source code repository. They show some rotated samples which should work.
