### ISSUE TITLE
Data Matrix Whether to support gs1 standard

### ISSUE THREAD

**Issue by MarkLogZhu** [micjahn/ZXing.Net#111]
Data Matrix Whether to support gs1 standard，If it is supported, what to do?
Here is my code：
public Bitmap getDataMatrix(string inputData, int barcodeWidth, int barcodeHeight) {
   

    DatamatrixEncodingOptions options = new DatamatrixEncodingOptions() {
        Width = barcodeWidth,//宽度
        Height = barcodeHeight,//高度                
        Margin = 0,
        PureBarcode = true,

        SymbolShape = SymbolShapeHint.FORCE_SQUARE
    };
    //
    options.Hints.Add(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
    //options.Hints.Add(EncodeHintType.MARGIN, 1);
    BarcodeWriter writer = new BarcodeWriter() {
        Format = BarcodeFormat.DATA_MATRIX,
        Options = options
    };
    var img = writer.Write(inputData);

    return img;

}

**Comment by micjahn** [comment]
Please take a look into the wiki:
https://github.com/micjahn/ZXing.Net/wiki/Generating-GS1-DataMatrix-and-GS1-Code128-barcodes

**Comment by MarkLogZhu** [comment]
Thank you very much for your prompt reply。If it is dynamic data When does the second separators need to be added?

**Comment by micjahn** [comment]
I strongly recommend reading the official specifications for GS1 barcodes:
https://www.gs1.org/barcodes/2d
There is everything explained which is important for the GS1 standard.
