### ISSUE TITLE
About Generating Data Matrix Coding Issues

### ISSUE THREAD

**Issue by MarkLogZhu** [micjahn/ZXing.Net#113]
I'm glad you had previously responded to my method for generating GS1 Data Matrix, but I used the QR code generated from your answer. When scanning QR codes, there will be a symbol in front of the displayed text data. I don't know if I'm really Success has generated GS1 Data Matrix。What method can I use to verify success?

Generate barcode：
![3le4qkmu_ u vj7 h ik](https://user-images.githubusercontent.com/24911132/40633277-46b8ad3a-6321-11e8-9c58-2ded98aa9fd8.png)

Scan results：

![02](https://user-images.githubusercontent.com/24911132/40633310-9450906c-6321-11e8-86a8-782225dfa3f2.png)

**Comment by micjahn** [comment]
You can try an online decoder like this one:
https://online-barcode-reader.inliteresearch.com/default.aspx

The symbol in the front might be correct because you have to process the group separator characters yourself (the "(char)29" parts in the wiki).

**Comment by MarkLogZhu** [comment]
I'm sorry to disturb you again。My customer feedback is right after the bar code reads, there is "]d2" in front, and the data I generated is not. I want to know if your “(char) 29” is equivalent to  "]d2"。If not, can I add it directly to the data? For example, "(char) 29 +]d2+ data"

**Comment by MarkLogZhu** [comment]
I'm sorry to disturb you again。My customer feedback is right after the bar code reads, there is "]d2" in front, and the data I generated is not. I want to know if your “(char) 29” is equivalent to  "]d2"。If not, can I add it directly to the data? For example, "(char) 29 +]d2+ data"
