### ISSUE TITLE
URL Length

### ISSUE THREAD

**Issue by mbowles201** [micjahn/ZXing.Net#114]
I have been unable to find a maximum length of a URL for a QrCode ro what settings are needed for it.  It seems to become an invalid code at about 34 characters.

**Comment by micjahn** [comment]
Why do you think that it becomes invalid? Are there any error while scanning the code?

**Comment by mbowles201** [comment]
Scanning with a mobile device and once I hit that character count, I get an error on the device that says invalid barcode.   Are there any settings changes that I need to make to allow for longer URL's?

**Comment by mbowles201** [comment]
It will not allow for an image to drop here.   Site can't process file type message.  Where can I send it?

**Comment by micjahn** [comment]
You can find my email address here: https://github.com/micjahn

**Comment by mbowles201** [comment]
Sent.  Any thoughts?

**Comment by micjahn** [comment]
The qr code is correct and can be successfully decoded with the WinForms demo:
https://github.com/micjahn/ZXing.Net/issues/114#issuecomment-393034175
I think the error is in the scanning app which you are using.
