### ISSUE TITLE
Can't generate QR Code with ASP.NET Core

### ISSUE THREAD

**Issue by Elsassmania** [micjahn/ZXing.Net#118]
I'm trying to generate a QR Code with ASP.NET Core but nothing happen.

I used this [link](https://code.msdn.microsoft.com/ZXINGNET-QRCode-Generator-05128cfb) to set up the QR Code generation method but it doesn't work for me.

I don't know what I did wrong, I haven't errors, I can access to the page where the QR Code is supposed to be but it's just empty.

I have implemented the ZXing.NET package (v.0.16.4 - even tried with the 0.15.0 like in the exemple but nothing change) and the CoreCompat.System.Drawing v1.0.0-beta006.

The only difference with the exemple is that I don't have a project.json file but a project.assets.json and the structure/content is not the same.

Have you an idea of what i'm doing wrong ?

**Comment by micjahn** [comment]
Please take a look at the ASP.Net Core demo in the source code repository:
https://github.com/micjahn/ZXing.Net/tree/master/Clients/ASP.NetCoreDemo
Without further information (like a sample project) I can't help here.
