### ISSUE TITLE
accurate recognition 

### ISSUE THREAD

**Issue by AngryShoes** [micjahn/ZXing.Net#119]
Hello,

I have install the ZXing.Net from Nuget.

>\<package id="ZXing.Net" version="0.16.4" targetFramework="net45"\>

Now I meet one problem is when I use the pure barcode paper without any disturb info it will works well and can return the correct result. However when I use the paper with barcode and the paper have some other disturb info such as include some words or drug instructions, the BarcodeReader will return empty result. code like this:
``` C#
private string GetBarCodes(string filePath)
        {
            BarcodeReader reader = new BarcodeReader();

            reader.Options.CharacterSet = "UTF-8";
            Bitmap bitmap = new Bitmap(filePath);
            ZXing.Result result = reader.Decode(bitmap);
            return result == null ? "" : result.Text;
        }
```
could you please give me some advice or instructions about it? This is my first use this library. Really thank you! Appreciate your reply.

**Comment by AngryShoes** [comment]
@micjahn yes, I use this library in Winform project.
when I use the barcode picture it doesn't work and return null result.
![order2](https://github.com/AngryShoes/DraggyBarCode/blob/master/Order2.png "cut picture")

the above picture is the cut part of the below.
![order1](https://github.com/AngryShoes/DraggyBarCode/blob/master/Order1.jpg)

I cannot get the barcode result in the second picture.
If possible,could give me some advice please? thanks a lot.

**Comment by micjahn** [comment]
Enable the TryHarder option.
`reader.Options.TryHarder = true;`
