### ISSUE TITLE
How to set Font Type and Font Size of barcode

### ISSUE THREAD

**Issue by AlexGeller** [micjahn/ZXing.Net#12]
Hi,

I have used BarcodeWriter class to generate a code128 barcode. Can you tell me how to set font type and font size in the generated barcode bitmap?

Alex

**Comment by micjahn** [comment]
Of course:

`         
var writerBitmap = new BarcodeWriter
{
   Format = ZXing.BarcodeFormat.CODE_128,
   Renderer = new BitmapRenderer
   {
      TextFont = new Font("Arial", 10, FontStyle.Regular) 
   }
};
`
