### ISSUE TITLE
How to have  a Carriage Return(ACSII)  in PDF417

### ISSUE THREAD

**Issue by SimonCMChang** [micjahn/ZXing.Net#120]
PD417 need to have  those two Tab /Carriage Return . For Tab portion, and it can used "	" to replace.
So I just wonder how to add Carriage Return(ASCII) in PDF417

**Comment by micjahn** [comment]
I don't know exactly what you mean but CR is supported by PDF417. Simply add it to your content.
Tabulators work the same way.
```
   [Test]
   public void PDF417_Should_Support_Carriage_Return()
   {
      var content = @"first line
second line after a Carriage Return";

      var writer = new BarcodeWriter
      {
         Format = BarcodeFormat.PDF_417
      };
      var pdf417Image = writer.Write(content);

      var reader = new BarcodeReader();
      var result = reader.Decode(pdf417Image);

      Assert.That(result?.Text, Is.EqualTo(content));
   }
```

**Comment by SimonCMChang** [comment]
Thanks for your update...
I should provide more detail about that.  
Problem of inserting Tab and Carriage Return in Bar-code PDF417
there are some decode methods for Tab /Carriage Return  which other function provided that
Tab                      : ~009  ,  \t  ,  #chr(9) , &Chr(9)&  , 0x09 ,<TAB>, or  "	"
Carriage Return  : ~013  ,  \r  ,  #chr(13) , &Chr(13)& , 0x0D ,<CR>
Question is about if there has any decode methods to inserting Tab and Carriage Return in your function

Sample as below
1)     var content = @"first line
second line after a Carriage Return"; 
2)      var content = @"first line~013second line after a Carriage Return";
3)      var content = @"first line\rsecond line after a Carriage Return";

**Comment by SimonCMChang** [comment]
Thanks for your update...
I should provide more detail about that.
there are some decode methods for Tab /Carriage Return which other function provided that
Tab : ~009 , \t , #chr(9) , &Chr(9)& , 0x09 ,, or "	"
Carriage Return : ~013 , \r , #chr(13) , &Chr(13)& , 0x0D ,
Problem of inserting Tab and Carriage Return in Bar-code PDF417, and the Carriage Return must be in the end of Content.
Question is about if there has any decode methods to inserting Tab and Carriage Return in your function

Sample as below
var content = @"first line
second line after a Carriage Return "; <<need Carriage Return
2) var content = @"first line013second line after a Carriage Return013";
3) var content = @"first line\r second line after a Carriage Return\r";

**Comment by micjahn** [comment]
There is no need for separate methods for inserting tabs and/or CR.
Your samples should work:
var content = @"first line\r second line after a Carriage Return\r";

If you need to add it after decoding simply add it via C# standard methods:
var reader = new BarcodeReader();
var result = reader.Decode(yourImageInstance);
var resultTextWithCRAtEnd = result.Text + "\r";

Every content which should be encoded or which is decoded is simply a string.
You can use all known and unknown string manipulation methods of C#/.Net with it.
