### ISSUE TITLE
How can I use Zxing.Net for WinJs Project 

### ISSUE THREAD

**Issue by NikitaShelar** [micjahn/ZXing.Net#121]
I  want to implement QR code Scanner in WinJS Cordova for UWP apps. I have added reference of ZXing.Net library but could not understand how to implement it in WinJS Cordova project . I am using visual studio 2017.Any help would be appreciated.

**Comment by micjahn** [comment]
Did you take a look at the WinJS demo?
https://github.com/micjahn/ZXing.Net-WINMD/tree/master/Clients/WindowsStoreJavaScriptDemo
It doesn't use Cordova but it should give you an idea of using ZXing.Net with WinJS.
