### ISSUE TITLE
Shorten decoder's leading quiet zone width 50% to 25% or such

### ISSUE THREAD

**Issue by kenjiuno** [micjahn/ZXing.Net#124]
I'm happy if I can tweak the width of whitespace before start pattern: from 50% to 25% (for ZXing.Net code39 decoder, by optional decoder settings or such)

https://github.com/micjahn/ZXing.Net/blob/09ec5be59cb528283602b8df4b3840992ef1f65a/Source/lib/oned/Code39Reader.cs#L258

for example,

from 50%:
```
  if (row.isRange(Math.Max(0, patternStart - ((i - patternStart) >> 1)), patternStart, false))
```

to 25%:
```
  if (row.isRange(Math.Max(0, patternStart - ((i - patternStart) >> 2)), patternStart, false))
```

or, or such tweaking optional:
```
  if (row.isRange(Math.Max(0, patternStart - ((i - patternStart) / divider)), patternStart, false))
```

**Comment by micjahn** [comment]
Not sure if it is such a good idea. I think you have to build your own version of the library with the changes you need for your project. The check for the quiet zone prevents false positives. I'm feeling not very comfortable by the idea to change that part.

**Comment by kenjiuno** [comment]
OK, thanks!
