### ISSUE TITLE
Unable to find DataMatrix barcode.

### ISSUE THREAD

**Issue by Eritey** [micjahn/ZXing.Net#126]
Having issues reading a DataMatrix from the following image;

https://imgur.com/a/3nkTmdP

If I extract just the barcode from the image, the barcode can be read

https://imgur.com/a/rjMGyzi

Is there a reason for this? is the original image too large? 

Thanks for any help that can be given.

**Comment by micjahn** [comment]
The data matrix detector has a little constraint. It looks only in the middle of the picture for a code.
It doesn't care for mobile use cases but in your case it fails.
Feel free to open a PR which extends the detector.
