### ISSUE TITLE
Can i get a bitmap with cmyk color space.

### ISSUE THREAD

**Issue by zhusheping** [micjahn/ZXing.Net#127]
I can get a bitmap with qrcode writer,and i want to put it into a pdf with itextsharp.
the problem is the qrcode img in pdf always with rgb colorspace,and i want a cmyk one.
[C#:Add a bitmap/image into PDF with CMYK color space](https://stackoverflow.com/questions/51465552/cadd-a-bitmap-image-into-pdf-with-cmyk-color-space)
```
 QrCodeEncodingOptions options = new QrCodeEncodingOptions();
                    options.CharacterSet = "UTF-8"; options.DisableECI = true;
                    options.ErrorCorrection = ZXing.QrCode.Internal.ErrorCorrectionLevel.L;
                    options.Width = 100; options.Height = 100; options.Margin = 0;
                    options.PureBarcode = true;                    
                    BarcodeWriter writer = new BarcodeWriter();
                    writer.Format = BarcodeFormat.QR_CODE;
                    writer.Options = options;
                    System.Drawing.Bitmap bitmap = writer.Write("http://www.google.com");
```
Thanks.

**Comment by micjahn** [comment]
ZXing.Net doesn't support CMYK out of the box. And as far as I know it isn't that easy with .Net. Correct me if I'm wrong. I did a little search with google and found some websites which should help you:
https://www.codeproject.com/Articles/781213/Fundamentals-of-Image-Processing-behind-the-scenes
https://msdn.microsoft.com/en-us/library/7kyc0t49(v=vs.110).aspx
https://stackoverflow.com/questions/5065371/how-to-identify-cmyk-images-in-asp-net-using-c-sharp

As far as I understand that websites you can take the RGB bitmap and convert it manually after creation of the barcode image.
