### ISSUE TITLE
Getting Code 128 string

### ISSUE THREAD

**Issue by asantaballa** [micjahn/ZXing.Net#13]
Have unusual requirement and was wondering it could use ZXing without mods. I am rpelacing an old Foxpro application which generates a Code 128 _string_ into and extract. So not the bar code image, but the intermediate string after converting the raw string input internally to Code 128. for instance the free online encoder page from ID Automation (http://www.bcgen.com/fontencoder/) converts the string "MA$7#LXB  #000074232088" to the corresponding Code 128 string "ÌMA$7#LXBÂÂ#ÇÂÂj74x.Î".

Because the consumer of my extract is not changing I need to be able to generate the string as the old app did. I expect that the string is generated within ZXing internally while generating a Code 128 barcode bitmap. 

Am asking only if you can answer of the top of your head. If not, I'd be glad to go into the code and research myself. 

Thanks in advance for any help and for mantaingin the great product....--Al-

**Comment by micjahn** [comment]
Sorry, the Code128 writer class doesn't use an internal representation of the content. It converts the string directly to bit patterns. There is no "high level encoder" like other barcode types uses it.

**Comment by asantaballa** [comment]
Sad to hear, but thanks for quick response.

--Al-
