### ISSUE TITLE
Class: BitmapLuminanceSource for .Net Core 2

### ISSUE THREAD

**Issue by AlaricDelany** [micjahn/ZXing.Net#132]
Hallo there,
Would it be Possible to have the BitmapLuminanceSource for .Net Core?

I am using .Net Core 2.0 and as i saw in the Nuget Package the BitmapLuminanceSource Class is Missing there.
Some time ago there was no Bitmap at .Net Core, now it is there and i would wish to have this this Source for .Net Core, too.

Thanks and i will wait for it.

**Comment by micjahn** [comment]
As far as I know it is only available with the Windows Compatibility Pack for .NET Core:
https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/
Bitmap class isn't supported directly in .Net Core and .Net Standard 2.0.
Do you have other information?

Perhaps you can try one of the different bindings for ZXing.Net
https://www.nuget.org/packages?q=micjahn

**Comment by AlaricDelany** [comment]
You are Right, thats what i mean.
System.Drawing.Common is now availible and not marked as "Windows-Only".

I testet some Hours ago compatibility with the Existing BitmapLuminanceSource  for FullFramework and just Copying it to a Core Project with a Reference to System.Drawing.Common works fine.
The Bitmap/Image Interface seems to be the same.

But you are right it is not part of the Standard, maybe you could just for core/standard push a seperate Package with uses System.Drawing.Common togehter with the Original BitmapLuminanceSource.

I did not looked into the Binding Packages yet, but my Company would prefer to use a Microsoft Component instead of an 3rd Party Library.

In Principal i could Fork and build it myself, but then me or my Company has to Sync the Core/Standard BitmapLuminanceSource with yours and for you it should be in best case another Nuget Package with a Link to an Existing Class File.

Or what do you think?

Would it be possible for you to do something like this?

**Comment by micjahn** [comment]
I made a first attempt. Please try the new package when it is available through nuget. Publishing process is running at the moment.
https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/0.16.5
