### ISSUE TITLE
No content in EAN 13 barcode

### ISSUE THREAD

**Issue by kwaazaar** [micjahn/ZXing.Net#134]
When using either BarcodeWriterPixelData or the more specific ZXing.ImageSharp.BarcodeWriter<Rgba32>, the content itself is not rendered in an EAN 13 barcode. It IS rendered when using the standard BarcodeWriter.

Eg: this works:
```
var barcodeWriter = new BarcodeWriter
            {
                Format = BarcodeFormat.EAN_13,
                Options = new EncodingOptions
                {
                    Height = 300,
                    Width = 300
                }
            };
            Bitmap bitmap = barcodeWriter.Write("123456789012");

            bitmap.Save(@"C:\Temp\barcode.png", ImageFormat.Png);
```
But this doesn't:

```
            var barcodeWriter = new BarcodeWriterPixelData
            {
                Format = BarcodeFormat.EAN_13,
                Options = new EncodingOptions
                {
                    Height = 300,
                    Width = 300,
                }
            };

            PixelData pixelData = barcodeWriter.Write("123456789012");
            var img = Image.LoadPixelData<Rgba32>(pixelData.Pixels, pixelData.Width, pixelData.Height);
            using (var fileOut = File.OpenWrite(@"C:\Temp\barcode.png"))
                img.SaveAsPng(fileOut);
```

**Comment by micjahn** [comment]
The output of the content below the barcode is only supported by the bitmap and svg renderer.
The bitmap renderer uses bitmap functions to draw the text and the svg renderer creates the font tags.
Fell free to provide a PR which adds the functionality to the other renderer implementation.
I don't have any idea how I should implement that for the pixel data renderer.
