### ISSUE TITLE
Bug when reading large QR codes?

### ISSUE THREAD

**Issue by knocte** [micjahn/ZXing.Net#135]
I'm using the [ZXing.Net.Mobile.Forms](https://www.nuget.org/packages/ZXing.Net.Mobile.Forms) (which uses ZXing.Net sources) to scan and render QR codes from Android and iOS. When testing on Android (with a real smartphone, not an emulator) I noticed a bug with larger QR codes, where the scanning process returns a random 5-7 digit number instead of the ~1,000 characters it was supposed to read.

Then I found that someone had already filed this bug in the ZXing.Net.Mobile repository here: https://github.com/Redth/ZXing.Net.Mobile/issues/624

Now, I'm not sure if this is a ZXing.Net bug or a ZXing.Net.Mobile bug, but the thing that led me to believe it could be the former, is the fact that large QR codes seem to be an issue in iOS as well: https://github.com/Redth/ZXing.Net.Mobile/issues/306 (appears as a closed issue but only a workaround is provided). I haven't tested with iOS yet myself but I'll do soon.

Any chance I can get some help to debug this issue? I'd be willing to contribute fixes if given enough guidance :)

**Comment by micjahn** [comment]
I checked the barcodes from the tickets you mentioned. They worked perfectly with the current WindowsFormDemo client.
Do you have any sample image which doesn't work for you?

**Comment by knocte** [comment]
Thanks for testing @micjahn.
This is one I'm having trouble with:
<img width="424" alt="screen shot 2018-08-19 at 1 42 57 pm" src="https://user-images.githubusercontent.com/331303/44305910-9ee54100-a3b6-11e8-9624-7eec5af374fb.png">


```
pVRdb9s4EPwrgZ5dgZ8iaSAPlhMnbhrHBys9JIGBo0Qq1kWmAolqkwv832+pODn3WhQFyidhObszO7vUS/TZtl3VuGgcoZjFKEbRKMqeH+1Cby0Ez/7UdW19nOriwToTX7uuunfWZK12nS48pP6F7+6+g/mnZtpULj7AXVqvjfZ6dPR/9ML6ldfO6NaMjvaCjvdyRkfTvvZ9a4+d7X2r69HRss/rqriwz1kD6ceur+v1GmR/1nUPml+iZds8Np2uw/dVW91XbmJMa7sOGqIquVjaPEnLfsWT/u+MLh6eJLte3LpNVmh6PYNKk23TOx/Sh5pZswKZ0RjkYE4QZ3wUpbrWrrATn23sZbO1zl+VAVW5+2+B075trSueQ7Wp7oKpaTaNdrtRdGI7XzkdzPlPIF5sRH9uvtwk5eKr/8Nf4jN+ejuZLT9NKU25atMIUt/MDFVnduj6FIpttf9mNqvqHzt36bO3UJrg5K21pW0vqroJF7OmnenOHyQN+uEwQVDy/RGjNyrAZtWwJgRh+QHJD1hliI8ZGiMBFjCa4NvopxYc0J60uhw8n7vH3oPeu5fD63PdbSCxZDkpJBWa4SLH1qDScGJQkYu8wIpYUyKhMSEEFVwhqnNVYo4wJUXJEoM1yLnqPRDMnbFP0Rjv92buVto33aYC4vfZHQxo7s4DPNIKM44pRoITLozMpbGSKGlFwYlU2OYsl0ISmisqRbRbv/G9NvQDLqw4U7+xDOvg41QXm2ELrjuzbKti+A4mjxOGklgQpRLOYXQnkzmQwnwxw0RRzmCaAYZpjJmEvjFGSYidw8IoFgtKpUqwgtRPAcfDYKlAiAgqgXivNezXS4SepCiZYnmK7ExMUXIKg5KIMM05twRD5CQRynIOZgxSXtlf+cCqX3idkBj6AvDl7GO2uQHV7qHtitTcfFkk2+3HbnO2VNktY9tFAAfV6937g+3ejTl8pIMrLOZ7M8J/59WCAMJIStDP9w5AaAfnXw==
```

But on Android, I just tested it, and it scans to the text "01281008".

**Comment by micjahn** [comment]
Make sure that the barcode format MSI isn't activated in the options. This one leads to false positives.

**Comment by knocte** [comment]
> Make sure that the barcode format MSI isn't activated in the options

I guess I'm not using MSI, this is my QRcode rendering code:

```
        let encodingOptions = EncodingOptions(Height = size,
                                              Width = size)
        let barCode = ZXingBarcodeImageView(HorizontalOptions = LayoutOptions.Center,
                                            VerticalOptions = LayoutOptions.Center,
                                            BarcodeFormat = BarcodeFormat.QR_CODE,
                                            BarcodeValue = qrCodeContents,
                                            HeightRequest = float size,
                                            WidthRequest = float size,
                                            BarcodeOptions = encodingOptions)
```

**Comment by knocte** [comment]
Wait, were you referring to the scanning options or the rendering options? If the former, I just try adding these (I was not using any options before, so default):

```
        let scanningOptions = ZXing.Mobile.MobileBarcodeScanningOptions(
                                  TryHarder = Nullable<bool>(true),
                                  PossibleFormats = System.Collections.Generic.List<ZXing.BarcodeFormat>([ZXing.BarcodeFormat.QR_CODE])
                              )
        let scanPage = ZXingScannerPage(scanningOptions)
```

I guess that not including BarcodeFormat.MSI in the list is enough to not activate it? I still have same problem after this though. Maybe I should try the `UseNativeScanning` option next.

**Comment by micjahn** [comment]
I'm not very familar with ZXing.Net.Mobile but in my opinion 
> PossibleFormats = System.Collections.Generic.List<ZXing.BarcodeFormat>([ZXing.BarcodeFormat.QR_CODE])
should do the trick. It's not an encoding issue. If you have all possible formats enabled the chance to get a false positive is bigger than selecting only one barcode format.
I checked your sample with the WindowsFormsDemo of ZXing.Net and it works as expected.
On the other hand if I disable QR and enable MSI I get a false positive.
I don't know how ZXing.Net.Mobile initializes ZXing.Net under the hood. Perhaps there is something wrong which leads to your false result.
I don't see any problem with ZXing.Net here and I will close the issue.

And as far as I know the option "UseNativeScanning" will disable the ZXing.Net engine and ZXing.Net.Mobile uses the platform specific implementation of the OS vendor.
