### ISSUE TITLE
Using COM interop with VBA fails

### ISSUE THREAD

**Issue by carrier92** [micjahn/ZXing.Net#139]
I want to crate an Word Document to create a Data matrix code.
I register the interop dll an used the generated .tlb as reference in the project.

For testing purpose I used the example code from the Wiki, but it fails with error message.
![image](https://user-images.githubusercontent.com/24352619/45302581-fab56c80-b513-11e8-8706-02a78d7e3116.png)

I tried differend location to place de dll/tlb files, all end up the same.

regards

carrier92

**Comment by micjahn** [comment]
I'm not sure what's the issue in your case but you can try the following modified register.cmd script:
```
@ECHO OFF

reg Query "HKLM\Hardware\Description\System\CentralProcessor\0" | find /i "x86" > NUL && set OS=32BIT || set OS=64BIT

ECHO %OS%

"%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\regasm.exe" /unregister %~dp0zxing.interop.dll
"%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\regasm.exe" /codebase %~dp0zxing.interop.dll /tlb %~dp0zxing.interop.tlb

if %OS%==64BIT "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\regasm.exe" /unregister %~dp0zxing.interop.dll
if %OS%==64BIT "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\regasm.exe" /codebase %~dp0zxing.interop.dll /tlb %~dp0zxing.interop.tlb

pause
```
Copy zxing.dll, zxing.interop.dll and register.cmd to C:\Windows.
Execute the register.cmd script from C:\Windows.

Please let me know if it changes anything.
I tried it on my machine and it works.

**Comment by carrier92** [comment]
With this modified script it works.
As far as I understand you modification it installed it always with 32bit Framework  and only if the OS is 64bit also the 64bit Framework.

we have WIN7 64bit but using Office 2010 32bit.

Many thanks for your help
carrier92
