### ISSUE TITLE
Porting zxing.kinect to Kinect 2.0

### ISSUE THREAD

**Issue by maxime-beck** [micjahn/ZXing.Net#14]
Hi Michael,

Are you planning on porting zxing.kinect to Kinect 2.0 anytime soon?

Best Regards,
Maxime Beck

**Comment by micjahn** [comment]
I committed some changes to the repository which are introducing Kinect V2 a a new binding.
But I don't have a Kinect device. I can't test the assembly. I think the color conversion to luminance values which are done in the class ColorFrameLuminanceSource isn't working at all or only for some ColorImageFormats. I really need someone who are willing to build the assembly and check it against all ColorImageFormats.

**Comment by maxime-beck** [comment]
Thanks for your answer! I did a quick little project to test it out but I get an `IndexOutOfRangeException ` when invoking the `Decode()` method.

**Code :**

``` C#
public partial class MainWindow : Window
{
    KinectSensor sensor;
    ColorFrameReader cfReader;
    byte[] cfDataConverted;
    WriteableBitmap cfBitmap;
    ZXing.Kinect.BarcodeReader reader;

    public MainWindow()
    {
        InitializeComponent();
        this.Loaded += MainWindow_Loaded;
    }        

    private void MainWindow_Loaded(object sender, RoutedEventArgs e)
    {
        sensor = KinectSensor.GetDefault();
        cfReader = sensor.ColorFrameSource.OpenReader();
        FrameDescription fd = sensor.ColorFrameSource.FrameDescription;
        cfDataConverted = new byte[fd.LengthInPixels * 4];
        cfBitmap = new WriteableBitmap(fd.Width, fd.Height, 96, 96, PixelFormats.Pbgra32, null);            
        reader = new ZXing.Kinect.BarcodeReader();

        image.Source = cfBitmap;
        sensor.Open();

        cfReader.FrameArrived += CfReader_FrameArrived;
    }

    private void CfReader_FrameArrived(object sender, ColorFrameArrivedEventArgs e)
    {
        using (ColorFrame cfFrame = e.FrameReference.AcquireFrame())
        {
            if (cfFrame != null)
            {
                cfFrame.CopyConvertedFrameDataToArray(cfDataConverted, ColorImageFormat.Bgra);
                Int32Rect rect = new Int32Rect(0, 0, (int)cfBitmap.Width, (int)cfBitmap.Height);
                int stride = (int)cfBitmap.Width * 4;
                cfBitmap.WritePixels(rect, cfDataConverted, stride, 0);

                var result = reader.Decode(cfFrame); // Exception thrown here
                if (result != null)
                {
                    MessageBox.Show("Barcode is :" + result.Text);
                }
            }
        }
    }
}
```
**TraceStack :**
System.IndexOutOfRangeException :   
   at ZXing.RGBLuminanceSource.CalculateLuminanceYUYV(Byte[] yuyvRawBytes) line:359
   at ZXing.RGBLuminanceSource.CalculateLuminance(Byte[] rgbRawBytes, BitmapFormat bitmapFormat)
   at ZXing.Kinect.ColorFrameLuminanceSource..ctor(ColorFrame bitmap, Boolean flipTheImage)
   at ZXing.Kinect.ColorFrameLuminanceSource..ctor(ColorFrame bitmap)
   at ZXing.Kinect.BarcodeReader.<>c.<.cctor>b__4_0(ColorFrame bitmap)
   at ZXing.BarcodeReader`1.Decode(T barcodeBitmap)
   at ColorFrameTest.MainWindow.CfReader_FrameArrived(Object sender, ColorFrameArrivedEventArgs e)
**With values :**
uyvyIndex = 4147200
luminanceIndex = 2073598

**Comment by micjahn** [comment]
Please try again with the newest sources.

**Comment by maxime-beck** [comment]
I tried all ColorImageFormats and they all work fine!
Thank you for your help.

Best Regards,
Maxime Beck.
