### ISSUE TITLE
Unable to decode/read barcodes in images

### ISSUE THREAD

**Issue by DanielMidler** [micjahn/ZXing.Net#140]
I am trying to decode barcodes in images taken from a camera but it is not working for any image I try.

Here's the code I'm currently using:

    protected void ReadBarcodeZXing(string imagePath)
    {
        BarcodeReader reader = new BarcodeReader()
        {
            Options =
                {
                    TryHarder = true,
                    ReturnCodabarStartEnd = false,
                    PureBarcode = false
                }
        };

        Bitmap barcodeBitmap = (Bitmap)Bitmap.FromFile(imagePath);

        var result = reader.Decode(barcodeBitmap);

        if (result != null)
            lblResult.Text = result.BarcodeFormat.ToString() + "<br />" + result.Text;
        else
            lblResult.Text = "No barcodes found in image";

        barcodeBitmap.Dispose();
    }

I've tried with AutoRotate and TryInverted set to true and I've tried using PossibleFormats.

Here are some barcode images I've tried decoding:

  > 1: https://imgur.com/yPkDNRM

  > 2: https://imgur.com/bNKzh73 (Close-up of 1)

  > 3: https://imgur.com/DJ1lcAa

  > 4: https://imgur.com/Q3nN6Do

  > 5: https://imgur.com/e8JbpmV (Close-up of 4)

  > 6: https://imgur.com/pCEj9Iu

  > 7: https://imgur.com/Q3qlVDP

6 & 7 are sample images taken from the EAN test images folder in this repo. There were more samples that didn't work but many of them **did** work.

Anyone able to help me get it working properly? Or help me understand why it's not working for my own images?

**Comment by micjahn** [comment]
Most of them are decodable if you reduce the resolution to 768x1024 pixels. If the resolution is to high there is a lot of noise which makes it hard to decode.
