### ISSUE TITLE
MaxiCode Support

### ISSUE THREAD

**Issue by cooperb0199** [micjahn/ZXing.Net#141]
Hi Michael,

My inquiry is not an issue per se, but I was wondering if there was going to be any support for encoding Maxicode at any point. I noticed that the BarcodeFormat enum contains Maxicode, but when trying to use it an exception is thrown stating that that particular encoding is not supported.

Thanks!
Ben Cooper

**Comment by micjahn** [comment]
Only if someone other would write it. I don't have enough freetime to implement a complete new writer.
Feel free to open the issue again with a corresponding pull request.
The BarcodeFormat enumeration is for shared between encoding and decoding. It doesn't mean that every implementation is available.
