### ISSUE TITLE
Can't recognize large scaled images

### ISSUE THREAD

**Issue by snoward** [micjahn/ZXing.Net#145]
Hello!

I tried to decode qr-code from images that are scanned documents. But on some of them qr-code was not found. When I reduced them several times, qr-code is recodnized well. 

Original image was recognized well at zxing.org site. Can you please fix ZXing.NET ?

Some examples in attachment. 

[scaled-images.zip](https://github.com/micjahn/ZXing.Net/files/2441014/scaled-images.zip)

**Comment by micjahn** [comment]
The website zxing.org tries both available binarizer implemenations sequentially.
The default implementation of the BarcodeReader class of ZXing.Net uses only the HybridBinarizer.
If you want to get the same behaviour like zxing.org you have to implement the call of the Decode method twice:

```
// default binarizer (HybridBinarizer)
var barcodeReader = new BarcodeReader();
var result = barcodeReader.Decode(theBitmap):
if (result == null)
{
   // explicitly use the GlobalHistogramBinarizer if nothing is found with the HybridBinarizer
   // simulates the behaviour of zxing.org
   barcodeReader = new BarcodeReader(null, null, s => new GlobalHistogramBinarizer(s));
   result = barcodeReader.Decode(theBitmap):
}
```

**Comment by tomasloksa** [comment]
@skygate2012 i'm using Zxing.Net.Bindings.Windows.Compatibilty (even tried Skiasharp bindings). - with Zxing.Net 0.16.9. 
And your fix - if i understood it correctly, wasn't working.

Here's my code - 

`private static IEnumerable<string> ReadQrCode(MemoryStream documentStream)
{
    var reader = new BarcodeReader()
    {
        Options = new ZXing.Common.DecodingOptions
        {
            PossibleFormats = new[] { ZXing.BarcodeFormat.QR_CODE },
            TryHarder = true,
            TryInverted = false
        }
    };

    var bitmap = new Bitmap(documentStream);

    Result[] results = reader.DecodeMultiple(bitmap);

    return results?.Select(result => result.Text) ?? Enumerable.Empty<string>();
}`

When i used the code provided by @micjahn, it extracted the QR successfully.
