### ISSUE TITLE
Version 0.16.4 Datamatrix rectangular

### ISSUE THREAD

**Issue by samardzievboris** [micjahn/ZXing.Net#146]
After updating to version 0.16.4 from version 0.16.2 same code produces rectangular data matrix, before they ware square.

0.16.2
![image](https://user-images.githubusercontent.com/43950283/46597558-e77cc900-cae0-11e8-9d77-14e630a1e917.png)

0.16.4
![image](https://user-images.githubusercontent.com/43950283/46597580-011e1080-cae1-11e8-926c-9ac614cb8b94.png)

Code sample:

 BarcodeWriter writer = new BarcodeWriter()
            {
                Format = BarcodeFormat.DATA_MATRIX,
                Options =
                {
                    Height = 256,
                    Width = 256,
                    Margin = 0
                }
            };

            System.Drawing.Bitmap bitmap = writer.Write(content);

**Comment by micjahn** [comment]
It's because of the following changes:
https://github.com/micjahn/ZXing.Net/commit/2ab640de417410bd211349033696da0df4acabfa
(ported changes from the java version)
If can force a square shape by setting the following option:
```
BarcodeWriter writer = new BarcodeWriter()
{
   Format = BarcodeFormat.DATA_MATRIX,
   Options = new DatamatrixEncodingOptions
   {
      Height = 256,
      Width = 256,
      Margin = 0,
      SymbolShape = SymbolShapeHint.FORCE_SQUARE
   }
};
```
