### ISSUE TITLE
Unhandled NullReferenceException when decode qr-code with GlobalHistogramBinarizer

### ISSUE THREAD

**Issue by snoward** [micjahn/ZXing.Net#147]
Hello! 
In previous issue you advice me to use GlobalHistogramBinarizer. But it throws NullReferenceException in some cases. 

```
System.NullReferenceException : Ссылка на объект не указывает на экземпляр объекта.
   в ZXing.Multi.QrCode.Internal.MultiFinderPatternFinder.findMulti(IDictionary`2 hints)
```

```
qrReader = new BarcodeReader(null, null, s => new GlobalHistogramBinarizer(s))
{
      Options = { PossibleFormats = new[] { BarcodeFormat.QR_CODE }, TryHarder = true },
};
```

[qr-code.zip](https://github.com/micjahn/ZXing.Net/files/2464965/qr-code.zip)

**Comment by micjahn** [comment]
I tried your sample with the current version and I didn't get an exception.
Can you provide a full stacktrace of your exception?

**Comment by micjahn** [comment]
Do you use the current version of ZXing.Net? Do you use the pure version or the ZXing.Net.Mobile project?

**Comment by snoward** [comment]
Sorry, the example file is incorrect -- I cropped only qr-code from the image, but the problem exists on the original sized. 
I have add the correct one.

I am using the last version of ZXing.NET (0.16.4) and not using ZXing Mobile at all. 

```
System.NullReferenceException : Ссылка на объект не указывает на экземпляр объекта.
   в ZXing.Multi.QrCode.Internal.MultiFinderPatternFinder.findMulti(IDictionary`2 hints) в C:\git\ZXing.Net\Source\lib\multi\qrcode\detector\MultiFinderPatternFinder.cs:строка 245
   в ZXing.Multi.QrCode.Internal.MultiDetector.detectMulti(IDictionary`2 hints) в C:\git\ZXing.Net\Source\lib\multi\qrcode\detector\MultiDetector.cs:строка 54
   в ZXing.Multi.QrCode.QRCodeMultiReader.decodeMultiple(BinaryBitmap image, IDictionary`2 hints) в C:\git\ZXing.Net\Source\lib\multi\qrcode\QRCodeMultiReader.cs:строка 53
   в ZXing.BarcodeReaderGeneric.DecodeMultiple(LuminanceSource luminanceSource) в C:\git\ZXing.Net\Source\lib\BarcodeReaderGeneric.cs:строка 316
   в ZXing.BarcodeReader`1.DecodeMultiple(T barcodeBitmap) в C:\git\ZXing.Net\Source\lib\BarcodeReaderCustom.cs:строка 141
```

[not recognized by histogram binarizer.zip](https://github.com/micjahn/ZXing.Net/files/2466200/not.recognized.by.histogram.binarizer.zip)
