### ISSUE TITLE
Can't be able to chage the Height and Width of PDF417.

### ISSUE THREAD

**Issue by nomantalish** [micjahn/ZXing.Net#148]
I am using this library to generate pdf417 and barcode. But the issue is with the dimensions like height and width changes are not applied to pdf417 as well as other formates. Please suggest a solution how to reduce the height of pdf417.

**Comment by micjahn** [comment]
What did you try? Do you have some sample code?
Normally you should use something like the following:
```
var writer = new BarcodeWriter
{
    Format = BarcodeFormat.PDF_417,
    Options = new PDF417EncodingOptions
    {
        Width = 0,
        Height = 0,
        Margin = 1
    }
};
var barcode = writer.Write("<content here>");
```
That code snippet should give the smallest possible barcode for the given content.

**Comment by siqusoft** [comment]
@micjahn

tried the above suggestion but still having issue resizing height and width of PDF_417 Barcode. let me know if there is other work around.

Thanks,

**Comment by micjahn** [comment]
It would be helpful when you describe your issues.

**Comment by Solmyr1982** [comment]
Please don't mind my previous comment, I didn't notice there are other parameters.
It works well if I do it like that:

Options = new ZXing.PDF417.PDF417EncodingOptions { Margin = 0, ImageAspectRatio = 3/2 }

**Comment by Solmyr1982** [comment]
Dear @micjahn ,
Unfortunately, I'm still facing the issue with the size. The barcode I'm generating is still too small, despite that I changed the aspect ratio. When I'm specifying the Width / Height, it only adds white space to the canvas.
As I understood, I need to specify the symbol size, but I can't find this option.
I tried something like that but it doesn't work.
``                    
Options = new ZXing.Datamatrix.DatamatrixEncodingOptions
{                        
    MinSize = new Dimension(150, 100),
    //MaxSize = new Dimension(26, 12),
    Margin = 0
}
``

Could you please advise how can I make the resulting barcode bigger?

**Comment by micjahn** [comment]
ZXing.Net can resize the resulting barcode image only by integer values. There is no anti-aliasing or similar functionality implemented. That's the cause behind the white space which is added around the barcode.
If you need a specific size of the resulting image you should generate the barcode with a width and height of 1. That will give you the smallest representation of the barcode. After that, you can resize the image with an image manipulation library of your choice which supports resizing with anti-aliasing.

**Comment by Solmyr1982** [comment]
@micjahn thanks a lot for your reply. For those who might be looking for the same question, here is the snippet for resizing the resulting image (the trick is to use InterpolationMode, so it won't make it smooth and the barcode will remain sharp).

``
  private static Bitmap ScaleImage(Bitmap bmp, int maxWidth, int maxHeight)
  {
      var ratioX = (double)maxWidth / bmp.Width;
      var ratioY = (double)maxHeight / bmp.Height;
      var ratio = Math.Min(ratioX, ratioY);
      var newWidth = (int)(bmp.Width * ratio);
      var newHeight = (int)(bmp.Height * ratio);
      var newImage = new Bitmap(newWidth, newHeight, PixelFormat.Format24bppRgb);
      using (var graphics = Graphics.FromImage(newImage))
      {
          graphics.InterpolationMode = InterpolationMode.NearestNeighbor;
          graphics.PixelOffsetMode = PixelOffsetMode.HighQuality;
          graphics.DrawImage(bmp, 0, 0, newWidth, newHeight);
      }
      return newImage;
  }
``

**Comment by mnikolovski** [comment]
Hi @Solmyr1982 

Can you post the solution to the problem if you were able to scale it correctly?

Thank you for.
