### ISSUE TITLE
zxing .NET4.0 version is built against the ".NETFramework,Version=v4.6.1"

### ISSUE THREAD

**Issue by ptodorov** [micjahn/ZXing.Net#15]
Hello,

I have a problem referencing one of my projects which is dependent on zxing. All my projects target .NET4.0. This is the error I get:

The primary reference "D:\fakepath\Assembly1.dll" could not be resolved because it has an indirect dependency on the assembly "zxing, Version=0.15.0.0, Culture=neutral, PublicKeyToken=4e88037ac681fe60" which was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".

I double checked this and I'm sure I'm referencing the net40 version from the nuget package. Probably this version was built with net461?

Thanks,
Panayot

**Comment by micjahn** [comment]
ILSpy say .Net 4.0. Please make sure that NuGet uses the right target from the package.

// zxing, Version=0.15.0.0, Culture=neutral, PublicKeyToken=4e88037ac681fe60
// Architecture: AnyCPU (64-bit preferred)
// Runtime: .NET 4.0

using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
[assembly: AssemblyVersion("0.15.0.0")]
[assembly: CLSCompliant(true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AssemblyCompany("ZXing.Net Development")]
[assembly: AssemblyCopyright("Copyright © 2012-2017")]
[assembly: AssemblyDescription("port of the java based barcode scanning library for .net (java zxing 27.02.2017 19:21:59)")]
[assembly: AssemblyFileVersion("0.15.0.0")]
[assembly: AssemblyProduct("ZXing.Net")]
[assembly: AssemblyTitle("zxing.net for .net 4.0")]
[assembly: AssemblyTrademark("")]
[assembly: CompilationRelaxations(8)]
[assembly: InternalsVisibleTo("zxing.sl4.test, PublicKey=002400000480000094000000060200000024000052534131000400000100010045fb4acb951cd5e32ae9e53a82b1e62b0294957b73746118eab0d94e49a5463f4994b060431b6389dff138dc1b6932006be2fe007a82176261ed88d3d9dddd0ee568988bb96f3667aad84c2bee1395f9ec23cf61ddf5a7ca540e34b4a2e41920c6a204d39cf78ebf7d4331c823a96cb36a1d5bc1a8c666db1edef4ab67c167dc")]
[assembly: InternalsVisibleTo("zxing.test, PublicKey=002400000480000094000000060200000024000052534131000400000100010045fb4acb951cd5e32ae9e53a82b1e62b0294957b73746118eab0d94e49a5463f4994b060431b6389dff138dc1b6932006be2fe007a82176261ed88d3d9dddd0ee568988bb96f3667aad84c2bee1395f9ec23cf61ddf5a7ca540e34b4a2e41920c6a204d39cf78ebf7d4331c823a96cb36a1d5bc1a8c666db1edef4ab67c167dc")]
[assembly: InternalsVisibleTo("zxing.sl4.test, PublicKey=0024000004800000140100000602000000240000525341310008000001000100014c9a01956f13a339130616473f69f975e086d9a3a56278936b12c48ca45a4ddfee05c21cdc22aedd84e9468283127a20bba4761c4e0d9836623fc991d562a508845fe314a435bd6c6ff4b0b1d7a141ef93dc1c62252438723f0f93668288673ea6042e583b0eed040e3673aca584f96d4dca19937fbed30e6cd3c0409db82d5c5d2067710d8d86e008447201d99238b94d91171bb0edf3e854985693051ba5167ca6ae650aca5dd65471d68835db00ce1728c58c7bbf9a5d152f491123caf9c0f686dc4e48e1ef63eaf738a12b3771c24d595cc5a5b5daf2cc7611756e9ba3cc89f08fb9adf39685bd5356858c010eb9aa8a767e5ef020408e0c9746cbb5a8")]
[assembly: InternalsVisibleTo("zxing.test, PublicKey=0024000004800000140100000602000000240000525341310008000001000100014c9a01956f13a339130616473f69f975e086d9a3a56278936b12c48ca45a4ddfee05c21cdc22aedd84e9468283127a20bba4761c4e0d9836623fc991d562a508845fe314a435bd6c6ff4b0b1d7a141ef93dc1c62252438723f0f93668288673ea6042e583b0eed040e3673aca584f96d4dca19937fbed30e6cd3c0409db82d5c5d2067710d8d86e008447201d99238b94d91171bb0edf3e854985693051ba5167ca6ae650aca5dd65471d68835db00ce1728c58c7bbf9a5d152f491123caf9c0f686dc4e48e1ef63eaf738a12b3771c24d595cc5a5b5daf2cc7611756e9ba3cc89f08fb9adf39685bd5356858c010eb9aa8a767e5ef020408e0c9746cbb5a8")]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Guid("ECE3AB74-9DD1-4CFB-9D48-FCBFB30E06D6")]
[assembly: TargetFramework(".NETFramework,Version=v4.0,Profile=Client", FrameworkDisplayName = ".NET Framework 4 Client Profile")]

**Comment by ptodorov** [comment]
Hello again,

The Path property for the referenced assembly says:
...\packages\ZXing.Net.0.15.0\lib\net40\zxing.dll

But still when I add reference to this project, I get the same error.

**Comment by micjahn** [comment]
I double checked it again. I created a new C# class library project which target .Net Framework 4.0.
I referenced the ZXing.Net nuget package, v 0.15.0.0. Everything builds fine, all references are correct.
I don't see any error within the nuget package. I have no similar reports from other users.
Please make sure that the referenced assembly Assembly1.dll is build against the correct version of ZXing.Net. Without a complete sample project from you I can't help here and I don't see an issue related to the ZXing.Net nuget package.
