### ISSUE TITLE
Cannot decode EAN_13 barcode depending on section / barcode size?

### ISSUE THREAD

**Issue by MichaelUray** [micjahn/ZXing.Net#151]
Hi guys,

I am wondering why the scanner cannot decode the following two barcodes,
https://i.imgur.com/joMEi3m.png
https://i.imgur.com/6DnyqpD.png

but it can decode this one:
https://i.imgur.com/mlJSUhI.png

Any idea why this could be?

Is there actually a certain size or position of the barcode which is required in the picture?

**Comment by micjahn** [comment]
To prevent false positives zxing needs an appropriate quiet zone at the left and at the right. I think the white quiet zone at the right of your first two examples is too small.
