### ISSUE TITLE
Question about image

### ISSUE THREAD

**Issue by warrenkc** [micjahn/ZXing.Net#153]
Hello. First of all thank you so much for your hard work.
I am using this and I noticed that many qr codes are not recognized.
Even using the sample client it will not recognize the qr code. However, other qr code scanners work and can recognize it.
I have included a sample here:
![image](https://user-images.githubusercontent.com/6418791/48058742-2d1cd680-e1f2-11e8-8532-2c4aee41a633.png)
![image](https://user-images.githubusercontent.com/6418791/48058771-3d34b600-e1f2-11e8-831d-7c5bfc82a8a6.png)

**Comment by micjahn** [comment]
ZXing doesn't work very well with image which have such a big resolution.
You should generally reduce the width of the image. I tried 1024 pixel which works very well.

**Comment by warrenkc** [comment]
Thank you so much! That is very helpful information.
