### ISSUE TITLE
Read Aztec 2d Barcode

### ISSUE THREAD

**Issue by jaysolanki180** [micjahn/ZXing.Net#154]
aztec 2d barcode reading form web camera through aforge in c# not working.i try it in different way but not work.it read all QRCode from web camera but not Aztec 2d barcode.but it decode aztec  if i provide physical file path.Aforge Demo Project.

1)
LuminanceSource source = new BitmapLuminanceSource(currentBitmapForDecoding);
BinaryBitmap bitmap = new BinaryBitmap(new [HybridBinarizer(source));
Result result = new MultiFormatReader().decode(bitmap);
----------------------------------
2)
            barcodeReader = new BarcodeReader
            {
                AutoRotate = true,
                Options = new DecodingOptions
                {
                    TryHarder = true,

                    PossibleFormats = new List<BarcodeFormat> { BarcodeFormat.QR_CODE, BarcodeFormat.AZTEC}
                }
            };
         Result result = barcodeReader.Decode(currentBitmapForDecoding);

**Comment by micjahn** [comment]
Without a dump of the instance "currentBitmapForDecoding" I can't help here.
Please try the ZXing Aforge.Net demo app from the repository.
https://github.com/micjahn/ZXing.Net/tree/master/Clients/AForgeDemo
