### ISSUE TITLE
QRCode model and version

### ISSUE THREAD

**Issue by zhivko** [micjahn/ZXing.Net#156]
What to put inside **EncodeHintType QR_VERSION** to get

Model 2
Version 4
ECC level L

I have code now like this:
`
			Hashtable<EncodeHintType, String> hintMap = new Hashtable<EncodeHintType, String>();
			hintMap.put(EncodeHintType.CHARACTER_SET, "UTF-8");
			hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L.toString());
			hintMap.put(EncodeHintType.QR_VERSION, "4");
`

where or how do I set model?

**Comment by micjahn** [comment]
You can't set the model.

**Comment by zhivko** [comment]
So which one is it? 1 or 2?
http://www.qrcode.com/en/codes/model12.html

**Comment by micjahn** [comment]
I didn't write the original code but in my opinion it is model 2.
