### ISSUE TITLE
The type 'Bitmap' exists in both.... error for using both OpenCvSharp3 and .ZXing.CoreCompat same on same project

### ISSUE THREAD

**Issue by alibolugit** [micjahn/ZXing.Net#158]
Hello,
I use ZXing.CoreCompat to decode QRcode on .Net Core 2.1. As below. It works fine with qrcode image file on my pc. 
```
public static string DetectBarcode(Bitmap qrCode)
        {
            var coreCompatReader = new ZXing.CoreCompat.System.Drawing.BarcodeReader();
            var coreCompatResult = coreCompatReader.Decode(qrCode);
            return coreCompatResult.Text;
        }
```
But I should read qrcode from webcam and optimize image with OpenCvSharp3.
This code work fine. At the end, I have Mat class. 
I want to decode this Mat or byte array of this Mat with DetectBarcode that above.
When I use System.Drawing.Bitmap it get an error

The type 'Bitmap' exists in both 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

I try to use ZXing.OpenCV.BarcodeReader() as your's .net core sample. But there is no ZXing.OpenCV method on this nuget package.

How can I use both opencvsharp3 and zxing to detect and decode QRcode.

**Comment by micjahn** [comment]
In my opinion that's not an issue with ZXing.Net. If you don't use ZXing.Net but both libraries (CoreCompat and System.Drawing.Common) in one project you will get the same error.
Anyway, why do you use ZXing.Net.Bindings.CoreCompat.System.Drawing? The package ZXing.Net.Bindings.Windows.Compatibility should work better in your case, I think. Or perhaps the best solution would be the package ZXing.Net.Bindings.OpenCV which is ZXing.Net with OpenCVSharp 3. That one contains the class ZXing.OpenCV.BarcodeReader.

**Comment by micjahn** [comment]
Perhaps you are using the wrong package. I'm not sure.
The package https://www.nuget.org/packages/ZXing.Net.Bindings.OpenCVSharp.V2/
doesn't support .Net Core and it uses OpenCV Sharp V2.
The package https://www.nuget.org/packages/ZXing.Net.Bindings.OpenCV/
supports .Net standard 1.6, uses OpenCV Sharp V3 and should work with .Net Core.
Both packages definitly containing the class ZXing.OpenCV.BarcodeReader.
https://github.com/micjahn/ZXing.Net/blob/master/Source/Bindings/ZXing.OpenCVSharp.V2/BarcodeReader.cs
https://github.com/micjahn/ZXing.Net/blob/master/Source/Bindings/ZXing.OpenCVSharp.V3/BarcodeReader.cs

**Comment by alibolugit** [comment]
I use .Net Core 2.1. And also I try 2.0
The package is https://www.nuget.org/packages/ZXing.Net.Bindings.OpenCV/ 
I get "ZXing.OpenCV doesn't exist" error. But all other OpenCVSharp3 and Zxing classes exist and usable.

**Comment by micjahn** [comment]
My mistake. There is no class inside the assembly. Can't believe that I missed that. Perhaps it was lost by changing from VS 2015 to VS 2017.
Anyway, I fixed the project file and pushed a new version to nuget. Version 0.16.5 of the OpenCSSharp3 bindings should be available for download within the next few hours. It will contain the missing ZXing.OpenCV.BarcodeReader class.

**Comment by alibolugit** [comment]
Thank you, I can use class now. But there is another problem that ZXing.OpenCV.BarcodeReader doesn't decode a Mat file. The response is null. I checked mat file it was read by another app. My method is below.

```
    public static string DecodeBarcode(Mat img)
        {
            ZXing.OpenCV.BarcodeReader barcodeReader = new ZXing.OpenCV.BarcodeReader();
            var resp=barcodeReader.Decode(img);
            return resp.Text;
        }
```
