### ISSUE TITLE
Support for .NET Core (netstandard)

### ISSUE THREAD

**Issue by justdmitry** [micjahn/ZXing.Net#16]
Please add support for .NET Core (netstandard).

**Comment by micjahn** [comment]
ZXing.Net v0.15.0 supports .NET Standard 1.6. The NuGet package and the binary release contain all necessary assemblies. What are you missing?

**Comment by justdmitry** [comment]
Oops, sorry. I looked for framework list in NuGet "Dependencies" section. 

Yes, successfully installed into `netcoreapp1.1` VS2017 project.
