### ISSUE TITLE
Error creating PDF417 using a long text

### ISSUE THREAD

**Issue by anandramaswamy** [micjahn/ZXing.Net#160]
Team,

I'm trying to create a PDF417 barcode using the Nuget package in visual studio. I'm using a large text which is attached. The code i'm using is 

 **public byte[] GenerateBarCodeZXing(string data)
        {
            var writer = new BarcodeWriter
            {
                Format = BarcodeFormat.PDF_417,
                Options = new EncodingOptions { Width = 200, Height = 50, } //optional
            };
            var imgBitmap = writer.Write(data);
            using (var stream = new MemoryStream())
            {
                imgBitmap.Save(stream, ImageFormat.Png);
                return stream.ToArray();
            }
        }**

I'm getting the below error when the input data is sent to the writer. Is there any input limit ? Is there a way to increase the limit? Any help is really appreciated.

**Encoded message contains too many code words, message too big (2832 bytes)** 
[Input.txt](https://github.com/micjahn/ZXing.Net/files/2601018/Input.txt)

**Comment by micjahn** [comment]
PDF 417 theoretically can hold up to 1850 alphanumeric characters or 1108 bytes. It depends on the structure of the data. And no, there is no way to increase the limit. You can only split the data accross many separate symbols. But the PDF417 encoder doesn't support structured append.
