### ISSUE TITLE
unable to decode Datamatrix

### ISSUE THREAD

**Issue by bpopow** [micjahn/ZXing.Net#162]
Hello everyone,

im using ZXing.Net and it works good for many different barcode types, but i have trouble with decoding barcodes of the type DataMatrix. For example this one from Wikipedia: 

![wikipedia_datamatrix](https://user-images.githubusercontent.com/39404531/49077884-c14feb80-f23c-11e8-8e96-0f320aba7bbe.png)

I am creating the Barcode reader like this:

```
BarcodeReader barcodeReader = new BarcodeReader()
{
    AutoRotate = true,
    TryInverted = true,
    Options = new DecodingOptions()
    {
        TryHarder = true,
        PossibleFormats = new List<BarcodeFormat>()
        {
            BarcodeFormat.DATA_MATRIX
        }
    }
};
```

Im using the latest version of ZXing.Net 0.16.4

I have tried to add some white border which helps for some QR codes, but still no luck. Any tips on howto make this work would be appreciate, thanks!

**Comment by bpopow** [comment]
Thanks for testing this @gwynjudd. Its a bit strange that you can decode it and it does not work for me. I have tried with the options you have provided here and still do not get any result.  

Maybe im doing something wrong with the LuminanceSource i guess. Could you please post your complete example. This would really help me find the issue.

I have attached a minimal example project:
[BarcodeMinimalExample.zip](https://github.com/micjahn/ZXing.Net/files/2633824/BarcodeMinimalExample.zip)

**Comment by gwynjudd** [comment]
Hi @bpopow, I don't really have much more to add. My full example is too big to post here as it is part of a large application. But all I am doing is taking the reader as configured above, and doing a scan:

	ZXing.Result zxingResult = this.reader.Decode(bitmap);

**Comment by micjahn** [comment]
@bpopow 
your sample can't work. A RAW byte array isn't the same like a BMP encoded image in your memory stream.
RAW bytes means that it contains the pure RGB pixel data without any header, compression or other stuff.
The BmpEncoder creates a BMP encoded image which contains a header structure.

You have two options. You can go the hard way and re-implement the following luminance source implementation: https://github.com/micjahn/ZXing.Net/blob/master/Source/Bindings/ZXing.ImageSharp/ImageSharpLuminanceSource.cs
Or you try the nuget package ZXing.Net.Bindings.ImageSharp: https://www.nuget.org/packages/ZXing.Net.Bindings.ImageSharp

If you are using the nuget package you can go with the following snippet:
```
		static void Main(string[] args)
		{
			var barcodeReader = new ZXing.ImageSharp.BarcodeReader<Rgba32>
			{
				AutoRotate = true,
				TryInverted = true,
				Options = new DecodingOptions
				{
					TryHarder = true,
				}
			};
			var fileName = @"datamatrix_test.png";

			using (var image = Image.Load<Rgba32>(fileName))
			{
				var barcodeScannerResult = barcodeReader.DecodeMultiple(image);
				if (barcodeScannerResult != null)
				{
					Console.WriteLine(barcodeScannerResult[0]);
				}
			}

			Console.WriteLine("done");
			Console.ReadKey();
		}```

**Comment by bpopow** [comment]
@micjahn 
the ZXing.Net.Bindings.ImageSharp package works, i did not know about it. Thank you!

**Comment by ajlabiste** [comment]
Hi! I just found this and I want to try to make a simple Data Matrix Decoder Application. I tried installing the ZXing.Net.Bindings.ImageSharp but it returns an error. Is there any possible way aside from changing the target framework of my application? Thanks!

![image](https://user-images.githubusercontent.com/42951620/75674150-759db480-5cbf-11ea-91c9-e6f8214b5aa6.png)

**Comment by micjahn** [comment]
answered in separate issue
