### ISSUE TITLE
AutoRotate not always working for Data Matrix

### ISSUE THREAD

**Issue by Jonarw** [micjahn/ZXing.Net#165]
This is the image I'm trying to scan:
![bw6](https://user-images.githubusercontent.com/18097859/50283571-8bc2aa80-0456-11e9-9238-1ba53ecade89.png)

I use the following C# code to scan the image, using the latest ZXing.net nuget package in a .NET 4.7.1 console application:
```
    var reader = new BarcodeReader(new DataMatrixReader(), bm => new BitmapLuminanceSource(bm), ls => new HybridBinarizer(ls))
    {
        AutoRotate = true,
        Options =
        {
            PossibleFormats = new List<BarcodeFormat> {BarcodeFormat.DATA_MATRIX},
            TryHarder = true
        }
    };

    var bm = (Bitmap)Image.FromFile("bw6.png");
    var result = reader.Decode(bm);
```

The image is not recognised. 

**If I rotate the image manually by 90° clockwise, it IS recognised.**

Also, if I set up my reader like this:
`var reader = new BarcodeReader(new DataMatrixReader(), bm => new BitmapLuminanceSource(bm).rotateCounterClockwise().rotateCounterClockwise().rotateCounterClockwise(), ls => new HybridBinarizer(ls))`
the original image is recognised.

Shouldn't the AutoRotate option take care of this? Why does the rotation of the image make a difference with AutoRotate=true?

Thanks in advance!

**Comment by micjahn** [comment]
Your image works for me. I tested the image with the WindowsFormsDemo.
![grafik](https://user-images.githubusercontent.com/3475026/50305296-a61a7980-0492-11e9-97c6-07ed039f197d.png)

A small unit test with your code works, too. And the command line decoder demo of the project does also give the correct result.

**Comment by Jonarw** [comment]
Can confirm that my problem is solved when I remove the nuget package and directly add a reference to 'zxing.net4.7' from source code. It appears this problem was fixed since the last push to nuget.

Possibly related to https://github.com/micjahn/ZXing.Net/pull/143?

Would it be possibly to update the nuget package?
In any case, thanks for your help!
