### ISSUE TITLE
How to get barcode coordinates from ResultPoints

### ISSUE THREAD

**Issue by vickyrathee** [micjahn/ZXing.Net#168]
The ResultPoints return the `x,y array`. Is there a way I can use those to calculate the `width`, `height`, `left`, `top` properties of barcode found or can create a border on image using those coordinates later.

![image](https://user-images.githubusercontent.com/6106479/50671570-c00e9d00-0ff8-11e9-9e80-40f5bba8bc9b.png)

Expected result : 

```
"left": 195
"top": 327
"width": 182
"height": 95
```

Example Image 

![bc4](https://user-images.githubusercontent.com/6106479/50671630-1a0f6280-0ff9-11e9-9ffd-3f84514d68a8.jpg)

**Comment by micjahn** [comment]
Not for 1D barcodes. ZXing.Net doesn't try to find the complete area of the barcode. If it finds one single line which can be decoded it will stop and return the result. Only 2D codes like QR, DataMatrix or PDF417 will give you a rectangle of the barcode area.
