### ISSUE TITLE
Can read barcode using Android app but not zxing.net 

### ISSUE THREAD

**Issue by long1000** [micjahn/ZXing.Net#171]
![extracted](https://user-images.githubusercontent.com/12707587/51151690-b6155580-18a6-11e9-83f9-72f03825fa0d.png)

Hi, I'm unable to read the barcode in the attached image even though the quality seems fine.  
When I tried using the ZXing Android app using camera, it can read it.
Quite a few times, I encounter the situation where the android app can read it but not zxing.net
What can I do to improve the reading capability when using zxing.net ?

Thanks.

**Comment by micjahn** [comment]
I would say there are too much noise and a little warping which prevents the decoding.
The main difference between a static image and an app with a webcam is the number of pictures
which are available. If you use a webcam you will get a constant stream of images. Everyone is slightly
different from the previous one. There is a good chance that one image from the stream will work.
There is nothing you can do with other options or similar things in zxing.net. Perhaps you can write a
little image preprocessing which reduces noise and warping.
Btw. you sample image can also not be decoded by the original java implementation. You can try it online:
https://zxing.org/w/decode.jspx
