### ISSUE TITLE
NuGet out of date

### ISSUE THREAD

**Issue by drikusvd** [micjahn/ZXing.Net#172]
When will Nuget be updated with the more recent changes to the project?

**Comment by micjahn** [comment]
I'm working on it. It's a question of free time.

**Comment by mrtristan** [comment]
@micjahn are there any blockers to creating a new release here? I would dive in to making a release and hosting it internally until an official release shows up, but don't want to if there is any reason you havent done so yet (like known issues or item in progress or something along those lines).

my use case involves needing to use it for .net core and needing a bitmap to be created, which seems to be available in code but not the latest release.

thanks!

**Comment by micjahn** [comment]
Before the next release, I want to finish porting the latest changes from the java version of zxing.
Anyway, it should be possible to generate a bitmap in .Net Core with the current release. You need the base ZXing.Net package and one of the bindings to a supported image library, f.e. https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/

**Comment by rfiori** [comment]
Hi @micjahn , 
Can you inform one perspective for new release. It has lot of updates in master branch and more than one year of the last update.

**Comment by micjahn** [comment]
Q3 of 2019 is the plan

**Comment by mrutter** [comment]
Any news? Thank you.

**Comment by micjahn** [comment]
I'm working on the new release in my rare free time. Please be patient.

**Comment by mrutter** [comment]
@micjahn Thank you for your great job and for your time. I appreciate it. Can we help (maybe with a donation)? Thanks.

**Comment by micjahn** [comment]
Hopefully next week. Not absolutely sure.
I have to update the WinMD port first. Next update will be the last one which contains old .Net targets like WinMD, Silverlight and Windows Phone. That makes it a lot easier to provide new versions in the future.

**Comment by micjahn** [comment]
Version 0.16.5 was released and pushed to nuget.org. Sorry for the long delay.
