### ISSUE TITLE
Official code is not working for decoding barcode files

### ISSUE THREAD

**Issue by yogyogi** [micjahn/ZXing.Net#173]
The official code is not working anymore when using in asp.net core. 

`// create a barcode reader instance
IBarcodeReader reader = new BarcodeReader();
// load a bitmap
var barcodeBitmap = (Bitmap)Image.LoadFrom("C:\\sample-barcode-image.png");
// detect and decode the barcode inside the bitmap
var result = reader.Decode(barcodeBitmap);
// do something with the result
if (result != null)
{
   txtDecoderType.Text = result.BarcodeFormat.ToString();
   txtDecoderContent.Text = result.Text;
}`

First of all there is no method `Image.LoadFrom()` anymore in [asp.net core](http://www.yogihosting.com/category/aspnet-core/). So i have to change it to `Image.FromFile()`. 

Then on the below line of code:

`var result = reader.Decode(barcodeBitmap);`

It gets compile time error saying:

> var result = reader.Decode(barcodeBitmap);

Check this below image which shows this error:
![err](https://user-images.githubusercontent.com/13145917/51615145-2712d800-1f4d-11e9-83b7-4e4c12a0210a.png)

**Comment by micjahn** [comment]
The official code sample works for the target platform for which it is written.
If you look carefully you will find the hint in the caption that the sample is for .Net 2.0/3.5/4.x.
If you want to use it with .Net Core you have to choose an imaging library and you have to use an appropriate ZXing binding (https://www.nuget.org/packages?q=Zxing.Net.Bindings).
