### ISSUE TITLE
IBarcodeReader missing overload of Result Decode(Bitmap barcodeBitmap); when installed in ASP.NET Core 

### ISSUE THREAD

**Issue by yogyogi** [micjahn/ZXing.Net#174]
When I installed ZXing.NET in ASP.NET Core 2.0 then IBarcodeReader has only 2 overloades of Decode() instead of 3. 

The below one is missing:

`Result Decode(Bitmap barcodeBitmap);`

When I install ZXing.NET in asp.net 4.6.1 then there are 3 overload of Decode() method.

Due to this problem the below code lines do not work in asp.net core 2.0.

`var barcodeBitmap = (Bitmap)Image.FromFile("wwwroot/qrr/" + Path.GetFileName(file));`
`// detect and decode the barcode inside the bitmap`
`var result = reader.Decode(barcodeBitmap);`

Please check and update me?

**Comment by micjahn** [comment]
As I wrote in the other issue #173, .Net core doesn't contain a built-in bitmap class. So there can't be a third overload at this place.

**Comment by yogyogi** [comment]
OK micjahn. Thanks
