### ISSUE TITLE
Read Barcodes from PDF-File

### ISSUE THREAD

**Issue by haasi79** [micjahn/ZXing.Net#176]
Hello,

I would like to read the barcode from a pdf-file. Someone knows it is possible and how it works? 

regards

**Comment by micjahn** [comment]
I added very basic sample code to the Windows Forms demo client:
https://github.com/micjahn/ZXing.Net/blob/master/Clients/WindowsFormsDemo/PdfSupport.cs
and
https://github.com/micjahn/ZXing.Net/blob/master/Clients/WindowsFormsDemo/WindowsFormsDemoForm.cs
(method btnStartDecoding_Click)
