### ISSUE TITLE
can't read this QRCode witch contents Chinese

### ISSUE THREAD

**Issue by Lvlanqiu** [micjahn/ZXing.Net#177]
Dear Michael,  I'm having a trouble when using ZXing, I can't read this QRCode correctly, the result turns to be a messy code. Could you give me a hand? Thank you very much.
![tim 20190221173955](https://user-images.githubusercontent.com/23529549/53163595-66dee500-3609-11e9-875a-358295adfbd9.png)

Here's my QRCode img, and the result is messy code.

the result:
 PZA2| ·ÀÎ±Âë :480329489838299813| ｸﾖｾ�ｺﾅ :8105650001    | ｱ�ﾇｩｺﾅ :C5X8024424| ﾃｫﾖﾘ : 8860kg| ｾｻﾖﾘ

Best Regards,
A Chinese Programmer.

**Comment by micjahn** [comment]
If I try to decode your image with the WindowFormsDemo application I get the following result:

PZA2| ·ÀÎ±Âë :480329489838299813| ｸﾖｾ晗ﾅ :8105650001    | ｱ・ｩｺﾅ :C5X8024424| ﾃｫﾖﾘ : 8860kg| ｾｻﾖﾘ : 8780kg| ﾈﾕﾆﾚ :20180516| ¹æ¸ñ (mm): 2.000X0945 X00000 | ｲﾎｿｼｳ､ｶﾈ :00000 | ｵｽｸﾛﾕｾ : ﾖﾘﾇ・ｨﾉ霙・ｷ                                               | ｺﾏﾍｬｺﾅ :L8FC001583 | ÊÕ»õµ¥Î» : ±±¾©ÅôÁúÌì´´Îï×ÊÃ³Ò×ÓÐÏÞ¹«Ë¾                               | ±ê×¼¡öÅÆºÅ :Q/WG(LZ)27-2015 HC420/780DP A      | Æ·Ãû : ÀäÔþ¸Ö´ø                     | ÕÅÊý :0000 | Â¯ºÅ :B813140101| ｶﾆｲ聊ﾘﾁｿ :   -      

What result do you expect?

**Comment by micjahn** [comment]
No new information until today. I will close the issue for now. Please reopen it if you have additional information.
