### ISSUE TITLE
QR code not scanned

### ISSUE THREAD

**Issue by GOBIMANI** [micjahn/ZXing.Net#178]
![capturepng](https://user-images.githubusercontent.com/48114885/53618129-06a30100-3c10-11e9-820d-6175730c81fd.PNG)

**Comment by micjahn** [comment]
There is no guarantee that every image can be decoded. I think your sample is too blurry for such a high-density code.

**Comment by GOBIMANI** [comment]
captured image based, that qr code read some times ??how
