### ISSUE TITLE
QR

### ISSUE THREAD

**Issue by GOBIMANI** [micjahn/ZXing.Net#179]
hi @micjahn ...... am captured same card based(2 copy) scan the qr code image but one qr code is working another one is not getting information, why and how **** or please suggest any other way to rectify these issues bcz i read 10 qr code only 2 will be getting information

**Comment by micjahn** [comment]
I can't give any hints here. As I said before there is no guarantee that a qr code can be decoded. Sometimes
it is too blurry, sometimes other image artifacts prevent successful decoding.
The original java library was developed for a mobile phone scenario with a continues stream of captured image. In that case it doesn't have any impact if one or more images can't be decoded. The next one will provide better quality and can be decoded.
