### ISSUE TITLE
Replace CoreCompat.System.Drawing with System.Drawing.Common

### ISSUE THREAD

**Issue by niklr** [micjahn/ZXing.Net#180]
Since CoreCompact has been archived and is no longer maintained (https://github.com/CoreCompat/CoreCompat) maybe it would make sense to replace it entirely  with the official System.Drawing.Common library.

As far as I was able to test it, the existing bindings code in ZXing.CoreCompat.System.Drawing can be re-used 1:1. Renaming the namespace/project and replacing the package reference should be sufficient:

Old:
`<PackageReference Include="CoreCompat.System.Drawing.v2" Version="5.2.0-preview1-r131" />`
New:
`<PackageReference Include="System.Drawing.Common" Version="4.5.1" />`

**Comment by micjahn** [comment]
A new nuget package with System.Drawing.Common support from the Windows Compatibility Pack is already available (since August last year).
https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/
Or do you reference another implementation of System.Drawing.Common?
