### ISSUE TITLE
NullReferenceException while decoding (not always)

### ISSUE THREAD

**Issue by Life45** [micjahn/ZXing.Net#182]
I'm using VB and the latest NuGet version of ZXing. I was using it without a problem until two weeks ago and my code has never been changed. 

I'm using 2 timers (one for copying the graphics from screen to PictureBox with 100 ms interval and other one to decode the QR code with a interval of 1000 ms.)

`Public Class Form2`
`     18.  Dim Reader As New BarcodeReader()`
`     ...`

`312. Private Sub Timer6_Tick(sender As Object, e As EventArgs) Handles Timer6.Tick`
   `     313. Dim result As Result = Reader.Decode(pic)`
      `  314. Dim decoded As String = result.ToString().Trim()`
      `  315. QR.Text = decoded`

System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: FrozenInjector.Form2.Timer6_Tick(Object sender, EventArgs e) C:\Users\Berke\source\repos\FrozenInjector - son - Kopya\FrozenInjector\Form2.vb içinde: satır 313
   konum: System.Windows.Forms.Timer.OnTick(EventArgs e)
   konum: System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   konum: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by JeffWhitledge** [comment]
if `Reader.Decode(pic)` returns `null` then `result.ToString()` throws a `NullReferenceException`.

**Comment by micjahn** [comment]
It's not an error of the library.
You have to check result == null in your code. The result is null if there couldn't a barcode be found.
