### ISSUE TITLE
GS1 Qr Barcode generate

### ISSUE THREAD

**Issue by hilmikurt** [micjahn/ZXing.Net#187]
Hi,

I need to generate Qr code with Gs1 compatible but i couldn't get attached qr code(taken from zebraDesinger and works fine). Can someone help me which part I am doing wrong.

var barcodeWriter = new BarcodeWriter
            {

                Format = ZXing.BarcodeFormat.QR_CODE,
                Options = new ZXing.QrCode.QrCodeEncodingOptions
                {
                    Width = 126,
                    Height = 126,
                    GS1Format = true
                    
                }
            }.Write((char)29 + "91002" + (char)29 + "921" + (char)29 + "930123456789" + (char)29 + "94HM" + (char)29 + "95TR" + (char)29 + "253000000000000000000000");
            using (var memory = new MemoryStream())
            {
                using (FileStream fs = new FileStream("gs1-qrbarcode.png", FileMode.Create, FileAccess.ReadWrite))
                {
                    barcodeWriter.Save(memory, ImageFormat.Png);
                    byte[] bytes = memory.ToArray();
                    fs.Write(bytes, 0, bytes.Length);
                }
            }
![Capture](https://user-images.githubusercontent.com/14977227/57955896-cd6d5980-78ff-11e9-84cc-3a6f0264e316.PNG)

**Comment by Kim-SSi** [comment]
The following gets me a QRCode

```
string fnc = "" + (char) 29;
var barcodeWriter = new BarcodeWriter
{
    Format = ZXing.BarcodeFormat.QR_CODE,
    Options = new ZXing.QrCode.QrCodeEncodingOptions
    {
        Width = pictureBox1.Width,
        Height = pictureBox1.Height,
        GS1Format = true
    }
}.Write(fnc + "91002" + fnc + "921" + fnc + "930123456789" + fnc + "94HM" + fnc + "95TR" + fnc + "253000000000000000000000");

using (var memory = new MemoryStream())
{
    barcodeWriter.Save(memory, ImageFormat.Png);
    memory.Position = 0;
    File.WriteAllBytes("gs1-qrbarcode.png", memory.ToArray());
}
```

**Comment by hilmikurt** [comment]
Hi,

Thanks for reply.

when i check the output as raw i can see : 9100292193012345678994HM95TR253000000000000000000000

But on my attached qr code raw output is : 0123456789012345678901234567890123456789

something must be different gs-1 qr code. Still didnt get it.

**Comment by Kim-SSi** [comment]
You are writing 9100292193012345678994HM95TR253000000000000000000000 as the barcode content.
If you want 0123456789012345678901234567890123456789 then you need to set it.
Change the content writing line in my example - you need to format your content with appropriate fnc characters:
```
var bitmap = barcodeWriter.Write(fnc + "0123456789012345678901234567890123456789");
```
