### ISSUE TITLE
PackFromRgba32 method is missing(ZXing.ImageSharp.BarcodeWriter)

### ISSUE THREAD

**Issue by ScarletKuro** [micjahn/ZXing.Net#188]
Getting error when using new ImageSharp 1.0.0-beta0006, it works fine with 1.0.0-beta0003

```
private Image<Rgba32> GenerateAztec(int height, int width, string code)
{
	var aztecWriter = new ZXing.ImageSharp.BarcodeWriter<Rgba32>
	{
		Format = BarcodeFormat.AZTEC,
		Options = new EncodingOptions
		{
			Height = height,
			Width = width
		}
	};
   
	return aztecWriter.WriteAsImageSharp<Rgba32>(code);
}
```

**Comment by rlightner** [comment]
Having this same issue

**Comment by micjahn** [comment]
Please fetch the new nuget package version.

**Comment by rlightner** [comment]
I'm still seeing v0.16.4, am I pointing to the wrong feed?

**Comment by micjahn** [comment]
No. To the wrong package. Please update the binding package:
https://www.nuget.org/packages/ZXing.Net.Bindings.ImageSharp/0.16.7-beta
