### ISSUE TITLE
ZXing.Net Pharmacode

### ISSUE THREAD

**Issue by marcoripper** [micjahn/ZXing.Net#189]
Hallo 
Bin noch ziemlicher Neuling beim Programmieren .
Kann man irgendwie den Pharmacode implementieren ?

**Comment by micjahn** [comment]
Wenn ich das richtig verstehe, wird Pharmacode durch einen Code39 Barcode abgebildet. Insofern müsste es bereits jetzt (zumindest teilweise) funktionieren.
Hast Du es schon mal probiert? Hast Du einen Beispiel Code?

**Comment by marcoripper** [comment]
Hallo danke für deine Antwort.
Ja ich habe probiert ihn zu lesen funktioniert aber leider nicht.
Hab hier einen Link wo genau beschrieben ist wie der Pharmacode aufgebaut ist.
http://www.rcelectronica.com/RC/Archivos/Pharma%20Code%20specifications.pdf
Habe gesehen das jemand den Pharmacode in ZXing für Android implementiert hat, hier auch der Link dazu. 
https://github.com/ruslan2k/zxing/blob/master/README-PHARMACODE.md
Wäre sehr nett wenn du mir helfen könntest .

**Comment by micjahn** [comment]
Ich habe eine portierte Implementierung eingecheckt.
Jedoch ist der Pharmacode Reader standardmäßig nicht aktiv. Das Format ist recht simpel und ich vermute, es führt zu False-Positives. Deshalb muss man es explizit aktivieren
```
            var reader = new BarcodeReader
            {
                Options = new DecodingOptions
                {
                    PossibleFormats = new List<BarcodeFormat>
                    {
                        BarcodeFormat.PHARMA_CODE
                    }
                }
            };
```

Bis eine neues offizielles Release rauskommt, musst Du die Assembly selbst compilieren.

**Comment by marcoripper** [comment]
Herzlichen Dank für die Implementierung
Vielleicht könntest du mir nochmal auf die Sprünge helfen. Wie kriege ich den Pharma Code in VB.Net aktiviert ? Die dll Datei habe ich compiliert , Aber irgendwie bekomme ich den Pharma Code nicht aktiviert.
Vielen Dank im vorraus

**Comment by micjahn** [comment]
Jetzt musst Du mir erstmal auf die Sprünge helfen. Schick mir mal bitte ein Snippet, wie Du den Reader in VB.Net aktuell nutzt.

**Comment by marcoripper** [comment]
Erstmal vielen Dank für deine Hilfe .
So lese ich die Barcodes aus.

Imports ZXing
Imports ZXing.Common

Public reader As New BarcodeReader()

 If auswahl = 2 Then
            Try
                Dim result As Result = reader.Decode(BMP)
                Dim decode As String = result.ToString() 
                TextBox1.Text = decode
            Catch ex As Exception
            End Try
        End If

Beim Pharma Code habe ich es so probiert, jedoch leider ohne Erfolg .

 reader.Options.PossibleFormats.Add(BarcodeFormat.PHARMA_CODE)
                Dim Result As Result = reader.Decode(BMP)
                Dim decode As String = Result.ToString()
                TextBox1.Text = decode

**Comment by micjahn** [comment]
Sollte eigentlich funktionieren.
Kannst Du mir das Bild schicken, welches Du zum Testen verwendest?

**Comment by marcoripper** [comment]
Hallo 
Habe es mit mehreren Pharma Codes ausprobiert.
Hier ist mal ein Beispiel Bild.

![pharmacode](https://user-images.githubusercontent.com/51260701/59790216-b68b9f80-92cf-11e9-82ef-d62bfb929810.jpg)

**Comment by micjahn** [comment]
Bei mir funktioniert es problemlos.
![grafik](https://user-images.githubusercontent.com/3475026/59826758-339e2f80-9337-11e9-9b5f-331772c0ef72.png)
Und da mache ich auch nichts anders als Du.
Kannst Du mir ein komplettes VB Projekt mit der von dir verwendeten Zxing.dll bereitstellen?
Ich habe sonst keine Idee mehr.

**Comment by marcoripper** [comment]
Hallo
Habe hier ein kleines Beispiel Projekt mit der dll die ich verwendet habe
[Zxingtest.zip](https://github.com/micjahn/ZXing.Net/files/3315738/Zxingtest.zip)
