### ISSUE TITLE
Extra blank space on the right and bottom in the DataMatrix barcode bitmap image

### ISSUE THREAD

**Issue by sclcwwl** [micjahn/ZXing.Net#19]
I run the windowsformdemo in the  project zxing.vs2015, and found there is Extra blank space on the right and bottom in the DataMatrix barcode bitmap image when set the height and width of the barcode.

Is there a way to avoid this , because the image is too small (height = 12 or 14) when using the default  height and width?

**Comment by micjahn** [comment]
You have to use a height and width which is an integer multiple of the smallest possible datamatrix barcode.
Alternatively you use the value 1 for width and height and scale the image yourself. The renderer doesn't support anti-aliasing which leads to white borders if the width and an height not an integer multiple.

**Comment by sclcwwl** [comment]
OK, I set width and height to 84, and it works well until now.
Thank you for your quick response @micjahn
