### ISSUE TITLE
Can't read datamatrix

### ISSUE THREAD

**Issue by sikemullivan** [micjahn/ZXing.Net#191]
Hi,

I have a pretty simple datamatrix that can't be read by Zxing. I've used a few other sites, and there is no issue.

```
var reader = new BarcodeReader();
reader.Options.TryHarder = true;
reader.Options.PossibleFormats = new List<ZXing.BarcodeFormat>() { ZXing.BarcodeFormat.DATA_MATRIX };

var text = reader.Decode(image)?.Text;
```
![broken_datamatrix](https://user-images.githubusercontent.com/23320600/59081118-1e92bc80-88b2-11e9-9a01-a164db18a8dd.jpg)

**Comment by micjahn** [comment]
The datamatrix detector has trouble with the blurry edges of the black rectangles. I have no idea how to fix that. I don't know the detector code enough. Sorry.
