### ISSUE TITLE
Can't decode qr code generated by this lib

### ISSUE THREAD

**Issue by lazybnz** [micjahn/ZXing.Net#192]
QR code generated with text:
`var content = "БанкЗенитДокумент|242|2019|111||2019-06-17T12:18:47.7174750+03:00|Иной|Новое|2|2019-06-01T20:00:00.0000000+00:00";
`
but https://zxing.org/w/decode.jspx decodes this code without problem 

```
           var barcodeWriter = new BarcodeWriter
            {
                Format = BarcodeFormat.QR_CODE,
                Options = new EncodingOptions
                {
                    Height = 300,
                    Width = 300
                }
            };
            barcodeWriter.Options.Hints.Add(EncodeHintType.CHARACTER_SET, "UTF-8");

           var bitmap = barcodeWriter.Write(content);
```

and try to decode it by
```
            IBarcodeReader barcodeReader = new BarcodeReader();
            barcodeReader.Options.Hints.Add(DecodeHintType.CHARACTER_SET, "UTF-8");
            barcodeReader.Options.Hints.Add(DecodeHintType.POSSIBLE_FORMATS, new 
            List<BarcodeFormat> { BarcodeFormat.QR_CODE });
            barcodeReader.Options.Hints.Add(DecodeHintType.TRY_HARDER, true);
            
            var result = barcodeReader.Decode(bitmap);
```
and result == null

but if decode by
`var results = reader.DecodeMultiple(barcodeBitmap);`
results has one entry
tried to subscribe to reader.ResultPointFound, output:
```
resultpoint: X = 54,5 Y = 54,5
resultpoint: X = 244,5 Y = 54,5
resultpoint: X = 74,5 Y = 207
resultpoint: X = 229,5 Y = 229,5
resultpoint: X =  Y =

```
![recreate](https://user-images.githubusercontent.com/49546672/59667176-58739500-91c7-11e9-87a9-cc3cd4bb056b.png)

**Comment by micjahn** [comment]
I don't know why but the detector fails. Perhaps there is a false positive pattern.
You can workaround it if you enable AutoRotate.

**Comment by micjahn** [comment]
I know why it works with https://zxing.org/w/decode.jspx.
The online decoder uses the decoding hint "PureBarcode".
If you enable Options.PureBarcode then it works without AutoRotate (like zxing.org).

**Comment by lazybnz** [comment]
thanks, AutoRotate helped. "PureBarcode", can't use, because some images can contain mixed content - barcodes with text, or other image data. Or may be just stick with "DecodeMultiple".
