### ISSUE TITLE
ZXing.Net 0.16.4 fails to read barcode

### ISSUE THREAD

**Issue by nstrom-tn** [micjahn/ZXing.Net#194]
Sorry if this is a known issue already. The attached file will read a barcode in 0.16.2, but not in 0.16.4. 

![barcode](https://user-images.githubusercontent.com/29987000/60194826-0b677280-9808-11e9-896e-dcc56bdfea4d.png)

Example reproduction code:

            using (var image = Image.FromFile("barcode.png"))
            using (var bitmap = new Bitmap(image))
            {
                var reader = new BarcodeReader();

                // IF ZXing.Net is upgraded to 0.16.4, result will be null. It works with 0.16.2.
                var result = reader.Decode(bitmap);

                Console.WriteLine(result?.Text ?? "no barcode found");
                Console.ReadLine();
            }

**Comment by micjahn** [comment]
Thanks for reporting. Current build from source code repository decodes it successfully.
