### ISSUE TITLE
Cannot decode code_128 barcode?

### ISSUE THREAD

**Issue by flypigeon** [micjahn/ZXing.Net#198]
I try to decode barcode ，but decode result is null. How can I do decode the barcode image.
![10](https://user-images.githubusercontent.com/8320971/63070853-6f2c3300-bf4f-11e9-9402-fb59a4653186.jpg)

**Comment by micjahn** [comment]
I think the image is too blurry and has a low contrast. Try to take a clearer image is the only way in my opinion.
