### ISSUE TITLE
Not able to write more than 80 character in zxing.net library 

### ISSUE THREAD

**Issue by sonisudarshan0** [micjahn/ZXing.Net#199]
While creating barcode i have found that barcode is not generating for more than 80 characters below is my code and attached error details.

![image](https://user-images.githubusercontent.com/50704950/64023944-f506cb80-cb56-11e9-8463-08c1accec8aa.png)

error:

![image](https://user-images.githubusercontent.com/50704950/64024061-36977680-cb57-11e9-8b5e-bb9482e4ba9c.png)

**Comment by micjahn** [comment]
That limitation is taken from the original java implementation. I don't know the specification of the code 39 barcode format. Without a current spec which allows more than 80 characters, I don't want to change that validation. If you have a spec document and perhaps a pull request I will take a look.
