### ISSUE TITLE
 ITF-14 barcode checksum is not working 

### ISSUE THREAD

**Issue by sonisudarshan0** [micjahn/ZXing.Net#201]
using System;
                        using System.Drawing.Imaging;
                        using ZXing;
                        using ZXing.Common;
                        using ZXing.CoreCompat.System.Drawing;

                        namespace ConsoleApp1
                        {
                         class Program
                         {
                          private const BarcodeFormat DEFAULT_BARCODE_FORMAT = 
                             BarcodeFormat.ITF;
                          private static readonly ImageFormat DEFAULT_IMAGE_FORMAT = 
                                ImageFormat.Png;
                             private const String DEFAULT_OUTPUT_FILE = "out";
                              private const int DEFAULT_WIDTH = 500;
                             private const int DEFAULT_HEIGHT = 250;

                         static void Main(string[] args)
                         {
                           var barcodeWriter = new BarcodeWriter
                       {
                        Format = DEFAULT_BARCODE_FORMAT,
                       Options = new EncodingOptions
                          {
                                 Height = DEFAULT_HEIGHT,
                                  Width = DEFAULT_WIDTH,
                                 GS1Format = true
                          }
                           };

                              var bitmap = barcodeWriter.Write("12345678978940");

                           bitmap.Save(DEFAULT_OUTPUT_FILE, DEFAULT_IMAGE_FORMAT);
                           Console.ReadLine();
                        }
                          }
                          }

Current Image:

![image](https://user-images.githubusercontent.com/50704950/64177160-8d18f380-ce7c-11e9-944f-062d6277f2ed.png)

Expected Image:

![image](https://user-images.githubusercontent.com/50704950/64177250-bb96ce80-ce7c-11e9-9bc1-7905ff32b441.png)

**Comment by micjahn** [comment]
The ITF writer class doesn't support generating a checksum and the reader doesn't check it. The writer takes the content as-is and generates the barcode. The user of the barcode writer class is responsible that the content includes the checksum. Please open a pull request with necessary changes if you want to have builtin support.
