### ISSUE TITLE
Can't encode RSS_14 and RSS_EXPANDED barcode format

### ISSUE THREAD

**Issue by sonisudarshan0** [micjahn/ZXing.Net#203]
Here is my code:-

                using System;
                using System.Drawing.Imaging;
                using ZXing;
                using ZXing.Common;
                using ZXing.CoreCompat.System.Drawing;

                namespace ConsoleApp1
                 {
                 class Program
                   {
                   private const BarcodeFormat DEFAULT_BARCODE_FORMAT = BarcodeFormat.RSS_14;
                   private static readonly ImageFormat DEFAULT_IMAGE_FORMAT = ImageFormat.Png;
                   private const String DEFAULT_OUTPUT_FILE = "out";
                   private const int DEFAULT_WIDTH = 500;
                   private const int DEFAULT_HEIGHT = 250;

                 static void Main(string[] args)
                 {
                 var barcodeWriter = new BarcodeWriter
                {
                Format = DEFAULT_BARCODE_FORMAT,
                Options = new EncodingOptions
                {
                    Height = DEFAULT_HEIGHT,
                    Width = DEFAULT_WIDTH,
                    GS1Format = true
                }
              };

              var bitmap = barcodeWriter.Write("01234567891345");

             bitmap.Save(DEFAULT_OUTPUT_FILE, DEFAULT_IMAGE_FORMAT);
             Console.ReadLine();
             }
            }
         }

![image](https://user-images.githubusercontent.com/50704950/64422987-01dd6f00-d0c3-11e9-9b3d-56bf2db25d24.png)

![image](https://user-images.githubusercontent.com/50704950/64423354-f6d70e80-d0c3-11e9-85e8-2c0aa0ac3f21.png)

@micjahn  please provide any custom way to encode the above  barcode format or any custom way to generate GS1 databar or update this library

**Comment by micjahn** [comment]
Sorry, I can't help here. Zxing only supports decoding of RSS-14. There is no encoder. There is no custom way. I nobody else finds the free time to implement an encoder, you have to try another library.
