### ISSUE TITLE
Is there any way to change font size,style etc of barcode in zxing.net ??

### ISSUE THREAD

**Issue by sonisudarshan0** [micjahn/ZXing.Net#205]

**Comment by micjahn** [comment]
It depends on the renderer which you want to use. The different bitmap renderers and the SVG renderer supporting different fonts. The following snippet shows only one specific example. The properties which can be used, are depending on the renderer class implementation and the target .net platform.
```
var writer = new BarcodeWriter
{
    Renderer = new BitmapRenderer
    {
        TextFont = new Font(...)
    }
};
```
