### ISSUE TITLE
EAN-13, UPC-A, ITF-14 barcodes containing the numbers at bottom in the standard format

### ISSUE THREAD

**Issue by biliktamas79** [micjahn/ZXing.Net#206]
Hi!

At first, thanks for your great work so far.

Secondly: I would like to be able to generate EAN-13, ITF-14 and UPC-A barcode images containing the data string at the bottom of the generated barcodes, matching the standard format.

Now it seems that by using BarcodeWriterPixelData the Options.PureBarcode is useless, it does not output the text even if this is false. Neither the Options.GS1Format does (whatever it's use is, I did not find any documentation about the usage of the Options.GS1Format property).

I use a netcore 2.2 mstest project for evaluating your library, but the output barcode images does not contain the input data numbers.
Could you please fix the PureBarcode implementation or guide me for another renderer or solution that is able to do what I need?

my code:
`
public Bitmap RenderBarcodeBitmap(BarcodeTypeEnum type, string data, int width, int height)
        {
            if (data == null)
                throw new ArgumentNullException(nameof(data));
            if (string.IsNullOrWhiteSpace(data))
                throw new ArgumentException("String is empty or contains whitespace characters only.", nameof(data));
            if (width < 1)
                throw new ArgumentOutOfRangeException(nameof(width), "Width cannot be less than 1.");
            if (height < 1)
                throw new ArgumentOutOfRangeException(nameof(height), "Height cannot be less than 1.");

            var barCodeWriter = new Z.BarcodeWriterPixelData
            {
                Format = ToBarcodeFormat(type),
                Options = new Z.Common.EncodingOptions()
                {
                    GS1Format = true,
                    Height = height,
                    Width = width,
                    //PureBarcode = false
                }
            };

            var pixelData = barCodeWriter.Write(data);

            // creating a bitmap from the raw pixel data; if only black and white colors are used it makes no difference
            // that the pixel data ist BGRA oriented and the bitmap is initialized with RGB
            var bitmap = new Bitmap(pixelData.Width, pixelData.Height, PixelFormat.Format32bppRgb);
            var bitmapData = bitmap.LockBits(new Rectangle(0, 0, pixelData.Width, pixelData.Height), ImageLockMode.WriteOnly, PixelFormat.Format32bppRgb);
            try
            {
                // we assume that the row stride of the bitmap is aligned to 4 byte multiplied by the width of the image
                System.Runtime.InteropServices.Marshal.Copy(pixelData.Pixels, 0, bitmapData.Scan0, pixelData.Pixels.Length);
            }
            finally
            {
                bitmap.UnlockBits(bitmapData);
            }

            return bitmap;
        }
`

**Comment by biliktamas79** [comment]
Links for the standard barcode image layouts:
EAN: https://www.gs1.org/standards/barcodes/ean-upc
1D: https://www.gs1.org/standards/barcodes/1d-general-distribution

**Comment by micjahn** [comment]
The output of the content below the barcode is only supported by some of the render implementations. 
The bitmap renderer and SVG for example. The pixel data renderer doesn't have it.
Perhaps you should better use the barcode writer implementation from one of the bindings packages, f.e. https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/
It creates a bitmap object directly.
The property GS1Format is only used by the QR and Code 128 writer. If set the writers add a FNC1 control character at the first position if not already present.

**Comment by tumngust2** [comment]
> The output of the content below the barcode is only supported by some of the render implementations.

Does this mean there's no way to render bottom characters while using ZXing.ImageSharp.BarcodeWriter for example?
