### ISSUE TITLE
Cannot decode some qrcode.

### ISSUE THREAD

**Issue by shiayoung** [micjahn/ZXing.Net#207]
![352a7ced-1fe6-49d2-8349-80f2797ed462_cr1](https://user-images.githubusercontent.com/2594757/65099123-fe6ab180-d9f9-11e9-8d52-ac423876eac4.jpg)

zxing cannot decode this qrcode image, but my phone and other apps can decode.

**Comment by jplanders** [comment]
I was able to use ZXing to decode that.  You may need to test different Pixel/Bitmap formats.  That was the issue I ran into recently.

**Comment by shiayoung** [comment]
> I was able to use ZXing to decode that. You may need to test different Pixel/Bitmap formats. That was the issue I ran into recently.

Thanks, i will try that.

**Comment by shiayoung** [comment]
> I was able to use ZXing to decode that. You may need to test different Pixel/Bitmap formats. That was the issue I ran into recently.
Would you like to tell me which pixelformat is the right choice to decode above qrcode image? I tried, but failed.

**Comment by jplanders** [comment]
The pixelformat appears to be more dependent on which device you are using.  I've had different results across different android devices.  So far I've had to switch between `RGBLuminanceSource.BitmapFormat.Gray8` and `RGBLuminanceSource.BitmapFormat.RGB24` depending on the device.  Also, I was using Unity and Vuforia's CameraDevice to get image data.

**Comment by micjahn** [comment]
I tried to decode your qr code with the current windows forms demo and it worked perfectly.

**Comment by wh569860630** [comment]
mobile failed
