### ISSUE TITLE
Read QR Code from PDF file

### ISSUE THREAD

**Issue by Hrddk** [micjahn/ZXing.Net#211]
Hello,

Is there any solution for reading QR Code from PDF file?

**Comment by Sicos1977** [comment]
Use muPDF to turn the PDF pages to images and throw those into ZXing.Net

```c#
        private List<BarcodeResult> DetectBarcodesInPdf(
            string pdfFileName,
            BarcodeFormat barcodeFormat, 
            bool firstPageOnly,
            bool stopOnFirstHit)
        {
            var result = new List<BarcodeResult>();

            using (var pdfDoc = new MuPDF(pdfFileName, string.Empty))
            {
                pdfDoc.AntiAlias = _pdfAntiAlias;
           
                for (var page = 1; page <= pdfDoc.PageCount; page++)
                {
                    pdfDoc.Page = page;

                    using (var bitmap = pdfDoc.GetBitmap(_pdfRenderDpi, _pdfRenderDpi, 0, RenderType.Grayscale, true, false, 0))
                    {
                        var barcode = DetectBarcodeInBitMap(bitmap, barcodeFormat);
                        if (barcode != null)
                        {
                            barcode.Page = page;
                            result.Add(barcode);
                            if (stopOnFirstHit) break;
                        }

                        if (firstPageOnly) break;
                    }
                }
            }

            return result;
        }
```

**Comment by Hrddk** [comment]
@Sicos1977 Is this will work with dotnet core?
I looked at sourse files but there is no DLL if MuPDF in it.
Can you please guide me, how to use MuPDF to dotnetcore Application?

**Comment by micjahn** [comment]
PDF isn't supported out of the box by zxing.net. You need a third-party library like MuPDF or PdfSharp. I don't know if any of them supports .net core.
For PdfSharp there are some code samples in the WinForms demo client (for the full .net framework version 4). Take a look at the following files and methods:
https://github.com/micjahn/ZXing.Net/blob/master/Clients/WindowsFormsDemo/PdfSupport.cs
https://github.com/micjahn/ZXing.Net/blob/master/Clients/WindowsFormsDemo/WindowsFormsDemoForm.cs (method btnStartDecoding_Click)
