### ISSUE TITLE
Unity Vuforia Android 64bit Release build.  BarcodeReader.Decode() errors.

### ISSUE THREAD

**Issue by jplanders** [micjahn/ZXing.Net#212]
When running from the Unity Editor the QR codes are read without issue.  When I do a build on Android they have only been detected a handful of times but mostly result in "No QR code detected !".  I've recently implemented BugSnag and discovered that when I use the BarcodeReader to decode an image I am getting errors.  I am using version 2019.1.7f1 of Unity and the current version of Vuforia.   In Update I ensure the correct pixel format is being used:

```
PIXEL_FORMAT _mPixelFormat = PIXEL_FORMAT.UNKNOWN_FORMAT;
RGBLuminanceSource.BitmapFormat _mBitmapFormat = RGBLuminanceSource.BitmapFormat.Unknown;

#if UNITY_EDITOR
        _mPixelFormat = PIXEL_FORMAT.GRAYSCALE;        //Need Grayscale for Editor
        _mBitmapFormat = RGBLuminanceSource.BitmapFormat.Gray8;
#else
        _mPixelFormat = PIXEL_FORMAT.RGB888;               //Need RGB888 for mobile
        _mBitmapFormat = RGBLuminanceSource.BitmapFormat.RGB24;
#endif    

```
Some runtime stats:
```
{
  "unity": "2019.1.7f1",
  "osBuild": "PPR1.180610.011.G973USQS2BSI4",
  "androidApiLevel": "28",
  "unityScriptingBackend": "IL2CPP",
  "dotnetScriptingRuntime": ".NET 3.5 equivalent",
  "dotnetApiCompatibility": ".NET 2.0"
}
```
Stacktrace:

**IndexOutOfRangeException**
> <00000000000000000000000000000000>ZXing.Common.BitArray.get_Item(System.Int32 i)	
<00000000000000000000000000000000>ZXing.OneD.RSS.RSS14Reader.parseFoundFinderPattern(ZXing.Common.BitArray row, System.Int32 rowNumber, System.Boolean right, System.Int32[] startEnd)	
<00000000000000000000000000000000>ZXing.OneD.RSS.RSS14Reader.decodePair(ZXing.Common.BitArray row, System.Boolean right, System.Int32 rowNumber, System.Collections.Generic.IDictionary`2[TKey,TValue] hints)	
<00000000000000000000000000000000>ZXing.OneD.RSS.RSS14Reader.decodeRow(System.Int32 rowNumber, ZXing.Common.BitArray row, System.Collections.Generic.IDictionary`2[TKey,TValue] hints)	
<00000000000000000000000000000000>ZXing.OneD.MultiFormatOneDReader.decodeRow(System.Int32 rowNumber, ZXing.Common.BitArray row, System.Collections.Generic.IDictionary`2[TKey,TValue] hints)	
<00000000000000000000000000000000>ZXing.OneD.OneDReader.doDecode(ZXing.BinaryBitmap image, System.Collections.Generic.IDictionary`2[TKey,TValue] hints)	
<00000000000000000000000000000000>ZXing.OneD.OneDReader.decode(ZXing.BinaryBitmap image, System.Collections.Generic.IDictionary`2[TKey,TValue] hints)	
<00000000000000000000000000000000>ZXing.MultiFormatReader.decodeInternal(ZXing.BinaryBitmap image)	
<00000000000000000000000000000000>ZXing.BarcodeReaderGeneric.Decode(ZXing.LuminanceSource luminanceSource)	
<00000000000000000000000000000000>HandleQRScan.DecodeQr(System.Object state)

**Comment by micjahn** [comment]
Can you provide a dump of the instance "luminanceSource" which you use to call the method "Decode"?

**Comment by jplanders** [comment]
Sorry, I was frantically trying to figure out how to do that and now I'm not certain that I can.  I'm using the BarcodeReader's Decode method which I just pass a BitmapFormat from the RGBLuminanceSource class.

```
var data = barCodeReader.Decode(
  cameraFeed.Pixels,
  cameraFeed.BufferWidth,
  cameraFeed.BufferHeight,
  _mBitmapFormat
);
```

The instance of luminanceSource is then created inside the lib:

https://github.com/micjahn/ZXing.Net/blob/503c96e9f2796ab875c506c30106cecadcee598b/Source/lib/BarcodeReaderGeneric.cs#L417

**Comment by jplanders** [comment]
I will create the luminanceSource myself and dump that and get back with you.

**Comment by jplanders** [comment]
Turns out on android Vuforia's CameraDevice.Instance.GetCameraImage()  is returning an empty byte array with a height and width of 0.

**Comment by micjahn** [comment]
A dump of the values cameraFeed.Pixels, BufferWidth and BufferHeight would be enough for analyzing. But if I understand you right you found the problem because the method GetCameraImage doesn't give you an appropriate image, right?

**Comment by jplanders** [comment]
Correct, the dump was:

```
{
  "Matrix": [],
  "RotateSupported": true,
  "CropSupported": true,
  "InversionSupported": true,
  "Width": 0,
  "Height": 0
}
```

After seeing this I added a check to make sure they were not empty before calling Decode and switched Vuforia's PIXEL_FORMAT and RGBLuminanceSource's BitmapFormat to the value my webcam was using and it started working again.  It looks like even within the android family different devices require different formats.

Thanks for your help!
