### ISSUE TITLE
Can't find and decode DataMatrix in a document

### ISSUE THREAD

**Issue by carrotinside** [micjahn/ZXing.Net#215]
Hi,
I'm trying to locate and decode DataMatrix in a document without success.

```
var bitmap = (Bitmap)Image.FromFile(@"data_matrix_doc8.png");

var reader = new ZXing.BarcodeReader();

reader.Options.PureBarcode = false;
reader.Options.TryHarder = true;
reader.Options.ReturnCodabarStartEnd = true;
//reader.Options.PossibleFormats = new List<ZXing.BarcodeFormat> { ZXing.BarcodeFormat.DATA_MATRIX };
//reader.AutoRotate = true;
//reader.TryInverted = true;

var result = reader.Decode(bitmap);
if (result != null)
{
	Console.WriteLine(result.BarcodeFormat.ToString());
	Console.WriteLine(result.Text);
}
```
I use it with 1D codes or QRcodes with success, but with DataMatrix it has a problem.
Any idea?
Thank you.

![data_matrix_doc8](https://user-images.githubusercontent.com/56627298/66898851-416c7480-effa-11e9-91c4-0542030c360c.png)

**Comment by pavel-pv** [comment]
Hi, we are having exactly the same issue.. would appreciate any help.

Thanks.

**Comment by micjahn** [comment]
The Datamatrix detector doesn't work very well. The code has to be in the middle of the image.
The only workaround in your case would be that you cut out the upper right area and only decode that region.

**Comment by micjahn** [comment]
Btw. originally zxing was written for scanning barcodes with mobile devices which are normally used with barcodes in the center of the scanning region.

**Comment by carrotinside** [comment]
OK, thanks.

**Comment by Sicos1977** [comment]
I had something simular but I solved it by using opencvsharp to find the datamatrix, get it and place it in the middle of an image and then detect the value.

**Comment by pavanagrawal123** [comment]
@Sicos1977, can you please share your solution if possible? thank you :)

**Comment by Sicos1977** [comment]
I'll have it at work (home now) so I will share it tomorrow
