### ISSUE TITLE
Black has Alpha Channel 0

### ISSUE THREAD

**Issue by hollandar** [micjahn/ZXing.Net#22]
The default definition for Black in NET CORE is new Color(0) which has an alpha channel of 0.  This causes the SVG Renderer to render a transparent svg.

I am overriding your defaults such that Foreground = new Color() { A = 255, R = 0, B = 0, G = 0 }
Works perfectly then.

Thanks.

**Comment by micjahn** [comment]
Thanks for reporting. Now I know why I never saw an image as I tried the ASP.Net Core demo with SVG output.
