### ISSUE TITLE
Cannot decode some CODE128

### ISSUE THREAD

**Issue by maiksonstrife** [micjahn/ZXing.Net#220]
List<BarcodeFormat> codeformats = new List<BarcodeFormat>();
            codeformats.Add(BarcodeFormat.CODE_128);

        // Primeira Tentativa : ZXing
        BarcodeReader reader = new BarcodeReader
            {
                AutoRotate = true,
                TryInverted = true,
                Options =
            {
                PossibleFormats = codeformats,
                TryHarder = true,
                ReturnCodabarStartEnd = false,
                PureBarcode = false,
            }
            };

            Result res = reader.Decode(img);

![temp](https://user-images.githubusercontent.com/32269310/68401679-eb05d800-0158-11ea-93e3-e378bdf40e22.jpg)

**Comment by micjahn** [comment]
I'm really not sure what's wrong with your barcode. I looked into it with the debugger. The barcode reader decodes two values wrong which leads to a checksum mismatch. Perhaps the width of the bars are not fully correct.

**Comment by maiksonstrife** [comment]
Decreasing the width of the image and put it in bitonal solved the problem for me, thanks
