### ISSUE TITLE
Query - Can we generate a QR code that redirects user to app store or play store app?

### ISSUE THREAD

**Issue by PallaviGarg7** [micjahn/ZXing.Net#221]
Hi,

We are using ZXing to generate QR codes with given links. I have two queries- 
1. Can we create QR code using this library such that when user scans it, it opens either play store or app store to download app depending upon the phone? Basically can we create single QR code having two links?
2. Can we add background image to the QR code via code?

Thanks & Regards
Pallavi Garg

**Comment by micjahn** [comment]
You can generate a QR code with nearly every content you want. But the QR code itself doesn't open anything automatically. It depends on the barcode scanner app which is used to read the code. If that app supports opening of urls then it should work.
I don't know if there is a scanner app that can open two links. But if your goal is that you have a link to the apple app store and a second one to the google play store then perhaps there is a better solution.
You can host a redirection url on your website which redirects to the correct store depending on the http header information of the request. The QR code only contains the redirection url.

You can add a background image but you have to do it yourself. The library doesn't support it out of the box. Use the highest error correction mode for the QR code, generate the pure image with the library and then use a different image manipulation library to add a background image.

**Comment by PallaviGarg7** [comment]
Thank you so much :)
