### ISSUE TITLE
Multiple QR-Codes with zxing.interop.dll

### ISSUE THREAD

**Issue by dekoforce** [micjahn/ZXing.Net#223]
Hi,

i´m using zxing.interop.dll in my VB6 Project. Works perfect, but i want to decode multiple QR-Codes from my Image.
As i can see reader.DecodeImageFile("D:\Barcodes\QrCodes\www.png") is the only decode option.
Is there a possibility to receive more than one QR-Code?

**Comment by micjahn** [comment]
Sorry, that isn't possible a the moment. Interface and implementation has to be extended with "DecodeMultiple" methods.

**Comment by dekoforce** [comment]
What a pitty :-(
Is it a problem to implement this Feature in a later release? I would love to see that!
Thanks alot for your work!!

**Comment by micjahn** [comment]
[zxing.interop.zip](https://github.com/micjahn/ZXing.Net/files/3882592/zxing.interop.zip)
You can try this one. Not sure if it works. I didn't have the time to make enough tests.

**Comment by dekoforce** [comment]
Wow, cool! Many Thanks!
First tests are working. I will implement the stuff and go productive tomorrow.

**Comment by MuthuD** [comment]
I was looking for a qr and bar code lib and this seems to be a good one, But the open issues count gives me a wrong perception.

I would suggest to close all the answered or unwanted open issues. 

Thanks

**Comment by dekoforce** [comment]
Ok, Sorry! Needed time to test.
Multiple Barcodes working fine, I have tested 3 weeks with many scans.

**Comment by micjahn** [comment]
@dekoforce 
No need for sorry. It's not your fault. Normally I close the issues after solving it or I didn't get any response after some weeks.
