### ISSUE TITLE
Which barcodes support text?

### ISSUE THREAD

**Issue by goodmanpersonguy** [micjahn/ZXing.Net#225]
Hey there,
I would just like to know if ZXing.NET supports text for all 1D barcodes and not for 2D barcodes :)

Thanks in advance!

**Comment by micjahn** [comment]
Do you mean the text below the barcode?
It depends on the renderer implementation. The bitmap and svg renderer for example supporting all 1D codes, the raw pixel data renderer doesn't support it at all.

**Comment by goodmanpersonguy** [comment]
Thanks for your reply!

Yes, I mean the text below the barcode. So currently I use this Code

```cs
BarcodeWriter barcodeWriter = new BarcodeWriter 
{
  Format = BarcodeFormat,
  Options = new EncodingOptions 
  {
    Width = width,
    Height = height,
    PureBarcode = textOnly
  }
};

Bitmap barcode = barcodeWriter.Write(content);
```

and for testing purposes I passed in the Barcode 128 (1D) which will generate a Barcode with text. The second example is the QRcode (2D) which will not generate a text.

Just wanted to be sure that 1D barcodes support text and 2D barcodes will only generate the barcode itself 👍
