### ISSUE TITLE
Strange indentation

### ISSUE THREAD

**Issue by bsoja** [micjahn/ZXing.Net#23]
Hi, I noticed you are using strange indentation in files - 3 spaces. Is it intentional or issue caused by auto conversion or sth? 

Edit: I found many other code formatting issues and inconsistency, for example below there aren't spaces between arithmetic operators:

`float q = distance(poutd, pouta)*nbCenterLayers/(distance(pind, pina)*(nbCenterLayers + 2));`

but sometimes even in the same file, spaces appeared:

`var pinax = new ResultPoint(pina.X + 0.5f, pina.Y - 0.5f);`

**Comment by micjahn** [comment]
I wouldn't say that the indentation is strange. It is historical. When I started writing code for my first employer I had to use 3 spaces. I never changed it in the last more than 15 or 20 years.

The other inconsistency is related to the java conversion tasks. It doesn't matter for me. Sometimes if I had to fix something in a file I do reformatting the part which I have to fix.

**Comment by dave-c-whitney** [comment]
Visual Studio can automatically re-indent to the contemporary standard of 4 spaces. It'll also apply spacing around operators, etc.

**Comment by micjahn** [comment]
The main question is what is the most common standard? If I change it to 4 spaces, someone will explain that tabulators are better or more standard. My (own) good old standard  with whom I started was 3 spaces.

**Comment by dave-c-whitney** [comment]
Whatever you prefer, I guess. I've been a professional software engineer for more than 25 years and we've always used 4 spaces. It's what I'm used to, it's what VS keeps pushing whenever I type a close brace. Any edits I hope to contribute here will likely get re-indented. Re-indent as you like, of course.

**Comment by micjahn** [comment]
Indentation changed to 4 white spaces. Added .editorconfig.
