### ISSUE TITLE
BarcodeWriter generates data matrix of incorrect size depending on input

### ISSUE THREAD

**Issue by gjermund-stensrud** [micjahn/ZXing.Net#232]
I'm having a problem where the output of the BarcodeWriter varies in size depending on input.
An input of "0123456789012345" Gives the following output, which looks good to me:
![image](https://user-images.githubusercontent.com/58514637/72065766-44b48b00-32df-11ea-8e25-b456b95884a3.png)

Whereas the input of "01234567890123456" gives the following output:
![image](https://user-images.githubusercontent.com/58514637/72065808-5f86ff80-32df-11ea-95fc-fb649069ccc1.png)
It is readable by barcode readers but can cause problems when printing with low dpi as it can become too small.

The code I use is as follows using Visual Studio 2019 and .NET Core 3.1

```
var bw = new BarcodeWriter
{
  Format = BarcodeFormat.DATA_MATRIX,
  Options = new EncodingOptions { Width = 300, Height = 300 }
};
var img = bw.Write("01234567890123456");
```

Changing width and height in EncodingOptions has no effect.
Other online barcode-generation tools supporting data-matrix do not seem to have this problem.

**Comment by micjahn** [comment]
Please use the following code snippet to force the encoder to generate a square output:

```
var bw = new BarcodeWriter
{
  Format = BarcodeFormat.DATA_MATRIX,
  Options = new DatamatrixEncodingOptions 
  {
    Width = 300,
    Height = 300,
    SymbolShape = SymbolShapeHint.FORCE_SQUARE
  }
};
var img = bw.Write("01234567890123456");
```

**Comment by gjermund-stensrud** [comment]
Excellent. Thank you!
DatamatrixEncodingOptions was the missing piece I couldn't find. Will look for alternative encoding options next time I run into this kind of problem.
