### ISSUE TITLE
Incorrect method naming

### ISSUE THREAD

**Issue by Serproger** [micjahn/ZXing.Net#233]
According to standard C# conventions, methods must be named in UpperCamelCase (first letter is upper), but in many classes from this library first letter of method names is lower - QRCodeReader, QRCodeWriter etc. Please fix these problems. Popular and public accessible libraries should use correct code style.

**Comment by micjahn** [comment]
I understand your issue. But I will not change the naming of the methods. I don't have enough free time to do it and it would not add any new feature to the library nor will it fix a bug. ZXing.Net is a port of the original zxing library written in Java. All classes and methods which were ported from java kept their original names. It makes the porting of new code changes much easier.
