### ISSUE TITLE
Image quality and autofocus

### ISSUE THREAD

**Issue by gauribulbule** [micjahn/ZXing.Net#236]
Camera image quality is poor on Samsung devices. How to improve it ? Also, How to add autofocus feature? Thank you. Would appreciate your reply. Thanks.

**Comment by micjahn** [comment]
This library doesn't control the camera nor the autofocus. The decoding is based upon an image regardless where it comes from. Perhaps you are asking about some issue with a different library like this one: https://github.com/Redth/ZXing.Net.Mobile
