### ISSUE TITLE
Generate QR code with logo

### ISSUE THREAD

**Issue by BakytzhanAkzhol** [micjahn/ZXing.Net#237]
Hello, I want to generate QR code with logo like this: 
Environment: Unity3D C# 
<img src="https://user-images.githubusercontent.com/10961423/73434743-892cc700-4371-11ea-8e54-c304b72e5b13.png"  width="120" height="120">

I try to write code by examples from Internet. 
```c#
private Texture2D GenerateBarcode(string data, BarcodeFormat format, int width, int height)
{
        var encodeOptions = new EncodingOptions
        {
            Height = height,
            Width = width,
            Margin = 0,
            PureBarcode = false
        };
        encodeOptions.Hints.Add(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
        
        BarcodeWriter writer = new BarcodeWriter
        {
            Format = BarcodeFormat.QR_CODE,
            Options = encodeOptions
        };
        
        Color32[] pixels = writer.Write(text);
        Texture2D tex = new Texture2D(width, height);
        tex.SetPixels32(pixels);
        tex.Apply();
        return tex;
}
```
Q1: How i can change fill color the QR code from black color to the green color? 
Q2: How i can change "black squares" on the sides of the QR code  to another similiar figuare?
<img src="https://user-images.githubusercontent.com/10961423/73435223-71097780-4372-11ea-82e0-b9c245a91b4a.png"  width="120" height="120">

Please, help. I have no idea what i need did .

**Comment by BakytzhanAkzhol** [comment]
Wow, I understand. I can put any picture in center at QR code and it will work.

**Comment by kevin-nick** [comment]
hola saludos, y como realizaste el cambio de color y la forma de los cuadros grndes de las esquinas ??
saludos

**Comment by Unity3D-Hardik** [comment]
Is there any example for this ?

**Comment by BenetatosG** [comment]
here is a Kotlin example:
` val hints = mapOf(EncodeHintType.ERROR_CORRECTION to ErrorCorrectionLevel.H)
   val bitMatrix = qrCodeWriter.encode(text, BarcodeFormat.QR_CODE, width, height, hints)`
