### ISSUE TITLE
How i can get Metadata from QR code?

### ISSUE THREAD

**Issue by BakytzhanAkzhol** [micjahn/ZXing.Net#238]
Hello, everyone.
I need get metadata information from scanned QR code for make duplication QR code on the system. I have first QR code, but when try to generate on Zxing Library, then my new generated QR code it makes different with filled block and lines(not image logo and "white squares"), but content is same.

Scanned QR code:
<img src="https://user-images.githubusercontent.com/10961423/73514538-44aa3580-441c-11ea-8c10-03f564e08278.png" width="130"  height="130">
Generated QR code:
<img src="https://user-images.githubusercontent.com/10961423/73514684-d619a780-441c-11ea-9175-9e7549bbc05d.png" width="130" height="130">

```c#
var result = barcodeReader.Decode(rawRGB, this.ScreenWidth, this.ScreenHeight, RGB565LuminanceSource.BitmapFormat.BGR24);

 IDictionary<ResultMetadataType, object> metadata = (IDictionary<ResultMetadataType, object>)result.ResultMetadata;
                    if (metadata != null)
                    {
                        object a;
                        metadata.TryGetValue(ResultMetadataType.AZTEC_EXTRA_METADATA, out a );
                        // How i can get metadata?
                    }
```
p.s. It's function need for anti-cheat system in AR game.

**Comment by micjahn** [comment]
You are trying to get a metadata object from an Aztec code but you are decoding a QR code. That won't work.
Only the following metadata is set by the QR code reader:
ResultMetadataType.ERROR_CORRECTION_LEVEL
ResultMetadataType.BYTE_SEGMENTS
ResultMetadataType.STRUCTURED_APPEND_SEQUENCE
ResultMetadataType.STRUCTURED_APPEND_PARITY

But there is no guarantee that you will get exactly the same QR code for the same content and error correction level. QR codes are using a mask pattern which can lead to different images for the same content.
https://en.wikipedia.org/wiki/QR_code#Encoding
https://en.wikipedia.org/wiki/File:QR_Code_Mask_Patterns.svg

**Comment by BakytzhanAkzhol** [comment]
My mistake, I didn't know what i need search. I put this code as example. I have problem with read  metadata parameters.  Please, Can you show how i need read Metadata and show _logs_ from scanned QR code?  
```
ResultMetadataType.ERROR_CORRECTION_LEVEL
ResultMetadataType.BYTE_SEGMENTS
ResultMetadataType.STRUCTURED_APPEND_SEQUENCE
ResultMetadataType.STRUCTURED_APPEND_PARITY
```

**Comment by micjahn** [comment]
First, please use the newest version. The type RGB565LuminanceSource doesn't exist anymore.
In my opinion you only need ResultMetadataType.ERROR_CORRECTION_LEVEL. Byte segments are not useful in your case and structured append is only used if you have splitted data over more than one code.
And your code should work:
 object a;
metadata.TryGetValue(ResultMetadataType.ERROR_CORRECTION_LEVEL, out a );

The variable a will get the string representation of the value from type ErrorCorrectionLevel.
