### ISSUE TITLE
Using ZXing.Net with powershell only need to read one barcode of multiple barcodes in picture, always on same location in picture.

### ISSUE THREAD

**Issue by robforxdf** [micjahn/ZXing.Net#241]
Running this in powershell:
Add-Type -Path <place the path to the zxing.dll here>\zxing.dll
$reader = New-Object -TypeName ZXing.BarcodeReader
$reader.Options.TryHarder = 1 # set TryHarder option to true, other options can be set the same way
$bitmap = [System.Drawing.Bitmap]::FromFile("<path to your bitmap image file>")
$result = $reader.Decode($bitmap)
$bitmap.Dispose()
#$result.Text
$result

output from $Result:
Text           : 580-22767323
RawBytes       : 
ResultPoints   : {(775, 667), (1112, 667)}
BarcodeFormat  : CODE_39
ResultMetadata : {[ORIENTATION, 0]}
Timestamp      : 637168409811962422
NumBits        : 0

Text           : 1001529
RawBytes       : 
ResultPoints   : {(147, 1369), (374, 1369)}
BarcodeFormat  : CODE_39
ResultMetadata : {[ORIENTATION, 0]}
Timestamp      : 637168409812206563
NumBits        : 0

Text           : 06517755
RawBytes       : 
ResultPoints   : {(754,5, 435), (692, 435)}
BarcodeFormat  : UPC_E
ResultMetadata : {[ORIENTATION, 180]}
Timestamp      : 637168409821923360
NumBits        : 0

Text           : 08578114
RawBytes       : 
ResultPoints   : {(108,5, 668), (181,5, 668)}
BarcodeFormat  : UPC_E
ResultMetadata : {[ORIENTATION, 0]}
Timestamp      : 637168409834618672
NumBits        : 0

Always only need data Text from this barcode:

Text           : 1001529
RawBytes       : 
ResultPoints   : {(147, 1369), (374, 1369)}
BarcodeFormat  : CODE_39
ResultMetadata : {[ORIENTATION, 0]}
Timestamp      : 637168409812206563
NumBits        : 0

How to only read data from that location(Resultpoints) in powershell? to get Text : 1001529

Best Regards,

Robert

**Comment by micjahn** [comment]
How did you get more than one result from one call to the method Decode?
Only DecodeMultiple supports multiple results.
Anyway, if you know that you only want to get Code 39 you can restrict the barcode reader:
$reader.Options.PossibleFormats = ...

**Comment by robforxdf** [comment]
Thank you for the answer.
typo from me, i did use decode multi.
back to the questian.
how do i read from a rectangle example: rect(100, 20,80,75)
to read only that barcode.

**Comment by micjahn** [comment]
There is no built-in option or an argument that restricts the decoding process to a single code.
As I said before if you only want to get Code 39 you can use the option PossibleFormats.
If you have more than one Code 39 code inside your picture you have to crop the image before decoding so that zxing only gets the desired area ($bitmap.Clone(<rectangle>, <format>)) or you have to filter the results after the decoding process based on your needs (f.e. the length of the code or the result points).
