### ISSUE TITLE
Does ZXing.Net have a plan about generating qrcode with logo？

### ISSUE THREAD

**Issue by yaoqs** [micjahn/ZXing.Net#244]
Dear author：
Does ZXing.Net have a plan about generating qrcode with logo？
I find some code in this page (https://www.cnblogs.com/xiangzhong/p/5373822.html), and i think it's a good idea and it works well. So I wish that could be a new function in new version.
Looking forward to your answer.
Thank you!

**Comment by micjahn** [comment]
Sorry, there are no plans to add such a function. ZXing only generates QR codes that conform to the specifications. Support for logos is not included in the QR code specifications.

**Comment by yaoqs** [comment]
Thanks for answering questions in the busy schedule. I've got it

**Comment by AgrMayank** [comment]
Hi, any updates on the logo part? Is it not possible in Unity?
