### ISSUE TITLE
I have some trouble when I use  Chinese contents to create QRCode

### ISSUE THREAD

**Issue by yaoqs** [micjahn/ZXing.Net#245]
Dear author:
When I use zxing.net to generate a QRcode with Chinese contents,  the result which is decoded by zxing.net turns to be a messy code. 
such as, I used zxing.net to generate a QRcode from a character like '为' , and it turns to character '?' when I use decoder to decode this new qrcode. 
My code is likes:
```
MultiFormatWriter mutiWriter = new MultiFormatWriter();
 BitMatrix bm = mutiWriter.encode(内容.Text, BarcodeFormat.QR_CODE, 300, 300);
                Bitmap img = barcodeWriter.Write(bm);
```
It looks like something wrong in DEFAULT_ENCODING_NAME("ISO-8859-1"). Could you please provide an interface to access character sets?
look forward to your answer.
thanks.

ps：
```
EncodingOptions options = new QrCodeEncodingOptions
                {
                    DisableECI = true,
                    CharacterSet = "UTF-8",
                    //CharacterSet = "Unicode",
                    ErrorCorrection = ZXing.QrCode.Internal.ErrorCorrectionLevel.H,
                };
```
When I add these code, it couldnot work too.

**Comment by micjahn** [comment]
The following snippet works:
```
            var barcodeWriter = new BarcodeWriter
            {
                Format = BarcodeFormat.QR_CODE,
                Options = new QrCodeEncodingOptions
                {
                    CharacterSet = "UTF-8"
                }
            };
            Bitmap img = barcodeWriter.Write(内容.Text);
```

Here are two snapshots from the WindowsFormDemo client:
![grafik](https://user-images.githubusercontent.com/3475026/75184823-4c23dc80-5745-11ea-8a36-24398f205a04.png)
![grafik](https://user-images.githubusercontent.com/3475026/75184878-652c8d80-5745-11ea-9968-679942324c39.png)

**Comment by yaoqs** [comment]
Thanks very much. It do work well.

**Comment by yaoqs** [comment]
```
                MultiFormatWriter mutiWriter = new MultiFormatWriter();
                Dictionary<EncodeHintType, object> hints = new Dictionary<EncodeHintType, object>();
                //设置编码方式  
                hints.Add(EncodeHintType.CHARACTER_SET, "UTF-8");
                BitMatrix bm = mutiWriter.encode(内容.Text, BarcodeFormat.QR_CODE, 300, 300, hints);
                 Bitmap img = barcodeWriter.Write(bm);
```
It works too.
Is BarcodeWriter a better and smarter method to generate qrcode? Is MultiFormatWriter unnecessary or it can be instead of BarcodeWriter for short ?
Thanks.

**Comment by micjahn** [comment]
MultiFormatWriter ist the original class from the java project which is used by the class BarcodeWriter under the hood. BarcodeWriter only adds a more C#-like programming interface which is in some cases a little bit easier to use (like property based encoding options instead of a dictionary).

**Comment by yaoqs** [comment]
Thanks very much.
