### ISSUE TITLE
Can't Install ZXing.Net.Bindings.ImageSharp

### ISSUE THREAD

**Issue by ajlabiste** [micjahn/ZXing.Net#246]
Hi!

I am new to this library and I'm trying to find a way to make a simple Data Matrix Decoder Application.
I found a thread that suggested to use the above assembly but I can't install it using NuGet.

Is there any way to use the said assembly without changing my application's target framework?

Thanks!

Also I've attached a snip of the error.

![image](https://user-images.githubusercontent.com/42951620/75674494-18eec980-5cc0-11ea-96f2-a1f54a562953.png)

**Comment by micjahn** [comment]
Please try the new version 0.16.8-beta which contains assemblies for the target .Net 4.7.2 (like ImageSharp)
