### ISSUE TITLE
Aztec barcode rendering speed

### ISSUE THREAD

**Issue by kimbell** [micjahn/ZXing.Net#247]
We are using this library together with the Skia extension on .NET Core 3.1 to produce Aztec barcodes. 
When measuring things, it looks like producing a single Aztec barcode takes around 100 ms. 
To put things into perspective, producing an Apple Wallet file takes <10ms and reading and writing to our database takes <50ms. 

Is there any way of speeding things up?

**Comment by micjahn** [comment]
Probably yes. But I'm no expert with Skia.
I played a little bit with faster methods. Can I send you a pre-release assembly for testing the speed improvements?

**Comment by kimbell** [comment]
I can try out a prerelease if you want. 

In our case we are using it for airline boarding passes. I have created a sample program that I have used to measure things. The barcode string has been modified to contain dummy data. 

On my new i7 machine, the average time is around 100ms. 

```cs
using SkiaSharp;
using System;
using System.Diagnostics;
using System.IO;
using ZXing;
using ZXing.Aztec;
using ZXing.Common;
using ZXing.SkiaSharp;

namespace BarcodeTest
{
    class Program
    {
        static void Main(string[] args)
        {
            const string barcodeStrings = "M1SMITH/JOHN         WAHIXO OSLTRDX6 0123 065Y001F0001 348>6180 M    BX6              2A             0 X6                        N^460MEYCIQDKDY+u6mJV+IEY4tU00SLPyId8Y46XXXXXXXR8GasxhAIhAPpZunpCXXXXXXS8z9J1OM4P5/nkQxf5jjWdi/MCCgG0";

             BarcodeWriter _barcodeWriter = new BarcodeWriter
             {
                 Format = BarcodeFormat.AZTEC,
                 Options = new EncodingOptions
                 {
                     Height = 250,
                     Width = 250,
                 },
                 Encoder = new AztecWriter()
             };

            var swTotal = Stopwatch.StartNew();
            const int itt = 20;

            for (int i = 0; i < itt; i++)
            {
                using (var image = _barcodeWriter.Write(barcodeStrings))
                {                    
                    using (var memoryStream = new MemoryStream())
                    using (var managedStream = new SKManagedWStream(memoryStream))
                    {
                        SKPixmap.Encode(managedStream, image, SKEncodedImageFormat.Png, 100);

                        memoryStream.Flush();
                        var data = Convert.ToBase64String(memoryStream.ToArray());
                    }
                }
            }

            swTotal.Stop();

            Console.WriteLine($"Average Rendering Time: {swTotal.ElapsedMilliseconds / itt}");
        }
    }
}
```

**Comment by micjahn** [comment]
I used your sample code for measuring. The speed based upon my modifications looks impressive. So I built a new nuget package and uploaded it to nuget.org (version 0.16.9). Please try it.
Btw. you don't have to set the property "Encoder". And you can use the class AztecEncodingOptions instead of EncodingOptions.

             BarcodeWriter _barcodeWriter = new BarcodeWriter
             {
                 Format = BarcodeFormat.AZTEC,
                 Options = new AztecEncodingOptions
                 {
                     Height = 250,
                     Width = 250,
                 }
             };

**Comment by kimbell** [comment]
Thanks. 

I'll give it a try when I'm back in the office. 

The encoder property is something left over as I was experimenting with things.

**Comment by kimbell** [comment]
Wow. Those are are some impressive improvements. 

I'd love to see what changes you did to achieve this, but I have trouble finding the commit that looks like this change.

**Comment by micjahn** [comment]
I didn't commit it yet. But now it's online:
https://github.com/micjahn/ZXing.Net/commit/fe27b0c6fec9654bc8eaff14e7ba5a364a7e2037
The main changes are that I switched from drawing a single point into a canvas to modifying the pixel memory area directly. But I had to use some unsafe pointer access.

**Comment by kimbell** [comment]
Impressive. Haven't used pointers in any degree since I did C++ 20 years ago. 

Since we have several thousand people depending on these barcodes every day, I'm waiting on getting this tested on actual scanner machines before deploying our fix to production.

**Comment by micjahn** [comment]
Good old days with C++ ;)
And yes, there are pointers in C# but you can only use them within an unsafe context. I'm not sure if it is supported in every environment. Perhaps the old windows phone platform and silverlight didn't support it. But they are both gone away.

**Comment by micjahn** [comment]
can you talk about the application which uses zxing.net? I'm interested to know in which program the library is used.

**Comment by kimbell** [comment]
We are using it as part of a boarding pass service for an airline. This service produces boarding passes in various forms, including Apple and Google wallets. Those two platforms have built in barcode renderes that just need the string. We also have a native version running on mobile clients, this needs a PNG that we use this library to produce. 

This library is only used on servers, nothing gets distributed.
