### ISSUE TITLE
Cant Resolve Packages Unity UWP

### ISSUE THREAD

**Issue by JSWorkspace1** [micjahn/ZXing.Net#248]
To Reproduce 
1. Create fresh Unity Project
Unity Version: 2018.4.18f1
Scripting Runtime Version .Net 4.x Equivalent 
Scripting Backend IL2CPP 
Targeting: UWP x86  (hololens)
2. import ZXing.net.0.16.5 via Nuget 

Result This Exception:
`Assembly 'Assets/Packages/ZXing.Net.0.16.5/lib/net47/zxing.presentation.dll' will not be loaded due to errors:
Unable to resolve reference 'PresentationCore'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
`
when trying to build  this Exception:
`ArgumentException: The Assembly PresentationCore is referenced by zxing.presentation ('Assets/Packages/ZXing.Net.0.16.5/lib/net47/zxing.presentation.dll'). But the dll is not allowed to be included or could not be found.`

Is this a Bug or is my Environment not Supported ?

**Comment by micjahn** [comment]
If possible skip using the assembly zxing.presentation.dll. You should only use zxing.dll.
But I have no experience with unity and nuget. In the past I added the zxing assembly manually to the unity project.
In the release section https://github.com/micjahn/ZXing.Net/releases you will find a zip archive with all the binaries. There is a special build of zxing.net inside the archive (unity\zxing.unity.dll) which isn't included in the nuget package.

**Comment by JSWorkspace1** [comment]
Thank you. Simply deleting the presentation.dll from the nuget Packet did resolve the issue.
Reading QR-Code worked both in the editor and build on the holoLens1.
Closing Issue. 
However i think using nuget for unity is quite common and others will probably run into the same problem. I would recommend at least mentioning a solution in the documentation or offer the unity.dll in its own nuget. 
Out of curiosity what are the differences in between the nuget Packet and the unity.dll?

**Comment by micjahn** [comment]
The zxing.unity assembly contains a barcode reader and writer which support the Color32 type directly. And there is an issue with two attributes which aren't included in the zxing.unity dll.
https://github.com/micjahn/ZXing.Net/issues/6
https://github.com/micjahn/ZXing.Net/issues/75
Not sure if this problem exists with the newest version of unity.
