### ISSUE TITLE
Low quanlity code can not recognize

### ISSUE THREAD

**Issue by pardont** [micjahn/ZXing.Net#250]
Hi, I qry to recognize qrcode on PCB, but the qrcode can not be recognized. 

I attach the sample image, please help. many apps can reconize the qrcode by scanning the sample image directly.
![code1](https://user-images.githubusercontent.com/2252587/76582851-741b8a00-6512-11ea-874b-8a84975a9161.png)

**Comment by micjahn** [comment]
Sorry, there is nothing I can do here. There is no guarantee that every barcode can be decoded with zxing. You should try to capture an image with a better quality.
