### ISSUE TITLE
SIGABRT: Text and bytes are null

### ISSUE THREAD

**Issue by Logan2014** [micjahn/ZXing.Net#253]
Hi, we use your library for over 4k Android and iOS users combined. And five of our users occasionally catch app crash when they open Scanner fragment and start scanning. Here is stack trace:
`ZXing.Result..ctor (System.String text, System.Byte[] rawBytes, System.Int32 numBits, ZXing.ResultPoint[] resultPoints, ZXing.BarcodeFormat format, System.Int64 timestamp) <0x106eea580 + 0x00154> in <ccd33a3710ff407d90a31fb75c8c27de#de643ba3b52c33ba31a870a5ee74f6fd>:0
ZXing.Result..ctor (System.String text, System.Byte[] rawBytes, ZXing.ResultPoint[] resultPoints, ZXing.BarcodeFormat format) <0x106eea3d0 + 0x00093> in <ccd33a3710ff407d90a31fb75c8c27de#de643ba3b52c33ba31a870a5ee74f6fd>:0
AVCaptureScannerView+<>c__DisplayClass32_0.<SetupCaptureSession>b__0 (System.Collections.Generic.IEnumerable`1[T] metaDataObjects)
CaptureDelegate.DidOutputMetadataObjects (AVFoundation.AVCaptureMetadataOutput captureOutput, AVFoundation.AVMetadataObject[] metadataObjects, AVFoundation.AVCaptureConnection connection)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)`

All crashes happened at iOS 13.x.
We use Zing.Net.Mobile 2.4.1 and this scanning options:
```csharp
{
    UseNativeScanning = true,
    UseFrontCameraIfAvailable = false,
    TryInverted = true,
    TryHarder = false,
    AutoRotate = false
}
```

As you can see this exception happens in lambda function in SetupCaptureSession method and related to ZXing.Result constructor.  Maybe some text scanned too fast or scanned text converted to null due to wrong format, but this cases should not cause app to crash.

Each user catch this exception just ones. They crash app when first-time enter scanner Fragment or even after they successfully scan before. Some crashes happened after a second, when Scanner fragment opens, others - happened after a while (see CaptureDelegate.DidOutputMetadataObjects call at stacktrace, maybe some system message caused this exception)

**Comment by micjahn** [comment]
Sorry, I can only help with issues that are related to ZXing.Net. Your issue targets the ZXing.Net.Mobile project. Please open a new issue here: https://github.com/Redth/ZXing.Net.Mobile
Anyway, I think the following value is null: readableObj.StringValue
It's located in the following file at line 211:
https://github.com/Redth/ZXing.Net.Mobile/blob/master/ZXing.Net.Mobile/iOS/AVCaptureScannerView.ios.cs
This only happens when the builtin scanner of iOS via AVCaptureSession is used.
