### ISSUE TITLE
Code128 max length constant

### ISSUE THREAD

**Issue by kinguru** [micjahn/ZXing.Net#254]
https://github.com/micjahn/ZXing.Net/blob/2310b9c1c8a57224f38e0ae3c4b0d95e77501302/Source/lib/oned/Code128Writer.cs#L96-L100

It is really need a public constant with maximum Code128 length. To check input string for a max length before encoding and trim it to avoid runtime exception.

BTW, why only 80 characters? Code128 wikipedia document said that Code128 could contain 103 data characters.

**Comment by micjahn** [comment]
This restriction was originally introduced in the java version before I ported the code to .net. I have no idea why there is that restriction.
I checked the definition for code 128 at wikipedia. One point is wrong. There are 103 data symbols to encode the content and not a restriction to 103 characters at all. To be clear, the definition of code 128 doesn't restrict the length of the content at all.
I removed the check and generated a code 128 barcode image with 176 alphanumeric characters without any problems. This one could be decoded by different barcode readers without any problems.
I think I will remove that validation from the code base.
![Code_128_with_length_of_176_characters](https://user-images.githubusercontent.com/3475026/78397847-42b64b80-75f2-11ea-8675-5e25b948d270.png)
