### ISSUE TITLE
How to specify Code128 width?

### ISSUE THREAD

**Issue by kinguru** [micjahn/ZXing.Net#255]
I need an ability to specify concrete width or max-width for a Code128.
This is needed as images will be printed on a concrete size paper. So I can't do it more than width limit.
Looks like there is no such feature as of now?
 My code is below. Width is not taken into account.

`var barcodeWriter = new BarcodeWriter
{
                Format = BarcodeFormat.CODE_128,
                Options = new Code128EncodingOptions { Width = width, Height = height, PureBarcode = true, Margin = 0 }
            };
            var result = barcodeWriter.Write(jGuid.Newid());`

**Comment by micjahn** [comment]
You should encode the content with a width of 0 like the following snippet shows and after that resize it to your desired size. This gives you full control over the resulting image size.

```
var writer = new BarcodeWriter
{
   Format = BarcodeFormat.CODE_128,
   Options = new Code128EncodingOptions
   {
      Width = 0,
      Height = height,
      PureBarcode = true,
      Margin = 0
   }
};
var result = barcodeWriter.Write(jGuid.Newid());
```
You will get a barcode image with the smallest possible width. Now you can scale it to your output size:
```
var resized = new Bitmap(result, new Size(width, height));
```

**Comment by micjahn** [comment]
Btw. width is taken into account but ZXing.Net can resize only by integer values. There is no anti-aliasing support.

**Comment by kinguru** [comment]
Thank you

**Comment by aledut** [comment]
> "You should encode the content with a width of 0 like the following snippet shows and after that resize it to your desired size."


This generates a blurry image

**Comment by micjahn** [comment]
Do you have a code sample that shows what you have tried?
