### ISSUE TITLE
QR code unexpected margin

### ISSUE THREAD

**Issue by kinguru** [micjahn/ZXing.Net#256]
Hi, I'm creating a simple QR code from GUID
The code is:
var barcodeWriter = new BarcodeWriter();
barcodeWriter.Format = BarcodeFormat.QR_CODE;
barcodeWriter.Options = new QrCodeEncodingOptions { Width = size.Width, Height = size.Height, PureBarcode = true, Margin = 0 };
var result = barcodeWriter.Write(jobGUID.ToString());

In case QR code size > 86px it generates withour maring. If 86 or less it adds 10-12 pixels margins.
I'm confused trying to position generated QR code :) Why it adds margin if i set margin=0?

**Comment by micjahn** [comment]
It doesn't really add a margin. It does some kind of padding to the requested size if the generated code doesn't fully fit. As I wrote here: #255, ZXing.Net can resize only by integer values. There is no anti-aliasing support.

**Comment by micjahn** [comment]
And the same advice here: generate the image with a width and height of 0. This give you the smallest possible image which you can resize afterwards.

**Comment by kinguru** [comment]
Why i have unexpected margin for qr code less then 86 px?
I can't position it on my label. Because margin is unknown. Why 87 px qr is without margin? Magic ;)

**Comment by micjahn** [comment]
It's not magic, it's not a margin, it is padding to fit the image to the requested size.
You can do it this way to prevent padding:
```
var writer = new BarcodeWriter
{
   Format = BarcodeFormat.QR_CODE,
   Options = new QrCodeEncodingOptions
   {
      Width = 0,
      Height = 0,
      PureBarcode = true,
      Margin = 0
   }
};
var result = barcodeWriter.Write(jobGUID.ToString());
```

You will get a barcode image with the smallest possible size. Now you can scale it to your output size:

`var resized = new Bitmap(result, new Size(width, height));
`

**Comment by joaommvsoares** [comment]
> It's not magic, it's not a margin, it is padding to fit the image to the requested size.
> You can do it this way to prevent padding:
> 
> ```
> var writer = new BarcodeWriter
> {
>    Format = BarcodeFormat.QR_CODE,
>    Options = new QrCodeEncodingOptions
>    {
>       Width = 0,
>       Height = 0,
>       PureBarcode = true,
>       Margin = 0
>    }
> };
> var result = barcodeWriter.Write(jobGUID.ToString());
> ```
> 
> You will get a barcode image with the smallest possible size. Now you can scale it to your output size:
> 
> `var resized = new Bitmap(result, new Size(width, height)); `

It get blurry...
Ain't nothing that you can do?
One improment would be returning the image without the padding, then we could resize it (or you) and it would have less blurr...

**Comment by micjahn** [comment]
I don't understand what you mean. If you create the code with Width = 0 and Height = 0 you will get the smallest possible image without any margin or padding. Then you can resize it in any direction, with any possible algorithm, with anti-aliasing and without, resize it by integer or float values, get it blurry or sharp, use an image manipulation library of your choice. It's up to you. The smallest possible image is the best base for all kind of individual resizing.

**Comment by joaommvsoares** [comment]
Your suggestion take a lok of computation (time), I need it to be fast!
Explaining my suggestion:
Imagime that you generate a QrCode with 200x200px with a certain text, but the generated code uses only 180x180px and "you" make a padding of 10px. 
I suggest that you create another parameter (NoPagging) that when it's value is TRUE will render a final Bitmap with 180x180px and 0 padding.

**Comment by Likenttt** [comment]
How to generate a qrcode as big as possible given a width & height

**Comment by micjahn** [comment]
Option EncodeHintType.NO_PADDING/EncodingOptions.NoPadding added
