### ISSUE TITLE
Add Support OMR Sheet Recognition?

### ISSUE THREAD

**Issue by sayeduzzamancuet** [micjahn/ZXing.Net#257]
Is it possible to add OMR sheet recognition using this library?

**Comment by micjahn** [comment]
Do you mean something like this: https://en.wikipedia.org/wiki/Optical_Mark_Recognition
Generally I don't have enough free time to add a complete new barcode format.
In your case I think it isn't a barcode at all. So in my opinion it doesn't fit to the goals of this library here. There are other ones which are specialized to OMR, I think,
