### ISSUE TITLE
BitmapRenderer for netstandard

### ISSUE THREAD

**Issue by Lunat1q** [micjahn/ZXing.Net#258]
Greetings!

For some reason BitmapRenderer is not available for netstandard assemblies, is that possible to add it there?

**Comment by micjahn** [comment]
.Net standard 1.0 to 2.0 are missing some classes which are necessary for bitmap support. But there are some special nuget packages which are adding the missing support by using other libraries.
You can find them by looking for "zxing bindings" at nuget.org:
https://www.nuget.org/packages?q=zxing+bindings

**Comment by Lunat1q** [comment]
But, for 2.0 it's not, I've just copy-pasted BitmapRenderer to my netstandard2.0 project and it works.

**Comment by micjahn** [comment]
I don't know which the target framework of your project is but it can't be a pure .net standard 2.0 implementation. You can take a look into the docs of the Bitmap class for example: https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap?#moniker-applies-to
You will that it isn't supported by .net standard 2.0. Perhaps your project is targetting .net core 3.0 which implements .net standard 2.1.

**Comment by Lunat1q** [comment]
https://apisof.net/catalog/System.Drawing.Bitmap 
According to this, that is available with .netstandard 2.0 + PlatformExtensions. And my project is .netstandard 2.0.

**Comment by jackletter** [comment]
![image](https://user-images.githubusercontent.com/15626065/83235096-ede31b80-a1c3-11ea-9162-b45424ecfa86.png)

![image](https://user-images.githubusercontent.com/15626065/83235343-4dd9c200-a1c4-11ea-9c2c-186e61fa0229.png)


ZXing.Windows.Compatibility The code of is also netstandard, version = 2.0.0.0 environment, and there are only a few classes. Why not write it directly ZXing.net ?

**Comment by micjahn** [comment]
Because not everybody needs a dependency to System.Drawing.Common from the Compatibility Pack.
There are a couple of other imaging libraries which are useable with the ZXing.Net core functionality. So I decided to divide the whole system into the core classes without a specific image library (based upon the available features of the .net standard version) and the binding classes. So you can pick the components for your needs out of the different packages.

**Comment by wtujvk** [comment]
ZXing.Windows.Compatibility only enable in  window, but not in linux

**Comment by wtujvk** [comment]
copy 'BitmapRenderer' and 'BarcodeWriter' class from netfreamwork version  to netcore version 。
Both set Options.Margin =0,   but in netfreamwork it margin 10px , in netcore it ablut 1px。


![core](https://user-images.githubusercontent.com/17868266/94511908-35021b80-024d-11eb-8949-58a5adc9c5bb.png)
![netframework](https://user-images.githubusercontent.com/17868266/94511911-36334880-024d-11eb-8af6-c3b06ea3959a.png)

Anyway set ?

**Comment by wtujvk** [comment]
copy 'BitmapRenderer' and 'BarcodeWriter' class from netfreamwork version to netcore version 。
Both set Options.Margin =0, but in netfreamwork it margin 10px , in netcore it ablut 1px。

netframework
![netframework](https://user-images.githubusercontent.com/17868266/94512956-08033800-0250-11eb-80d8-7a375630e362.png)

core
![core](https://user-images.githubusercontent.com/17868266/94512955-076aa180-0250-11eb-9cd9-71861db353fb.png)




Anyway to set ?

**Comment by micjahn** [comment]
The following code snippet generates a qr code without any margin / quiet zone for both, full framework and .net core.
```
                var writer = new BarcodeWriter
                {
                    Format = BarcodeFormat.QR_CODE,
                    Options = new ZXing.QrCode.QrCodeEncodingOptions
                    {
                        Height = 0,
                        Width = 0,
                        Margin = 0
                    }
                };
                var bitmap = writer.Write("<content here>");
```
