### ISSUE TITLE
How can the width get changed?

### ISSUE THREAD

**Issue by TJay159** [micjahn/ZXing.Net#26]
I'm working on where a barcode will form when a button is pressed but for some reason the width won't change, it stays tiny, this is in Unity 5.5.

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using ZXing;
using ZXing.Rendering;

public class Barcode : MonoBehaviour {

	//public float calcPrice;
	public static float price;
	public static string print;
	public static bool error = false;
	private bool show = false;
	public GameObject generateBttn;

	[SerializeField] Button Bcode;

	public Calculator calc;


    // Use this for initialization
    void Awake () {
		calc = GetComponent<Calculator> ();
	}
	
	// Update is called once per frame
	void Update () {
		if (show) {
			generateBttn.GetComponent<Image> ().color = Color.green;
		} else {
			generateBttn.GetComponent<Image> ().color = Color.red;
		}
		if (error) {
			errorMessage ();
		}
		price = Mathf.RoundToInt (calc.chargePrice);
	}

	public void reset(){
		error = false;
	}

	public void setCode(float charge){
		price = Mathf.RoundToInt (calc.chargePrice);
	}

	private static Color32[] Encode (string textForEncoding, int width, int height)
	{
		var writer = new BarcodeWriter {
			Format = BarcodeFormat.CODE_39,
			Options = new ZXing.Common.EncodingOptions 
			{Height = height,Width = width}
		};
			if (price < 0) {
				print =  ("02043541000" + price);
			}
			else if (price < 10 && price >= 0) {
				print =  ("0204354100" + price + "99");
			}
			else if (price < 100 && price >= 10) {
				print =  ("020435410" + price + "99");
			}
			else if (price >= 100 && price < 1000) {
				print =  ("02043541" + price + "99");
			}
			else if (price > 1000) {
				print = 00000.ToString();
				error = true;
				//errorMessage ();
			}
		//}
		return writer.Write (print);
	}

	public void errorMessage(){
		show = false;
		calc.barcodeError ("There has been an error, app is not calibrated to print barcodes over $1,000.00. We appologize for the inconvenience");
		error = false;
	}

	public Texture2D generateCode(string text) {
		var encoded = new Texture2D (256, 300); //256
		var color32 = Encode (text, encoded.width, encoded.height);
		encoded.SetPixels32 (color32);
		encoded.Apply ();
		return encoded;
	}

	public void showBrcode(){
			if (show) {
				show = false;
			} else {
				show = true;
			}
	}

	void OnGUI(){
		if (show && price != 0) {
			Texture2D bbCode = generateCode ("Arrangement");
			if (GUI.Button (new Rect ( Screen.width/2, Screen.height/2, 1000, 500), bbCode, GUIStyle.none)) {
			}
			;
		}
	}
}
```

"var encoded = new Texture2D (256, 300); //256" 
when I change the variables here the only variable that takes effect is the height but the width will stay the same even after changing the variable.
Am I missing something or is there a different way of changing the width?

**Comment by micjahn** [comment]
The BarcodeWriter does not support anti-aliasing. You can only stretch the image by an integer number.
For example, if the minimum width of the barcode is 200, then the next supported width is is 400. Every value between this two numbers leads only to a bigger white area at the left and right side of the barcode image.

You should be able to make the barcode with the value 1 for the width. The BarcodeWriter selects the smallest possible width automatically. After that you use the Color32 array with the Texture2D instance and the desired size. Now it should be possible to do the stretching. As far as I know you have
to use something like TextureScale:
http://wiki.unity3d.com/index.php?title=TextureScale
Not sure if it works. I can't test it.

`	public Texture2D generateCode(string text) {
		var color32 = Encode (text, 1, 256);
		var encoded = new Texture2D (color32.Length / 256, 256);
		encoded.SetPixels32 (color32);
		encoded.Apply ();
		TextureScale.Bilinear(encoded, 500, 256);
		return encoded;
	}`
