### ISSUE TITLE
[V0.16.5] DataMatrix decoder occasionally throws NullReferenceException

### ISSUE THREAD

**Issue by Johnson-Hsu** [micjahn/ZXing.Net#260]
Hi,

I am trying to decode DataMatrix and encountered occasional exceptions:

> System.NullReferenceException: 'Object reference not set to an instance of an object.'

>    at ZXing.Datamatrix.Internal.BitMatrixParser..ctor(BitMatrix bitMatrix)
>    at ZXing.Datamatrix.Internal.Decoder.decode(BitMatrix bits)
>    at ZXing.Datamatrix.DataMatrixReader.decode(BinaryBitmap image, IDictionary`2 hints)
>    at ZXing.MultiFormatReader.decodeInternal(BinaryBitmap image)
>    at ZXing.BarcodeReaderGeneric.Decode(LuminanceSource luminanceSource)

This is the image triggering the exception. It is not the DataMatrix on the phone causing problems, the exception is occasional all the time.
<img width="213" alt="20200502_000736" src="https://user-images.githubusercontent.com/53847608/80820489-8b6d1e80-8c09-11ea-84aa-c610f62d3a0f.png">

I'm using WPF (.NET Core 3.1) with the following snippet,
```
var bmp = openCvMat.ToBitmap();
var bmpSrc = bmp.ToImageSource();
var src = new BitmapSourceLuminanceSource(bmpSrc);
var reader = new BarcodeReader(null, null, lr => new HybridBinarizer(lr))
{
	AutoRotate = true,
	Options = new DecodingOptions()
	{
		PossibleFormats = new[]
		{
			BarcodeFormat.QR_CODE,
			BarcodeFormat.DATA_MATRIX
		}
	}
};

var result = reader.Decode(src);
```

Also, DataMatrix decoder is very sensitive to angle. The 2D code must be horizontally or vertically aligned by one side to be successfully decoded. Arbitrary angles would fail to decode even the image is clear. Am I using it wrong?

**Comment by micjahn** [comment]
The NullReferenceException will be fixed with the next version (#242).
The datamatrix decoder isn't perfect. It has some constraints to the image to find a code (f.e. the code has to be in the middle of the image).

Btw., there are two nuget packages with bindings for OpenCV. If you use one of them you don't have to convert the Mat object to a bitmap or image source object. The BarcodeReader class inside the package directly uses a Mat instance.

**Comment by carlcyber** [comment]
Great! Thank you for the help and tips.

**Comment by Johnson-Hsu** [comment]
Great! Thank you for the help and tips.

**Comment by mpaul9** [comment]
Hello

Unfortunately I have the same problem, but cannot deactivate the DataMatrix code. Is there another workaround? When do you plan to release the fixed version?
Thanks a lot!

**Comment by micjahn** [comment]
Hopefully next week.

**Comment by rbdv159** [comment]
+ 1
