### ISSUE TITLE
Having problems reading barcode in UPC A format

### ISSUE THREAD

**Issue by jeffattilted** [micjahn/ZXing.Net#261]
The following code reads EAN_13 like a champ. But can't detect UPC A codes. Here's my code.

```
using (var magickImage = new ImageMagick.MagickImage(fs))
                    {
                        magickImage.Grayscale();
                        magickImage.Sharpen();
                        var reader = new BarcodeReader
                        {
                            Options =
                            {
                                TryHarder = true,
                                PossibleFormats = new List<BarcodeFormat>()
                                {
                                    BarcodeFormat.CODE_93,
                                    BarcodeFormat.CODE_128,
                                    BarcodeFormat.CODE_39,
                                    BarcodeFormat.EAN_8,
                                    BarcodeFormat.EAN_13,
                                    BarcodeFormat.UPC_EAN_EXTENSION,
                                    BarcodeFormat.UPC_A,
                                    BarcodeFormat.ITF,
                                }
                            },
                            AutoRotate = true,
                            TryInverted =true
                        };


                        var result = reader.Decode(magickImage);
                        if (result != null)
                        {
                            res.format = result.BarcodeFormat.ToString();
                            res.result = result.Text;
                        }
                    }
```

I've attached the UPC image. Am I missing something here? Been trying to get this to read for several hours now.
![IMG_5573](https://user-images.githubusercontent.com/64328786/81222230-94634480-8fa9-11ea-8ab3-ecdfc5435cf5.jpg)

**Comment by micjahn** [comment]
The resolution is too high, there is too much noise around the bars. Shrink the image by 50% or use a lower resolution for the webcam.
![grafik](https://user-images.githubusercontent.com/3475026/81228258-15442f80-8fee-11ea-8a0d-a4d49496fe4d.png)

**Comment by jeffattilted** [comment]
> The resolution is too high, there is too much noise around the bars. Shrink the image by 50% or use a lower resolution for the webcam.
> ![grafik](https://user-images.githubusercontent.com/3475026/81228258-15442f80-8fee-11ea-8a0d-a4d49496fe4d.png)

That was exactly it, thanks for the quick response. This library is awesome, great work!
