### ISSUE TITLE
BitmapLuminanceSource not available in Version 0.16.5

### ISSUE THREAD

**Issue by GhostSource** [micjahn/ZXing.Net#263]
Hi all,

I've just installed the latest version of ZXing.Net from NuGet.org (0.16.5). Unfortunately, I cannot find the class "BitmapLuminanceSource.cs". It sais: "Cannot resolve symbol BitmapLuminanceSource".

How can I solve this issue? I really don't want to copy the file from the Git repository myself.

I'm running on .NET Core 3.1 if this is important for you guys.

EDIT: I guess, it's because BitmapLuminanceSource relies on PresentationCore which is not compatible with .NET Core. Can you confirm this?

Thank you very much in advance.
GhostSource

**Comment by micjahn** [comment]
ZXing.Net 0.16.5 only supports .Net Standard 2.0. Bitmap support isn't included in .Net Standard 2.0.
Next version of ZXing.net will support .Net CoreApp 3.0 and will include bitmap support.
Meanwhile you can try some of the binding packages instead.
https://www.nuget.org/packages?q=ZXing.Net.Bindings
