### ISSUE TITLE
QRCode GS1 Identification

### ISSUE THREAD

**Issue by Int32Overflow** [micjahn/ZXing.Net#267]
Dear ZXing Team,

i have a GS1 QRCode and one without GS1 which i read through this library.
Can I identify which code is GS1?

**Comment by micjahn** [comment]
I'm not absolutely sure but there should be a specific identifier at the beginning of the result.
You can take a look into the GS1 specification here:
https://www.gs1.org/sites/default/files/docs/barcodes/GS1_General_Specifications.pdf
The GS1 QR data format is documented at 5.7.4.3.

"The GS1 system requires the use of symbology identifiers. GS1 QR Code uses the symbology identifier of ]Q3(see figure5.7.4.3-1) ..."

"For example, a GS1 QR Code symbol encoding AI (01) element string 10012345678902 produces the transmitted data string “]Q30110012345678902.” "

**Comment by Int32Overflow** [comment]
> 
> 
> I'm not absolutely sure but there should be a specific identifier at the beginning of the result.
> You can take a look into the GS1 specification here:
> https://www.gs1.org/sites/default/files/docs/barcodes/GS1_General_Specifications.pdf
> The GS1 QR data format is documented at 5.7.4.3.
> 
> "The GS1 system requires the use of symbology identifiers. GS1 QR Code uses the symbology identifier of ]Q3(see figure5.7.4.3-1) ..."
> 
> "For example, a GS1 QR Code symbol encoding AI (01) element string 10012345678902 produces the transmitted data string “]Q30110012345678902.” "


But that seems to be exactly the problem. When decoding a GS1 QR code, FNC1 is not appended to the text at the beginning. In the raw data the first byte contains the correct flag for FNC1. Means the code is correct!

According to the GS1 specification every GS1 code must start with an FNC1.
