### ISSUE TITLE
EAN13 label not proper generate

### ISSUE THREAD

**Issue by mayurjansari** [micjahn/ZXing.Net#269]
`BarcodeWriter barcode = null;
                try
                {
                    barcode = new BarcodeWriter { Format = format, Options = Option
                        bmp = barcode.Write(text);
                }
                catch (Exception ex)
                {
                    ex.log();
                    barcode = new BarcodeWriter { Format = format };
                    bmp = barcode.Write(text);
                }`

![Preview 11_08_2020 12_59_24 PM](https://user-images.githubusercontent.com/18002706/89872879-38771000-dbd7-11ea-89e0-e0d240f16ebe.png)

I am also trying to do this but not got success 

[zxing ean13 barcode encoding with 'lead', 'separator' and 'trailer'](https://stackoverflow.com/questions/24408954/zxing-ean13-barcode-encoding-with-lead-separator-and-trailer)

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ZXing;
using ZXing.Common;
using ZXing.OneD;

namespace PdfCard
{

    public class EAN13WriterJava : OneDimensionalCodeWriter
    {

        //  For an EAN-13 barcode, the first digit is represented by the parities used
        //  to encode the next six digits, according to the table below. For example,
        //  if the barcode is 5 123456 789012 then the value of the first digit is
        //  signified by using odd for '1', even for '2', even for '3', odd for '4',
        //  odd for '5', and even for '6'. See http://en.wikipedia.org/wiki/EAN-13
        // 
        //                 Parity of next 6 digits
        //     Digit   0     1     2     3     4     5
        //        0    Odd   Odd   Odd   Odd   Odd   Odd
        //        1    Odd   Odd   Even  Odd   Even  Even
        //        2    Odd   Odd   Even  Even  Odd   Even
        //        3    Odd   Odd   Even  Even  Even  Odd
        //        4    Odd   Even  Odd   Odd   Even  Even
        //        5    Odd   Even  Even  Odd   Odd   Even
        //        6    Odd   Even  Even  Even  Odd   Odd
        //        7    Odd   Even  Odd   Even  Odd   Even
        //        8    Odd   Even  Odd   Even  Even  Odd
        //        9    Odd   Even  Even  Odd   Even  Odd
        // 
        //  Note that the encoding for '0' uses the same parity as a UPC barcode. Hence
        //  a UPC barcode can be converted to an EAN-13 barcode by prepending a 0.
        // 
        //  The encoding is represented by the following array, which is a bit pattern
        //  using Odd = 0 and Even = 1. For example, 5 is represented by:
        // 
        //               Odd Even Even Odd Odd Even
        //  in binary:
        //                 0    1    1   0   0    1   == 0x19
        // 

        private static readonly IList<BarcodeFormat> supportedWriteFormats = new List<BarcodeFormat> { BarcodeFormat.EAN_13 };

        /// <summary>
        /// returns supported formats
        /// </summary>
        protected override IList<BarcodeFormat> SupportedWriteFormats
        {
            get { return supportedWriteFormats; }
        }

        static int[] FIRST_DIGIT_ENCODINGS = { 0x00, 0x0B, 0x0D, 0xE, 0x13, 0x19, 0x1C, 0x15, 0x16, 0x1A };

        static int[] START_END_PATTERN = { 1, 1, 1, };

        static int[][] L_AND_G_PATTERNS;

        static int[][] L_PATTERNS ={
      new[]  {3, 2, 1, 1}, // 0
      new[]  {2, 2, 2, 1}, // 1
      new[]  {2, 1, 2, 2}, // 2
      new[]  {1, 4, 1, 1}, // 3
      new[]  {1, 1, 3, 2}, // 4
      new[]  {1, 2, 3, 1}, // 5
      new[]  {1, 1, 1, 4}, // 6
      new[]  {1, 3, 1, 2}, // 7
      new[]  {1, 2, 1, 3}, // 8
      new[]  {3, 1, 1, 2}  // 9
};

        static int[] MIDDLE_PATTERN = { 1, 1, 1, 1, 1 };

        static EAN13WriterJava()
        {
            L_AND_G_PATTERNS = new int[20][];
            Array.Copy(L_PATTERNS, 0, L_AND_G_PATTERNS, 0, 10);
            for (int i = 10; i < 20; i++)
            {
                int[] widths = L_PATTERNS[i - 10];
                int[] reversedWidths = new int[widths.Length];
                for (int j = 0; j < widths.Length; j++)
                {
                    reversedWidths[j] = widths[widths.Length - j - 1];
                }
                L_AND_G_PATTERNS[i] = reversedWidths;
            }
        }

        private static readonly int CODE_WIDTH = 3 + // start guard
        (7 * 6) + // left bars
        5 + // middle guard
        (7 * 6) + // right bars
        3; // end guard
        public override int DefaultMargin { get { return 10; } }
        List<int> mLongLinePositions;
        public EAN13WriterJava()
        {
            mLongLinePositions = new List<int>();

        }

        public int appendPatternAndConsiderLongLinePosition(bool[] target, int pos, int[] pattern, bool startColor)
        {
            bool color = startColor;
            int numAdded = 0;
            foreach (int len in pattern)
            {
                for (int j = 0; (j < len); j++)
                {
                    // If the pattern is the start-, middle- or end-pattern save the position for rendering later
                    if ((pattern.Equals(START_END_PATTERN) || (pattern.Equals(MIDDLE_PATTERN) || pattern.Equals(START_END_PATTERN))))
                    {
                        mLongLinePositions.Add(pos);
                    }

                    target[pos++] = color;
                }

                numAdded = (numAdded + len);
                color = !color;
                //  flip color after each segment
            }

            return numAdded;
        }

        public override bool[] encode(string contents)
        {
            int length = contents.Length;
            switch (length)
            {
                case 12:
                    // No check digit present, calculate it and add it
                    var check = getStandardUPCEANChecksum(contents);
                    if (check == null)
                    {
                        throw new ArgumentException("Checksum can't be calculated");
                    }
                    contents += check.Value;
                    break;
                case 13:
                    try
                    {
                        if (!checkStandardUPCEANChecksum(contents))
                        {
                            throw new ArgumentException("Contents do not pass checksum");
                        }
                    }
                    catch (ZXing.FormatException ignored)
                    {
                        throw new ArgumentException("Illegal contents", ignored);
                    }
                    break;
                default:
                    throw new ArgumentException("Requested contents should be 12 (without checksum digit) or 13 digits long, but got " + contents.Length);
            }

            try
            {
                if (!checkStandardUPCEANChecksum(contents))
                {
                    throw new ArgumentException("Contents do not pass checksum");
                }

            }
            catch (Exception ignored)
            {
                throw new ArgumentException("Illegal contents");
            }

            int firstDigit = int.Parse(contents.Substring(0, 1));
            int parities = FIRST_DIGIT_ENCODINGS[firstDigit];
            bool[] result = new bool[CODE_WIDTH];
            int pos = 0;
            pos = (pos + appendPatternAndConsiderLongLinePosition(result, pos, START_END_PATTERN, true));
            //  See {@link #EAN13Reader} for a description of how the first digit & left bars are encoded
            for (int i = 1; (i <= 6); i++)
            {
                int digit = int.Parse(contents.Substring(i, (i + 1)));
                if (((parities + ((6 - i) & 1)) == 1))
                {
                    digit += 10;
                }

                pos = (pos + appendPatternAndConsiderLongLinePosition(result, pos, L_AND_G_PATTERNS[digit], false));
            }

            pos = (pos + appendPatternAndConsiderLongLinePosition(result, pos, MIDDLE_PATTERN, false));
            for (int i = 7; (i <= 12); i++)
            {
                int digit = int.Parse(contents.Substring(i, (i + 1)));
                pos = (pos + appendPatternAndConsiderLongLinePosition(result, pos, L_PATTERNS[digit], true));
            }

            appendPatternAndConsiderLongLinePosition(result, pos, START_END_PATTERN, true);
            return result;
        }

        public BitMatrix encodeAndRender(String contents, int width, int height)
        {
            bool[] code = encode(contents);
            int inputWidth = code.Length;
            //  Add quiet zone on both sides.
            int fullWidth = (inputWidth + DefaultMargin);
            int outputWidth = Math.Max(width, fullWidth);
            int outputHeight = Math.Max(1, height);
            int multiple = (outputWidth / fullWidth);
            int leftPadding = ((outputWidth - (inputWidth * multiple)) / 2);
            BitMatrix output = new BitMatrix(outputWidth, outputHeight);
            for (int inputX = 0, outputX = leftPadding; inputX < inputWidth; inputX++, outputX += multiple)
            {
                if (code[inputX])
                {
                    int barcodeHeight = outputHeight;
                    //if the position isn't in the list for long lines we have to shorten the line by 5%
                    if (!mLongLinePositions.Contains(inputX))
                    {
                        barcodeHeight = (int)((float)outputHeight * 0.95f);
                    }
                    output.setRegion(outputX, 0, multiple, barcodeHeight);
                }
            }
            return output;
        }
        static int? getStandardUPCEANChecksum(String s)
        {
            int length = s.Length;
            int sum = 0;
            for (int i = length - 1; i >= 0; i -= 2)
            {
                int digit = s[i] - '0';
                if (digit < 0 || digit > 9)
                {
                    throw new ArgumentException("Contents should only contain digits, but got '" + s[i] + "'");
                }
                sum += digit;
            }
            sum *= 3;
            for (int i = length - 2; i >= 0; i -= 2)
            {
                int digit = s[i] - '0';
                if (digit < 0 || digit > 9)
                {
                    throw new ArgumentException("Contents should only contain digits, but got '" + s[i] + "'");
                }
                sum += digit;
            }
            return (1000 - sum) % 10;
        }
        static bool checkStandardUPCEANChecksum(String s)
        {
            int length = s.Length;
            if (length == 0)
            {
                return false;
            }

            int check = s[length - 1] - '0';
            return getStandardUPCEANChecksum(s.Substring(0, length - 1)) == check;
        }
      
        //static bool checkStandardUPCEANChecksum(string s)
        //{
        //    int length = s.Length;
        //    if ((length == 0))
        //    {
        //        return false;
        //    }

        //    int sum = 0;
        //    for (int i = (length - 2); (i >= 0); i -= 2)
        //    {
        //        int digit = (((int)(s[i])) - ((int)('0')));
        //        if (((digit < 0) || (digit > 9)))
        //        {
        //            throw new System.FormatException();
        //        }

        //        sum = (sum + digit);
        //    }

        //    sum = (sum * 3);
        //    for (int i = (length - 1); (i >= 0); i -= 2)
        //    {
        //        int digit = (((int)(s[i])) - ((int)('0')));
        //        if (((digit < 0)
        //                    || (digit > 9)))
        //        {
        //            throw new System.FormatException();
        //        }

        //        sum = (sum + digit);
        //    }

        //    return ((sum % 10) == 0);
        //}

    }
}
`

**Comment by andriks2** [comment]
I think the selected font is too large for the selected dimensions. Try reducing font size or increasing the width.

**Comment by micjahn** [comment]
You can try the class AlternateBitmapRenderer:
```
var writer = new BarcodeWriter
{
   Renderer = new AlternateBitmapRenderer(),
   BarcodeFormat = ...
};
var bitmap = writer.Write("<content>");
```

**Comment by philip247** [comment]
Since EAN13 is always used on products like mayurjansari described, there is absolutely the need to have EAN13 with 'lead', 'separator' and 'trailer'. Take a look on any product packaging.
If possible with standard library, please post example.

**Comment by micjahn** [comment]
An example is written in the comment https://github.com/micjahn/ZXing.Net/issues/269#issuecomment-731370313
