### ISSUE TITLE
Release of 0.16 as nuget package

### ISSUE THREAD

**Issue by codedevote** [micjahn/ZXing.Net#27]
Would it be possible that you push 0.16 to nuget? Milestone (https://github.com/micjahn/ZXing.Net/milestone/1?closed=1) seems complete, and I am currently having the .NET Core transparent svg image problem (see #22). I would be happy to get rid of my regex fixing this right now.
Thx.

**Comment by micjahn** [comment]
I'm not finished with porting the last changes to the WinMD branch. After that I will create a new release.

**Comment by os1r1s110** [comment]
Any update on that matter? I am also facing the transparent svg problem. *I also implemented a regex "hack" to work around the issue but it will be nicer when it will be fixed directly from source :)

Thanks in advance!

**Comment by micjahn** [comment]
Hopefully I will finish the last issues this week...

**Comment by micjahn** [comment]
Done.
