### ISSUE TITLE
Make text contents/font size  under the Barcode big

### ISSUE THREAD

**Issue by geojaya** [micjahn/ZXing.Net#271]
I have  powershell script to create a Barcode. I will like to have text font  under Bar
![test](https://user-images.githubusercontent.com/4351259/90076887-abef4f00-dcb5-11ea-9228-791916e4d060.jpg)
code to be slightly Big. Is there any property/options, that  I can set.

Add-Type -Path "C:\Users\XXXX\Downloads\ZXing.Net.DemoClients.0.16.5.0\Clients\CommandLineEncoder\zxing.dll"
$writer = New-Object -TypeName ZXing.BarcodeWriter
$writer.Format = "CODE_39"
#$writer.Options.PureBarcode = $true
$writer.Options.Height = 150
$writer.Options.Width = 400
$writer.Options.Margin = 500

$yy = $writer.Write("12AB345") 
$yy.Save("c:\dev\test.jpg", "jpeg")

**Comment by micjahn** [comment]
Please try the following:
```
Add-Type -Path "C:\Users\XXXX\Downloads\ZXing.Net.DemoClients.0.16.5.0\Clients\CommandLineEncoder\zxing.dll"
$writer = New-Object -TypeName ZXing.BarcodeWriter
$writer.Format = "CODE_39"
#$writer.Options.PureBarcode = $true
$writer.Options.Height = 150
$writer.Options.Width = 400
$writer.Options.Margin = 500

$renderer = New-Object ZXing.Rendering.BitmapRenderer
$renderer.TextFont = New-Object System.Drawing.Font("Arial", 20)
$writer.Renderer = $renderer

$yy = $writer.Write("12AB345")
$yy.Save("c:\dev\test.jpg", "jpeg")
```

**Comment by geojaya** [comment]
thanks for your help
