### ISSUE TITLE
Some code not included when using NET48

### ISSUE THREAD

**Issue by andriks2** [micjahn/ZXing.Net#275]
In some classes the meta directive does not include NET48, only NET47 etc. I think this is by accident, not by design. Please check:

e.g. PIxelDataRenderer lines 25, 116
  AssemblyInfo, after line 30
  DecodedBitStreamParser lines 20, 80, 884
  PDF417HighLevelEncoder line 22 and maybe more.

Seek for NET47 and see if NET48 should be added.

**Comment by micjahn** [comment]
The .Net 4.8 project file was using the value NET47. Nothing was missing. But I changed it now.
