### ISSUE TITLE
Call .NET Framework library with zxing from .NET Core project

### ISSUE THREAD

**Issue by dusbn** [micjahn/ZXing.Net#276]
I've still got some projects left in .NET Framework which I want to use for a new ASP.NET Core project.
When I try to generate a barcode via ZXing BarcodeWriter class through my .NET Framework library I ended up with the following exception:

_Could not load type 'ZXing.BarcodeWriter' from assembly 'zxing, Version=0.16.5.0, Culture=neutral, PublicKeyToken=4e88037ac681fe60'._

Should I first migrate my .NET Framework libraries to Standard or Core before using them in .NET Core applications?
Any suggestions to fix this issue?

Thanks in advance :)

**Comment by micjahn** [comment]
I really have no idea. I need more details. A sample project would help.
Anyway the best way, in my opinion, would be that you migrate every project to .net standard first.

**Comment by dusbn** [comment]
I created an example solution with two projects.
A library in net framework 4.5.2 referencing ZXing.net and a net Core 3.1 console application.

I tried the following by referencing my net framework library as a project reference to my net core console application. When calling a given function of the library to generate a barcode from the console application, everything is working just fine as it should.

But when I pack my net framework library and reference the nuget package of my library to the console application and do the same procedure again, the type exception will be thrown again.

Am I missing a reference? It seems so...

Sample project: https://github.com/dusbn/zxing_example_temp

**Comment by micjahn** [comment]
As far as I understand the problem, it exists because with the nuget package reference in your netcore project includes the netcore version of zxing. But your netframework assembly is build against the net 4.5 version of zxing.
The only way I found is the following: you have to tweak your netcore project file.
  <ItemGroup>
    <PackageReference Include="ZXing.Net" Version="0.16.5" ExcludeAssets="Compile" />
    <PackageReference Include="netframework" Version="1.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="4.7.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ZXing.Net">
        <HintPath>$(NuGetPackageRoot)zxing.net\0.16.5\lib\net461\zxing.dll</HintPath>
    </Reference>
  </ItemGroup>

**Comment by dusbn** [comment]
This works like a charm! 👍 

Maybe this topic would be better placed on Stackoverflow as this was my fault... but thank's anyway :)
I will keep that in mind^^
