### ISSUE TITLE
NullReferenceException inside "Decore" function

### ISSUE THREAD

**Issue by eyanson** [micjahn/ZXing.Net#277]
![error](https://user-images.githubusercontent.com/32112569/92305582-f84d4800-ef5e-11ea-90be-9027a71a5b43.PNG)

Hi. I have webcam that fires an event "NewFrame" not in main thread. (see image)
All works fine but randomily "Decode" fires a NullReferenceException.

note: anythink of this are null. (BarcodeReader and bmp) has value.
Dim result = BarcodeReader.Decode(bmp)

If you want, I can prepare a sample project.

thanks

**Comment by micjahn** [comment]
Without a stacktrace I can not help here.
But I assume it is the same error in the DataMatrix decoder which is reported here: [#260 ]

**Comment by eyanson** [comment]
Here is exception detail, and can you debug directilly too. I put an example to reproduce it.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=zxing
  StackTrace:
   at ZXing.Datamatrix.Internal.BitMatrixParser..ctor(BitMatrix bitMatrix)
   at ZXing.Datamatrix.Internal.Decoder.decode(BitMatrix bits)
   at ZXing.Datamatrix.DataMatrixReader.decode(BinaryBitmap image, IDictionary`2 hints)
   at ZXing.MultiFormatReader.decodeInternal(BinaryBitmap image)
   at ZXing.BarcodeReaderGeneric.Decode(LuminanceSource luminanceSource)
   at ZXing.BarcodeReader`1.Decode(T barcodeBitmap)
   at qrerror2.Form1.CurrentWebCam_NewFrame(Object sender, NewFrameEventArgs e) in C:\Users\xxx\source\repos\qrerror2\qrerror2\Form1.cs:line 53

Howto reproduce:
Create winform app, add this packages:

Install-Package AForge
Install-Package AForge.Video
Install-Package AForge.Video.DirectShow
Install-Package ZXing.Net

        private AForge.Video.DirectShow.VideoCaptureDevice CurrentWebCam;
        private ZXing.BarcodeReader bc;

        private void Form1_Load(object sender, EventArgs e)
        {
            FormClosing += (object sender2, FormClosingEventArgs e2) => { CurrentWebCam.Stop(); };

            bc = new ZXing.BarcodeReader();

            var videoDevices = new AForge.Video.DirectShow.FilterInfoCollection(AForge.Video.DirectShow.FilterCategory.VideoInputDevice);
            CurrentWebCam = new AForge.Video.DirectShow.VideoCaptureDevice(videoDevices[0].MonikerString);
            CurrentWebCam.VideoResolution = CurrentWebCam.VideoCapabilities.Last();
            var snapVabalities = CurrentWebCam.SnapshotCapabilities;
            CurrentWebCam.NewFrame += CurrentWebCam_NewFrame;
            CurrentWebCam.Start();           
        }

        private void CurrentWebCam_NewFrame(Object sender, AForge.Video.NewFrameEventArgs e)
        {
            var bmp = (System.Drawing.Bitmap)e.Frame.Clone();
            var result = bc.Decode(bmp);
            pictureBox1.Image = bmp;
        }

**Comment by vegard-st1** [comment]
I also had this issue and it has already been fixed in this PR: https://github.com/micjahn/ZXing.Net/pull/226, but there seems to be no new version after September 2019, and this was merged to master in December 2019

**Comment by kko123** [comment]
I have the same issue now. Did you solve it?
`private void video_NewFrame(object sender, AForge.Video.NewFrameEventArgs eventArgs)
        {
            try
            {
                BitmapImage bi;
                using (var bitmap = (Bitmap)eventArgs.Frame.Clone())
                {
                    var result = _reader.Decode(bitmap);
                    if (result != null) Console.WriteLine(result);
                    
                    bi = bitmap.ToBitmapImage();
                }
                bi.Freeze(); // avoid cross thread operations and prevents leaks                
                Dispatcher.BeginInvoke(new ThreadStart(delegate { videoPlayer.Source = bi; }));
            }
            catch (Exception exc)
            {
                MessageBox.Show("Error on _videoSource_NewFrame:\n" + exc.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                StopCamera();
            }
        }`

**Comment by micjahn** [comment]
the new version 0.16.6 is available.
