### ISSUE TITLE
Bug in Pdf417 decoder

### ISSUE THREAD

**Issue by ahanssens** [micjahn/ZXing.Net#278]
I have an image where the pdf417 barcode is not recognized. It seems to fail in the error correction phase. I can't find anything wrong with this barcode. This barcode does get recognized by the on-line engines.

![200_Bottom_Right_rot](https://user-images.githubusercontent.com/54364954/92335522-72a7c600-f04c-11ea-992d-1b67d13b4ae7.png)

**Comment by micjahn** [comment]
I checked your image with the current version of zxing.net using the windows forms demo. The PDF417 was successfully decoded without any problems. If possible please build an own version from the sources of the repository and try again. By the way, it is not the best idea to use monochrom images. If possible use grayscale scans.

**Comment by ahanssens** [comment]
Hi,

                Thanks for your response. I downloaded the ZXing.Net-master a week ago and I’m using the vs2017 solution (Screenshot 1)

[cid:image001.png@01D685DF.7E8DC5F0]
                                Screenshot 1

This is the result when I use the compiled demo program for the indicated file (successfully decoded)

[cid:image002.png@01D685DF.7E8DC5F0]

This is the result when I use the compiled demo program for the indicated file (failed decoding)

[cid:image003.png@01D685DF.7E8DC5F0]

The second image fails on

            int[] errorLocations = findErrorLocations(sigma);

            if (errorLocations == null)
            {
                return false;
            }
In the errorcorrection.cs file




I attach both files. Those images come from a sample ID card, scanned with a scanner at 400DPI.  I don’t know what I’m doing wrong

I’m sorry that I did send the bitonal image but that was an image I saved after the zxing binarization of the image.


Thanks for any help you can provide me.

Regards
                Arsene
