### ISSUE TITLE
Read Barcode Types

### ISSUE THREAD

**Issue by cGiesen** [micjahn/ZXing.Net#279]
There is a list of supported barcodes.
I play arround and see, I can't read all types.

I can read CODE_128, Interleaved 2 of 5, QR Code (but not all), UPC-A EAN-13. 

I'am the only one with this problems?

CU
Carsten

https://www.pdfill.com/images/barcode_screen.png

Edit:
[Barcode_Examples_2.pdf](https://github.com/micjahn/ZXing.Net/files/5212645/Barcode_Examples_2.pdf)
I add a pdf file.
Here I get 
```
{
  "IsError": false,
  "ResultMessage": "",
  "Data": {
    "Duration": 540,
    "ListBarcodeValues": [
      {
        "ID": 0,
        "Page": 1,
        "Value": "123456789123",
        "TargetFullPath": null,
        "BarcodeFormat": "CODE_39",
        "X0": 144.0,
        "Y0": 407.0,
        "X1": 727.5,
        "Y1": 407.0
      },
      {
        "ID": 1,
        "Page": 1,
        "Value": "0123456789128",
        "TargetFullPath": null,
        "BarcodeFormat": "EAN_13",
        "X0": 122.5,
        "Y0": 158.0,
        "X1": 432.5,
        "Y1": 158.0
      },
      {
        "ID": 2,
        "Page": 1,
        "Value": "1234567891231",
        "TargetFullPath": null,
        "BarcodeFormat": "EAN_13",
        "X0": 628.5,
        "Y0": 20.0,
        "X1": 961.0,
        "Y1": 20.0
      }
    ]
  }
} 
```

**Comment by micjahn** [comment]
Sorry, there is no guarantee that all barcodes in all circumstances can be decoded successfully. Especially if the sample image is more or less no real-world use case.
