### ISSUE TITLE
Cannot decode data matrix

### ISSUE THREAD

**Issue by bobmanz** [micjahn/ZXing.Net#28]
Hello,

Could anyone give me any insight as to why this cannot be decoded and always returns null?  Attached the image and below is my code.

```
var decoder = new BarcodeReader();
decoder.Options = new ZXing.Common.DecodingOptions() { PureBarcode = true, TryHarder = true, PossibleFormats = new List<BarcodeFormat>() { BarcodeFormat.DATA_MATRIX } };
decoder.AutoRotate = true;
decoder.TryInverted = true;
var results = decoder.Decode(new Bitmap(filename_datamatrix));
```

![datamatrix](https://user-images.githubusercontent.com/1812678/28295398-5a7f8988-6b2e-11e7-9163-c7fb9dd2b0c7.png)

**Comment by micjahn** [comment]
As far as I can see the image is a little bit too blurry and stretched at the x-axis.
You should try to capture an image with a better quality. There is no other option 
which you can set to improve the scannung rate.

**Comment by bobmanz** [comment]
Hmm, some of the websites can decode this successfully.  Do you think they're using some more robust libraries that cost?

**Comment by micjahn** [comment]
That's the case.

**Comment by bobmanz** [comment]
Ok thanks for the information!  This library was actually working really well (better than DataMatrix.Net) up until the PDF was faxed and the barcode must have lost quality along the way.
