### ISSUE TITLE
Can't read some ITF barcodes

### ISSUE THREAD

**Issue by kamilkrzyzanowski** [micjahn/ZXing.Net#280]
Hello 
I have a problem to read attached barcode by ZXing.Net. It's read correctly by https://zxing.org/w/decode.jspx. I have many ITF generated in the same way and only a few of them are problematic. Does somebody know where could be problem? 

My code:
`            BarcodeReader reader = new BarcodeReader();

            reader.AutoRotate = true;
            reader.TryInverted = true;
            reader.Options.TryHarder = true;
            reader.Options.PossibleFormats = new List<BarcodeFormat> { BarcodeFormat.ITF, BarcodeFormat.CODE_128 };
            var result = reader.Decode(image.ToBitmap());`

ITF barcode:
![bb3](https://user-images.githubusercontent.com/3829983/96195603-754fe200-0f4d-11eb-970f-5776db8e1f4a.png)

Please help :)

**Comment by micjahn** [comment]
How did you generate the barcode? Can you provide a code sample?

**Comment by micjahn** [comment]
@viniciusverasdossantos
I think there is something wrong with the scaling of the barcode which leads to incorrect widths of the bars.
I recreated barcode from the content (23794877400016213274600092100831280299999990) with the current implementation. That newly created image could be decoded successfully. Please check your scaling of the barcode. Try to avoid it.

@kamilkrzyzanowski 
Without knowing the content of your barcode I could not help any further here.
