### ISSUE TITLE
Unable to find DataMatrix barcode. See: #126

### ISSUE THREAD

**Issue by msschl** [micjahn/ZXing.Net#282]
Hi,

I'm having the same issue. Is this still the same reason as in #126?

```cs
var reader = new BarcodeReader
            {
                AutoRotate = true,
                TryInverted = true,
                Options = new DecodingOptions
                {
                    PossibleFormats = new List<BarcodeFormat> { BarcodeFormat.DATA_MATRIX },
                    TryHarder = true,
                    PureBarcode = false
                }
            };

var results = reader.DecodeMultiple(bitmap);
```

**Comment by micjahn** [comment]
Without a sample picture, I have no chance to answer your question.

**Comment by msschl** [comment]
![18183780b](https://user-images.githubusercontent.com/5054780/97698281-931e5a80-1aa8-11eb-951c-14dd1ecff0b2.jpg)

**Comment by micjahn** [comment]
Your case is similar to #126.
You will get a result if the image is taken a little bit more centric.

**Comment by msschl** [comment]
That's why I asked whether this is still the case or if it was already fixed. But thanks @micjahn 👍🏽
