### ISSUE TITLE
QR Code Roundtrip does not work for certain ISO-8859-1 strings

### ISSUE THREAD

**Issue by HeinziAT** [micjahn/ZXing.Net#284]
Please consider the following minimal repro example (Console Application, using .net Framework 4.8 and ZXing.Net 0.16.6 from nuget):

```
using System;
using ZXing;

public class Program
{
    public static void Main(string[] args)
    {
        Console.WriteLine(Roundtrip("ÄÖÜäöü")); // works, prints ÄÖÜäöü
        Console.WriteLine(Roundtrip("äöü"));    // fails, prints ???
    }

    static string Roundtrip(string content)
    {
        var bitmap = new BarcodeWriter { Format = BarcodeFormat.QR_CODE }.Write(content);
        return new BarcodeReader().Decode(bitmap).Text;
    }
}
```

Expected result: The second line should print `äöü`.
Actual result: It prints `???`.

Notes:

- I am aware that I could work around this problem by using ECI with UTF-8, i.e., using `EncodeHintType.CHARACTER_SET` with `"utf-8"` fixes the issue. However, `äöü` is a perfectly valid ISO-8859-1 string, so the default QR Code binary encoding should work as well.
- Unfortunately, I am not familiar enough with ZXing (or QR codes for that matter) to diagnose whether the problem exists in the QR Code encoder or the decoder. Thus, I have prepared a minimal, complete and verifiable example in the hope that someone else can pinpoint the source of the problem.

**Comment by micjahn** [comment]
Weird thing. It only happens in some corner case because the decoder guesses the character encoding wrong.
The 'ä' at the beginning leads to UTF-8 in the decoding step. Other combinations like 'ööö' or 'öüä' are working.
The encoding process works correctly. Not sure how it should be fixed.
Perhaps a better workaround would be to set the encoding hint CHARACTER_SET to "ISO-8859-1"
`new BarcodeWriter { Format = BarcodeFormat.QR_CODE, Options = new QrEncodingOptions{CharacterSet="ISO8859-1" }};`

**Comment by HeinziAT** [comment]
Indeed, `StringUtils.guessEncoding(Encoding.GetEncoding(1252).GetBytes("äöü"), null)` yields `UTF-8`. Thanks for your help.

The QR Code standard says (since 2005) that the encoding is ISO-8859-1 if there's no ECI, so no guesswork should be necessary, but I guess we can't change that without breaking compatibility with a lot of existing systems.

Oh, well, we'll just have to use ECI then (either with UTF-8, as suggested in my initial post, or ISO-8859-1, as suggested by you).

**Comment by micjahn** [comment]
As far as I know there are some other encoders that use UTF-8 by default without ECI.
