### ISSUE TITLE
zxing ean13 adn ean8 barcode encoding with 'lead', 'separator' and 'trailer'

### ISSUE THREAD

**Issue by albgen** [micjahn/ZXing.Net#286]
I'm using zxing to generate an EAN13 barcode. Everything works fine when I use this code:

`        public static Bitmap GenerateCodeEAN13(string strToBarCode)
        {
            var writer = new BarcodeWriter
            {
                Format = BarcodeFormat.EAN_13,
                Options = new ZXing.Common.EncodingOptions()
                {                   
                    Width = 100,
                    Height = 100
                }
            };
            return writer.Write(strToBarCode);
        }`

This is generating a bitmap like https://i.stack.imgur.com/qO4iE.png
but i want something like the standard EAN13 or EAN8 which uses these lead, separator and trailor like the following:
https://i.stack.imgur.com/RVXRp.gif

any chance that the library can do this?

**Comment by micjahn** [comment]
You can try the class AlternateBitmapRenderer:
```
var writer = new BarcodeWriter
{
   Renderer = new AlternateBitmapRenderer(),
   BarcodeFormat = ...
};
var bitmap = writer.Write("<content>");
```

**Comment by albgen** [comment]
hello,

same result even if i set the property Renderer = new AlternateBitmapRenderer(),

**Comment by micjahn** [comment]
Do you use version 0.16.6? Target .net framework is full framework 4.x?
If so, the following code should work. I checked it twice.
```
public static Bitmap GenerateCodeEAN13(string strToBarCode)
{
   var writer = new BarcodeWriter
   {
      Format = BarcodeFormat.EAN_13, 
      Options = new ZXing.Common.EncodingOptions() 
      { 
         Width = 100, 
         Height = 100,
         PureBarcode = false
      },
      Renderer = new AlternateBitmapRenderer(),
   }; 
   return writer.Write(strToBarCode); 
}
```

**Comment by albgen** [comment]
Still not working.
i'm using full framework. The project zxing.net4.7 within the solution.

thank you

**Comment by albgen** [comment]
hi micjahn,

other suggestions?

thank you

**Comment by micjahn** [comment]
Really, I have no idea. Everything works like a charm for me.
Do you have a complete repro for me?

**Comment by albgen** [comment]
you can download it from [https://we.tl/t-742gBQPJY4](url)
The solution is a git clone from the master branch but i have removed all the projects except zxing.net4.7 and added the console app for testing purposes.

**Comment by micjahn** [comment]
Your sample works for me. But I had to change the width of the EAN8 barcode image from 100 to 200 because 100 was too small for the content and the default font size. And I had to explicitly build the zxing project because the project wasn't selected in the build configuration manager.
[ConsoleApp-issue-286.zip](https://github.com/micjahn/ZXing.Net/files/5649323/ConsoleApp-issue-286.zip)

**Comment by albgen** [comment]
hello,

just run the executable within your zip and guess what: it produces the same wrong images as my project 

how is that even possible?

**Comment by micjahn** [comment]
I really have no idea what's wrong. You say the images are wrong but in the second sentence, you say it works perfectly. Please describe exactly how the image should look like and what is displayed instead.
Please make sure that there is no old version of the assembly in the global assembly cache. Remove them from the GAC.
Make a clean build, catch all exceptions, especially look into the exceptions which are thrown when the requested width is too small.

**Comment by albgen** [comment]
i think you pin pointed the issue: _Please make sure that there is no old version of the assembly in the global assembly cache. Remove them from the GAC._

Removed it from the GAC and everything started working perfectly.

thank you
