### ISSUE TITLE
Not reading barcode

### ISSUE THREAD

**Issue by adyr16** [micjahn/ZXing.Net#287]
I am trying to read a simple barcode from a file after scanning using the IBarcodeReader interface from Zxing library. The barcode result returns as null although the barcode type is Code_39. How can I read a single barcode from a page ? I am using the below code to read my barcode. The 'barcodeResult' always returns null. Can someone help ? Is there any dimensions or specific size or orientation required to follow for the barcode to be identified from the scanned page.

    IBarcodeReader reader = new BarcodeReader();
    var barcodeResult = reader.Decode(bitmap);

**Comment by micjahn** [comment]
Can you provide a sample image of your barcode?
