### ISSUE TITLE
Unable to decode Aztec code when rotated

### ISSUE THREAD

**Issue by bigfoott** [micjahn/ZXing.Net#289]
Hello! I'm having some trouble decoding Aztech codes when the input is rotated.

I assumed at first it was a limiatation of the format, but according to the [wiki page](https://en.wikipedia.org/wiki/Aztec_Code#Structure) for it, it's possible to read it from different orientations.

Video of the issue (i'm using the Unity plugin): https://www.youtube.com/watch?v=SryCc8BxiM0

AutoRotate is enabled so it works on 90 degree angles but nothing in between.

**Comment by micjahn** [comment]
That's a limitation of the library. The original java-based library was designed, more or less, for mobile phones. In that use case, the user holds the mobile phone normally very straight in the front of the code.

**Comment by bigfoott** [comment]
Ah okay. Fortunately there should be ways around this in Unity. Thank you for the reply regardless :)
