### ISSUE TITLE
Data Matrix support vague

### ISSUE THREAD

**Issue by strpipe** [micjahn/ZXing.Net#29]
Hey I found ZXing does not work well with Datamatrix codes.

Also, using the BarcodeReader-Class with Options.PossibleFormats set to DATA_MATRIX does not find Datamatrix-Codes, even PureBarcode ones with a high quality. 
However, the DataMatrixReader will find some.

Did I misconfigure something? How come the generic reader does not find them?

Thank you for porting this over to .Net

**Comment by micjahn** [comment]
I can't answer your questions without further informations.
Please provide a sample image with a Datamatrix code and the source code which you used for decoding with the BarcodeReader class and the DataMatrixReader.

**Comment by strpipe** [comment]
I did not wanna bother.
