### ISSUE TITLE
Unable to read few barcode in a barcode sheet

### ISSUE THREAD

**Issue by manish-gtm10** [micjahn/ZXing.Net#291]
We have a barcode sheet with 33 barcodes. When we try to read barcodes from the scanned documents it was unable to read all 33 barcodes. Barcodes are CODE 128 barcodes .
Below is the code
private object[] ReadBarcode(string filePath)
{
EventLog.WriteEntry(_mEventLogSource, "Reading Barcode from path " + filePath + " Error Desc : ", EventLogEntryType.Information, _mintEvenId);
var barcodeReader = new BarcodeReader();
var barcodeBitmap = (Bitmap)Bitmap.FromFile(filePath);
try
{
barcodeBitmap.SetResolution(100, 100);
barcodeReader.Options.TryHarder = true;
barcodeReader.Options.PossibleFormats = new List<BarcodeFormat>();
barcodeReader.Options.PossibleFormats.Add(BarcodeFormat.All_1D);
barcodeReader.Options.PossibleFormats.Add(BarcodeFormat.CODE_128);
barcodeReader.Options.PossibleFormats.Add(BarcodeFormat.QR_CODE);
barcodeReader.AutoRotate = true;
barcodeReader.TryInverted = true;
barcodeReader.Options.TryHarder = true;
barcodeReader.Options.ReturnCodabarStartEnd = true;
barcodeReader.Options.PureBarcode = false;
// create an in memory bitmap

// decode the barcode from the in memory bitmap 
var barcodeResult = barcodeReader.DecodeMultiple(barcodeBitmap);
return barcodeResult;
}
catch (Exception ex)
{
m_Log.Info(" Error While reading Barcode " + ex.ToString());
EventLog.WriteEntry(_mEventLogSource, "ReadBarcode " + " Error Desc : ", EventLogEntryType.Error, _mintEvenId);
throw ex;
}
finally
{
if (barcodeReader != null)
barcodeReader = null;
if (barcodeBitmap != null)
{
barcodeBitmap.Dispose();
barcodeBitmap = null;
}
}
}

**Comment by micjahn** [comment]
There is no guarantee that ZXing will find every single barcode. It uses a very simple algorithm that divides the image into quadrants.
