### ISSUE TITLE
Issue executing example code

### ISSUE THREAD

**Issue by tekspacedemo** [micjahn/ZXing.Net#293]
Hi, 

I came across this library and was trying to give this a try. When I run the example code, I am getting convert error. Please see below.

![image](https://user-images.githubusercontent.com/72271557/101271989-2278f680-3756-11eb-9dfb-f7195e77f050.png)

Here are the packages I installed in `.net core 3.1` app.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.9" />
    <PackageReference Include="System.Drawing.Common" Version="5.0.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.6" />
  </ItemGroup>


</Project>

```

**Comment by tekspacedemo** [comment]
I just ended up doing this:

```
var reader = new BarcodeReader();
			var scanImage = (Bitmap)Image.FromFile(@"C:\temp\barcode\Barcode-Bottle.jpeg");
			var result = reader.Decode(scanImage);
			if (result != null)
			{
				
				return result.ToString();
			}
			return null;
```

**Comment by micjahn** [comment]
If you are using ZXing.Net with .Net Core you have to add a specific nuget package for the graphics library. In your case you have to add ZXing.Net.Bindings.Windows.Compatibility because you want to use the bitmap classes from System.Drawing.Common.

**Comment by tekspacedemo** [comment]
Hi @micjahn, thanks for your reply. I wanted to ask if there are additional documentation on this library you created?

**Comment by micjahn** [comment]
No, unfortunately not. There are only a few articles in the Wiki.
