### ISSUE TITLE
I don't seem to be able to read this QRCode

### ISSUE THREAD

**Issue by rcaeirodev** [micjahn/ZXing.Net#296]
I am unable to read this qr code. I can read it with the android phone app.
I have been trying to enhance the image with image magick and then feed it but without much success.
Is there something i can do either on zxing side or image side so i can get a reading? Thx in advance.
![ProcImage_2020_12_09_03_43_51_840](https://user-images.githubusercontent.com/58937718/101655372-74ad6680-3a39-11eb-9acc-80422a612963.png)

Code so far for zxing:

```
// create a barcode reader instance
var barcodereader = new ZXing.BarcodeReader() { AutoRotate = true, TryInverted = true };
barcodereader.Options.PossibleFormats = new List<BarcodeFormat>() { BarcodeFormat.QR_CODE };
barcodereader.Options.TryHarder = true;

 // decode the barcode from the in memory bitmap
var barcoderesult = barcodereader.Decode(barcodebitmap);
```

**Comment by pratikgohil1985** [comment]
Me too having same issue . unable to read QR from image taken from camera

`
protected Result fnScanQRinImg(System.Drawing.Image imgIn)
    {
        System.Drawing.Image zoomImg = new System.Drawing.Bitmap((int)(imgIn.Size.Width * 2), (int)(imgIn.Size.Height * 2));
        using (System.Drawing.Graphics g = System.Drawing.Graphics.FromImage(zoomImg))
        {
            g.ScaleTransform(2.0f, 2.0f);
            g.DrawImage(imgIn, new System.Drawing.Rectangle(new System.Drawing.Point(0, 0), imgIn.Size), new System.Drawing.Rectangle(new System.Drawing.Point(0, 0), imgIn.Size), System.Drawing.GraphicsUnit.Pixel);
        }
        System.Drawing.Bitmap bitmap = new System.Drawing.Bitmap(zoomImg);
            BarcodeReader qrCodeReader = new BarcodeReader
        {
            AutoRotate = true,
            TryInverted = true,
            Options = new DecodingOptions
            {
                TryHarder = true,
                PossibleFormats = new List<BarcodeFormat> { BarcodeFormat.QR_CODE }
            }
        };
        return qrCodeReader.Decode(bitmap);
    }`

**Comment by micjahn** [comment]
ZXing.Net isn't perfect. There is no guarantee that every single image can be decoded. Other apps are using different algorithms which can be better in some szenarios.

Your picture is very blurry at the edges of the black pixels. I think that's the problem here.

**Comment by MAINFRAMELOCALHOST** [comment]
Tree
