### ISSUE TITLE
Support for Hololens 2 (UWP arm32/arm64)

### ISSUE THREAD

**Issue by joaocc** [micjahn/ZXing.Net#297]
Hi, Has anyone managed to use ZXing.net on Hololens 2 (arm32/arm64)? Thanks!

**Comment by micjahn** [comment]
I don't own a Hololens device. I can't test it myself.
But there are some guys out there which were able to manage that:
https://stackoverflow.com/questions/48744531/using-zxing-with-hololens
https://forum.unity.com/threads/how-to-do-the-barcode-scanning-through-hololens.517642/
https://mtaulty.com/2016/12/28/windows-10-uwp-qr-code-scanning-with-zxing-and-hololens/
https://forums.hololens.com/discussion/2337/has-anyone-been-able-to-successfully-use-zxing-in-their-hololens-app
https://labs.eleks.com/2017/02/how-mixed-reality-hololens-user-experience-can-make-life-easier-retailers.html

There is also a building block from microsoft for QR:
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking

**Comment by dudziakl** [comment]
I can confirm that ZXing.Net.0.16.8.0 is still working for HoloLens 2 (OpenXR build). I have used Unity 2021.3.12f with zxing.unity.dll plugin from Unity folder. I know that is not very optimal but it allows me to build for ARM64 and winmd plugin is ARM only.
