### ISSUE TITLE
EAN8, EAN13, UPC-A, UPC-E text content

### ISSUE THREAD

**Issue by philip247** [micjahn/ZXing.Net#299]
For this 1d-Barcodes the text content has to be grouped.
It is not enough to add spaces only, anyhow the spaces have to be preserved in svg (with style="white-space: pre;").
Other point is cutting barcode to get place for additional text in Bitmap Renderer and increase the height for additional text in svg. (This will end in different result).
Also the grouping of the text content has the impact, that the width of the barcode will increase, otherwise it has to be considered before creating the barcodes.
Working on acceptable solution...

**Comment by micjahn** [comment]
Please try the alternative bitmap renderer "AlternateBitmapRenderer". Feel free to provide a PR for the SVG renderer which adds the grouping.
