### ISSUE TITLE
Generating PDF417 from hex

### ISSUE THREAD

**Issue by Retosi** [micjahn/ZXing.Net#3]
Is it possible to build a PDF417 barcode from HEX? I tried something with ZXing, but it wont work with an encoded string in my case.
`HEX: fe-30-**09**-33-31-37-30-31-30-32-30-31-f9-20-**01**-34-fe-30-**01**-20-fc-20-**06**`
I highlighted some Hexchars which won't work (e.g 09, 01, 06).
The main problem is that our HEX has to be converted into a string, before being able to generate a pdf417 barcode and no encoding (ascii, utf-8, etc.) supports those hexcharacters.
Is there a way to get a byte array into the generator or somehow make sure that, when reading the barcode, these characters will be displayed correctly?
Other than that ZXing fits all my needs, but I cant find a propper way of using my data in this case.

**Comment by jl-yndu** [comment]
The following HEX throws the error:

> Non-encodable character detected:   (Unicode: 132)

`30303142415243303030333739373830323541463937363330303130303106414142415243fe3009333137303130323031f9200134fe30fb2006373937383032f420114f6e6c696e652d4d61686e616e74726167fe200a30312e31322e32303038d6200430314b53fe20023030ce200a3538303831486167656edb200158fc200158f4200430314153fe2007303120476d6248e2200b59616e64757520476d6248b9200430314153fe200d30335765737472696e67203235e9200b3434373837426f6368756dec200144ce203c30314153475620303147657363688466747366816872656e64657220476573656c6c736368616674657220204a756c69656e204c81747a656e696368bd2012303142414e4b203030314445383334333035fe300b3130303431343136363239f5200b57454c4144454431424f43b8200430314147fe2003303131de20034a6f6be120034a6f6bd4200430314147fe200e30334f737473747261e165203235ea200e343535323548617474696e67656eef200144ce200430314147fe200e3034313434373832426f6368756d96200730314153504b20fe300135f72008526563686e756e67e6200435313031fe35e5200c313531323031313730313035fe300131fb30f2201030315a494e53203030382c3132204231912009303141535053203031fb300134fe30323135313230313137303130355665727a756773706175736368616c652067656d2e20f52032383820424742204162732e2034c6200642424e525748fe300133fb300131fb300138fb300135f7300131e9300131c420`

**Comment by micjahn** [comment]
Please post a complete stack trace of your error ("Non-encodable...").
For me it works like a charm.
And I checked the generated barcode against you online reader and I can't see any wrong value.
Did you really use my method for the conversion from hex to string?

**Comment by jl-yndu** [comment]
Full Error
`ZXing.WriterException wurde nicht behandelt.
  HResult=-2146233088
  Message=Non-encodable character detected:   (Unicode: 132)
  Source=zxing
  StackTrace:
       bei ZXing.PDF417.Internal.PDF417HighLevelEncoder.determineConsecutiveBinaryCount(String msg, Byte[] bytes, Int32 startpos) in C:\ZXing.Net.0.14.0.0\Source\lib\pdf417\encoder\PDF417HighLevelEncoder.cs:Zeile 739.
       bei ZXing.PDF417.Internal.PDF417HighLevelEncoder.encodeHighLevel(String msg, Compaction compaction, Encoding encoding, Boolean disableEci) in C:\ZXing.Net.0.14.0.0\Source\lib\pdf417\encoder\PDF417HighLevelEncoder.cs:Zeile 258.
       bei ZXing.PDF417.Internal.PDF417.generateBarcodeLogic(String msg, Int32 errorCorrectionLevel) in C:\ZXing.Net.0.14.0.0\Source\lib\pdf417\encoder\PDF417.cs:Zeile 682.
       bei ZXing.PDF417.PDF417Writer.bitMatrixFromEncoder(PDF417 encoder, String contents, Int32 width, Int32 height, Int32 margin, Int32 errorCorrectionLevel) in C:\ZXing.Net.0.14.0.0\Source\lib\pdf417\PDF417Writer.cs:Zeile 142.
       bei ZXing.PDF417.PDF417Writer.encode(String contents, BarcodeFormat format, Int32 width, Int32 height, IDictionary`2 hints) in C:\ZXing.Net.0.14.0.0\Source\lib\pdf417\PDF417Writer.cs:Zeile 111.
       bei ZXing.MultiFormatWriter.encode(String contents, BarcodeFormat format, Int32 width, Int32 height, IDictionary`2 hints) in C:\ZXing.Net.0.14.0.0\Source\lib\MultiFormatWriter.cs:Zeile 79.
       bei ZXing.BarcodeWriterGeneric`1.Encode(String contents) in C:\ZXing.Net.0.14.0.0\Source\lib\BarcodeWriterGeneric.cs:Zeile 72.
       bei ZXing.BarcodeWriterGeneric`1.Write(String contents) in C:\ZXing.Net.0.14.0.0\Source\lib\BarcodeWriterGeneric.cs:Zeile 86.
       bei Weiss.Form1.GeneratePDF417(String hexStr) in C:\Users\xxx\Desktop\xxx\xxx\xxx\xxx\Form1.cs:Zeile 696.
       bei Weiss.Form1.GetWeiss() in C:\Users\xxx\Desktop\xxx\xxx\xxx\xxx\Form1.cs:Zeile 159.
       bei Weiss.Form1..ctor() in C:\Users\xxx\Desktop\xxx\xxx\xxx\xxx\Form1.cs:Zeile 21.
       bei Weiss.Program.Main() in C:\Users\xxx\Desktop\xxx\xxx\xxx\xxx\Program.cs:Zeile 19.
       bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       bei System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       bei System.Threading.ThreadHelper.ThreadStart()
  InnerException: `

Code:
 var bitmap = writer.Write(byteArrayAsString); (throws the error)

`        private byte[] GeneratePDF417(string hexStr)
        {
            hexStr = "30303142415243303030333739373830323541463937363330303130303106414142415243fe3009333137303130323031f9200134fe30fb2006373937383032f420114f6e6c696e652d4d61686e616e74726167fe200a30312e31322e32303038d6200430314b53fe20023030ce200a3538303831486167656edb200158fc200158f4200430314153fe2007303120476d6248e2200b59616e64757520476d6248b9200430314153fe200d30335765737472696e67203235e9200b3434373837426f6368756dec200144ce203c30314153475620303147657363688466747366816872656e64657220476573656c6c736368616674657220204a756c69656e204c81747a656e696368bd2012303142414e4b203030314445383334333035fe300b3130303431343136363239f5200b57454c4144454431424f43b8200430314147fe2003303131de20034a6f6be120034a6f6bd4200430314147fe200e30334f737473747261e165203235ea200e343535323548617474696e67656eef200144ce200430314147fe200e3034313434373832426f6368756d96200730314153504b20fe300135f72008526563686e756e67e6200435313031fe35e5200c313531323031313730313035fe300131fb30f2201030315a494e53203030382c3132204231912009303141535053203031fb300134fe30323135313230313137303130355665727a756773706175736368616c652067656d2e20f52032383820424742204162732e2034c6200642424e525748fe300133fb300131fb300138fb300135f7300131e9300131c420";
            var byteArray = Enumerable.Range(0, hexStr.Length / 2).Select(x => Convert.ToByte(hexStr.Substring(x * 2, 2), 16)).ToArray();
            var byteArrayAsString = new String(byteArray.Select(b => (char)b).ToArray());
            var writer = new BarcodeWriter
            {
                Format = BarcodeFormat.PDF_417,
                Options = new PDF417EncodingOptions
                {
                    Height = 200,
                    Width = 200,
                    Margin = 10
                }
            };
            var bitmap = writer.Write(byteArrayAsString);
            
            
            using (var stream = new MemoryStream())
            {
                bitmap.Save(stream, ImageFormat.Png);
                return stream.ToArray();
            }
        }`

**Comment by micjahn** [comment]
Both errors are related to version 0.14 of ZXing.Net.
They are fixed in the next version.
Please try the current source code from the repository.

**Comment by jl-yndu** [comment]
Thanks a lot! It's working perfectly with the  current version from the source code!
