### ISSUE TITLE
For use in VB6

### ISSUE THREAD

**Issue by ravimolasaria** [micjahn/ZXing.Net#300]
Can you please let me know how to use this in vb6. I've checked one of the post of dekoforce / BobTB in which you have replied to use .tlb file. I've got zxing.interop.dll file but it is not getting registered in system. Please let me know how to generate the tlb file.

**Comment by micjahn** [comment]
Please try the steps which are described in the wiki:
https://github.com/micjahn/ZXing.Net/wiki/Using-ZXing.Net-with-VBA-%28COM-Interop%29
