### ISSUE TITLE
ZXing and .NET Standart 2.0

### ISSUE THREAD

**Issue by akucherk** [micjahn/ZXing.Net#302]
Hello.
All works like a charm till I changed my project to .NET Standart 2.0 and get Method not found "ZXing.Result ZXing.BarcodeReader.Decode(Byte[])" exception with 0.16.5 version.
(With 0.16.6 version I have no idea how to use it at all. Could you please add a using sample to readme?)

This is my code:
`private static string ParseQrFromImage(MemoryStream stream)
{
	var reader = new BarcodeReader();
	var result = reader.Decode(stream.ToArray());
	return result?.Text;
}`

**Comment by micjahn** [comment]
I have no idea what you mean. First, you should use the actual version 0.16.6.
Technically your sample code is ok, as long as the stream contains only the raw bytes of the RGBA pixel values.
A better way would be if you use one of the bindings for ZXing.Net which supports the image library of your project:
https://www.nuget.org/packages?q=ZXing.Bindings
The bindings contain a special BarcodeReader implementation which can decode an image in the format of the image library.

**Comment by akucherk** [comment]
Thanks, this works for me: 
update tolast vesion, install ZXing.Net.Bindings.ZKWeb.System.Drawing package and use
private static string ParseQrFromImage(MemoryStream stream)
{
	var barcodeBitmap = new System.DrawingCore.Bitmap(stream);
	var reader = new BarcodeReaderGeneric();
	var result = BarcodeReaderExtensions.Decode(reader, barcodeBitmap);
	return result?.Text;
}

**Comment by micjahn** [comment]
Alternative snippet:

```
private static string ParseQrFromImage(MemoryStream stream)
{
   var barcodeBitmap = new System.DrawingCore.Bitmap(stream);
   var reader = new ZXing.ZKWeb.BarcodeReader();
   var result = reader.Decode(barcodeBitmap);
   return result?.Text;
}
```
