### ISSUE TITLE
Leak memory in VB.net

### ISSUE THREAD

**Issue by davidlegrand266** [micjahn/ZXing.Net#303]
Hello
I am working on a program in VB.NET. (DLL NET4.6)
I followed the example well, but during execution.
The size of the memory only increases with each decoding.
To reach 4G0 and an out of memory.

Can you help me ?

Best regards

Sample code :

Dim Reader As New BarcodeReader With {
            .AutoRotate = True,
            .TryInverted = True
        }

        Dim XResult As Result = Nothing
        XResult = Reader.Decode(Picture_Decode)

       If XResult IsNot Nothing Then            
                LblDecoderType.Text = XResult.BarcodeFormat.ToString()
                LblDecoderContent.Text = XResult.Text.ToString             
             
       Else
                LblDecoderType.Text = "Pas de code"
                LblDecoderContent.Text = ""
       End If

**Comment by micjahn** [comment]
Without a complete repro I don't have any chance to help here.
Perhaps there is some trouble with "Picture_Decode". Did you dispose the instance?

**Comment by micjahn** [comment]
I made some tests with the windows forms demo client, take some memory snapshots and compared them. I didn't find a memory leak inside the library.
