### ISSUE TITLE
Unable to read Code39 barcode

### ISSUE THREAD

**Issue by TakOsato** [micjahn/ZXing.Net#304]
Hi,

I'm having trouble reading the attached barcode. reader.Decode returns Nothing.

Here is the code I'm using.
The variable pngFile contains the path to the attached file on the local drive.

                    Dim reader As ZXing.BarcodeReader = New ZXing.BarcodeReader() With {.AutoRotate = True}
                    Dim pngImage As New Bitmap(pngFile)

                    Dim result As ZXing.Result = reader.Decode(pngImage)
                    MsgBox(result.Text)

Are there reader.Options that I need to set to read this barcode?

Thanks,
Tak

![IMAQ6150B-02JA-021](https://user-images.githubusercontent.com/77915615/105626700-d6545380-5e74-11eb-8c67-3f26e256d844.png)

**Comment by micjahn** [comment]
How did you generate the barcode? What's the content of the barcode?

**Comment by TakOsato** [comment]
Thank you for your response.

I used an application called MiBarcode.
The barcode contains the following string: IM AQ6150B-02JA-021

I can read this barcode using an app on my iPhone.

**Comment by TakOsato** [comment]
Just a note: I was also able to read this barcode using Spire.Barcode trial version.

**Comment by micjahn** [comment]
I don't know the specifications for Code 39 in detail but perhaps the width of the black and white bars is not within the specified range. I'm not sure if I can fix that. Here is the barcode generated by zxing.net which can be successfully decoded.

![Code39_IM AQ6150B-02JA-021](https://user-images.githubusercontent.com/3475026/107736141-9e1c9400-6d01-11eb-86e4-8aceca5c9203.png)

**Comment by TakOsato** [comment]
Hi Michael,
Thanks for checking this out. Unfortunately, I need this to work for Code 39.
