### ISSUE TITLE
Which method should i use to read the three coordinates while scanning a QR Code?

### ISSUE THREAD

**Issue by mitchdie** [micjahn/ZXing.Net#308]
Hi, i need to find in an image the three coordinates to know where is located a QR Code. Whick method should I use and of which class. If you have an example, much better. Thanks a lot. I googled some examples in internet but they seem old because they don't work.  Thanks a lot.
Diego

**Comment by micjahn** [comment]
There is an event that is fired when the barcode reader finds some possible result points.
```
var barcodeReader = new BarcodeReader();
barcodeReader.ResultPointFound += <your event handler here>;
barcodeReader.Decode(<your image here>);
```

Or if you only need the result points after a code was found you can extract them from the result instance:
```
var barcodeReader = new BarcodeReader();
var result = barcodeReader.Decode(<your image here>);
result.ResultPoints ....
```
The windows forms demo client in the source code repo contains some code that draws a rectangle around the area.

**Comment by mitchdie** [comment]
Thank you MIchael.
Finally it works with your help
