### ISSUE TITLE
ean13 barcode encoding with 'lead', 'separator' and 'trailer'

### ISSUE THREAD

**Issue by EnamulDotNet** [micjahn/ZXing.Net#309]
![EAN-13description](https://user-images.githubusercontent.com/16699801/107604691-0fedd280-6c5b-11eb-82be-90f000db2057.gif)
I need  ean13 lead, separater and a trailer. How can i solve it in c#?
[https://stackoverflow.com/questions/24408954/zxing-ean13-barcode-encoding-with-lead-separator-and-trailer](url)

**Comment by micjahn** [comment]
You can try the class AlternateBitmapRenderer:

var writer = new BarcodeWriter
{
   Renderer = new AlternateBitmapRenderer(),
   BarcodeFormat = ...
};
var bitmap = writer.Write("<content>");

**Comment by EnamulDotNet** [comment]
You are great Michael Jahn. It works exactly what i want. Thanks a lot for your quick response.
