### ISSUE TITLE
Not able decode barcode on Color tiff

### ISSUE THREAD

**Issue by Sureshgoudb** [micjahn/ZXing.Net#31]
Hi,
 I am trying to read barcode from Color scanned tiff file and it is not working as expected. 
 Please help me out on this. 
I have attached the image for your reference
[07212017165503.zip](https://github.com/micjahn/ZXing.Net/files/1168101/07212017165503.zip)

 .

**Comment by Sureshgoudb** [comment]
Hi,
 please do help me out.

**Comment by Sureshgoudb** [comment]
Hi, 
 Can you please update on this.

**Comment by micjahn** [comment]
The scan is a little to much frayed at the edges of the barcode lines. You should add a blur filter before decoding the image.

**Comment by Sureshgoudb** [comment]
Can you guide me as how to add blur filter to the image.
Thanks.

**Comment by micjahn** [comment]
Please take a look at libraries like AForge.Net. ZXing.Net doesn't have any filters built in.
