### ISSUE TITLE
How can we create a dot QR code in Xamarin forms?

### ISSUE THREAD

**Issue by PatroxGaurab** [micjahn/ZXing.Net#310]

**Comment by micjahn** [comment]
I'm not familiar with Xamarin forms. Perhaps you should ask the question here: https://github.com/Redth/ZXing.Net.Mobile
If you use ZXing.Net directly with Xamarin forms you have to write your own renderer class which does your custom generation with dots.
In the repository you can find a sample implementation for the bitmaps of the .net classic framework:
https://github.com/micjahn/ZXing.Net/blob/master/Clients/WindowsFormsDemo/Renderer/CustomBitmapRenderer.cs
