### ISSUE TITLE
ImageSharpRenderer bug

### ISSUE THREAD

**Issue by aleksey-salow** [micjahn/ZXing.Net#312]
https://github.com/micjahn/ZXing.Net/blob/8f80700bb2ab36a485759b3225dd2d2dc1794a15/Source/Bindings/ZXing.ImageSharp/Rendering/ImageSharpRenderer.cs#L76

Size of drawn image is `width × height`, but created image size is `matrix.Width × matrix.Height`.

I created custom renderer to produce QR codes with fixed pixel size. It modifies options.Width & Height and call ImageSharpRenderer to render image. That's how I found this bug.

**Comment by micjahn** [comment]
Should be better now, right?
https://github.com/micjahn/ZXing.Net/commit/89074c140f6d55f3ff4587df34e0d8bf03ad6c83
