### ISSUE TITLE
Write QR code from byte array

### ISSUE THREAD

**Issue by JapanYoshi** [micjahn/ZXing.Net#315]
I’m trying to encode binary data into a QR code, but I can't seem to find the option to do so with ZXing.Net. I've tried doing `ZXing.BarcodeWriter.Write(byte[] data)`, but there doesn't seem to be an overload for a binary QR code as opposed to a text QR code.

**Comment by JapanYoshi** [comment]
Iron Barcode seems to support this feature, according to [this tutorial](https://ironsoftware.com/csharp/barcode/tutorials/csharp-qr-code-generator).

**Comment by JapanYoshi** [comment]
#193 seems to have the same issue. Is anyone maintaining this project?

**Comment by micjahn** [comment]
There is no native support for byte data. But it should be possible with encoding byte data as ISO-8859-15.

```
        private void EncodeDecodeBinaryDataRoundtripTest()
        {
            var bytedata = new byte[256];
            for (var i = 0; i < bytedata.Length; i++)
                bytedata[i] = (byte)(i % 256);
            var image = EncodeBinary(bytedata);
            var decodedByteData = DecodeBinary(image);
            for (var i = 0; i < decodedByteData.Length; i++)
                if (decodedByteData[i] != (byte)(i % 256))
                    throw new InvalidOperationException("encode-decode roundtrip failed");
        }

        private Bitmap EncodeBinary(byte[] byteData)
        {
             var writer = new BarcodeWriter
            {
                Format = BarcodeFormat.QR_CODE,
                Options = new ZXing.QrCode.QrCodeEncodingOptions
                {
                    CharacterSet = "ISO-8859-15",
                    DisableECI = true
                }
             };
            var content = System.Text.Encoding.GetEncoding("ISO-8859-15").GetString(byteData);
            return writer.Write(content);
        }

        private byte[] DecodeBinary(Bitmap image)
        {
            var reader = new BarcodeReader
            {
                Options = new DecodingOptions
                {
                    PossibleFormats = new List<BarcodeFormat> { BarcodeFormat.QR_CODE },
                    CharacterSet = "ISO-8859-15"
                }
            };
            var result = reader.Decode(image);
            if (result != null)
            {
                return System.Text.Encoding.GetEncoding("ISO_8859-15").GetBytes(result.Text);
            }
            return null;
        }
```

And yes, the project is maintained.

**Comment by JapanYoshi** [comment]
Thanks for the tip. I've managed to make my program support both the binary QR codes and the Base64 QR codes I've implemented in the interim, since my binary data happened to have a signature to check whether it's stored as Base64 or ISO_8859-15.

**Comment by toomad2309** [comment]
Hi Michael,
Two years later using 0.16.9 it appears that your solution no longer works. EncodeDecodeBinaryDataRoundtripTest fails on the decode step returning null calling reader.Decode. This block fails in the same way with qrCodeReader.decode. The encode step appears to work successfully generating a QR image.
`        public byte[] readQRImage(Bitmap bitmap)
        {
            try
            {
                //IDictionary<ZXing.DecodeHintType, object> decodingHints_ = new Dictionary<ZXing.DecodeHintType, object>();
                // ...
                //decodingHints_.Add(ZXing.DecodeHintType.CHARACTER_SET, "ISO-8859-15");
                ZXing.BitmapLuminanceSource source = new ZXing.BitmapLuminanceSource(bitmap);
                ZXing.BinaryBitmap binaryBitmap = new ZXing.BinaryBitmap(new ZXing.Common.HybridBinarizer(source));
                ZXing.Result result = qrCodeReader.decode(binaryBitmap, decodingHints_);
                if (result != null)
                {
                    return System.Text.Encoding.GetEncoding("ISO_8859-15").GetBytes(result.Text);
                }
            }
            catch (Exception e) 
            { 
                Console.WriteLine(e.StackTrace); 
            }
            return null;
        }`
