### ISSUE TITLE
Not Reading Data Matrix Barcodes

### ISSUE THREAD

**Issue by jpwalters** [micjahn/ZXing.Net#319]
I've been testing the demos like the (WindowsFormsDemo) and so far I'm not able to get the demo to read any barcodes in any of my images even though other libraries are reading all or most without issue.

Let me know what I'm doing wrong.

**Example Image:**
![DataMatrix](https://user-images.githubusercontent.com/4819310/112204091-a8c42600-8be9-11eb-8ad6-3cf90fda2b31.png)

**Comment by micjahn** [comment]
ZXing in general is optimized for mobile phone use cases which means that the barcodes are more or less center in the middle of the image. The datamatrix decoder in particular has exactly that limitation. The code has to be in the center of the image for successful decoding. I added a sample image which I cut of your image.
![112204091-a8c42600-8be9-11eb-8ad6-3cf90fda2b31_only_1](https://user-images.githubusercontent.com/3475026/112219301-16417800-8c25-11eb-8da4-891d0a0f03b7.png)

**Comment by jpwalters** [comment]
Got it ... yeah I didn't think about just trying to read 1 barcode.  🤦‍♂️  However yes you're right when just try to read 1 the demo works as expected.  Thank you for the quick response.
