### ISSUE TITLE
Display text beneath generated barcode

### ISSUE THREAD

**Issue by os1r1s110** [micjahn/ZXing.Net#32]
Hi there, I'm trying to generate a barcode (Code_39, 93 or 128) as an SVG inAsp.Net Core but I can't find a way to display the textual value beneath the generated barcode. 

As of my understanding, that's what the "PureBarcode" setting is for, but it doesn't seem to change anything setting it explicitely to true/false.

Is there something I'm missing here?

**Comment by os1r1s110** [comment]
Okay, as of my really limited understanding of the whole library, here are the observations I made up to now regarding textual value rendering in the output SVG:

The flow goes like this (correct me if I'm wrong) : TagHelper svg rendering-> BarcodeWriterCustom.Write (in this case BarcodeWriterSvg.Write)  -> <BarcodeFormat>Writer.Encode -> SvgRenderer.Render -> SvgRenderer.Create (which is pretty much the real worker in the chain here regarding the svg output)

1. The SVG renderer uses an hardcoded "quiet zone" of 5, which leaves no option to cutomize it. It could be nice to add an option to set the desired "quiet zone". I also found that the bitmatrix already takes into account the "margins" option, but that is only applied on the sides. It would be nice to have a way to put a margin top/bottom, else the text cannot be bigger than 5 (as it would overflow the viewport size).
2. There doesn't seem to be anywhere taking into account the textual value in the SVG renderer, so it would need to be added

**Comment by os1r1s110** [comment]
There is also another thing I don't fully understand, why bothering passing the "BarcodeFormat" to the base OneDimensionalCodeWriter if it doesn't use it anywhere?

**Comment by micjahn** [comment]
I will try to answer all of your questions:
1. text beneath the barcode is only supported by the bitmap renderer. Feel free to provide a PR which adds support for text generation for the SVG renderer. So the PureBarcode option has only an effect if the bitmap renderer is used.
2. I can't remember why I added a "quiet zone" in the SVG renderer. It doesn't make any sense. The margin value is the quiet zone which is added by the writer to the bitmatrix. I will remove that additional quiet zone. If you need more space at the bottom to write the text you should use an own custom renderer implementation.
3. The option PureBarcode is only used by the renderer implementations if they support it. The different bitmatrix writers doesn't support the generation of a textual representation of the content. The option isn't lost. The renderer implementation can use it.
4. The BarcodeFormat argument is passed to the OneDimensionalCodeWriter because the Writer interface defines it. The MultiFormatWriter implements the same interface and the argument is needed to call the correct implementation for the selected format. I can't answer the question why the architecture of the interface and classes were choosen like they are because I only converted the java version to .Net.

**Comment by os1r1s110** [comment]
Please do not remove the quiet zone, this is what I used to put the text beneath the generated SVG. If you could simply put that as a setting to the SVG renderer that would be great.

**Comment by micjahn** [comment]
Sorry, I have to remove the additional quiet zone. It's wrong. If you need it you can set the Margin property of the EncodingOptions.
The better way is extending the SVG renderer so that it adds the text below the barcode like the BitmapRenderer.

**Comment by os1r1s110** [comment]
Yeah, I understand why you need to remove it, but at the same time, your proposed solution doesn't work. Setting margin property on the EncodingOptions only affect sides margin, so that doesn't help here... :(

**Comment by micjahn** [comment]
You are right. Margin is only added add the left and right of 1D barcodes.
So there are only two options, a modified Svg renderer or you modify the resulting Svg code. You can change the value of the attribute "viewBox" of the "svg" element.
<svg xmlns="http://www.w3.org/2000/svg" style="background-color:rgb(255,255,255);background-color:rgba(1);" fill="rgb(0, 0, 0)" fill-opacity="1" **viewBox="0 0 25 25"** ....

**Comment by os1r1s110** [comment]
yes that's what I ended up doing (modifying the resulting svg element but I consider it as a "brute force hack" and I was hoping for a more suitable solution hehe :P 

I will try to make a custom svg renderer and maybe provide a PR sometime if it seems useful to you.

**Comment by micjahn** [comment]
Meanwhile I modified the SvgRenderer and added the ability to output text beneath the barcode. 
How does your svg code for the text output look like? At the moment I add the following at the end:
`<text x="0" y="201" font-family="Arial" font-size="10" textLength="115" lengthAdjust="spacingAndGlyphs">1   234567   890128</text>`
Font family and font size can be changed through properties.
Do you need something more? Do you now a better way to show the text?

The complete SVG:
`<?xml version="1.0" standalone="no"?><!-- Created with ZXing.Net (http://zxingnet.codeplex.com/) --><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" shape-rendering="crispEdges" viewBox="0 0 115 63" viewport-fill="rgb(255,255,255)" viewport-fill-opacity="1" fill="rgb(0,0,0)" fill-opacity="1" style="background-color:rgb(255,255,255);background-color:rgba(1);"><rect x="10" y="0" width="1" height="50"/><rect x="12" y="0" width="1" height="50"/><rect x="15" y="0" width="1" height="50"/><rect x="18" y="0" width="2" height="50"/><rect x="21" y="0" width="4" height="50"/><rect x="26" y="0" width="1" height="50"/><rect x="29" y="0" width="3" height="50"/><rect x="33" y="0" width="1" height="50"/><rect x="35" y="0" width="2" height="50"/><rect x="40" y="0" width="1" height="50"/><rect x="45" y="0" width="1" height="50"/><rect x="47" y="0" width="1" height="50"/><rect x="50" y="0" width="1" height="50"/><rect x="54" y="0" width="1" height="50"/><rect x="56" y="0" width="1" height="50"/><rect x="58" y="0" width="1" height="50"/><rect x="60" y="0" width="1" height="50"/><rect x="63" y="0" width="1" height="50"/><rect x="67" y="0" width="3" height="50"/><rect x="71" y="0" width="1" height="50"/><rect x="74" y="0" width="3" height="50"/><rect x="79" y="0" width="1" height="50"/><rect x="81" y="0" width="2" height="50"/><rect x="85" y="0" width="2" height="50"/><rect x="88" y="0" width="2" height="50"/><rect x="91" y="0" width="2" height="50"/><rect x="95" y="0" width="1" height="50"/><rect x="98" y="0" width="1" height="50"/><rect x="102" y="0" width="1" height="50"/><rect x="104" y="0" width="1" height="50"/><text x="0" y="63" font-family="Arial" font-size="10" textLength="115" lengthAdjust="spacingAndGlyphs">1   234567   890128</text></svg>`

**Comment by micjahn** [comment]
Or perhaps more like this:
`<text x="57" y="62" font-family="Arial" font-size="10" text-anchor="middle">1   234567   890128</text>`

**Comment by os1r1s110** [comment]
Personally I had something like this added just before the svg closing tag "the brute way" ahah 👍 
`<g><text x=\"50%\" y=\"100%\" style=\"font-size: 5px; font-family: sans-serif;\" text-anchor=\"middle\">{content}</text></g>`

**Comment by os1r1s110** [comment]
The g tag here is only to provide grouping option in case I wanted to modify only the text's style, etc... (that's how I understood SVG works for separating items into "chunks/groups"

**Comment by os1r1s110** [comment]
Thanks for the quick implementation, that's almost exactly what I had in mind! :)

**Comment by DikchaniSecureData** [comment]
Guy's i want to fix text overlap in bottom of barcode like retails UPC-A looking. can you please help me out how i can configure. like this
![upc_sample](https://user-images.githubusercontent.com/26226739/42092313-eb3b7e92-7bc1-11e8-8d65-65a7aeea3a06.jpg)

**Comment by biliktamas79** [comment]
Did you guys managed to fix the UPC-A layout of text overlapping?
@DikchaniSecureData how did you solve the issue?
