### ISSUE TITLE
BarcodeWriterPixelData unable to generate a valid QR code

### ISSUE THREAD

**Issue by thwl76** [micjahn/ZXing.Net#320]
![image](https://user-images.githubusercontent.com/5684587/112603068-6d2a9580-8e4f-11eb-947d-6bd6d993219a.png)

Unity 2019.4.14f1
ZXing.Net.0.16.6.0

I had used the following code from @micjahn and couldn't get a proper QR code generated (shown in attached pic). The upper half seemed compressed while the lower half was always bare / white.

Please help. 

```
using ZXing;
using ZXing.Rendering;

public class QRWrite : MonoBehaviour
{
    public Texture2D qrCode;
    public int dimensions = 512;
    public string qrText = "FooBar";

    void OnGUI()
    {
        // text inputfield
        qrText = GUI.TextField(new Rect(10, 10, 200, 20), qrText);

        // button
        if (GUI.Button(new Rect(210, 10, 50, 20), "Encode"))
        {
            qrCode = generateQR(qrText, dimensions, dimensions);
        }

        // qr image
        if (GUI.Button(new Rect(10, 50, dimensions,dimensions), qrCode)) { }
    }

    private static Texture2D generateQR(string text, int width, int height)
    {
        Texture2D encoded = new Texture2D(width, height);
        var writer = new BarcodeWriterPixelData
        {
            Format = BarcodeFormat.QR_CODE,
            Options = new QrCodeEncodingOptions
            {
                Height = height,
                Width = width
            }
        };
        var pixelData = writer.Write(text);

        encoded.SetPixels32(pixelData.ToColor32());
        encoded.Apply();

        return encoded;
    }
}

```

**Comment by micjahn** [comment]
Is there any chance that you can switch to the ZXing.Unity3D binding which is included in archive  ZXing.Net.Bindings.0.16.6.0.zip in the download section? If so you can change the code to the following which is using the special barcode writer implementation from the binding assembly. There is no need to do an extra step with the pixel data structure.

    private static Texture2D generateQR(string text, int width, int height)
    {
        Texture2D encoded = new Texture2D(width, height);
        var writer = new ZXing.Unity.BarcodeWriter
        {
            Format = BarcodeFormat.QR_CODE,
            Options = new QrCodeEncodingOptions
            {
                Height = height,
                Width = width
            }
        };
        var color32Data= writer.Write(text);

        encoded.SetPixels32(color32Data);
        encoded.Apply();

        return encoded;
    }

**Comment by micjahn** [comment]
I found and fixed the issue.
