### ISSUE TITLE
Micro QR decoder

### ISSUE THREAD

**Issue by ankitpriyarup** [micjahn/ZXing.Net#323]
I am trying to implement micro qr decode functionality in my unity project. I found this repository, https://github.com/GordonCox/ZXing-CSharp-MicroQR-Detector

Not sure how to use the MicroQRReader class though.

**Comment by micjahn** [comment]
This library here doesn't include MicroQR support. In my opinion you can't mix this ZXing.Net library here with the GordonCox branch. Perhaps you should look into the unit tests of the branch:
https://github.com/GordonCox/ZXing-CSharp-MicroQR-Detector/tree/master/Source/test/src/microqrcode
If you go through the tests with the debugger you possibly get an idea how to use that functionality.
