### ISSUE TITLE
Hi, how can i extract the format information from the qr decode? 

### ISSUE THREAD

**Issue by mitchdie** [micjahn/ZXing.Net#325]
Hi, i need to extract the format information from the qr code while is being decoded. How do i extract it? Thanks a lot

**Comment by micjahn** [comment]
Which format information do you mean?

**Comment by mitchdie** [comment]
This one.
[image: image.png]
Thank you

**Comment by mitchdie** [comment]
![image](https://user-images.githubusercontent.com/74085895/113968977-8269d180-980a-11eb-88da-3162403ccfc0.png)

**Comment by micjahn** [comment]
There is only the error correction level which can be accessed by Result.ResultMetadata:
```
var result = reader.Decode(barcodeBitmap);
if (result?.ResultMetadata != null)
{
   var ecLevel = result.ResultMetadata[ZXing.ResultMetadataType.ERROR_CORRECTION_LEVEL].ToString();
}
```

**Comment by mitchdie** [comment]
Thanks a lot. Michael
