### ISSUE TITLE
Datamatrix 2d

### ISSUE THREAD

**Issue by jameslgarrett** [micjahn/ZXing.Net#33]
I'm not able to scan 2d datamatrix codes.  Is this a feature that doesn't exist, or an issue with my barcode generator?

**Comment by micjahn** [comment]
Please provide a sample image. Datamatrix is supported.

**Comment by jameslgarrett** [comment]
Here you go.
![imag0358](https://user-images.githubusercontent.com/12520752/29231948-dbbe71f6-7eae-11e7-9609-e24877e4b789.jpg)
![imag0357](https://user-images.githubusercontent.com/12520752/29231947-dbbe75c0-7eae-11e7-9da2-2f2f4d0e9dd1.jpg)

**Comment by jameslgarrett** [comment]
Actually I believe I've figured it out.  The datmatrix here is inverted.  If I use Neo Reader (as an example) it scans fine.  If I use ZXing it doesn't work.   However, if I invert the dot in photoshop it works just fine.  Re-invert it again (back to original) and leave the zoom, phone distance, etc the same it doesn't work.

**Comment by micjahn** [comment]
ZXing.Net supports inverted barcodes. That's not an issue. But you have to enable it before scanning.

The main problem of your images is the orientation. The Datamatrix decoder has some issues if the code is
rotated. That's related to the roots of the project. The java version was developed primarly for mobile phones where you get a constant stream of images, the user holds the phone near to the code and the orientation is nearly horizontal.
What can you do? If possible, crop the image to the portion where the barcode is normally located. If possible the Datamatrix code should be near the center of the image. Set the option TryInverted and AutoRotate. Prevent scanning by an angle of 45 degrees.
Or much better provide a pull request which enhances the datamatrix decoder.
![29231947-dbbe75c0-7eae-11e7-9da2-2f2f4d0e9dd1_turn_90_cropped](https://user-images.githubusercontent.com/3475026/29250415-62e3bd96-8042-11e7-8134-2425a102b49c.jpg)
![29231948-dbbe71f6-7eae-11e7-9609-e24877e4b789_turn_45_cropped](https://user-images.githubusercontent.com/3475026/29250419-6aba5c28-8042-11e7-8da9-de79bc3f8833.jpg)
