### ISSUE TITLE
Barcode image is not showing the Actual code in footer note

### ISSUE THREAD

**Issue by sarkar-ritam** [micjahn/ZXing.Net#330]
![image](https://user-images.githubusercontent.com/62100923/116966173-3dcc3b80-accd-11eb-8fbd-194e764cdcd5.png)
Refer the attached image, This is the generated image by Zxing library in java base code. I want to show the actual UPC code as footer note, by default its not showing.
dependencies used  
     <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>core</artifactId>
            <version>3.3.0</version>
     </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
            <version>3.3.0</version>
        </dependency>

**Comment by micjahn** [comment]
This project here is the .Net port of zxing. Please ask your question in the original java based project at github.com/zxing/zxing/
