### ISSUE TITLE
Does the DrawString method support Arabic drawing?

### ISSUE THREAD

**Issue by e-jlion** [micjahn/ZXing.Net#331]
Does the DrawString method support Arabic drawing?

**Comment by e-jlion** [comment]
And here are its output
On Windows 10: It works correctly
[](https://user-images.githubusercontent.com/766010/37753782-45c44e38-2dbc-11e8-8545-3441a6841bb8.png)
On Linux (Ubuntu): Characters are separated and rotated
[](https://user-images.githubusercontent.com/766010/37753785-4c7da594-2dbc-11e8-9f49-57c7efede820.png)

**Comment by micjahn** [comment]
I have no idea. Perhaps you should try it out.
