### ISSUE TITLE
PureBarcode = false does not work with ZXing.ImageSharp

### ISSUE THREAD

**Issue by shapeh** [micjahn/ZXing.Net#332]
I am using ZXing.Net.Bindings.ImageSharp 0.16.9-beta in an ASP.NET 5.0 application to generate Code128 barcodes.

My problem is that I can not get the code produce text below the barcode - even if `PureBarcode = false` is specified.

I have created two methods to test:

1) The first method does not use ImageSharp but rather `System.Drawing`. This method `GetBarcode("123")` works as expected and produce a barcode with text below:
![123-1](https://user-images.githubusercontent.com/29387615/117574650-71003780-b0de-11eb-86cd-6ed05fb13800.jpg)

2) Second method uses `ImageSharp`. However, this method `GetBarcodeImageSharp("123")` does **not** produce a barcode with text below:
![123](https://user-images.githubusercontent.com/29387615/117574659-7c536300-b0de-11eb-9d3a-c847cd01dd60.jpg)

What am I doing wrong?

```
    [HttpGet]
    [Route("~/getbarcode")]
    public void GetBarcode(string barcode)
    {
        BarcodeWriter writer = new BarcodeWriter
        {
            Format = BarcodeFormat.CODE_128,
            Options = new EncodingOptions
            {
                Height = 100,
                Width = 300,
                Margin = 0,
                PureBarcode = false
            }
        };           
        writer.Write(barcode).Save(@$"C:\Web\{barcode}.jpg", ImageFormat.Jpeg);
    }

    [HttpGet]
    [Route("~/getbarcodeimagesharp")]
    public void GetBarcodeImageSharp(string barcode)
    {
        var barcodeWriter = new ZXing.ImageSharp.BarcodeWriter<Rgba32>
        {
            Format = ZXing.BarcodeFormat.CODE_128,
            Options = new EncodingOptions // have also tried with Code128EncodingOptions but no luck
            {
                Height = 100,
                Width = 300,
                Margin = 0,
                PureBarcode = false
            }
        };

        barcodeWriter.Write(barcode).Save(@$"C:\Web\{barcode}-imagesharp.jpg");
    }
```

PS: Also posted on SO: https://stackoverflow.com/questions/67458307/how-to-get-a-label-below-barcode-with-zxing-imagesharp

**Comment by micjahn** [comment]
The ImageSharpRenderer class doesn't support it. You are welcome to open a PR that adds the missing functionality.

**Comment by shapeh** [comment]
@micjahn - okay I understand. I would be happy to help fix it but don't know where to start. The ZXing.NET source code is completely new to me.

**Comment by micjahn** [comment]
You should start here:
Source\Bindings\ZXing.ImageSharp\Rendering\ImageSharpRenderer.cs
The method 
public Image<TPixel> Render(BitMatrix matrix, BarcodeFormat format, string content, EncodingOptions options)
needs to be extended to support the output of the content below the barcode.

The bitmap renderer (Source\lib\renderer\BitmapRenderer.cs) supports it already.
