### ISSUE TITLE
DrawString method does not support Arabic problem

### ISSUE THREAD

**Issue by e-jlion** [micjahn/ZXing.Net#334]
Hi:
 Scenario: Arabic is a string reversal based on semantics,
I use the DrawString method of the modified component. The Arabic language has been reversed when drawing, but the picture after drawing is not inverted, you can try it, hoping to fix the bug

**Comment by micjahn** [comment]
Can you provide some more details, please?
For example, a sample image of the current output, a sample image of the expected output, and a small code snippet that shows what you have tried.

**Comment by e-jlion** [comment]
You can use this "آمل أن تصلح الخلل" to try, whether the content output to the picture after drawing is what you see, 
You can also use Google Translate to make a paragraph of Arabic language to draw on the picture, and see if the order of the output and Google Translate is correct. I hope you fix the bug.

**Comment by e-jlion** [comment]
> Can you provide some more details, please?
> For example, a sample image of the current output, a sample image of the expected output, and a small code snippet that shows what you have tried.

The problem occurs in the linux system environment, and the windows system environment is normal

**Comment by micjahn** [comment]
Sorry, I have no linux environment, only windows.
But in my opinion, it is possible, that this issue isn't related to the ZXing.Net project here. Perhaps it is more or less a problem by the underlying implementation of the drawing method.

**Comment by e-jlion** [comment]
> Sorry, I have no linux environment, only windows.
> But in my opinion, it is possible, that this issue isn't related to the ZXing.Net project here. Perhaps it is more or less a problem by the underlying implementation of the drawing method.

So let’s see how to fix this problem in the underlying linux environment
