### ISSUE TITLE
Decode failure.

### ISSUE THREAD

**Issue by MartinDavidWaller** [micjahn/ZXing.Net#335]
Hi, I wonder if you can help me please? I'm using the latest version of the code:

<package id="ZXing.Net" version="0.16.6" targetFramework="net45" />

and trying to decode the attached JPG file. When I point by Android phone at the image using an app called "QR & Barcode Scanner" it tells me the DataMatrix represents the text "12345" which is what I'd expect.

The code i have is very simple - see below. When I run the code I always get a return value of null!

Any help / advice would be much appreciated.

Martin

            IBarcodeReader reader = new BarcodeReader();

            var barcodeBitmap = (Bitmap)Bitmap.FromFile(@"I:\RTDataMatrix.jpg");
            var result = reader.Decode(barcodeBitmap);
            
            if (result != null)
            {
                string x = result.BarcodeFormat.ToString();
                string y = result.Text;
                Console.WriteLine("pp");
            }

![RTDataMatrix](https://user-images.githubusercontent.com/8803621/118974729-10d58500-b96b-11eb-92b3-d913067a85be.jpg)

**Comment by micjahn** [comment]
That's a synthetic image which means it is not taken from a webcam. In such cases it can happen that the detector doesn't find the correct rectangle around the code. If you enable the option PureBarcode it can be decoded.
(reader.Options.PureBarcode = true)

**Comment by MartinDavidWaller** [comment]
Hi, Many thanks for your help with this. It is much appreciated.
