### ISSUE TITLE
Decoder missing some Barcodes

### ISSUE THREAD

**Issue by CanadianHusky** [micjahn/ZXing.Net#336]
Hello,

A very basic test detects 7 out of 8 barcodes on the attached image. What can I do to detect all 8 Barcodes ?

I tried changing the Input resolution, 200, 240, 300 dpi by rasterizing from the source scan - no change - only 7 barcodes are detected each time. 

```
         Dim reader As IBarcodeReader = New BarcodeReader
        reader.Options.PossibleFormats = New List(Of BarcodeFormat) From {BarcodeFormat.CODE_128}
        reader.Options.TryHarder = True
        Dim barcodebitmap As Bitmap = Image.FromFile(imagefile)
        Dim bcresult() As Result = reader.DecodeMultiple(barcodebitmap)
```

200dpi image file is attached. 
Thank you

![WF_2021-05-26-crn__18](https://user-images.githubusercontent.com/35332003/119969799-adc19f00-bfb7-11eb-8fcd-772ba301b1c7.png)

**Comment by micjahn** [comment]
In my opinion the only way would be that you take a deeper look inside the class GenericMultipleBarcodeReader. Perhaps it doesn't divide the image into sub-areas that fit your test case.

**Comment by CanadianHusky** [comment]
Thank you for the good tip.

Upon inspection of the source class, it is clear that an 'already found' logic is implemented. The code is designed to detect **unique** barcodes only. My sample above has line 4 and line 7 duplicates of the same encoded data.
One of them is skipped.
Segmentation and detection works fine for all barcodes when that part is adjusted.
