### ISSUE TITLE
BitmapRenderer.cs not inlcuded in .NETStandard2.0

### ISSUE THREAD

**Issue by joaommvsoares** [micjahn/ZXing.Net#337]
Why is not BitmapRenderer.cs included in .NETStandard2.0?

Can you please take care of that?

Thanks,
JMS

**Comment by joaommvsoares** [comment]
The class BarcodeReader.Bitmap.cs is also excluded...

**Comment by micjahn** [comment]
The core .Net standard 2.0 without platform extensions is missing some classes which are necessary for bitmap support. But there are some special nuget packages which are adding the missing support by using other libraries.
You can find them by looking for "zxing bindings" at nuget.org:
https://www.nuget.org/packages?q=zxing+bindings

In your case you can add the following package to your project:
https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/
This package adds the missing classes BitmapRenderer, BarcodeWriter and BarcodeReader for System.Drawing.Bitmap. (in the namespace ZXing.Windows.Compatibility)

**Comment by joaommvsoares** [comment]
Worked perfectly!
Thanks!
