### ISSUE TITLE
Problems Encoding barcodes from VB6 using COM Interop

### ISSUE THREAD

**Issue by Hypnodude** [micjahn/ZXing.Net#34]
Using VB6 and the COM Interop module, I can retrieve the PixelData object, but am unable to retrieve the actual bitmap and place it in a picture box on screen.
I have tried several different APIs including OleLoadPicture from a Stream of bytes and assigning it to an IPicture etc. but nothing worked.
My solution was create a couple of new methods on IBarcodeWriter and the BarcodeWriter class to a) save the image as a BMP as it loads natively in VB6 whereas a PNG requires some API manipulation, and b) return the barcode bitmap as an IPicture that can be assigned directly to the PictureBox.Picture property.
This works nicely with VB6.

I can now use PictureBox.Picture = writer.write("text to be encoded as a barcode")

I have attached my modified version of the zxing.interop module
[interop.zip](https://github.com/micjahn/ZXing.Net/files/1240652/interop.zip)

**Comment by Hypnodude** [comment]
VB6 function to try retrieve the IPicture from the PixelData.Pixels array:

Called as follows:
PictureBox.Picture = ArrayToPicture(Result.Pixels)
where Result is an instance of the PixelData object returned from using writer.write("text to be encoded as a barcode")

Public Function ArrayToPicture(inArray() As Byte) As IPicture

    ' function creates a stdPicture from the passed array
    ' Offset is first item in array: 0 for 0 bound arrays
    ' Size is how many bytes comprise the image
    Dim o_hMem  As Long
    Dim o_lpMem  As Long
    Dim aGUID(0 To 3) As Long
    Dim Offset As Long
    Dim Size As Long

    Dim IIStream As IUnknown

    aGUID(0) = &H7BF80980    ' GUID for stdPicture
    aGUID(1) = &H101ABF32
    aGUID(2) = &HAA00BB8B
    aGUID(3) = &HAB0C3000

    Offset = 0
    Size = UBound(inArray) + 1
        
    o_hMem = GlobalAlloc(&H2&, Size)
    If Not o_hMem = 0& Then
        o_lpMem = GlobalLock(o_hMem)
        If Not o_lpMem = 0& Then
            CopyMemory ByVal o_lpMem, inArray(Offset), Size
            'MoveMemory ByVal o_lpMem, inArray(Offset), Size
            Call GlobalUnlock(o_hMem)
            If CreateStreamOnHGlobal(o_hMem, 1&, IIStream) = 0& Then
                  Call OleLoadPicture(ByVal ObjPtr(IIStream), 0&, 0&, aGUID(0), ArrayToPicture)
            End If
        End If
    End If
End Function

**Comment by micjahn** [comment]
Thanks for the report.
