### ISSUE TITLE
SVGRenderer provides incorrect values into rgba css function.

### ISSUE THREAD

**Issue by meJevin** [micjahn/ZXing.Net#342]
There's an issue with parameters being passed in this code 
https://github.com/micjahn/ZXing.Net/blob/3d37940c6592e422db68f05b36f1b66366a2faa0/Source/lib/renderer/SVGRenderer.cs#L466

Fixed this issue in the following PR #341 

As I also mentioned in the PR, I'm not sure why `background-color` is being set twice. But I haven't touched that part of code if there's a specific reason why it's like that.

**Comment by micjahn** [comment]
A good find, thank you. 
I'm not sure why there are to background attributes. Perhaps it is for compatibility. rgb() is css2, rgba() is css3
