### ISSUE TITLE
Detection does not work on Unity and Android or iOS phone

### ISSUE THREAD

**Issue by kjyv** [micjahn/ZXing.Net#343]
Using the included sample app and building it to an android or iOS device, Decode() always returns null.
I've tried this with il2cpp or mono, net 2.0 or 4.x, 2019.4 or 2020.3.

At first, it seemed rotation related as the camera image is shown 90 degrees rotated, but I only got it to scan successfully once while rotating (Is the scanner not rotation invariant?). So in some combination of conditions it did detect a code - but it is basically not working at all.

**Comment by kjyv** [comment]
Feeling a bit stupid now: the QR code was inverted and I was sure I tried the TryInverted option. It works fine now.

**Comment by micjahn** [comment]
I'm glad to read that.
