### ISSUE TITLE
Multiple Barcode Detection

### ISSUE THREAD

**Issue by bagsergen** [micjahn/ZXing.Net#344]
Hi, I am trying to multiple barcode detection at same image but I couldn't.

```
var reader = new BarcodeReader();            
Bitmap barcodeBitmap = (Bitmap)Image.FromFile(path);
//var result = reader.Decode(barcodeBitmap);
var result = reader.DecodeMultiple(barcodeBitmap);
```
Expected result count  = 2
Actually = null or 1

![2barcode](https://user-images.githubusercontent.com/53207601/122221918-6c3b5a00-ceba-11eb-921a-d3eaff9d5179.png)
![2QR](https://user-images.githubusercontent.com/53207601/122221922-6d6c8700-ceba-11eb-81e7-a2cf884b41a2.jpg)

**Comment by micjahn** [comment]
Unique results are returned only once.

**Comment by bagsergen** [comment]
Thanks for your attention ⭐

**Comment by bagsergen** [comment]
Is there a way disable this feature, can i get all results ?

**Comment by micjahn** [comment]
Only by changing the source code. There is no option for disabling that filter.
