### ISSUE TITLE
Is there a way to cancel the Decode() or DecodeMultiple() process?

### ISSUE THREAD

**Issue by yasuaki-kan** [micjahn/ZXing.Net#346]
In my execution environment, the processing time for Decode() or DecodeMultiple() is as follows
Case A: When there is a code to be read
About 80 msec

Case B: When there is no code to be read
About 700 msec

Now I have set the interval time for code reading to 200msec. However, when there is no code to be read, it delays.

Is there a way to cancel the Decode() or DecodeMultiple() process?

**Comment by micjahn** [comment]
Not really. If you execute the decoding in a separate thread you can kill them. There is no concept like CancellationToken or similar implemented.
