### ISSUE TITLE
Issue in scanning some QR Codes

### ISSUE THREAD

**Issue by pratikgohil1985** [micjahn/ZXing.Net#347]
**I'm not getting text from QR Image**
>I'm using nuget version 0.16.6 of ZXing.NET, My ASP.NET Project is using .NET 4.8

> My code for reading image
`  ZXing.BarcodeReader qrCodeReader = new ZXing.BarcodeReader
        {
            AutoRotate = true,
            TryInverted = false,
            Options = new DecodingOptions
            {
                TryHarder = true,
                PossibleFormats = new List<BarcodeFormat> { BarcodeFormat.QR_CODE }
            }
        };`

>Expected output should be 
_eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ0NDQwNUM3ODFFNDgyNTA3MkIzNENBNEY4
QkRDNjA2Qzg2QjU3MjAiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJSRVFGeDRIa2dsQnlz
MHlrLUwzR0JzaHJWeUEifQ.eyJkYXRhIjoie1wiU2VsbGVyR3N0aW5cIjpcIjIwQ
UFRQ1M0MDc5TjFaU1wiLFwiQnV5ZXJHc3RpblwiOlwiMjBBQUFDWTIwNjhEMVpVX
CIsXCJEb2NOb1wiOlwiQk5KSFJTVzAwMDYxNC8yMFwiLFwiRG9jVHlwXCI6XCJJT
lZcIixcIkRvY0R0XCI6XCIwMS8wMS8yMDIxXCIsXCJUb3RJbnZWYWxcIjozNDgxM
C4wLFwiSXRlbUNudFwiOjEsXCJNYWluSHNuQ29kZVwiOlwiOTk4NTI0XCIsXCJJc
m5cIjpcIjQ3OTYxODkyNTg3MTI3ZmRiZjBmMmYwYmY5Y2E5YTQ2MmZjNmYyNjkxM
jljOGIwZGMzNzNhODVjMjA1NWM0YzVcIixcIklybkR0XCI6XCIyMDIxLTAxLTEyI
DEzOjI1OjAwXCJ9IiwiaXNzIjoiTklDIn0.W33G-T_ICwkZV8K4hNBOudS9Fmbh9
RV4NbIPQgPvw7WNXA2OvEj9KzyL3wWypPpA1IxaOXNcXBlwjRDcXI8OUbjBxE6rN
fe4JQr3KiOiNgMwzehmgRB2-UR4xOFqVkasliUqKftce5VuFF33QjER0nMw_Cv1K
eMHjBY--GdDCZF06NkjYDx1RVDk7-uxYHk6aJaBS-tb7giJxZf8A24vPIJSZv3mw
6eEbRp95sUKRnKFCrWTqpqRqb5K175qS6tLa8QNsfSMtdHlMJPewmjj4HyOuK9Ju
vJVRj1KRdLCc6eWJvb7yQIOVOhh4yaCXx3M-fcJUhNFNdfwe7GOBfU0Tw_

![486e317b-429b-4aa7-ab7a-6d649a159758](https://user-images.githubusercontent.com/46952019/124426033-122a0800-dd87-11eb-9e74-e0cf6b53ff47.jpg)

,

**Comment by micjahn** [comment]
ZXing is using more or less a heuristical approach to find and decode barcodes within an image. That method isn't perfect and sometimes there are images where a human sees a barcode and the library doesn't. This happens especially with images which are having a higher resolution. If you reduce the size of your image by 50 percent the code is found and decoded.

**Comment by pratikgohil1985** [comment]
Is there any range of image size? please let me know if known. I've actually expanded size of image 5x and got accuracy of more than 90%

**Comment by micjahn** [comment]
Practically a good resolution for mobile phone use case is between 1000x1000 and 1600x1600 pixels. If you want to read small codes from papers with a scanner you should use a higher resolution in grayscale.
