### ISSUE TITLE
CoreCompat adapter for NET Core 2.0

### ISSUE THREAD

**Issue by mrgleba** [micjahn/ZXing.Net#35]
NET Core 2.0 CoreCompat.System.Drawing adapter should reference package CoreCompat.System.Drawing.v2 otherwise there are type name collisions with netstandard2.0 library.

**Comment by micjahn** [comment]
In my opinion there is a new package needed: ZXing.CoreCompat.System.Drawing.V2
But at the moment the main problem is, that there are some types are missing in  CoreCompat.System.Drawing.V2: Rectangle and Color
Color can be replaced with an own implementation. But Rectangle is used by DrawString and LockBits. I have no idea what has to corrected here. Perhaps I'm missing some references.

**Comment by mrgleba** [comment]
The reason they're missing from CoreCompat.v2 is that they are now part of netstandard 2.0.
So there are no changes in code needed. Just new TargetFramework and a reference to CoreCompat.System.Drawing.v2 rather than CoreCompat.System.Drawing. 
I think upgrade to a csproj format would be required for that (at least for that one adapter) (right now I can see project.json stillbeing used everywhere).

**Comment by micjahn** [comment]
My mistake. I tried to build it with visual studio 2015. As far as I understand that isn't supported. I made it now with a csproj file and dotnet.exe.

**Comment by mrgleba** [comment]
Works perfect.
Thank you.
