### ISSUE TITLE
Convert BitMatrix To BitMap

### ISSUE THREAD

**Issue by rmrudro** [micjahn/ZXing.Net#350]
Hello I have Found MySelf in a problem of QRCodeWriter class . As I Mentioned that and created a issue previously [https://github.com/micjahn/ZXing.Net/issues/349](url) #349  Number  issue I customasize QRCodeWritter . From Here can I make QR Code . Here is my code 
`var encodeHint = new Dictionary<EncodeHintType, object>();
String contents;
Bitmap bitmap = null;
QRCodeWriter writer = new QRCodeWriter();
encodeHint.Add(EncodeHintType.CHARACTER_SET, ENCORD_NAME);
encodeHint.Add(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
BitMatrix bitData;
contents = ss;
bitData = writer.encode(contents, BarcodeFormat.QR_CODE,100,100, encodeHint);`

I want to convert this bitData to bitMap How can I do this . Whenever I try to do this I got error or exception of Null reference Though I debug I see There is Matrix Value I have and bits . Like in the picture below 
![image](https://user-images.githubusercontent.com/33390000/125924359-f4053694-c48d-46af-9b66-c533f36b226d.png)
 You can see I have Matrix , Mode , Version, EClavel . Which data convert mainly into bitMap so that I can show the picture . I need to convert bitData into bitMap but here 
       `bitmap = bitData.ToBitmap();` I got Null or in The Catch I got "Found Empty Contents". I also Asked in the stackoverflow you can check [https://stackoverflow.com/questions/68404864/convert-zxing-common-bitmatrix-to-bitmap-zxing-in-c-sharp#68404864](url)

**Comment by rmrudro** [comment]
I could convert this but my image is Full Black Like This 
![image](https://user-images.githubusercontent.com/33390000/125932876-6fce82d4-4ef0-45de-a14e-45cafd12fcb6.png)

**Comment by rmrudro** [comment]
Can you say The bitdata actually Have QR Code

**Comment by micjahn** [comment]
I really have no clue what you want to achieve. Why not using the BarcodeWriter class directly which is very easy to use? If you really want to generate it this way, then try the class ZXing.Rendering.BitmapRenderer or ZXing.Rendering.WriteableBitmapRenderer. The method ToBitmap is obsolete.
