### ISSUE TITLE
Code 128B

### ISSUE THREAD

**Issue by tinohager** [micjahn/ZXing.Net#351]
Hi, i need a special version of the code 128 barcode but i found no solution. Can you help me?

Code 128 have 4 different modes

- Code 128A: 0-9, A-Z, special chars
- Code 128B: 0-9, A-Z, a-z, special char
- Code 128C: 0-9 only
- Code 128Auto: All ASCII chars

I need for my project the mode 128B how i can set this?

**Required result**
![image](https://user-images.githubusercontent.com/8215186/126879684-14fdeb63-a909-4850-aecf-02af691b9f65.png)
**Current result**
![image](https://user-images.githubusercontent.com/8215186/126879725-0583d34f-8ac3-41a0-861a-580dd41a2b65.png)

**Comment by micjahn** [comment]
The following should work:

```
var writer = new ZXing.BarcodeWriter
{
	Format = BarcodeFormat.CODE_128,
	Options = new ZXing.OneD.Code128EncodingOptions
	{
		ForceCodesetB = true
	}
};
```
