### ISSUE TITLE
Can't decode QR from Image

### ISSUE THREAD

**Issue by n0sferatu** [micjahn/ZXing.Net#353]
![qr psd](https://user-images.githubusercontent.com/1777353/127870244-dd79567a-0f8e-4464-a628-7526636c38fb.jpg)

this qr code can't be scanned by zxing (c#), but with iphone camera, with original barcode reader of camera app, the code can be decoded.

the text in qr is 4-23-2508.

**Comment by micjahn** [comment]
Sorry, there is no guarantee that every single image can be decoded by zxing. The heuristical approach fails sometimes.

**Comment by sam9949286565** [comment]
Hi

**Comment by sam9949286565** [comment]
F
