### ISSUE TITLE
These two-dimensional codes can't be parsed

### ISSUE THREAD

**Issue by d723996886e** [micjahn/ZXing.Net#354]
![捕获](https://user-images.githubusercontent.com/44045778/129439961-92b06297-81c5-47e2-88cd-5b721355011d.PNG)
![7](https://user-images.githubusercontent.com/44045778/129439964-f706f0b1-bf8a-45f5-b538-ee0671cde960.PNG)
![43815702-89c11fe6-9ac0-11e8-967e-4dad7bfcc905](https://user-images.githubusercontent.com/44045778/129439970-5d9f33a1-60d6-43b6-a9ab-d02d7cf09774.jpg)
Hello!

I can't parse these QR codes with the above demo, which may be related to zxing's decoding ability, but I try to parse them with wechat. Can you help answer the reason.

**Comment by micjahn** [comment]
Low contrast, too much distortion, too blurry. Zxing can't decode every image of any quality.
Try to get better images.
