### ISSUE TITLE
COM Interop not returning null

### ISSUE THREAD

**Issue by towheed** [micjahn/ZXing.Net#359]
Using your code from the Wiki and passing an image without a valid QR Code does not return null.

I'm testing this in VBA using Access 2003.

`If res Is Nothing Then
    .
    .
End If`

This will always fail.

`res.BarCodeFormat` returns 0 for invalid QR Codes.

This fixed it for me from BarcodeReader.cs:

`return (result.BarcodeFormat != 0 ? result : null);`

Not sure if it's the decoder itself or just simply VBA.

**Comment by micjahn** [comment]
It's the decoder. It always returns a Result object. It only returns null if the decoding process throws an exception. Do you think that it is necessary to change that? Perhaps there should only be a new BarcodeFormat enumeration value like BarcodeFormat.None for the value 0. And in case of the exception it should return the same, an empty Result object with BarcodeFormat.None. What do you think?

**Comment by towheed** [comment]
>

**Comment by towheed** [comment]
>  Perhaps there should only be a new BarcodeFormat enumeration value like BarcodeFormat.None for the value 0. And in case of the exception it should return the same, an empty Result object with BarcodeFormat.None.

Then from VBA you will have to test for:
`If res.BarcodeFormat.None=0 then .. End If`

as opposed to:
`If res.BarcodeFormat=0 .. End If`

So might as well leave it as is and test from VBA.

**Comment by micjahn** [comment]
I decided to introduce two special "BarcodeFormat"s: None and Error.
In my opinion it is more consistent and functional now:
```
   Set res = reader.DecodeImageFile("...")
   If res.BarcodeFormat = BarcodeFormat.Error Then
      Rem TODO: error handling: res.Error
   ElseIf res.BarcodeFormat = BarcodeFormat.None Then
      Rem TODO: no barcode found
   Else
      Rem TODO: barcode found
   End If
```
