### ISSUE TITLE
Decode returns null since 0.16.4

### ISSUE THREAD

**Issue by jkatsiotis** [micjahn/ZXing.Net#362]
`/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCABbAV8DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+vP/ABb/AMle+HX/AHEv/RC16BXn/i3/AJK98Ov+4l/6IWgDgPh//wA0d/7jX/s1eP8AiH/kB+E/+wU//pbdV7B8P/8Amjv/AHGv/Zq8f8Q/8gPwn/2Cn/8AS26oA+n/AAl/yV74i/8AcN/9ENXAfCz/AJOF8a/9v3/pWld/4S/5K98Rf+4b/wCiGrgPhZ/ycL41/wC37/0rSgDv/CX/ACV74i/9w3/0Q1cB8LP+TevGv/b9/wCkiV3/AIS/5K98Rf8AuG/+iGrgPhZ/yb141/7fv/SRKAPP/in/AMyV/wBipY/+z10Hg3/k6G5/7Cupf+gzVz/xT/5kr/sVLH/2eug8G/8AJ0Nz/wBhXUv/AEGagDz/AMPf8gPxZ/2Ck/8AS21r3/4L/wDIc8Qf9grQv/SIV4B4e/5Afiz/ALBSf+ltrXv/AMF/+Q54g/7BWhf+kQoA4Dwb/wAnQ3P/AGFdS/8AQZq6D4gf81i/7gv/ALLXP+Df+Tobn/sK6l/6DNXQfED/AJrF/wBwX/2WgDv/AAl/yV74i/8AcN/9ENXkH7OP/JQ9Q/7BUn/o2KvX/CX/ACV74i/9w3/0Q1eQfs4/8lD1D/sFSf8Ao2KgA+MP/Ic8bf8AYV0j/wBIp65/xb/ySH4df9xL/wBHrXQfGH/kOeNv+wrpH/pFPXP+Lf8AkkPw6/7iX/o9aAPX9Y/5J58Jf+wro/8A6KNYH7TX/Mrf9vf/ALRrf1j/AJJ58Jf+wro//oo1gftNf8yt/wBvf/tGgDn5f+SeePP+wV4b/wDRUVdB8QP+axf9wX/2Wufl/wCSeePP+wV4b/8ARUVdB8QP+axf9wX/ANloAP2mv+ZW/wC3v/2jXn/xT/5kr/sVLH/2evQP2mv+ZW/7e/8A2jXn/wAU/wDmSv8AsVLH/wBnoA9/+Fn/ADOv/Y133/slfMHh7/kB+LP+wUn/AKW2tfT/AMLP+Z1/7Gu+/wDZK+YPD3/ID8Wf9gpP/S21oA9/1j/knnwl/wCwro//AKKNcB4N/wCTobn/ALCupf8AoM1d/rH/ACTz4S/9hXR//RRrgPBv/J0Nz/2FdS/9BmoA6D4gf81i/wC4L/7LR8LP+TevGv8A2/f+kiUfED/msX/cF/8AZaPhZ/yb141/7fv/AEkSgDz/AMJf8kh+Iv8A3Df/AEe1e/8Ai3/kr3w6/wC4l/6IWvAPCX/JIfiL/wBw3/0e1e/+Lf8Akr3w6/7iX/ohaAPAPFv/ACSH4df9xL/0etGo/wDMx/8AYqaV/wC4+jxb/wAkh+HX/cS/9HrRqP8AzMf/AGKmlf8AuPoA9/8Ain/zJX/Y12P/ALPXkH7R3/JQ9P8A+wVH/wCjZa9f+Kf/ADJX/Y12P/s9eQftHf8AJQ9P/wCwVH/6NloA6D4gf81i/wC4L/7LXj95/wAk80b/ALCt/wD+irSvYPiB/wA1i/7gv/steP3n/JPNG/7Ct/8A+irSgD3/AMCf8lD8M/8AZP7X/wBGrXQfCz/mdf8Asa77/wBkrn/An/JQ/DP/AGT+1/8ARq10Hws/5nX/ALGu+/8AZKAPmDw9/wAgPxZ/2Ck/9LbWvr/wJ/yTzwz/ANgq1/8ARS18geHv+QH4s/7BSf8Apba19f8AgT/knnhn/sFWv/opaAOgooooAK8/8W/8le+HX/cS/wDRC16BXn/i3/kr3w6/7iX/AKIWgDgPh/8A80d/7jX/ALNXj/iH/kB+E/8AsFP/AOlt1XsHw/8A+aO/9xr/ANmrx/xD/wAgPwn/ANgp/wD0tuqAPp/wl/yV74i/9w3/ANENXAfCz/k4Xxr/ANv3/pWld/4S/wCSvfEX/uG/+iGrgPhZ/wAnC+Nf+37/ANK0oA7/AMJf8le+Iv8A3Df/AEQ1cB8LP+TevGv/AG/f+kiV3/hL/kr3xF/7hv8A6IauA+Fn/JvXjX/t+/8ASRKAPP8A4p/8yV/2Klj/AOz10Hg3/k6G5/7Cupf+gzVz/wAU/wDmSv8AsVLH/wBnroPBv/J0Nz/2FdS/9BmoA8/8Pf8AID8Wf9gpP/S21r3/AOC//Ic8Qf8AYK0L/wBIhXgHh7/kB+LP+wUn/pba17/8F/8AkOeIP+wVoX/pEKAOA8G/8nQ3P/YV1L/0Gaug+IH/ADWL/uC/+y1z/g3/AJOhuf8AsK6l/wCgzV0HxA/5rF/3Bf8A2WgDv/CX/JXviL/3Df8A0Q1eQfs4/wDJQ9Q/7BUn/o2KvX/CX/JXviL/ANw3/wBENXkH7OP/ACUPUP8AsFSf+jYqAD4w/wDIc8bf9hXSP/SKeuf8W/8AJIfh1/3Ev/R610Hxh/5Dnjb/ALCukf8ApFPXP+Lf+SQ/Dr/uJf8Ao9aAPX9Y/wCSefCX/sK6P/6KNYH7TX/Mrf8Ab3/7Rrf1j/knnwl/7Cuj/wDoo1gftNf8yt/29/8AtGgDn5f+SeePP+wV4b/9FRV0HxA/5rF/3Bf/AGWufl/5J548/wCwV4b/APRUVdB8QP8AmsX/AHBf/ZaAD9pr/mVv+3v/ANo15/8AFP8A5kr/ALFSx/8AZ69A/aa/5lb/ALe//aNef/FP/mSv+xUsf/Z6APf/AIWf8zr/ANjXff8AslfMHh7/AJAfiz/sFJ/6W2tfT/ws/wCZ1/7Gu+/9kr5g8Pf8gPxZ/wBgpP8A0ttaAPf9Y/5J58Jf+wro/wD6KNcB4N/5Ohuf+wrqX/oM1d/rH/JPPhL/ANhXR/8A0Ua4Dwb/AMnQ3P8A2FdS/wDQZqAOg+IH/NYv+4L/AOy0fCz/AJN68a/9v3/pIlHxA/5rF/3Bf/ZaPhZ/yb141/7fv/SRKAPP/CX/ACSH4i/9w3/0e1e/+Lf+SvfDr/uJf+iFrwDwl/ySH4i/9w3/ANHtXv8A4t/5K98Ov+4l/wCiFoA8A8W/8kh+HX/cS/8AR60aj/zMf/YqaV/7j6PFv/JIfh1/3Ev/AEetGo/8zH/2Kmlf+4+gD3/4p/8AMlf9jXY/+z15B+0d/wAlD0//ALBUf/o2WvX/AIp/8yV/2Ndj/wCz15B+0d/yUPT/APsFR/8Ao2WgDoPiB/zWL/uC/wDsteP3n/JPNG/7Ct//AOirSvYPiB/zWL/uC/8AsteP3n/JPNG/7Ct//wCirSgD3/wJ/wAlD8M/9k/tf/Rq10Hws/5nX/sa77/2Suf8Cf8AJQ/DP/ZP7X/0atdB8LP+Z1/7Gu+/9koA+YPD3/ID8Wf9gpP/AEtta+v/AAJ/yTzwz/2CrX/0UtfIHh7/AJAfiz/sFJ/6W2tfX/gT/knnhn/sFWv/AKKWgDoKKKKACvP/ABb/AMle+HX/AHEv/RC16BXn/i3/AJK98Ov+4l/6IWgDgPh//wA0d/7jX/s1eP8AiH/kB+E/+wU//pbdV7B8P/8Amjv/AHGv/Zq8f8Q/8gPwn/2Cn/8AS26oA+n/AAl/yV74i/8AcN/9ENXAfCz/AJOF8a/9v3/pWld/4S/5K98Rf+4b/wCiGrgPhZ/ycL41/wC37/0rSgDv/CX/ACV74i/9w3/0Q1cB8LP+TevGv/b9/wCkiV3/AIS/5K98Rf8AuG/+iGrgPhZ/yb141/7fv/SRKAPP/in/AMyV/wBipY/+z10Hg3/k6G5/7Cupf+gzVz/xT/5kr/sVLH/2eug8G/8AJ0Nz/wBhXUv/AEGagDz/AMPf8gPxZ/2Ck/8AS21r3/4L/wDIc8Qf9grQv/SIV4B4e/5Afiz/ALBSf+ltrXv/AMF/+Q54g/7BWhf+kQoA4Dwb/wAnQ3P/AGFdS/8AQZq6D4gf81i/7gv/ALLXP+Df+Tobn/sK6l/6DNXQfED/AJrF/wBwX/2WgDv/AAl/yV74i/8AcN/9ENXkH7OP/JQ9Q/7BUn/o2KvX/CX/ACV74i/9w3/0Q1eQfs4/8lD1D/sFSf8Ao2KgA+MP/Ic8bf8AYV0j/wBIp65/xb/ySH4df9xL/wBHrXQfGH/kOeNv+wrpH/pFPXP+Lf8AkkPw6/7iX/o9aAPX9Y/5J58Jf+wro/8A6KNYH7TX/Mrf9vf/ALRrf1j/AJJ58Jf+wro//oo1gftNf8yt/wBvf/tGgDn5f+SeePP+wV4b/wDRUVdB8QP+axf9wX/2Wufl/wCSeePP+wV4b/8ARUVdB8QP+axf9wX/ANloAP2mv+ZW/wC3v/2jXn/xT/5kr/sVLH/2evQP2mv+ZW/7e/8A2jXn/wAU/wDmSv8AsVLH/wBnoA9/+Fn/ADOv/Y133/slfMHh7/kB+LP+wUn/AKW2tfT/AMLP+Z1/7Gu+/wDZK+YPD3/ID8Wf9gpP/S21oA9/1j/knnwl/wCwro//AKKNcB4N/wCTobn/ALCupf8AoM1d/rH/ACTz4S/9hXR//RRrgPBv/J0Nz/2FdS/9BmoA6D4gf81i/wC4L/7LR8LP+TevGv8A2/f+kiUfED/msX/cF/8AZaPhZ/yb141/7fv/AEkSgDz/AMJf8kh+Iv8A3Df/AEe1e/8Ai3/kr3w6/wC4l/6IWvAPCX/JIfiL/wBw3/0e1e/+Lf8Akr3w6/7iX/ohaAPAPFv/ACSH4df9xL/0etGo/wDMx/8AYqaV/wC4+jxb/wAkh+HX/cS/9HrRqP8AzMf/AGKmlf8AuPoA9/8Ain/zJX/Y12P/ALPXkH7R3/JQ9P8A+wVH/wCjZa9f+Kf/ADJX/Y12P/s9eQftHf8AJQ9P/wCwVH/6NloA6D4gf81i/wC4L/7LXj95/wAk80b/ALCt/wD+irSvYPiB/wA1i/7gv/steP3n/JPNG/7Ct/8A+irSgD3/AMCf8lD8M/8AZP7X/wBGrXQfCz/mdf8Asa77/wBkrn/An/JQ/DP/AGT+1/8ARq10Hws/5nX/ALGu+/8AZKAPmDw9/wAgPxZ/2Ck/9LbWvr/wJ/yTzwz/ANgq1/8ARS18geHv+QH4s/7BSf8Apba19f8AgT/knnhn/sFWv/opaAOgooooAK8/8W/8le+HX/cS/wDRC16BXn/i3/kr3w6/7iX/AKIWgDgPh/8A80d/7jX/ALNXj/iH/kB+E/8AsFP/AOlt1XsHw/8A+aO/9xr/ANmrx/xD/wAgPwn/ANgp/wD0tuqAPp/wl/yV74i/9w3/ANENXAfCz/k4Xxr/ANv3/pWld/4S/wCSvfEX/uG/+iGrgPhZ/wAnC+Nf+37/ANK0oA7/AMJf8le+Iv8A3Df/AEQ1cB8LP+TevGv/AG/f+kiV3/hL/kr3xF/7hv8A6IauA+Fn/JvXjX/t+/8ASRKAPP8A4p/8yV/2Klj/AOz10Hg3/k6G5/7Cupf+gzVz/wAU/wDmSv8AsVLH/wBnroPBv/J0Nz/2FdS/9BmoA8/8Pf8AID8Wf9gpP/S21r3/AOC//Ic8Qf8AYK0L/wBIhXgHh7/kB+LP+wUn/pba17/8F/8AkOeIP+wVoX/pEKAOA8G/8nQ3P/YV1L/0Gaug+IH/ADWL/uC/+y1z/g3/AJOhuf8AsK6l/wCgzV0HxA/5rF/3Bf8A2WgDv/CX/JXviL/3Df8A0Q1eQfs4/wDJQ9Q/7BUn/o2KvX/CX/JXviL/ANw3/wBENXkH7OP/ACUPUP8AsFSf+jYqAD4w/wDIc8bf9hXSP/SKeuf8W/8AJIfh1/3Ev/R610Hxh/5Dnjb/ALCukf8ApFPXP+Lf+SQ/Dr/uJf8Ao9aAPX9Y/wCSefCX/sK6P/6KNYH7TX/Mrf8Ab3/7Rrf1j/knnwl/7Cuj/wDoo1gftNf8yt/29/8AtGgDn5f+SeePP+wV4b/9FRV0HxA/5rF/3Bf/AGWufl/5J548/wCwV4b/APRUVdB8QP8AmsX/AHBf/ZaAD9pr/mVv+3v/ANo15/8AFP8A5kr/ALFSx/8AZ69A/aa/5lb/ALe//aNef/FP/mSv+xUsf/Z6APf/AIWf8zr/ANjXff8AslfMHh7/AJAfiz/sFJ/6W2tfT/ws/wCZ1/7Gu+/9kr5g8Pf8gPxZ/wBgpP8A0ttaAPf9Y/5J58Jf+wro/wD6KNcB4N/5Ohuf+wrqX/oM1d/rH/JPPhL/ANhXR/8A0Ua4Dwb/AMnQ3P8A2FdS/wDQZqAOg+IH/NYv+4L/AOy0fCz/AJN68a/9v3/pIlHxA/5rF/3Bf/ZaPhZ/yb141/7fv/SRKAPP/CX/ACSH4i/9w3/0e1e/+Lf+SvfDr/uJf+iFrwDwl/ySH4i/9w3/ANHtXv8A4t/5K98Ov+4l/wCiFoA8A8W/8kh+HX/cS/8AR60aj/zMf/YqaV/7j6PFv/JIfh1/3Ev/AEetGo/8zH/2Kmlf+4+gD3/4p/8AMlf9jXY/+z15B+0d/wAlD0//ALBUf/o2WvX/AIp/8yV/2Ndj/wCz15B+0d/yUPT/APsFR/8Ao2WgDoPiB/zWL/uC/wDsteP3n/JPNG/7Ct//AOirSvYPiB/zWL/uC/8AsteP3n/JPNG/7Ct//wCirSgD3/wJ/wAlD8M/9k/tf/Rq10Hws/5nX/sa77/2Suf8Cf8AJQ/DP/ZP7X/0atdB8LP+Z1/7Gu+/9koA+YPD3/ID8Wf9gpP/AEtta+v/AAJ/yTzwz/2CrX/0UtfIHh7/AJAfiz/sFJ/6W2tfX/gT/knnhn/sFWv/AKKWgDoKKKKACs+70TTr7WNO1a5t999pvm/ZJd7Dy/MXa/AODkDHIOO1aFFAHP6f4J8O6X/Y/wBi0/yv7G8/7B++kbyfOz5nVjuzk/ezjtise4+EHgS7gtIZ9C3x2kRhgH2ucbELtIRw/PzOx59fTFdxRQBn2miadY6xqOrW1vsvtS8r7XLvY+Z5a7U4JwMA44Az3rP0rwT4d0TxDe6/p2n+Tqd95n2ifzpG373Dt8rMVGWAPAFdBRQBn2miadY6xqOrW1vsvtS8r7XLvY+Z5a7U4JwMA44Az3rP0rwT4d0Tw9e6Bp2n+Tpl95n2iDzpG370CN8zMWGVAHBFdBRQBx+q/C3wbrf2L+0dG877DaR2Vv8A6VMuyFM7V+VxnGTycn3qxZ/Dvwrp/ihvEtrpfl6u0skxuPtEpy8gYOdpbbzubtxniuoooA4e3+EHgS0gu4YNC2R3cQhnH2uc70DrIBy/HzIp49PTNdBovhbRvD09xNpVn9nkuIoIZT5rvuSFPLiHzE4wvHHXvk1sUUAcvZ/Dvwrp/ihvEtrpfl6u0skxuPtEpy8gYOdpbbzubtxnirGoeCfDuqf2x9t0/wA3+2fI+3/vpF87yceX0YbcYH3cZ75roKKAM+00TTrHWNR1a2t9l9qXlfa5d7HzPLXanBOBgHHAGe9Y/hz4d+FfCOoyX+h6X9kupIjCz/aJZMoSCRh2I6qPyrqKKAOX1j4d+FdfnvZtT0vz5L6WGa4P2iVd7xI0cZ+VhjCuw4xnPOTVe7+Fvg2+0fTtJudG32Om+b9ki+1TDy/Mbc/IfJyRnknHauwooAx5vC2jXGnaRYS2e610iWGaxTzXHlPEMRnOctgf3s575qv4m8E+HfGP2X+39P8Atn2Xf5P76SPbuxu+4wznaOvpXQUUAcufh34VOnX9gdL/ANF1CK2huU+0S/vEtwBCM7sjaFHTGcc5qxqHgnw7qn9sfbdP83+2fI+3/vpF87yceX0YbcYH3cZ75roKKAOf8TeCfDvjH7L/AG/p/wBs+y7/ACf30ke3djd9xhnO0dfSs/Vfhb4N1v7F/aOjed9htI7K3/0qZdkKZ2r8rjOMnk5PvXYUUAZ+laJp2ifbf7Ot/J+3Xcl7cfOzb5nxub5icZwOBge1cvb/AAg8CWkF3DBoWyO7iEM4+1znegdZAOX4+ZFPHp6ZruKKAMebwto1xp2kWEtnutdIlhmsU81x5TxDEZznLYH97Oe+az7P4d+FdP8AFDeJbXS/L1dpZJjcfaJTl5Awc7S23nc3bjPFdRRQBz+oeCfDuqf2x9t0/wA3+2fI+3/vpF87yceX0YbcYH3cZ75o0rwT4d0Tw9e6Bp2n+Tpl95n2iDzpG370CN8zMWGVAHBFdBRQBx9p8LfBtjo+o6TbaNssdS8r7XF9qmPmeW25OS+RgnPBGe9dBd6Jp19rGnatc2+++03zfsku9h5fmLtfgHByBjkHHatCigDj7v4W+Db7R9O0m50bfY6b5v2SL7VMPL8xtz8h8nJGeScdqJPhb4Nl+079Gz9ptIrKX/Spvmhi8vYv3+MeTHyOTt5Jyc9hRQBn6romna39i/tG3877Ddx3tv8AOy7Jkztb5SM4yeDke1Y/iP4d+FfF2ox3+uaX9ruo4hCr/aJY8ICSBhGA6sfzrqKKAOf1DwT4d1T+2Ptun+b/AGz5H2/99IvneTjy+jDbjA+7jPfNY7/CDwJJp0Ng2hZtYZZJo0+1z/K7hAxzvzyI0/L3NdxRQBj2HhbRtM1G2v7Oz8u6tdPXTIX81zttlIKpgnBwQOTz71Y0rRNO0T7b/Z1v5P267kvbj52bfM+NzfMTjOBwMD2rQooA4e3+EHgS0gu4YNC2R3cQhnH2uc70DrIBy/HzIp49PTNdhYWNvpmnW1hZx+Xa2sSwwpuJ2ooAUZPJwAOtWKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//9k=`

On the above base64 image while decoding worked until 0.16.2, from 0.16.4 and onward the Decode method returns null.

This is the code the performs the decode and works in 0.16.2 and back

```string barcodeText = string.Empty;
try {
    byte[] bitmapData = Convert.FromBase64String(s);
    using (System.IO.MemoryStream streamBitmap = new System.IO.MemoryStream(bitmapData)) {
        using (var barcodeImg = Image.FromStream(streamBitmap)) {
            using (Bitmap bitImage = new Bitmap(barcodeImg)) {
                var reader = new BarcodeReader();
                barcodeText = reader.Decode(bitImage).Text;

            }
        }
    }
}
catch (Exception e) {
    barcodeText = string.Empty;
}
```

**Comment by micjahn** [comment]
I modified the value of MAX_INDIVIDUAL_VARIANCE. Your image decodes with the small increase of the variance.
