### ISSUE TITLE
Bitmap and WASM

### ISSUE THREAD

**Issue by hannespreishuber** [micjahn/ZXing.Net#366]
just to ensure I didn't miss anything.

Using this lib needs Bitmap (system.drawing) which is as gdi+ wrapper not available on Browser WASM. 

right?
or workaround?

**Comment by micjahn** [comment]
ZXing.Net for .Net Standard 2.0 + ImageSharp binding work in a Blazor app and WebAssembly.

**Comment by sabitertan** [comment]
I tested all latest ZXing.Net on .NET 7 + ImageSharp 1.0.4 , and it is working. But I think we need some upgrades in ZXing.Net.Bindings.ImageSharp because using ImageSharp 2.x or 3.x throwing this error :
Method not found: System.Span`1<!0> SixLabors.ImageSharp.Image`1.GetPixelRowSpan(int)

**Comment by sabitertan** [comment]
Oh my bad didn't realize you have v2 and v3 packages separately :)
