### ISSUE TITLE
Converting Camera2 YUV_420_888 image to PlanarYUVLuminanceSource

### ISSUE THREAD

**Issue by danielftz** [micjahn/ZXing.Net#367]
I am trying to use zxing.net in a Xamarin Android project. My preview image reader receives the Android.Media.Image object, which has three planes of Y, U, V data, each in its own byte array. 

`var planes  = Android.Media.Image.GetPlanes(); `
`Java.Nio.ByteBuffer Y = planes[0]; `
`Java.Nio.ByteBuffer U = planes[1]; `
`Java.Nio.ByteBuffer V = planes[2]; `

However the PlanarYUVLuminanceData only has one byte array as an argument. Should I convert the three YUV byte arrays into one (similar to NV21) first? What exactly is expected as an input for PlanarYUVLuminanceData?

**Comment by micjahn** [comment]
I'm not absolutely sure but I think you should only use planes[0].
PlanarYUVLuminanceSource needs the Y channel. This channel has to be the first in the byte array.

The original help text of this class:
    /// This object extends LuminanceSource around an array of YUV data returned from the camera driver,
    /// with the option to crop to a rectangle within the full data. This can be used to exclude
    /// superfluous pixels around the perimeter and speed up decoding.
    /// It works for any pixel format where the Y channel is planar and appears first, including
    /// YCbCr_420_SP and YCbCr_422_SP.

**Comment by danielftz** [comment]
Each Frame of Preview I capture from the Android device, I have these data: 

    byte array size 1589728
    rowStride 1472,
    pixelStride 1,
    photoWidth 1440, 
    photoHeight 1080,

How would I input these data into the PlanarYUVLuminanceSource?

**Comment by micjahn** [comment]
You can try the following, but I'm not sure if it works. I can't try it out.

```
var planes = Android.Media.Image.GetPlanes();
Java.Nio.ByteBuffer Y = planes[0]; 
luminanceSource = new PlanarYUVLuminanceSource(Y.GetBuffer(),
Y.GetRowStride(),
photoHeight,
0,
0,
photoWidth,
photoHeight,
false);
```
