### ISSUE TITLE
Barcode Decode Returning NULL

### ISSUE THREAD

**Issue by lvankadaru** [micjahn/ZXing.Net#368]
We are using Zxing.Net 0.16.6 some of the barcodes are decoded correctly but some we are having issues as the decoder sends null in return'
![Screenshot 2021-10-07 215803](https://user-images.githubusercontent.com/21339570/136491657-b07931be-00fa-42ef-ac55-9bff36913ff2.png)

attached barcode is one of the code we are trying to decode to extract the details. 

please help us in resolving this issue.

private Image SavePng(PdfiumViewer.PdfDocument document, int pageNumber)
       {
         int dpi = 600;
         SizeF sizeInPoints = document.PageSizes[pageNumber];
         int widthInPixels = (int)Math.Round(sizeInPoints.Width * (float)dpi / 72F);
         int heightInPixels = (int)Math.Round(sizeInPoints.Height * (float)dpi / 72F);

            Image image = document.Render(pageNumber, widthInPixels, heightInPixels, dpi, dpi,true);
         
         return image;
        }

        public dtoPDFParseInfo PDFParse(string fileName, string extension)
        {
           dtoPDFParseInfo res = new dtoPDFParseInfo();
           Bitmap barcodeBitmap = null;
            IBarcodeReader reader = new BarcodeReader();// { AutoRotate = true, TryInverted = true };
            
           var ext = extension.Replace(".","");

           if (ext.ToLower().Contains("pdf"))
           { 
              PdfiumViewer.PdfDocument document = PdfiumViewer.PdfDocument.Load(fileName);

             
              Image img = SavePng(document, 0);

              string fileName_tmp = Path.GetTempFileName();
              img.Save(fileName_tmp, ImageFormat.Png);
                               
              img.Dispose();
              document.Dispose();
                
              // load a bitmap
              barcodeBitmap = (Bitmap)Image.FromFile(fileName_tmp);
                
           }

           var imgExt = new List<string>() {"png", "jpg"};
           if (imgExt.Any(x=>x.Contains(ext.ToLower())))
           { 

             barcodeBitmap = (Bitmap)Image.FromFile(fileName);

           }

            reader.Options = new ZXing.Common.DecodingOptions
            {
                PossibleFormats = new List<BarcodeFormat>
                {
                    BarcodeFormat.PDF_417,
                    BarcodeFormat.CODE_93,
                    BarcodeFormat.CODE_128,
                    BarcodeFormat.CODE_39,
                    BarcodeFormat.EAN_8,
                    BarcodeFormat.EAN_13,
                    BarcodeFormat.UPC_EAN_EXTENSION,
                    BarcodeFormat.ITF,
                },
                TryHarder = true,
                PureBarcode = true,
                ReturnCodabarStartEnd = true
                

            };

           

            // detect and decode the barcode inside the bitmap
            var result = reader.Decode(barcodeBitmap);
                                   
             char[] separator = { '-' }; 
             // do something with the result
           
              string[] decContent;
              if (result != null)
              {
                // decType = result.BarcodeFormat.ToString();
                 decContent = result.Text.Split(separator).ToArray();
                    
                 if (decContent.Length>0)
                  {
                    res.Id = Guid.NewGuid();
                    res.DocumentType = Convert.ToInt32(decContent[0]);
                    res.DocumentCreatedByDate = DateTime.FromFileTime(Convert.ToInt64(decContent[1]));
                    res.DocumentPKey = Convert.ToInt32(decContent[2]);
                    res.DocumentCreatedByUser = Convert.ToInt32(decContent[3]);
                   }
               }

             barcodeBitmap.Dispose();

           return res;
        }

////////// Above is the code that we are using for barcode reader decode from pdf file

**Comment by micjahn** [comment]
ZXing.Net uses, more or less, a heuristical approach. There is no guarantee that it will find every barcode. Sometimes a small difference in the image quality leads to different results. In your case I added a small amount of white area around the code, see sample image attached.
Anyway, use "PureBarecode = true" only if you try to decode a synthetic image without any other pixels around which are not belong to the barcode. In all other cases leave "PureBarcode = false".
![136491657-b07931be-00fa-42ef-ac55-9bff36913ff2](https://user-images.githubusercontent.com/3475026/136505036-ebd6d622-96cb-461e-a04f-3d4ff38a0032.png)
.
