### ISSUE TITLE
GS1 datamatrix separator

### ISSUE THREAD

**Issue by antoniolgr-divimast** [micjahn/ZXing.Net#369]
Why the GS separator is replaced with FNC1 only once? According to GS1 specs the GS separator (char 29) needs to be replaced with FNC1 every time is entered into the string to encode, for separating variable length groups

https://github.com/micjahn/ZXing.Net/blob/58ddb9e780d6504daba1a43bf4fa5e9e51bc0043/Source/lib/datamatrix/encoder/ASCIIEncoder.cs#L86

Thanks

**Comment by micjahn** [comment]
You can find the explanation in the following issue:
https://github.com/micjahn/ZXing.Net/issues/41
