### ISSUE TITLE
Example code not working correctly.

### ISSUE THREAD

**Issue by SeppPenner** [micjahn/ZXing.Net#37]
I'm not quite sure if your example code in the readme file is working in .Net 4.0. But it definitely isn't in .Net 4.5. It should be `var barcodeBitmap = (Bitmap)Image.FromFile("C:\\sample-barcode-image.png");` instead of `var barcodeBitmap = (Bitmap)Bitmap.LoadFrom("C:\\sample-barcode-image.png");`.

So in total:

```
// create a barcode reader instance
IBarcodeReader reader = new BarcodeReader();
// load a bitmap
var barcodeBitmap = (Bitmap)Image.FromFile("C:\\sample-barcode-image.png");
// detect and decode the barcode inside the bitmap
var result = reader.Decode(barcodeBitmap);
// do something with the result
if (result != null)
{
   txtDecoderType.Text = result.BarcodeFormat.ToString();
   txtDecoderContent.Text = result.Text;
}
```

**Comment by micjahn** [comment]
For me it works with .net 4.5. But you are right, the static method is defined for the class Image not Bitmap.
