### ISSUE TITLE
image.ToBase64String produce different base 64 string and image in ZXing.Net.Bindings.ImageSharp 0.16.9-beta than 0.16.10

### ISSUE THREAD

**Issue by shapeh** [micjahn/ZXing.Net#373]
The barcode image for Code 128 is different in 0.16.9-beta than 0.16.10. 
I am wondering if this will cause any problems for barcode readers? 

I have the following TagHelper in a .NET 6.0 web project:

```
    [HtmlTargetElement("barcode")]
    public class BarcodeTagHelper : TagHelper
    {
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            var content = context.AllAttributes["content"].Value.ToString();
            var alt = context.AllAttributes["alt"].Value.ToString();
            var width =

               Convert.ToInt32(string.IsNullOrEmpty(context.AllAttributes["width"]?.Value.ToString())
                  ? "300"
                  : context.AllAttributes["width"].Value.ToString());
            var height =
               Convert.ToInt32(string.IsNullOrEmpty(context.AllAttributes["height"]?.Value.ToString())
                  ? "100"
                  : context.AllAttributes["height"].Value.ToString());
            var margin = 5;
            var barcodeWriter = new ZXing.ImageSharp.BarcodeWriter<Rgba32>
            {
                Format = ZXing.BarcodeFormat.CODE_128,
                Options = new EncodingOptions
                {
                    PureBarcode = false,
                    Height = height,
                    Width = width,
                    Margin = margin,
                }                 
            };

            using (var image = barcodeWriter.Write(content))
            {
                output.TagName = "img";
                output.Attributes.Clear();
                output.Attributes.Add("width", image.Width);
                output.Attributes.Add("height", image.Height);
                output.Attributes.Add("alt", alt);
                output.Attributes.Add("src", string.Format(image.ToBase64String(PngFormat.Instance)));
            }
        }
    }
```

Sample content for barcode:

N-c9fc4114210805000022

**0.16.9-beta produces this barcode:**
![site-3022](https://user-images.githubusercontent.com/29387615/145382412-e014f6b4-9168-41d1-ba26-fd342cd481e9.png)

**0.16.10 produces this barcode:**
![local-3022](https://user-images.githubusercontent.com/29387615/145382358-64262412-d9da-4621-a329-4617670cb30b.png)

**0.16.9-beta: Base 64:** `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAM0AAAAyCAYAAAD/eF+lAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAA+0lEQVR4nO3TQQ6CMAAAQUj8/5dVEkmwKejqdeYilFagurf70/K0ruv2sWyn2/Fr+O14t4/ta/Z1x+tn33UcH9d+c6/xu2brZ3Nn4+M9fnmG2bscz8excZ9m52d7Nnvvsqez+5W5n57p6nf6d+7Zu8+une3H1f+gzL0tQCIaiEQDkWggEg1EooFINBCJBiLRQCQaiEQDkWggEg1EooFINBCJBiLRQCQaiEQDkWggEg1EooFINBCJBiLRQCQaiEQDkWggEg1EooFINBCJBiLRQCQaiEQDkWggEg1EooFINBCJBiLRQCQaiEQDkWggEg1EooFINBCJBiLRQPQAGcOpxSvvDuwAAAAASUVORK5CYII=`

**0.16.10: Base 64:** 
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAM0AAAAyCAYAAAD/eF&#x2B;lAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAA/klEQVR4nO3TWwrCMAAAwRS8/5UVhUAJqbr6O/Nhbdr0Ed3bGOM&#x2B;nh/312Ycx/H6/tzO8fl9mmNzzpx3Pn51rfP4Ovebe63X2s3fnbsbX&#x2B;/xyzPs3uW8v46t67Tbv1qz3XuXNd3dr5z76Zne/U7/nnv17rtjV&#x2B;vx7n9Qzr0NIBENRKKBSDQQiQYi0UAkGohEA5FoIBINRKKBSDQQiQYi0UAkGohEA5FoIBINRKKBSDQQiQYi0UAkGohEA5FoIBINRKKBSDQQiQYi0UAkGohEA5FoIBINRKKBSDQQiQYi0UAkGohEA5FoIBINRKKBSDQQiQYi0UAkGohEA5FoIHoAfZamyPbQI3kAAAAASUVORK5CYII=`

From the Base64 we see differences in encoding of `+` sign, which in newer version sometimes will be `&#x2B;`

**Comment by micjahn** [comment]
Good find. Thanks for reporting. The foreground and background color is switched in 0.16.10. The image is inverted. I fixed it and published version 0.16.11. It should be available via nuget soon.
