### ISSUE TITLE
URL Based QRCode not Redirecting

### ISSUE THREAD

**Issue by sonisp** [micjahn/ZXing.Net#374]
Hi,
I m using ZXing.Net Ver 0.16.6 in my Visual Studio 2019 console app.  I am able to generated the QR Code but when I try to scan the QR Code with any App (in my case in Android) , I get an XML data with no redirection taking place to the Actual URL mentioned in the XML.

**Sample Code**

            string _FilePath = @"C:\Temp\QRCode\";
            Url generator = new Url("https://www.google.com");
            string payload = generator.ToString();

            var QCwriter = new BarcodeWriter();
            QCwriter.Format = BarcodeFormat.QR_CODE;
            QCwriter.Options = new ZXing.Common.EncodingOptions
            {
                Width = 200,
                Height = 200
            };
            var result = QCwriter.Write(payload);
            var qrCodeBitmap = new Bitmap(result);

            using (MemoryStream memStream = new MemoryStream())
            {
                using (FileStream fs = new FileStream(_FilePath + "MyQrCode2.jpg", FileMode.Create, FileAccess.ReadWrite))
                {
                    qrCodeBitmap.Save(memStream, ImageFormat.Jpeg);
                    byte[] bytes = memStream.ToArray();
                    fs.Write(bytes, 0, bytes.Length);
                }
            }

**Sample Output When Scanning from an Android App**
            <System.Security.Policy.Url version="1">
            <Url>https://www.google.com</Url>
            </System.Security.Policy.Url>

Loking for some insight why the redirection is not happening to the URL.

**Comment by micjahn** [comment]
That isn't a problem of the QR code itself. Your content doesn't use a gobal standard for URLs. You do only encode the serialized representation of the .Net Url instance. No QR code scanner app will interpret that content.
The "official" way to encode an uri looks like this: "URL:https://www.google.com".
Most scanner apps will also recognize "https://www.google.com".
Don't use the Uri class to generate you payload. Use the following instead:
`string payload = "URL:https://www.google.com";`
or
`string payload = "https://www.google.com";`
