### ISSUE TITLE
Margin and Width 0, but blurry image

### ISSUE THREAD

**Issue by diegobiasatti** [micjahn/ZXing.Net#376]
hi colleagues, i need your help.
I try print QR 25mm x 25mm (width 80 , heigth 80) ,

1 step : create qr (margin = 0, width and heigth = 0)
2 step : resize image (80x80)

 my code is::

`var bw = new ZXing.BarcodeWriter();
            var encOptions = new ZXing.Common.EncodingOptions() 
{ Width = Convert.ToInt32(txt_pixel1.Text), Height = Convert.ToInt32(txt_pixel1.Text), Margin = 0 };
            bw.Options = encOptions;
            bw.Format = ZXing.BarcodeFormat.QR_CODE;
            var result = new Bitmap(bw.Write(text));
            image_resize.Image= ResizeBitmap(result, width, width);
            return result; `

but result is blurry image 
![qr](https://user-images.githubusercontent.com/15107114/146374632-3eafb2f3-f315-4524-93b0-502e008ab9b0.png)

another side, i cant undersatnd when put width = 110 , heigth =110, margin is too much
![qr1](https://user-images.githubusercontent.com/15107114/146424700-7a77362c-1ef7-48fb-a4b7-5fbabdf045a7.png)

but don't happens with another's sizes, for example 125
![qr2](https://user-images.githubusercontent.com/15107114/146424862-21375f46-f5da-4744-be5f-f801da82fc48.png)

Do you any idea ? 
Thanks so much!

**Comment by micjahn** [comment]
ZXing can only perform resizing by integer values. There is no anti-aliasing support or similar things.
Your content fits into an image with a size of 125x125 pixels. Resizing is done with a factor of 2. 
The content doesn't fit into an image with a size of 110x110 pixels. Resizing by 2 would be too large. So it adds a white border around the qr code.
Blurry images are the result of non-integer resizing operations. Your method ResizeBitmap does anti-aliasing which makes the image blurry.

**Comment by diegobiasatti** [comment]
ok. thanks.. my problem was save to jpeg.. 
Now save QR as BMP monochromatic and all successful
