### ISSUE TITLE
Exception thrown while reading certain QR code

### ISSUE THREAD

**Issue by hillin** [micjahn/ZXing.Net#377]
While trying to read the image below, an exception was thrown:

> KeyNotFoundException: The given key '96' was not present in the dictionary.
    System.ThrowHelper.ThrowKeyNotFoundException<T>(T)
    System.Collections.Generic.Dictionary<TKey, TValue>.this[TKey].get(TKey)
    ZXing.Common.CharacterSetECI.getCharacterSetECIByValue(int)
    ZXing.QrCode.Internal.DecodedBitStreamParser.decode(byte[], ZXing.QrCode.Internal.Version, ZXing.QrCode.Internal.ErrorCorrectionLevel, System.Collections.Generic.IDictionary<ZXing.DecodeHintType, object>)
    ZXing.QrCode.Internal.Decoder.decode(ZXing.Common.BitMatrix, System.Collections.Generic.IDictionary<ZXing.DecodeHintType, object>)
    ZXing.QrCode.QRCodeReader.decode(ZXing.BinaryBitmap, System.Collections.Generic.IDictionary<ZXing.DecodeHintType, object>)
    ZXing.MultiFormatReader.decodeInternal(ZXing.BinaryBitmap)
    ZXing.MultiFormatReader.decode(ZXing.BinaryBitmap, System.Collections.Generic.IDictionary<ZXing.DecodeHintType, object>)
    ZXing.BarcodeReaderGeneric.Decode(ZXing.LuminanceSource)
    ZXing.BarcodeReaderGeneric.Decode(byte[], int, int, ZXing.RGBLuminanceSource.BitmapFormat)
    ...
    [Call Stack Truncated]

The exception disappears if I make certain changes to the image, like trimming the black background, or re-save it as PNG.

![4](https://user-images.githubusercontent.com/13517745/147049595-56cf1945-658f-4c56-b6e5-8370aad51f17.jpg)

**Comment by micjahn** [comment]
There is something wrong with the QR code itself. I didn't find a qr decoder which can successfully decode the content.
But I fixed the exception.
