### ISSUE TITLE
[Bug] Version 0.16.7 has breaking changes

### ISSUE THREAD

**Issue by Jakar510** [micjahn/ZXing.Net#380]
In version 0.16.7,  it will not compile because the `BitmapRenderer` and `BarcodeWriter` don't exist. The `BarcodeWriter` renders a Bitmap.

In version 0.16.6, the following code works. 

	var options = new EncodingOptions
				  {
					  Width       = width,
					  Height      = height,
					  Margin      = 0,
					  PureBarcode = true,
				  };

	options.Hints[EncodeHintType.ERROR_CORRECTION] = ErrorCorrectionLevel.H;

	return new ZXing.BarcodeWriter
		   {
			   Renderer = new ZXing.Rendering.BitmapRenderer(),
			   Options  = options,
			   Format   = ZXing.BarcodeFormat.QR_CODE,
		   };

**Comment by micjahn** [comment]
Please add the package https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/ to your project.
More details are described here:
https://github.com/micjahn/ZXing.Net/issues/379
