### ISSUE TITLE
0.16.6 vs 0.16.7

### ISSUE THREAD

**Issue by kriwec** [micjahn/ZXing.Net#385]
Hello,
Could you please advice how to convert the code below from 0.16.6 to 0.16.7
Many thanks

            var barcodeWriter = new BarcodeWriter//<Bitmap>
            {
                Format = BarcodeFormat.QR_CODE,
                Options = new QrCodeEncodingOptions
                {
                    Width = 256,
                    Height = 256,
                    Margin = 0
                },
                //Renderer = new ZXing.Rendering.BitmapRenderer()
            };
            var result = barcodeWriter.Write(qrCodeText);

            var barcodeBitmap = new Bitmap(result);

**Comment by micjahn** [comment]
Your code is correct. No need for conversion.
But I think you are developing for .Net 6.0. In that case you have to add the following nuget package:
https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/
The bitmap-specific classes are located in the namespace ZXing.Windows.Compatibility.

**Comment by kriwec** [comment]
Hello,
ASP.NET Core MVC Web App
Target framework 5.1.3 - <TargetFramework>net5.0</TargetFramework>
Currect ZXing - <PackageReference Include="ZXing.Net" Version="0.16.6" />
BarcodeWriter depends on BitmapRenderer
    public BarcodeWriter() => this.Renderer = (IBarcodeRenderer<Bitmap>) new BitmapRenderer();
After upgrading to 0.16.7 code above not working
public class BarcodeWriter<TOutput> : BarcodeWriterGeneric, IBarcodeWriter<TOutput>
BitmapRenderer - I can't find in 0.16.7

**Comment by kriwec** [comment]
without Renderer there is an exception - You have to set a renderer instance.

**Comment by kriwec** [comment]
<PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.10" /> - heps to solve problem
