### ISSUE TITLE
Exception when write a barcode with PureBarcode false.

### ISSUE THREAD

**Issue by dms-aping** [micjahn/ZXing.Net#391]
```
            var writer = new BarcodeWriter<Bitmap>
            {
                Format = BarcodeFormat.CODE_128,
                Options = new Code128EncodingOptions
                {
                    Width = 0,
                    Height = 10,
                    PureBarcode = true,
                    Margin = 0,
                },
                Renderer = (IBarcodeRenderer<Bitmap>)new BitmapRenderer()
            };
            var bitmap = writer.Write("12345678");

```
It's ok.

When PureBarcode = false. 
Exception throwed:
System.IndexOutOfRangeException:“Index was outside the bounds of the array.”

**Comment by micjahn** [comment]
The value of "Height" has to be at least the height of the font which is used for the content below the barcode.
For example, if you use a font with a height of 16 pixels you have to set Height = 16 at minimum.

I will provide a fix which prevent the output of the content below the code when the height of the image is too small.
