### ISSUE TITLE
Example of use case in .net 6 with linux

### ISSUE THREAD

**Issue by hectorccmx** [micjahn/ZXing.Net#392]
Hi, I'm using this library with an application that decode qr from images. This application has been ported to .net 6 and put in a docker container (working on linux). However, as you may know, I can't use Bitmap class in order to decode QR from linux.

We we upgrade to version 0.16.7 we cannot see BarcodeReader anymore. We added a reference to ZXing.Windows.Compatibility, however, our application is running in linux so it's making a complaint that there is only support for windows when using bitmap, can you give some advice to resolve this issue or may be you can give me an example of implementation in an scenario like this one?

best regards, 

Hector Castro.

**Comment by micjahn** [comment]
The nuget package System.Drawing.Common which is used by ZXing.Net.Bindings.Windows.Compatibility only targets windows platforms. There is more information here: https://aka.ms/systemdrawingnonwindows

I don't have a Linux environment myself but I think you have the following options:
* use another ZXing binding package that (possibly) supports Linux like SkiaSharp or ImageSharp.
* use the package ZXing.Net.Bindings.Android
I didn't try it out.
Perhaps there are other options which I don't know.

**Comment by hectorccmx** [comment]
Hello micjahn, 

Thank you for your advice, I've just made use of ImageSharp and it works like a charm. I can tell you that it works as expected on linux.

best regards, 

Hector Castro
