### ISSUE TITLE
Zxing.net generate qr code xamarin.android null reference

### ISSUE THREAD

**Issue by youssefyaza** [micjahn/ZXing.Net#394]
### Discussed in https://github.com/micjahn/ZXing.Net/discussions/393

<div type='discussions-op-text'>

<sup>Originally posted by **youssefyaza** January 18, 2022</sup>
I have a problem generating qr code. I used a sample from site: 
https://www.c-sharpcorner.com/article/generate-barcode-and-qr-code-in-xamarin-android/

I have used the exact same code as in the example but I got a null reference error at this line:
`bitmapMatrix = new MultiFormatWriter().encode(message, BarcodeFormat.QR_CODE, size, size);`

The problem only occurs BarcodeFormat.QR_CODE the others work well. 

In my project I have installed the next packages (the newest versions):
- Zxing.net
- Xamarin.AndroidX.AppCompat
- Xamarin.Essentials
- Xamarin.Google.Android.Material

The null reference exception comes from the writer.encode message (please see my debug info):
![zxingwriter](https://user-images.githubusercontent.com/22446075/149917285-b8fe3877-edc6-4ffa-8c7f-b1e728cc6153.PNG)

Does anyone experienced this problem?

</div>

**Comment by micjahn** [comment]
Thanks for reporting. It's a bug inside the static initialization routines which occurs if some encodings (character sets) are missing.

**Comment by youssefyaza** [comment]
Hi John I'm glad you found the problem. Let me know if you have updated the Nuget package.
