### ISSUE TITLE
Problem barcodewriter on unity-IOS

### ISSUE THREAD

**Issue by Amberas** [micjahn/ZXing.Net#399]
I'm using the zxing.unity.dll and want to use its barcodewriter function to generate a QRcode encoding an url with the id of a  screenshot I made and fetched to a database. This process works fine in the editor, but after building it for IOS, the QRcode doesn't get generated. I searched for the same type of issues, but I can't seem to find any having trouble with the barcodewriter for unity IOS.

**Comment by micjahn** [comment]
Is there any exception or other error message? I don't have an iOS dev environment. I can't reproduce it.

**Comment by Amberas** [comment]
I think I got a clue into solving the problem, I see now that I might have run into a problem with another plugin, thank you for helping me!

**Comment by Amberas** [comment]
Oke nevermind this is the error I get in the IOS dev environment:
<img width="1060" alt="Screenshot 2022-01-30 at 18 26 16" src="https://user-images.githubusercontent.com/72079687/151710248-ce6c200f-9653-44df-9c20-55aca6656030.png">

**Comment by micjahn** [comment]
I should be the same problem as this one #394.
I'm working on a new version with a fix for that.

**Comment by Amberas** [comment]
Oke let me know when the fix is ready, thanks for helping me out.

**Comment by micjahn** [comment]
version 0.16.8 is released
