### ISSUE TITLE
Update Nuget Package

### ISSUE THREAD

**Issue by ArgTang** [micjahn/ZXing.Net#4]
Nuget Package is v 0.14.0.1 from 2014. Last commit was in december 2016, is there any reason it cant be updated?

**Comment by micjahn** [comment]
Freetime. I need more of them. But I'm working on it. Hopefully, the update will come soon.

**Comment by micjahn** [comment]
Done. ;)

**Comment by ArgTang** [comment]
Thank you 👍

**Comment by h82258652** [comment]
Thanks a lot. Any plan with .net core?

**Comment by micjahn** [comment]
In the current NuGet package are binaries for .Net Standard 1.6 target included.
They should work with .Net Core.
