### ISSUE TITLE
Camera zoom?

### ISSUE THREAD

**Issue by baneageorge** [micjahn/ZXing.Net#404]
Hi,

Thank you so much for this amazing library. So easy to use.

We run into a problem scanning code128 barcode, which I hope we can find a solution for it.
We successfully can scan a barcode 2.5cm wide and we are trying to scan the same barcode that is only 1.6cm wide.
Xiaomi phone comes with a barcode, which seems to still be able to scan the 1.6cm wide code and what I noticed is that the camera seems to be a little zoomed (maybe that helps with detection).
Is there any option to do that?
Also, I am thinking is there also an option to limit the scan area, maybe that will improve the performance as well.

Best regards,
George

**Comment by micjahn** [comment]
Do you really use ZXing.Net? I think you are using ZXing.Net.Mobile: https://github.com/Redth/ZXing.Net.Mobile
The bare ZXing.Net library doesn't have any option to control the zoom or limit the scan area.

**Comment by baneageorge** [comment]
Ups, you are right! not sure how this happened.
