### ISSUE TITLE
Support ImageSharp 2.0

### ISSUE THREAD

**Issue by jamesgurung** [micjahn/ZXing.Net#405]
In the latest major release of ImageSharp, there are some [breaking API changes](https://github.com/SixLabors/ImageSharp/issues/1739) (for example, `GetPixelRowSpan` has been removed). This causes compatibility issues if a project uses ImageSharp 2 alongside `ZXing.Net.Bindings.ImageSharp`.

Minimal repro:

**Project.csproj**
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="2.0.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.8" />
    <PackageReference Include="ZXing.Net.Bindings.ImageSharp" Version="0.16.12" />
  </ItemGroup>
</Project>
```

**Program.cs**
```c#
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using ZXing.ImageSharp;

using var image = new Image<Rgba32>(10, 10);
var reader = new BarcodeReader<Rgba32>();
var result = reader.Decode(image); // System.MissingMethodException
Console.WriteLine(result is null);
```

**Expected**
> True

**Actual**
>**System.MissingMethodException:** 'Method not found: 'System.Span\`1<SixLabors.ImageSharp.PixelFormats.Rgba32> SixLabors.ImageSharp.Image\`1.GetPixelRowSpan(Int32)'.'
>    at ZXing.ImageSharp.ImageSharpLuminanceSource\`1..ctor(Image\`1 bitmap)
>   at ZXing.ImageSharp.BarcodeReader\`1.<>c.<.cctor>b__4_0(Image\`1 bitmap)
>   at ZXing.BarcodeReader\`1.Decode(T barcodeBitmap)

**Comment by micjahn** [comment]
Please try the new package for ImageSharp 2.0:
https://www.nuget.org/packages/ZXing.Net.Bindings.ImageSharp.V2/
(should be available in a few minutes)

**Comment by jamesgurung** [comment]
Thank you, all working now.
