### ISSUE TITLE
Demo Client - DataMatrix codes?

### ISSUE THREAD

**Issue by towe96** [micjahn/ZXing.Net#409]
Hi!
I'm looking for a simple Windows command line tool I supply and image to and get a readout back from for images of DataMatrix codes.
I think the "CommandLineDecoder" Demo Client would be perfect, but apparently it only supports barcodes.
From what I've read, zxing should be capable of also reading Data Matrix codes.
Is it possible to read those with a similarly simple client?

**Comment by micjahn** [comment]
Why do you think that the CommandLineDecoder only supports barcodes? I can't remember any restrictions on the type of code.
Do you have a sample image? Did you try it with the WindowsForms demo client?
