### ISSUE TITLE
EAN / UPC encoding

### ISSUE THREAD

**Issue by Trawacho** [micjahn/ZXing.Net#412]
Hi,
using the "WindowsFormsDemo" and trying to create an EAN13 or UPC-A image with the "AlternateBitmapRenderer" are not working. ErrorMessage: "Bitmap dimension too small for text. Reduce fontsize or enlarge bitmap."
Thought the AlternateBitmapRenderer is the correct one, exactly for this kind of barcode.

Any workaround?

**Comment by micjahn** [comment]
In the options dialog set other values for "Width" and "Height".
For example, you can try a height of 100 and a width of 300.
