### ISSUE TITLE
CommandLineEncoder options or using the dll directly in VBA

### ISSUE THREAD

**Issue by BobTB** [micjahn/ZXing.Net#42]
I have a simple VBA app, where I can use the command line to get an QR code image. Everything works great, I just need more options for the commandLineEncoder. I am missing options for ErrorCorrection, ECI, symbolversion etc... , I do not have VisualStudio to fix it myself.

On the other hand, I would use the new ZXing.Net with VBA (COM Interop) but can not do it because I will need to register it on every users computer. 

I am already using freeimage.dll which I can simply load with using

` Private Declare Function LoadLibrary Lib "kernel32" Alias "LoadLibraryA" (ByVal lpLibFileName As String) As Long`

and loading it by
```
Function FreeImgLoad(ByVal dllFilename As String) As Boolean

    If FreeDLLhm = 0 Then
        ' attempt to load the module
        FreeDLLhm = LoadLibrary(dllFilename)

        If FreeDLLhm > 0 Then
            FreeImgLoad = True
        End If
    End If
End Function
```

and then using its functions by

```
Public Declare Function FreeImage_HasPixelsInt Lib "FreeImage.dll" Alias "_FreeImage_HasPixels@4" ( _
                                               ByVal Bitmap As Long) As Long
```

Is it possible to use the dll for zxing in the same way? Or am I barking up the wrong tree? :)

**Comment by micjahn** [comment]
The .Net Assemblies at all doesn't export any functions which can be called with LoadLibrary/GetProcAdress or as externally declared function. As far as I know the freeimage.dll isn't a .Net asssembly.
Perhaps you will find some other solutions to call a .Net Assembly from VBA if you look at stackoverflow.com. Here is one example
https://stackoverflow.com/questions/37074533/how-to-call-net-methods-from-excel-vba
I only know the COM Interop way but the registration of the assembly is required.

On the other hand there are no plans to extend the options of the CommandLineEncoder. Feel free to provide a pull request which adds the functionality.

**Comment by BobTB** [comment]
After a few hours with visualstudio (never ever used it before) I came out with this

`var barcodeWriter = new BarcodeWriter
                                {
                                   Format = barcodeFormat,
                                   Options = new ZXing.QrCode.QrCodeEncodingOptions
                                                {
                                       CharacterSet = "ISO-8859-1",
                                       Width = 600,
                                        Height = 600,
                                        ErrorCorrection = x,
                                        QrVersion = 15
                                                }
                                };`
Which works, now what I need to do is set ECI value to 000004.  Does setting the charset change the ECI by itself?

**Comment by micjahn** [comment]
ECI is only set if the selected character set differs from the default. The default is "ISO-8859-1". That means, no ECI is needed.
Byte Mode is selected automatically. You can't set it via options. It depends on the content. If you only encode numbers then numeric mode is selected. If you encode alphanumeric characters (table 5 of JISX0510:2004 (p.19)) then alphanumeric mode is used. Otherwise byte mode.

**Comment by BobTB** [comment]
Thank you for explaining, so if I set it to ISO-8859-2 then ECI will be set to 000004 and I am good to go. Great.

**Comment by BobTB** [comment]
One more question, do you perhaps know if there is some utility  to display all this data from the QR code, i mean, ECI, Version, mask, encoding type, length etc...

**Comment by micjahn** [comment]
Yes, ECI 4 is added. And no, sorry, don't any tool which fits your needs.
