### ISSUE TITLE
Cannot run simplest example with nuget package in .NET 6 command line app

### ISSUE THREAD

**Issue by jonaumann** [micjahn/ZXing.Net#424]
Using nuget Package on Windows 10 .Net 6
The example from the readme is not compiling:

````C#
using System.Drawing;
using ZXing;
using ZXing.Common;

var reader = new BarcodeReader(); // not compiling
// load a bitmap
var barcodeBitmap = new Bitmap("C:\\sample-barcode-image.png");
// detect and decode the barcode inside the bitmap
var result = reader.Decode(barcodeBitmap);
// do something with the result
if (result != null)
{
  Console.WriteLine(result.BarcodeFormat.ToString());
  Console.WriteLine(result.Text);
}
````
There is no BarcodeReader() constructor.
Only BarcodeReader\<T\>(Func<T, LuminarSource> createLuminarSource)

Am I doing something wrong?

EDIT: I cloned the ZXing.NET repo and build for .NET 3.5 and used this zxing.dll. Then it worked. There seems to be something wong with the nuget package for .NET 6?

**Comment by micjahn** [comment]
As written above the sample, the code snippet works with .Net 2.0/3.5/4.x (out of the box).
There is nothing wrong with the nuget package and .Net 6.0.
.Net 6.0 doesn't contain a System.Drawing namespace with a Bitmap class implementation by default.
You have to add a specific ZXing.Net.Bindings package to your project:
https://www.nuget.org/packages?q=ZXing.Net.Bindings
You can try this one:
https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/
That package contains the missing BarcodeReader class:
ZXing.Windows.Compatibility.BarcodeReader 
The package uses the [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/) dependency.
