### ISSUE TITLE
ZXing.net with EmguCV

### ISSUE THREAD

**Issue by jonaumann** [micjahn/ZXing.Net#425]
I installed nuget package ZXing.net, ZXing runtime and Zxing.net bindings for Emgu.
Running this code
````C#
var reader = new MultiFormatReader();
var image = new Image<Bgr, byte>("/tmp/barcodes2/1.jpg");
BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(new ImageLuminanceSource(image)));
````

I get this error:;
![image](https://user-images.githubusercontent.com/24921722/171809708-a9a7431d-f551-45dd-8450-feceefa656dc.png)

**Comment by jonaumann** [comment]
ok, found the bug in the bindings source code. For some reason at the end of each line (=image width) in the emgu Image data has 9 bytes with value 0. Changing the constructor for ImageLuminanceSource like this makes it work:
````C#
public ImageLuminanceSource(Image<Emgu.CV.Structure.Bgr, byte> image)
       : base(image.Size.Width, image.Size.Height)
    {
      var bytes = image.Bytes;
      var counter = 0;
      for (int x = 0; x < bytes.Length; x += 3)
      {
        var b = bytes[x];
        var g = bytes[x + 1];
        var r = bytes[x + 2];
        luminances[counter] = (byte)((r + g + g + b) >> 2);

        counter++;
        if (counter % image.Width == 0) { x += 9; }
      }
      
    }
````

**Comment by jonaumann** [comment]
sure, here are same images with different "paddings".

![2](https://user-images.githubusercontent.com/24921722/173036768-bcfe2118-b009-47da-a466-8db805a0acf5.jpg)
![3](https://user-images.githubusercontent.com/24921722/173036770-411dd493-066c-47ac-ab6f-749bebbbea85.jpg)
![4](https://user-images.githubusercontent.com/24921722/173036773-42f97518-48e3-4e4e-86b9-6cc95abebb63.jpg)
![5](https://user-images.githubusercontent.com/24921722/173036774-c3b26ba9-3df6-4f8b-a7ab-8f231f21e2af.jpg)
![6](https://user-images.githubusercontent.com/24921722/173036776-dbc99571-6eeb-424d-b366-c78cf9097f73.jpg)

![7](https://user-images.githubusercontent.com/24921722/173036760-9e8f09ab-fe7f-4698-9f60-144f44f7c899.jpg)
![1](https://user-images.githubusercontent.com/24921722/173036765-93204895-4e73-400c-ad61-ce08b903e8c4.jpg)

**Comment by micjahn** [comment]
The length of a line in the byte array is longer than the width of the image (line padding).
Here is a fix for that. I committed it to the repository. Not sure, when I will find the time to build a new nuget package. Hopefully soon.
```
        public ImageLuminanceSource(Image<Emgu.CV.Structure.Bgr, byte> image)
           : base(image.Size.Width, image.Size.Height)
        {
            var bytes = image.Bytes;
            var width = image.Width;
            var lineLength = image.MIplImage.WidthStep;
            var indexL = 0;
            var bLength = bytes.Length;
            for (int indexB = 0; indexB < bLength; indexB += 3)
            {
                var b = bytes[indexB];
                var g = bytes[indexB + 1];
                var r = bytes[indexB + 2];
                // Calculate luminance cheaply, favoring green.
                luminances[indexL++] = (byte)((r + g + g + b) >> 2);
                if (indexL % width == 0)
                {
                    indexB += lineLength - (indexB % lineLength) - 3;
                }
            }
        }
```

**Comment by micjahn** [comment]
Push version 0.16.3 of ZXing.Net.Bindings.EmguCV
