### ISSUE TITLE
Setting the CharacterSet for decoding PDF417 in VBA has no effect？

### ISSUE THREAD

**Issue by guyuantian** [micjahn/ZXing.Net#428]
I use "ZXing.Net" to decode PDF417 barcode in VBA, here's my VBA code:
```
Sub test()
    Dim x As New BarcodeReader
    x.Options.PossibleFormats.Add BarcodeFormat_PDF_417
    x.Options.CharacterSet = "GBK"
    MsgBox x.DecodeImageFile("D:\Desktop\test.png").Text
End Sub
```
![image](https://user-images.githubusercontent.com/105156880/173288421-869d23d5-f7ab-457e-b650-676d5517cbe2.png)
The result is garbled.

This is the PDF417 barcode:
![test](https://user-images.githubusercontent.com/105156880/173288075-96006241-81bc-446c-8723-c725282cbb23.png)

The PDF417 barcode was generated by other software, the correct content is:
```
GB0626-2005^1234567890^abcdefghijklmn^^^^使用在需要位置出现的新按钮在 Word 中保存时间。若要更改图片适应文档的方式，请单击该图片，图片旁边将会显示布局选项按钮。当处理表格时，单击要添加行或列的位置，然后单击加号。^无^无^20220613^^^20220613^^|
```
I use the mobile browser(HUAWEI Browser) to scan the code, it can get the correct result.
![image](https://user-images.githubusercontent.com/105156880/173289915-25a31e26-f5d1-4923-887f-74401aef1330.png)

I try to set "Options.CharacterSet" to GBK/GB2312/UTF-8/ISO-8859-1,
but no matter how I set it up, the results are the same...

How to fix garbled characters?

**Comment by micjahn** [comment]
Please try the following
```
Sub test()
    Dim x As New BarcodeReader
    Dim myOptions As New DecodingOptions
    myOptions.PossibleFormats.Add BarcodeFormat_PDF_417
    myOptions.CharacterSet = "GBK"
    Set x.Options = myOptions
    MsgBox x.DecodeImageFile("D:\Desktop\test.png").Text
End Sub
```

**Comment by guyuantian** [comment]
> Please try the following
> 
> ```
> Sub test()
>     Dim x As New BarcodeReader
>     Dim myOptions As New DecodingOptions
>     myOptions.PossibleFormats.Add BarcodeFormat_PDF_417
>     myOptions.CharacterSet = "GBK"
>     Set x.Options = myOptions
>     MsgBox x.DecodeImageFile("D:\Desktop\test.png").Text
> End Sub
> ```

I tried this code, the results are the same... T_T
![image](https://user-images.githubusercontent.com/105156880/174676612-2e31b5e2-6ff2-4cd8-a81f-f50905c6ddaa.png)

**Comment by guyuantian** [comment]
@micjahn Is there a solution to this problem?

**Comment by micjahn** [comment]
Please try the following:

[zxing.interop_20220628-428.zip](https://github.com/micjahn/ZXing.Net/files/9004941/zxing.interop_20220628-428.zip)
(includes the changes from the other issue, too)
```
Sub test()
    Dim x As New BarcodeReader
    x.Options.PossibleFormats.Add BarcodeFormat_PDF_417
    x.Options.CharacterSet = "GBK"
    MsgBox x.DecodeImageFile("D:\Desktop\test.png").Text
End Sub
```

**Comment by guyuantian** [comment]
> Please try the following:
> 
> [zxing.interop_20220628-428.zip](https://github.com/micjahn/ZXing.Net/files/9004941/zxing.interop_20220628-428.zip) (includes the changes from the other issue, too)
> 
> ```
> Sub test()
>     Dim x As New BarcodeReader
>     x.Options.PossibleFormats.Add BarcodeFormat_PDF_417
>     x.Options.CharacterSet = "GBK"
>     MsgBox x.DecodeImageFile("D:\Desktop\test.png").Text
> End Sub
> ```

This version is perfect and solved all my problems! ^_^
