### ISSUE TITLE
Generic type parameter required

### ISSUE THREAD

**Issue by MarvinKlein1508** [micjahn/ZXing.Net#437]
We have updated the library from v 14.x to the latest v16.10.

Now our code doesn't compile anymore.

```
ZXing.BarcodeWriter writer = new ZXing.BarcodeWriter()
{
    Format = ZXing.BarcodeFormat.DATA_MATRIX
};
```

We rely on getting back a bitmap from writer.Write();

Could you tell us what we'll need to change for this? 

Would be nice if you can add examples for creating barcodes to the README as well.

**Comment by micjahn** [comment]
I assume that you are using .Net Core or .Net 5.0/6.0.
In that case the base package ZXing.Net doesn't include a BarcodeWriter implementation for a specific bitmap implementation.
Only the old classic .Net framework 4.x includes the Bitmap classes by default.

In your case you have to select one of the binding packages: https://www.nuget.org/packages?q=Zxing.Net.Binding
Perhaps this specific one should fit your needs:
https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility
(ZXing.Windows.Compatibility.BarcodeWriter)
