### ISSUE TITLE
The type or namespace name 'Android' does not exist in the namespace 'ZXing' 

### ISSUE THREAD

**Issue by subsembly** [micjahn/ZXing.Net#440]
After updating from ZXing.Net 0.16.6 to ZXing.NET 0.16.8 with package ZXing.Net.Android.Bindings 0.16.7 the following code no longer compiles:

var aBarcodeWriter = new ZXing.Android.BarcodeWriter();

even a

using ZXing.Android;

leads to the error CS0234: The type or namespace name 'Android' does not exist in the namespace 'ZXing' 

Downgrading to ZXing.Net 0.16.6 and ZXing.Net.Android.Bindings 0.16.6 makes it compile again.

Any idea what can be wrong?

**Comment by micjahn** [comment]
Thanks for reporting this issue.
Please update to the newest version 0.16.8 of the ZXing.Net.Bindings.Android package.
