### ISSUE TITLE
ZXing.Net not compatible with Magick.Net >= 12.0.0

### ISSUE THREAD

**Issue by andreadistefano** [micjahn/ZXing.Net#441]
Hi!
First of all, thank you for this library, it's immensely useful to me.

As reported [here](https://github.com/dlemstra/Magick.NET/issues/1176), Magick.Net 12.0.0 split the `BitDepth` method into 2 methods:
- `DetermineBitDepth`
- `SetBitDepth`

This breaks the `CalculateLuminance` method in [MagickImageLuminanceSource.cs](https://github.com/micjahn/ZXing.Net/blob/89074c140f6d55f3ff4587df34e0d8bf03ad6c83/Source/Bindings/ZXing.Magick/MagickImageLuminanceSource.cs#L65).

I should be able to cook up a PR just for this issue, but I'm afraid that there are other issues with the new major release of Magick.Net.

Do you have any plan to support the new release soon? Should we stick with version 11.3.0 for now?

Thanks again!

**Comment by micjahn** [comment]
Thanks for reporting.
I pushed version 0.16.12 of the package ZXing.Net.Binding.Magick to nuget.org which is built against 12.1.0 of Magick.Net.Core

**Comment by andreadistefano** [comment]
Thank you so much!
