### ISSUE TITLE
0.16.5 升级到ZXing.Net 0.16.8使用泛型类型“BarcodeReader”需要1个类型参数

### ISSUE THREAD

**Issue by ghd258** [micjahn/ZXing.Net#443]
ZXing.Net 0.16.8使用泛型类型“BarcodeReader”需要1个类型参数
![微信图片_20220912101819](https://user-images.githubusercontent.com/4811375/189562615-ae6f4c24-5f58-40a8-b16b-e05ae21ff463.png)

**Comment by ghd258** [comment]
错误	CS1503	参数 1: 无法从“Android.Graphics.Bitmap”转换为“System.DrawingCore.Bitmap”

**Comment by ghd258** [comment]
已解决

**Comment by neiloe8023** [comment]
> 已解决

请问怎么解决的啊

**Comment by ghd258** [comment]
ZXing.Net.Bindings.Android 加这个包就好了
