### ISSUE TITLE
How to read a DataMatrix barcode using ZXing.Net on .NET 6?

### ISSUE THREAD

**Issue by trustieee** [micjahn/ZXing.Net#445]
I'm trying to find examples of ZXing.Net barcode reading for .NET 6 and I haven't been lucky so far.
I have an image loaded from `System.Drawing.Image.FromFile("path/to/image");` and am trying to construct a `DataMatrixReader` or a `BarcodeReader`, but haven't had luck so far because I'm not sure of the correct LuminanceSource usage.

```cs
var image = System.Drawing.Image.FromFile(bmp);

LuminanceSource source = image.PixelFormat switch
{
    PixelFormat.Format1bppIndexed => new RGBLuminanceSource(ToByteArray(image), image.Width, image.Height, RGBLuminanceSource.BitmapFormat.ARGB32),
    PixelFormat.Format32bppArgb => new RGBLuminanceSource(ToByteArray(image), image.Width, image.Height, RGBLuminanceSource.BitmapFormat.RGB24),
    PixelFormat.Format24bppRgb => new RGBLuminanceSource(ToByteArray(image), image.Width, image.Height, RGBLuminanceSource.BitmapFormat.RGB32),
    _ => new RGBLuminanceSource(ToByteArray(image), image.Width, image.Height)
};

var binarizer = new HybridBinarizer(source);
var binBitmap = new BinaryBitmap(binarizer);

var reader = new DataMatrixReader();
var result = reader.decode(binBitmap);
return result == null ? string.Empty : result.Text;
```

My `PixelFormat` is always `PixelFormat.Format1bppIndexed`, so I guessed to use `RGBLuminanceSource.BitmapFormat.ARGB32`, not sure though.

The current exception I get is:
> System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'

which happens on this line
```cs
 new RGBLuminanceSource(ToByteArray(image), image.Width, image.Height, RGBLuminanceSource.BitmapFormat.ARGB32)
```

My `ToByteArray` is simply
```cs
private static byte[] ToByteArray(System.Drawing.Image image)
{
    using (var ms = new MemoryStream())
    {
        image.Save(ms, image.RawFormat);
        return ms.ToArray();
    }
}
```

**Comment by micjahn** [comment]
Add the nuget packges ZXing.Net and https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility to your project.
```
var image = System.Drawing.Image.FromFile(bmp);
var reader = new ZXing.Windows.Compatibility.BarcodeReader();
var result = reader.Decode(binBitmap);
return result == null ? string.Empty : result.Text;
```

**Comment by trustieee** [comment]
> Add the nuget packges ZXing.Net and https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility to your project.
> 
> ```
> var image = System.Drawing.Image.FromFile(bmp);
> var reader = new ZXing.Windows.Compatibility.BarcodeReader();
> var result = reader.Decode(binBitmap);
> return result == null ? string.Empty : result.Text;
> ```

Yeah without all the Luminance logic I can use your code to get past the exception. It does not detect the barcode on the image (`result` is `null`), but a couple of other libraries do detect it. I'm trying to figure out what sort of modifications I can make to the image to get it to scan the barcode. But thank you for that snippet at least, it did get past the exception.

**Comment by micjahn** [comment]
Can you add the image file here?

**Comment by trustieee** [comment]
> Can you add the image file here?
 
I can't attach a bmp file to github, so here's a jpg of the same file I used. I tested with the jpg and the result is the same. Lots of redacted info.

![1](https://user-images.githubusercontent.com/1885172/190412598-786cad47-f481-4052-866c-a525e34ce16d.jpg)

**Comment by micjahn** [comment]
Your image triggers two problems of zxing in general (which means, the java version has the same restriction):
Datamatrix codes can only be scanned if there are located in the center of the picture. That's a limitation of the datamatrix finder.
And zxing doesn't work very well with black-and-white images. It's better to scan them as grayscale.
Sorry, I can't really help here. Perhaps you have to use another library which works better in your cases.

**Comment by piotrszpruta** [comment]
Hey, @trustieee did you find anything which works better for barcodes anywhere in file? I have smiliar problem where ZXing can't find barcode which isn't centered.

**Comment by trustieee** [comment]
> Hey, @trustieee did you find anything which works better for barcodes anywhere in file? I have smiliar problem where ZXing can't find barcode which isn't centered.

Nope, I haven't found one yet.
