### ISSUE TITLE
how fix to erorr in DecodeMulti

### ISSUE THREAD

**Issue by AbdalaMask** [micjahn/ZXing.Net#446]
![image](https://user-images.githubusercontent.com/37013638/190841960-30ab91d4-2377-4d73-a6cb-edf132d0980a.png)
 if (openFileDialog1.ShowDialog() == DialogResult.OK)
            {
                using var obj = new QRCodeDetector();

                using var withQr = new Mat(openFileDialog1.FileName, ImreadModes.Color);

                bool detected = obj.DetectMulti(withQr, out var points);
                bool decoded = obj.DecodeMulti(withQr, points, out var decodedStrings, out var straightQrCode);
                List<List<Point>> listOfListOfPoint2D = new List<List<Point>>();
                List<Point> listOfPoint2D = new List<Point>();

                int m = 0;

                for (int x = 0; x < straightQrCode.Length; x++)
                {
                     
                    for (int i = 0; i <= 3; i++)
                    {
                        listOfPoint2D.Add(new Point(points[m].X, points[m].Y));
                        m++;
                    }
                    listOfListOfPoint2D.Add(listOfPoint2D);
                   
                }

                if (straightQrCode.Length > 0)
                {

                    

                    openFileTextBox.Invoke(new MethodInvoker(delegate ()
                    {
                        openFileTextBox.Text = decodedStrings[0];
                    }));
                    var s = new Scalar(255, 0, 0);

                    withQr.Polylines(  listOfListOfPoint2D, true, s, 3);

                    var bs = OpenCvSharp.Extensions.BitmapConverter.ToBitmap(withQr);
                    openFileBox.Image = bs;
                }

            }
![qr_multi](https://user-images.githubusercontent.com/37013638/190841978-4ca3742b-2a54-45e1-a744-1127b32beea0.png)

**Comment by micjahn** [comment]
Please describe the problem in detail. I tried to decode the QR codes with the Windows Forms Demo client application and it works like a charm.
![grafik](https://user-images.githubusercontent.com/3475026/191343593-1e89a926-3d46-4fe6-8ddb-6442917c9ed4.png)

**Comment by AbdalaMask** [comment]
Can I have a link to the app in the picture?

**Comment by AbdalaMask** [comment]
Maybe the code used in the picture?

**Comment by micjahn** [comment]
The app is available in the source code repository of this project here:
https://github.com/micjahn/ZXing.Net/tree/master/Clients/WindowsFormsDemo

**Comment by AbdalaMask** [comment]
ok good working
