### ISSUE TITLE
Unable to scan QRCodes

### ISSUE THREAD

**Issue by dimeom** [micjahn/ZXing.Net#447]
Hi there.

I have been trying to scan a qrcode on xamarin forms for ios but it has not worked yet :(

I am using Microsoft Visual Studio 2022, Xamarin.iOS and Xamarin.Mac SDK   15.12.0.2 and ZXing.Net 0.16.8.

This is how I am trying:

                var lOptions = new ZXing.Mobile.MobileBarcodeScanningOptions();
                lOptions.PossibleFormats = new List<ZXing.BarcodeFormat>() {
                    ZXing.BarcodeFormat.QR_CODE
                    };
                lOptions.TryHarder = true;
                lOptions.CharacterSet = "utf-8";

                lOptions.AutoRotate = true;
                lOptions.TryInverted = true;
                lOptions.UseNativeScanning = true;

                var lScanner = new ZXing.Mobile.MobileBarcodeScanner();
                await Task.Delay(500);
                var lResult = await lScanner.Scan();

and I initialize Zxing on the FinishLaunching().. in the AppDelegate.cs from the iOS project  like this -> ZXing.Net.Mobile.Forms.iOS.Platform.Init();

I have also added the camera permissions to the info.plist 
    <key>NSCameraUsageDescription</key>
	<string>Please allow access to the camera to scan QR codes.</string>

what am I doing wrong? 

I have also tried the ZXing.Mobile.Net and ZXing.Mobile.Forms but it has not worked :(
Could you please help me out?

Thanks in advance,

Antonio

**Comment by micjahn** [comment]
You are using the separate library ZXing.Net.Mobile on top of ZXing.Net.
Please open a new issue here:
https://github.com/Redth/ZXing.Net.Mobile
