### ISSUE TITLE
Can not use interop zxing after registering

### ISSUE THREAD

**Issue by BobTB** [micjahn/ZXing.Net#45]
I followed instructions, copied both zxing.dll and zxing.interop.dll to c:\windows and from there with admin rights run register.cmd
It registered, but now in VBA Access, I can not add a reference. It is not listed, and if clicking on browse, and selecting the dll , I get the error - "Can't add a reference to the specified file."

How can I add this to work?

**Comment by micjahn** [comment]
Did you try a restart of Access and/or the whole computer?

**Comment by BobTB** [comment]
Yes I did. It did not help.

**Comment by micjahn** [comment]
which version of access do you use?

if it works it should like the following screenshot:
![grafik](https://user-images.githubusercontent.com/3475026/31353642-914f1356-ad33-11e7-80ec-df510b808f6b.png)

**Comment by BobTB** [comment]
I had to install VisualStudio2017, run it as administrator, and build zxing.interop. After this it is visible in VBA. 
Now the question is, how can this be done without installing visual studio and building it on every computer. The register.com if run from c:\Windows dir does not work (run as Administrator) It is registered successfully but not visible in VBA. I really don't know what is wrong. I checked the registry and it seems to be ok. What is the difference when running it with regasm vs building it from Visual Studio? A am on Windows 10 PRO 64 bit and am using a 32 bit office, so there should not be a problem.

I found this, http://edndoc.esri.com/arcobjects/9.2/NET/9826f81b-278c-49cc-a912-ab8d86f5e91e.htm
and it seems an installer has to be made for it to work. Any ideas?

**Comment by BobTB** [comment]
I checked the registry and when run as described above it looks like this:

![image](https://user-images.githubusercontent.com/15887688/31376888-a0ae5154-ada6-11e7-8911-9e3a377945e2.png)

I will try to put the dll somewhere else, not in c:\windows and see if it registers successfully (well it does register no matter what, but does not show up in the VBA)

**Comment by BobTB** [comment]
I also noticed that building in VS there is the tlb file created. Can this be the problem? Should I use regasm /tlb ?

**Comment by BobTB** [comment]
It seem tlb is needed:
https://www.red-gate.com/simple-talk/dotnet/visual-studio/build-and-deploy-a-.net-com-assembly/

**Comment by micjahn** [comment]
I thought the TLB file would be created because of the /tlb parameter:
"%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\regasm.exe" /codebase %~dp0zxing.interop.dll /tlb %~dp0zxing.interop.tlb

I have to check it again.

**Comment by micjahn** [comment]
It looks to me that there is an issue if the register.cmd is executed on 64bit windows.
Please try it manually with the following command:
`"%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\regasm.exe" /codebase C:\Windows\System32\zxing.interop.dll /tlb C:\Windows\System32\zxing.interop.tlb`
