### ISSUE TITLE
special characters Data Matrix

### ISSUE THREAD

**Issue by kansasdev** [micjahn/ZXing.Net#454]
I am producing DataMatrix barcode as follows:
ZXing.Presentation.BarcodeWriter writer = new ZXing.Presentation.BarcodeWriter
            {
                Format = ZXing.BarcodeFormat.DATA_MATRIX,
                }
var content = System.Text.Encoding.GetEncoding("ISO-8859-1").GetString(hex);
            WriteableBitmap image = writer.Write(content);
My hex is byte array which contains unfortunately non ascii characters, since it is c40 encoding.
I have found that all characters which are special characters like here https://cs.stanford.edu/people/miles/iso8859.html
(A0 A1 ... AF B0 B1 .. BF) are produced incorrectly.
When I read raw bytes back from produced barcode instead for example b8 there is 3f, for a6 there is 7c etc.
Are there any ideas - can I use in input string for special characters some indicator of special character?

**Comment by micjahn** [comment]
I made two round-trip tests with an array of byte values from 0 to 255.
The tests are green. Perhaps I made something wrong, not sure.
Can you provide a dump of your data?

```
        [Test]
        public void TestEncodeDecodeISO88591AllChars()
        {
            var writer = new DataMatrixWriter();
            var options = new DatamatrixEncodingOptions();
            var data = new byte[256];
            for (var i = 0; i < 256; i++)
            {
                data[i] = (byte)i;
            }
            var strData = System.Text.Encoding.GetEncoding("ISO8859-1").GetString(data);
            var matrix = writer.encode(strData, BarcodeFormat.DATA_MATRIX, 0, 0, options.Hints);

            Assert.That(matrix, Is.Not.Null);

            var res = new Internal.Decoder().decode(matrix);

            Assert.That(res, Is.Not.Null);
            Assert.That(res.Text, Is.EqualTo(strData));

            var resData = System.Text.Encoding.GetEncoding("ISO8859-1").GetBytes(res.Text);
            for (var i = 0; i < 256; i++)
            {
                Assert.That(resData[i], Is.EqualTo(data[i]), i.ToString());
            }
        }

        [Test]
        public void TestEncodeDecodeISO88591AllCharsBitmap()
        {
            var writer = new BarcodeWriter
            {
                Format = BarcodeFormat.DATA_MATRIX
            };
            var options = new DatamatrixEncodingOptions();
            var data = new byte[256];
            for (var i = 0; i < 256; i++)
            {
                data[i] = (byte)i;
            }
            var strData = System.Text.Encoding.GetEncoding("ISO8859-1").GetString(data);
            var bitmap = writer.Write(strData);

            Assert.That(bitmap, Is.Not.Null);

            var reader = new BarcodeReader
            {
                Options = new DecodingOptions
                {
                    PureBarcode = true
                }
            };

            var res = reader.Decode(bitmap);

            Assert.That(res, Is.Not.Null);
            Assert.That(res.Text, Is.EqualTo(strData));

            var resData = System.Text.Encoding.GetEncoding("ISO8859-1").GetBytes(res.Text);
            for (var i = 0; i < 256; i++)
            {
                Assert.That(resData[i], Is.EqualTo(data[i]), i.ToString());
            }
        }
```

**Comment by kansasdev** [comment]
Thanks for answer adn your input. When I take a look onto your code I have realized that I was doing ISO-8859-15 encoding instead iso-8859-1..I was somehow confused with https://github.com/micjahn/ZXing.Net/issues/315. When I get back to ISO-8859-1 it works as expected. Thank you again
