### ISSUE TITLE
AZTEC and DATA_MATRIX do not honor EncodeHintType.MARGIN

### ISSUE THREAD

**Issue by MikeGratsas** [micjahn/ZXing.Net#457]
Please answer if it is possible to implement margin usage in ZXing.Net source to encode DataMatrix and Aztec Code? There is a known bug in [zxing project](https://github.com/zxing/zxing/issues/26), which was not fixed jet.
[lib.zip](https://github.com/micjahn/ZXing.Net/files/9818973/lib.zip)

**Comment by micjahn** [comment]
Sometimes there are issues that are easy to fix, like this one.
