### ISSUE TITLE
Bad DataMatrix output

### ISSUE THREAD

**Issue by mattkr83** [micjahn/ZXing.Net#46]
I want to create DataMatrix Codes with a fixed length of 15 characters. But there is a formating issue with the following Code using the NuGet v0.16.2:

```
var dmWriter = new ZXing.BarcodeWriter() { Format = ZXing.BarcodeFormat.DATA_MATRIX };
dmWriter.Options.PureBarcode = true;

//Output OK
var t = dmWriter.Write("0000319%0009367%S");
t.Save("tmp_fine.bmp", System.Drawing.Imaging.ImageFormat.Bmp);

//Output NOK
t = dmWriter.Write("000319%009367%S");
t.Save("tmp_bad.bmp", System.Drawing.Imaging.ImageFormat.Bmp);

```

When I use 17 characters, everything is OK. With 15 characters, the barcode is displayed blurred. See the attached pictures.

15 Characters:
![tmp_bad](https://user-images.githubusercontent.com/4363974/31237497-6ee3cb02-a9f7-11e7-9a5b-b55d63346d2b.png)

17 Characters:
![tmp_fine](https://user-images.githubusercontent.com/4363974/31237506-7356fccc-a9f7-11e7-8987-7708bb01b7f9.png)

**Comment by micjahn** [comment]
Workaround:
```
dmWriter.Options = new DatamatrixEncodingOptions {
   PureBarcode = true,
   SymbolShapeHint = SymbolShapeHint.FORCE_SQUARE
};
```

**Comment by mattkr83** [comment]
Thanks, thats it. (Y)
Grate Work.
