### ISSUE TITLE
BarcodeWriter<Bitmap> problems

### ISSUE THREAD

**Issue by dmitryvhf** [micjahn/ZXing.Net#460]
Problems.
1. I tryed found information how to writing barcodes. But found only one page - [Using a custom renderer](https://github.com/micjahn/ZXing.Net/wiki/Using-a-custom-renderer). All pages in this repository with samples to Reading barcode.
Please, add something about Writing too.

2. Information about BarcodeWriter outdated.
Current build have only generic class  - `BarcodeWriter<T>`.
Please, actualize this.

3. InvalidOperationException 
```
BarcodeWriter<Bitmap> writer = new BarcodeWriter<Bitmap>
{
   Format = BarcodeFormat.QR_CODE,
   Options = new EncodingOptions { Height = 500, Width = 500 }
};
var bitmap = writer.Write(content);
```
Write method cause exception

> InvalidOperationException: You have to set a renderer instance.

I found solution for my problem in this Issue #458.
Changed nuget from "ZXing.Net" to "ZXing.Net.Bindings.Windows.Compatibility". But i exception exists.
I fix my writer initialization to:
```
BarcodeWriter<Bitmap> writer = new BarcodeWriter<Bitmap>
{
   Format = BarcodeFormat.QR_CODE,
   Options = new EncodingOptions { Height = 500, Width = 500 },
   Renderer = new BitmapRenderer()
};
var bitmap = writer.Write(content);
```
Problem solved. Strange, because 
`public class BarcodeWriter : BarcodeWriter<System.Drawing.Bitmap>, IBarcodeWriter`
already initialized Renderer inside constructor.
Please 
* check why Renderer is not inited
* update documentation with announce to use Windows.Compatibility for use Bitmap

Question.
What Nuget package i need use for multi OS (Windows and Linux) support?
Main package "ZXing.Net" compatible with Linux? If yes - so i will migrate Bitmap to Svg.

**Comment by micjahn** [comment]
You have to use it this way:
```
var writer = new ZXing.Windows.Compatibility.BarcodeWriter
{
   Format = BarcodeFormat.QR_CODE,
   Options = new EncodingOptions { Height = 500, Width = 500 }
};
var bitmap = writer.Write(content);
```

I didn't test ZXing.Net. But the package contains assemblies for .Net Standard.
So it should be working with linux.
