### ISSUE TITLE
net6.0-android and net6.0-ios

### ISSUE THREAD

**Issue by JimWilcox3** [micjahn/ZXing.Net#468]
Are there any plans to support net6.0-android and net6.0-ios?  The problem I see is that these platforms do not support Xamarin Forms and that seems to be required by the library.

**Comment by micjahn** [comment]
I don't have any experience with Android and iOS. And I'm missing a test system, too.
A common .Net6 version is included in the nuget package. What is missing in detail?

**Comment by JimWilcox3** [comment]
It won't compile is the biggest issue.  Xamarin is going away next year and I was trying to get ahead of it.  It has been working with Xamarin.  It turns out that I was using a nuget called ZXing.Net.Mobile which might not be you.  It does use ZXing.net.  Maybe I need to figure out how they are using your library and try to fix it from there.

**Comment by micjahn** [comment]
That's right, ZXing.Net.Mobile is a different project.
