### ISSUE TITLE
Dependency to System.Drawing

### ISSUE THREAD

**Issue by dariusbuinovskij** [micjahn/ZXing.Net#475]
Any plans to remove dependency to System.Drawing and to use [SkiaSharp](https://github.com/mono/SkiaSharp) for example?

Asking, since System.Drawing is not supported in latest .NET versions and Microsoft suggest to use SkiaSharp.

**Comment by micjahn** [comment]
Not sure, what you mean.
The .Net Standard, .Net 5.0 and .Net 6.0 versions of ZXing.Net doesn't use System.Drawing.
There are special binding packages that contain separate assemblies for different image libraries.
https://www.nuget.org/packages?q=ZXing.Net.Bindings*
It is possible to use SkiaSharp by adding the package
https://www.nuget.org/packages/ZXing.Net.Bindings.SkiaSharp
to your project.

**Comment by dariusbuinovskij** [comment]
Yes, you are right. Somehow without any binding packages I can access classes with System.Drawing. Installing SkiaSharp package resolved my problem.
Thanks.
