### ISSUE TITLE
Will this project support DecodeMultiple of BarcodeReaderGeneric?

### ISSUE THREAD

**Issue by AndriDev** [micjahn/ZXing.Net#476]
subj

**Comment by micjahn** [comment]
What do you mean? BarcodeReaderGeneric supports DecodeMultiple already. What are you missing?

**Comment by AndriDev** [comment]
@micjahn Yes, but I missing some ability to use it via IMobileBarcodeScanner interface.
Maybe some new method of IMobileBarcodeScanner interface, like following
 		Task<Result[]> ScanMultiple(MobileBarcodeScanningOptions options);

Here Result[] is multiple barcodes of scanned by camera

**Comment by AndriDev** [comment]
Sorry, I mean  another project with almost same name - [Redth](https://github.com/Redth)
[ZXing.Net.Mobile](https://github.com/Redth/ZXing.Net.Mobile)
