### ISSUE TITLE
DataMatrix GS1 compliance in question

### ISSUE THREAD

**Issue by d-buchmann** [micjahn/ZXing.Net#478]
According to GS1 specs 5.6.3.3, the only allowed symbology identifier for data matrix codes is `]d2`.
However, every DM Encoder lib I found so far seems to generate their codes with `]d1`.
This also applies to ZXing.Net, regardless of the setting of `EncodingOptions.GS1Format`.
[This link](https://support.honeywellaidc.com/s/article/What-are-the-differences-between-DataMatrix-with-identifier-d1-and-d2) has some detailed info on the difference.

Issue #267 also (kind of) referred to this, although for QR codes. For this code type the `GS1Format` flag changes the symbology identifier from `]q1` to `]q3` which is the expected behaviour.

Am I fundamentally wrong somewhere or is this a thing?
I validate barcodes with the "barValid" app (which says my codes are OK), but I didn't trust it enough, so i built my own decoder based on ZXing which decodes the symbology as `]d1`.

**Comment by d-buchmann** [comment]
Sorry for this, I just found out that you can prepend your payload with ASCII character 29, which produces the right header.
I thought I had tried this before and it didn't work, but I probably tried with (char)232, which won't work (that character will actually land in the payload and the symbol identifier remains unchanged).

Leaving this open in case someone still wants to comment.

**Comment by d-buchmann** [comment]
Maybe the gist of my struggle is that either the docs should mention this behaviour somewhere or the `GS1Format` flag should take care of correctly formatting the symbology identifier. Anyway, this is a non-issue, so closing.

**Comment by Trevor-** [comment]
Is there a possibility of fixing this?

**Comment by d-buchmann** [comment]
After reviewing the code, I interpret the meaning of `GS1Format` flag as follows:
- `DataMatrixWriter.encode()`: The flag hardcodes the "designated" FNC1 character to `0x1D` if set, or -1 if not set.
- `MinimalEncoder.getDataBytes()`: The high level encoder then compares against this value to decide if FNC1 or a plain character should be encoded in the message.

As I said, I don't think it requires a fix, just the correct usage. E.g. I do (simplified):
```
BarcodeWriter writer = new BarcodeWriter
{
    [...],
    Options = new DatamatrixEncodingOptions()
    {
        [...],
        GS1Format = true
    }
};
var barcode = writer.Write("\x1D" + payload);
```
and it works well. You need to set both the `GS1Format` flag and the character(s) that shall be encoded as FNC1 in the message.
I think changing the behavior of the flag *will* eventually break someone's workflow.

**Comment by d-buchmann** [comment]
Just found the [wiki page](https://github.com/micjahn/ZXing.Net/wiki/Generating-GS1-DataMatrix-and-GS1-Code128-barcodes) that states exactly this since 2017. (RTFM, I guess ;)

There's an actual bug in that page, referring to the relevant character as `0x29`, but it's actually decimal 29, or hex `0x1D`.
Didn't check if the same applies to the Code128 special char. Reopening this issue to fix the docs @micjahn. =)

No mention of the `GS1Format` flag whatsoever. Anyway, if I read the code correctly, I'd still say it's required. Probably it was added so that you can encode the actual character `\x1D` in a non GS1-symbol.
