### ISSUE TITLE
Enum.TryParse("ALL_1D", out BarcodeFormat format) fails

### ISSUE THREAD

**Issue by RodBarnes** [micjahn/ZXing.Net#48]
[Searched and didn't see this so adding.]

The statement:

`Enum.TryParse("ALL_1D", out BarcodeFormat format)`

returns false.  It should return true with the format variable filled with the BarcodeFormat.ALL_1D value.  It works correctly with all the other recognized codes.

**Comment by micjahn** [comment]
Please try `Enum.TryParse<BarcodeFormat>("ALL_1D", out BarcodeFormat format);`

**Comment by micjahn** [comment]
It works as expected, but you have to take care of the upper case and lower case.
```
      [Test]
      public void Test_Enum()
      {
         BarcodeFormat format;

         Enum.TryParse("All_1D", out format);
         Assert.That(format, Is.EqualTo(BarcodeFormat.All_1D));

         Enum.TryParse<BarcodeFormat>("All_1D", out format);
         Assert.That(format, Is.EqualTo(BarcodeFormat.All_1D));

         Enum.TryParse("all_1d", true, out format);
         Assert.That(format, Is.EqualTo(BarcodeFormat.All_1D));

         Enum.TryParse("ALL_1D", true, out format);
         Assert.That(format, Is.EqualTo(BarcodeFormat.All_1D));
      }
```

**Comment by RodBarnes** [comment]
Interesting.  Well, both of the following statements take the FAILURE path when I execute them.  I am using ZXing.Net 0.16.2 via NuGet.

`                if (Enum.TryParse<BarcodeFormat>("ALL_1D", out BarcodeFormat test1))
                {
                    // SUCCESS
                    ;
                }
                else
                {
                    // FAILURE
                    ;
                }
                if (Enum.TryParse("ALL_1D", out BarcodeFormat test2))
                {
                    // SUCCESS
                    ;
                }
                else
                {
                    // FAILURE
                    ;
                }
`

**Comment by micjahn** [comment]
It's not a mistake. I choose lower case because it is not a real barcode format.
You can use `Enum.TryParse("ALL_1D", true, out format);` in this case.
