### ISSUE TITLE
It is impossible to specify CharacterSetECI values to encode

### ISSUE THREAD

**Issue by MikeGratsas** [micjahn/ZXing.Net#482]
Testing matrix barcode encoding I found that it is impossible to specify some CharacterSetECI values to encode.

For example, for QR code CharacterSetECI must be indicated using:

```
string encodingName = "ISO-8859-1";
encodingOptions.CharacterSet = encodingName;

```

In this case function CharacterSetECI.getCharacterSetECIByName(encodingName) returns the result corresponding to CharacterSetECI with value 16, not 3 or 1 as expected.
If encodingName = "ISO-8859-3" the result value is 18, not 5 as expected.
If encodingName = "ISO-8859-4" the result value is 12, not 6 as expected.

Moreover, using Aztec encoder if encodingName = "CP437" an exception is thrown since corresponding Encoding.WebName = "IBM437" in this case and CharacterSetECI.getCharacterSetECI(encoding) can not be found. If encodingName = "ISO-8859-11" Encoding.WebName = "windows-874",  if encodingName = "UTF-16BE" Encoding.WebName = "unicodeFFFE".

I think the mentioned bugs should be fixed in some way.

**Comment by micjahn** [comment]
Thanks for the report. Really a good find. Can't believe no one has stumbled across it before.
