### ISSUE TITLE
WriteableBitmapRenderer class not  available in ZXing.Windows.Compatibility Version 0.16.11 for net 7.0

### ISSUE THREAD

**Issue by steirensis** [micjahn/ZXing.Net#488]
Hi there!!

The WriteableBitmapRenderer class is not available in ZXing.Windows.Compatibility Version 0.16.11 for net7.0

Version: 0.16.10
![image](https://user-images.githubusercontent.com/51659181/221437895-1a23d4b1-aeb3-4baf-a26a-853d1a40b8a5.png)

Version: 0.16.11
![image](https://user-images.githubusercontent.com/51659181/221437994-a33e8ee8-3780-422d-8588-199cb7c71ed6.png)

(for write bitmapsource)

Thanks in advance!!!!

**Comment by micjahn** [comment]
Thanks for reporting this issue. Nuget package is updated.
