### ISSUE TITLE
Cannot Decode QRCode 

### ISSUE THREAD

**Issue by kent-williams** [micjahn/ZXing.Net#49]
Hello,

I'm having an issue decoding one specific QR code. I have not had any issues with any others that were generated from the same source except this particular one. I have attached the image below. This QR code image is scanned from a piece of paper just FYI. Decode returns null on the result.

Text value should be : 37d59b9d-ad37-11e7-a3da-2e6a680acb2

![qrcode](https://user-images.githubusercontent.com/479648/31689772-5e30e400-b345-11e7-92da-5bc9973d1ba3.jpg)

Thanks!
-Kent

**Comment by micjahn** [comment]
This one is rotated by 180 degress. Rotate it manually if you know your webcam orientation or activate the option AutoRotate. If I understand you right you don't use a camera. The picture is from a classic scanner, the orientation of the scanned paper isn't known.
```
var reader = new BarcodeReader
{
   AutoRotate = true
};
```

**Comment by kent-williams** [comment]
Thanks for the response @micjahn!

All the QR codes I'm working with are rotated 180. This is the only one that doesn't want to decode for some reason though. I will try setting the AutoRotate though and report back.

-Kent
