### ISSUE TITLE
Trouble Making PDF417 with custom dimensions

### ISSUE THREAD

**Issue by icefnmercy** [micjahn/ZXing.Net#491]
Hello,

I am attempting to create a pdf417 with custom row and column count but couldn’t find much information on the implementation for this. Could you please tell me how I could accomplish this?

**Comment by micjahn** [comment]
Not sure, if the following snippet fits your needs. But it should give you an idea, I think.

```
            var writer = new ZXing.BarcodeWriter
            {
                Format = ZXing.BarcodeFormat.PDF_417,
                Options = new ZXing.PDF417.PDF417EncodingOptions
                {
                    Dimensions = new ZXing.PDF417.Internal.Dimensions(minCols, maxCols, minRows, maxRows)
                }
            };
            var bitmap = writer.Encode("<content here>");
```

**Comment by icefnmercy** [comment]
thank you. is there a way to use ascii control characters when encoding information such as {lf} and {cf}

**Comment by icefnmercy** [comment]
and how can i set the error correction of the pdf417 barcode

**Comment by micjahn** [comment]
If you need a specific character set, you can set it by PDF417EncodingOptions.CharacterSet. But it is only used for byte compaction mode. Line feed characters and similar can be included in the content string.

```
var bitmap = writer.Encode(@"<content here
with line break>");
```
