### ISSUE TITLE
Support ImageSharp v3

### ISSUE THREAD

**Issue by viceice** [micjahn/ZXing.Net#492]
ImageSharp [`v3`](https://github.com/SixLabors/ImageSharp/releases/tag/v3.0.0)  was releases recently.

⚠️  It only supports net6.0+. ⚠️

**Comment by micjahn** [comment]
I made a new nuget package for this:
https://www.nuget.org/packages/ZXing.Net.Bindings.ImageSharp.V3
Every user can decide which version and which license would fit.

**Comment by viceice** [comment]
> Watchout with ImageSharp, they have changed there license about using it in commercial applications. If you app is opensource then you are fine but when it is closed source you have to buy a commercial license. This makes it unuasable if you don't want to pay anything.

good catch, didn't saw that in release notes 🤔

**Comment by viceice** [comment]
it seems if you use it as transitive dep from zxing then you can use it under the zxing license

**Comment by micjahn** [comment]
You have to fulfill the license model for both libraries. If you cannot use the ImageSharp license you can't use the ZXing binding package for it.

**Comment by viceice** [comment]
you are right, I've hidden my wrong comment.

we fulfill the license but now switched to skiasharp, as we had that library as indirect dependency already 😅
