### ISSUE TITLE
Barcode Rendering Quality

### ISSUE THREAD

**Issue by phuzi** [micjahn/ZXing.Net#5]
Although not broken the rendering of SVG QR Codes could be improved by setting the `shape-rendering` attribute to `crispEdges` on the generated SVG element to remove anti-aliasing artefacts.

The images below were rendered by Chrome Version 57.0.2987.98 (64-bit) with the results being replicated in Firefox 52.0 (64-bit)

Before:
![image](https://cloud.githubusercontent.com/assets/3404766/24004339/f9a5fd8a-0a5d-11e7-8d58-a488cacc037d.png)

After:
![image](https://cloud.githubusercontent.com/assets/3404766/24004299/d99c26a4-0a5d-11e7-85f3-842328fb298a.png)

Doing the same with 1D barcodes e.g. EAN-13.
Before:
![image](https://cloud.githubusercontent.com/assets/3404766/24004222/a5699bb4-0a5d-11e7-8480-4c81aea9bd27.png)

After:
![image](https://cloud.githubusercontent.com/assets/3404766/24004252/b886a624-0a5d-11e7-9e95-153898558815.png)

**Comment by micjahn** [comment]
fixed

**Comment by phuzi** [comment]
Wow, that was quick. Nice one
