### ISSUE TITLE
ZXing have code reading from a string?

### ISSUE THREAD

**Issue by jenokizm** [micjahn/ZXing.Net#501]
Hello everyone, please advise. We have numeric codes instead of an image. Does the library support their parsing?
I need something like this:

```
string iPhone14WhiteCode = "0194253408475";
var res = Barcode.Parse(iPhone14WhiteCode);
```

**Comment by micjahn** [comment]
What result value should the variable res hold after the call to Barcode.Parse?

**Comment by jenokizm** [comment]
> What result value should the variable res hold after the call to Barcode.Parse?

barcode format (EAN / UPS / GTIN / etc.), country, manufacturer, product

**Comment by micjahn** [comment]
No, ZXing.Net doesn't support your cases.
There are some other formats, especially use with QR code like vEvent, vCard, Wifi and similar.
They can be parsed by

`                var parsedResult = ResultParser.parseResult(result);`
