### ISSUE TITLE
ITF barcode is not decoded in tiff image, but decoded in JPG image

### ISSUE THREAD

**Issue by SanKumSan** [micjahn/ZXing.Net#512]
I have an ITF barcode with 10 digits value.

When an scanned tiff image with ITF barcode, tried to decode this barcode, NO value is decoded.
But the same image, when scanned as JPG, and tried to decode, it is decoded successfully.

I am wondering why the image format, tiff or jpeg, effects the decoding of this ITF value.
Any inputs are appreciated.

**Comment by micjahn** [comment]
Can you provide the JPG and TIFF files?

**Comment by SanKumSan** [comment]
![sample_Jpeg](https://github.com/micjahn/ZXing.Net/assets/57710619/f1c92e76-07c9-4889-b6e2-d410905c1283)

Here is the sample JPEG file with ITF barcode and it is decoded.

**Comment by SanKumSan** [comment]
![sample_Jpeg](https://github.com/micjahn/ZXing.Net/assets/57710619/73b3d6cf-fbaf-4aa0-83b8-8a94e347c4bb)
 Here is a jpeg sample image with ITF barcode and it is decoded.

**Comment by SanKumSan** [comment]
https://github.com/SanKumSan/testercr7/blob/main/sample_tiff.tif

Here is the tiff file with the same ITF barcode and it is not decoded by ZXing.

Note : Tiff has LZW compression.

Does the compression of the tiff effects the decoding behaviour ?

Does the image formats (tiff, jperg, png  and others) effects the decoding behaviour ?

**Comment by micjahn** [comment]
Sorry, I can't check it for the next three weeks.
Anyway, the file format doesn't affect the decoding success. Internally every image format is converted to Bitmap before decoding. Only the compression algorithm of the format can in some cases affect the bitmap quality (difference between lossless and not lossless compression).

**Comment by SanKumSan** [comment]
Thanks @micjahn . Thanks for the answers.

**Comment by micjahn** [comment]
I couldn't decode both of them if I used the original image size.
If I reduce the size to 75% both versions are successfully decoded.
I think the main problem is more or less the black-and-white ratio of the image and the pixel artifacts in the black areas.
Perhaps a real-world image with more content would give better results. Or you generally shrink the scanned image by 25% before decoding which reduces artifacts in the black areas.

**Comment by SanKumSan** [comment]
Hello
Reducing the size of the barcode rectangle or the whole image has improved decoding.
Thanks
