### ISSUE TITLE
how to generate a GS1-128 barcode with parentheses

### ISSUE THREAD

**Issue by John0King** [micjahn/ZXing.Net#518]
I want to generate a GS1-128 barcode like this 
<img width="832" alt="屏幕截图 2023-07-24 163944" src="https://github.com/micjahn/ZXing.Net/assets/13639146/fd6f14f5-f8eb-4b0b-ac38-1693d8e98ede">

I tried both `"\u001d0106901234567892172007031012AB\u001d21345XYZ"` and `"\u001d(01)06901234567892(17)200703(10)12AB\u001d(21)345XYZ"`, but  it's has wrong text in first text and  wrong barcode-content in second content

**Comment by micjahn** [comment]
Sorry, the available renderer implementations of this project don't support the output of parentheses.
You should go with the version that creates the correct content.
