### ISSUE TITLE
How to generate svg file 

### ISSUE THREAD

**Issue by vishnushanmughan** [micjahn/ZXing.Net#52]
i found this  https://github.com/micjahn/ZXing.Net/blob/master/Source/lib/BarcodeWriter.SvgImage.cs but i am not able to generate svg file is there any way?

**Comment by micjahn** [comment]
Please use the BarcodeWriterSvg class.
```
var writer = new BarcodeWriterSvg();
writer.Format = BarcodeFormat.QR_CODE;
writer.Write("<your content here>");
```
