### ISSUE TITLE
Unable to read QRCode from scan

### ISSUE THREAD

**Issue by sameermanuja** [micjahn/ZXing.Net#520]
Hello,

I am having an issue reading the following QR code. The code comes from a scanned image, and can't be read by the ZXing library.

![AB_Barcode](https://github.com/micjahn/ZXing.Net/assets/42500656/32b2694c-295c-40aa-ba41-3e3e6dd31e51)

I have tried reading both with the QRCodeReader and MultiFormatReader with format hint as QR_CODE. Neither worked.

			Reader reader = new MultiFormatReader();
			BufferedImage buffered = areaOfInterest.toBufferedImage();
			LuminanceSource luminance = new BufferedImageLuminanceSource(buffered);
			BinaryBitmap image = new BinaryBitmap(new HybridBinarizer(luminance));
			
			Map<DecodeHintType, Object> hintsMap = new EnumMap<DecodeHintType, Object>(DecodeHintType.class);
			hintsMap.put(DecodeHintType.TRY_HARDER, true);
			hintsMap.put(DecodeHintType.POSSIBLE_FORMATS, Arrays.asList(BarcodeFormat.QR_CODE));

Looking for any help to resolve.
Thanks in advance.

**Comment by micjahn** [comment]
I could successfully decode the QR code with the WinForms demo application of ZXing.Net.
Your code looks like java. Perhaps you should ask your question on the original zxing java project page.
The page here is for the C# port.
