### ISSUE TITLE
UTF-8 not properly detected in some cases - german umlauts corrupted (ASSUME_SHIFT_JIS broken with .Net Core)

### ISSUE THREAD

**Issue by Michael-Hofer** [micjahn/ZXing.Net#522]
Relevant change probably happened with Commit f7c3406e11699fcd6d88d576400a76a287bb2d1c

Background information:
On ~~a german Windows 10 system~~ .NET Core a call to
`System.Text.Encoding.GetEncoding("SJIS");`
thows an exception.
Due to this the call to `CharacterSetECI.getEncoding(SHIFT_JIS);` returns UTF-8 as a fallback.
As UTF-8 is also the default characterset the following comparison results in true.
```
ASSUME_SHIFT_JIS =
                PLATFORM_DEFAULT_ENCODING_T.Equals(SHIFT_JIS_ENCODING) ||
                PLATFORM_DEFAULT_ENCODING_T.Equals(EUC_JP_ENCODING);
```
This seems to be wrong. On a german system ASSUME_SHIFT_JIS should be false (as it had been before the change).

With ASSUME_SHIFT_JIS == true later on (in StringUtils.cs) (first assumption was:ISO-8859-1) **UTF-8 is not correctly detected and german umlauts get corrupted**.
With older versions this had worked fine.

**Comment by micjahn** [comment]
Can you provide a sample image?

**Comment by Michael-Hofer** [comment]
Please find 2 sampe QR codes attached.
The text is encoded as UTF-8.
first qr code is fine (expected text: [RC]pat=101798;proc=1068496;cat=Aufklärung §630 Röntgen)
**second qr code fails** (expected text: [RC]pat=095142;proc=3282245;cat=Einverständnis)

With older versions of the library (tested with "ZXing.Net.Bindings.SkiaSharp" Version="0.16.5") both QR codes had been decoded as expected.

![qr-code_UTF8_german_umlaut_and_paragraph_sign](https://github.com/micjahn/ZXing.Net/assets/26085159/22c12601-6630-4f05-937d-4e10148fdceb)
![qr-code_UTF8_only_one_german_umlaut](https://github.com/micjahn/ZXing.Net/assets/26085159/4624ed4b-3d05-4a3b-893f-e7d03751261a)

**Comment by micjahn** [comment]
I tested your samples with the current release version of ZXing.Net and the WinForms demo. Both are decoded successfully. The decoded text shows in both cases your expected result. I used a Windows 10 german system.
Perhaps this is only true for .Net classic framework. There is a slightly different initialization in the constructor for .Net standard targets. But in my opinion, this is also true and the same for older versions of the library.

**Comment by Michael-Hofer** [comment]
Thanks for testing.
My tests with the demo application had also been successful.

The code in question **targets .net6.**
I have found the dotnet-issue https://github.com/dotnet/runtime/issues/20715.
With .Net Core the "windows desktop" codepages are not available by default.
A call to `System.Text.Encoding.GetEncoding("EUC-JP")` or `System.Text.Encoding.GetEncoding("SJIS")` throws an exception and with the fallbacks in place in ZXing.Net in turn the switch ASSUME_SHIFT_JIS is wrongly set to true.
When I add
`Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);`
to my unit test before decoding the QR code everything works fine.
(The GetEncoding-calls do not throw exceptions anymore.)

The issue mentioned above suggests to add the `RegisterProvider`-call to application code and not to library code.
Please check yourself - you might want to add a note in the documentation if you do not want to add the `RegisterProvider`-call to the ZXing-library itself.

**Comment by micjahn** [comment]
I don't want to add the RegisterProvider-call to the library code.
But I think I will slightly modify the initializations in the static constructor in StringUtils.
With an additional check that SHIFT_JIS_ENCODING/EUC_JP_ENCODING isn't the same as the fallback encoding UTF-8, ASSUME_SHIFT_JIS should not be set to true in your case.

```
        static StringUtils()
        {
#if (NETFX_CORE || PORTABLE || NETSTANDARD)
            PLATFORM_DEFAULT_ENCODING = UTF8;
            PLATFORM_DEFAULT_ENCODING_T = Encoding.UTF8;
#else
            PLATFORM_DEFAULT_ENCODING = Encoding.Default.WebName.ToUpper();
            PLATFORM_DEFAULT_ENCODING_T = Encoding.Default;
#endif
            SHIFT_JIS_ENCODING = CharacterSetECI.getEncoding(SHIFT_JIS) ?? PLATFORM_DEFAULT_ENCODING_T;
            GB2312_ENCODING = CharacterSetECI.getEncoding(GB2312) ?? PLATFORM_DEFAULT_ENCODING_T;
            EUC_JP_ENCODING = CharacterSetECI.getEncoding(EUC_JP) ?? PLATFORM_DEFAULT_ENCODING_T;
            ISO88591_ENCODING = CharacterSetECI.getEncoding(ISO88591) ?? PLATFORM_DEFAULT_ENCODING_T;
            ASSUME_SHIFT_JIS =
                (PLATFORM_DEFAULT_ENCODING_T.WebName.Equals(SHIFT_JIS_ENCODING.WebName) && !Encoding.UTF8.WebName.Equals(SHIFT_JIS_ENCODING.WebName)) ||
                (PLATFORM_DEFAULT_ENCODING_T.WebName.Equals(EUC_JP_ENCODING.WebName) && !Encoding.UTF8.WebName.Equals(EUC_JP_ENCODING.WebName));
        }
```

**Comment by Michael-Hofer** [comment]
Thanks for checking.
Your proposal for the code change looks good to me
and we would not have to add `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);` in our application code.

**Comment by micjahn** [comment]
I committed the changes.

> and we would not have to add Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); in our application code.

That's not fully correct. It depends on your use case.
If you need a correct decoding for more than only UTF-8 encoded content you should add the missing code pages.

**Comment by Michael-Hofer** [comment]
Thanks for fixing and the advice about the code pages - probably UTF-8 will be sufficient.

We tested the change locally and it solved our issue.
Do you already have a plan/roadmap when the fix will be available as Nuget-package?

**Comment by micjahn** [comment]
Hopefully soon, but I want to add the latest changes from the java version first. Sorry, there is no fixed deadline for the next version.
