### ISSUE TITLE
EAN - 13 produce diffrent barcode 

### ISSUE THREAD

**Issue by vishnushanmughan** [micjahn/ZXing.Net#53]
I tried to generate an EAN 13 image but the out put is different. It doesnt not look like a EAN 13 but when i read the data it produces correct out put

`var writer = new BarcodeWriter
                {
                    Format = BarcodeFormat.EAN_13,
                    Options = new ZXing.Common.EncodingOptions
                    {
                        PureBarcode = false,
                        Height = 124,
                        Width = 220
                    }
  };`
It produce out put like this 
![barcode_ean_13](https://user-images.githubusercontent.com/28772646/31896480-8484fc68-b831-11e7-9bd4-d50a56b7e164.PNG)

but i want an out like this one 
![ean13](https://user-images.githubusercontent.com/28772646/31896540-aa7a28bc-b831-11e7-92e1-7de3e6365f38.jpg)
Is there any way to do this?

**Comment by micjahn** [comment]
I'm not sure what you mean. It is a EAN-13 code and scans perfectly.
If you want the design of the other barcode (longer lines at the beginning, the end and in the middle, font size scaled to the barcode image) you have to write your own renderer. The current implementation only supports the output as you can see it in your generated sample image.
You are welcome to enhanced the existing renderer implementation and open a PR to merge it in the project.

**Comment by Tashla** [comment]
@vishnushanmughan Have you ever been able to enhance the existing renderer or come around to writing a custom renderer? I am currently facing the same 'problem' in a project of mine and I can't wrap my head around a custom renderer that offers this functionality. Would love to see what approach you've taken to achieve your goal.
