### ISSUE TITLE
Add some unsafe methods?

### ISSUE THREAD

**Issue by ConanNobita** [micjahn/ZXing.Net#530]
The buffer, read from native memory, needs to be copied into a C# byte array in order to call the methods of ZXing to decode it, which affects performance.
Can you add a method to parse the content of the QR code directly from the pointer to memory, or the data of the pointer is encapsulated with the Span type?

**Comment by micjahn** [comment]
Can you please give me a little bit more context? Do you have a code snippet that shows how you use ZXing.Net at the moment?
Which is your target .Net platform (.Net 4.x, .Net Core, .Net 5.0 or above)? Do you use a specific image library like SkiaSharp, ImageSharp, Windows Compatibility pack or similar?
