### ISSUE TITLE
0.16.6 vs 0.16.9

### ISSUE THREAD

**Issue by mey1k** [micjahn/ZXing.Net#532]
issue :

      For some image,
      It is decoded in 0.16.6, but not in 0.16.9.
      Why is that?

     I think it's because of the black-and-white reversal, is it correct?
    
code :

        ZXing.IBarcodeReader zxing_reader = new BarcodeReader()
        {
            AutoRotate = true,
            TryInverted = true,
            Options = new ZXing.Common.DecodingOptions()
            {
                TryHarder = true,
                ReturnCodabarStartEnd = true,
                PureBarcode = false,
                PossibleFormats = new List<BarcodeFormat>()
                {
                    BarcodeFormat.DATA_MATRIX
                }
            }
        };

**Comment by micjahn** [comment]
Do you have a sample image?
