### ISSUE TITLE
Version out dated while opening in vs22, using version 4.0

### ISSUE THREAD

**Issue by ks1990cn** [micjahn/ZXing.Net#534]
Hi,

Its giving me error for too old version, any plan for upgrade or how we can do with latest versions?

**Comment by micjahn** [comment]
I'm not sure what you mean. The solution contains many different projects that target different .Net platform versions from .Net 2.0 to .Net 7.0.

**Comment by ks1990cn** [comment]
So these are getting used cause we don't have alternative for those projects in solution?

**Comment by micjahn** [comment]
I don't get the point. If you have problems with some projects which targeting older .Net platforms than remove it from your copy of the solution or create a new one which fits your needs. At the moment I will not remove them generally. There are other users of the library out there which are stick to .Net 4.x for example.
