### ISSUE TITLE
Scannig QR Code with Oppo devices doesn't work

### ISSUE THREAD

**Issue by Moro890** [micjahn/ZXing.Net#535]
I'm using an Oppo device with the latest version of ZXing.Net.Maui to scan QR codes. The OnBarcodeDetected event doesn't trigger when scanning QR codes. It's working fine on iOS and other devices, but there's an issue specifically with Oppo.
Debugging the ZXing.Net.Maui seem like that the problem is in ZXing.Net and not in the wrapper

Let me now if you guys need more details.
Thanks

**Comment by micjahn** [comment]
Why do you think that this is not a problem in the wrapper?

**Comment by Moro890** [comment]
I tried Camera.Maui and the issue is not there, then it seem a problem of the wrapper. I take it back
