### ISSUE TITLE
如何设置条形码的尺寸以及密度

### ISSUE THREAD

**Issue by wangfei9999** [micjahn/ZXing.Net#539]
这个是一个标签大小为70mm*50mm，宽度为70mm，高度为50mm，当我生成条码时出现了超出标签宽度的问题，请问我改如何设置条形码在我固定的标签宽度内呢？
![image](https://github.com/micjahn/ZXing.Net/assets/73685882/7003a769-2ebb-4e41-96f1-4ac2b36bb49a)

使用的条码生成库为：ZXing.Net.Bindings.SkiaSharp -- version 0.16.13

**Comment by micjahn** [comment]
I think the only way would be, that you create the barcode with a "Width = 1" and than stretch it manually with another image manipulation library to the desired width.
Can you please post a code snippet of the code which you are currently using for generating barcodes?
