### ISSUE TITLE
Extended Code 39 issue

### ISSUE THREAD

**Issue by Sathunter** [micjahn/ZXing.Net#54]
I have been trying to get the writer for extended Code39 barcodes working without success. I tried encoding using Zxing.Net demo with Windows forms and that was fine. Can't see how I apply the extended barcodes but everything else is working . Looked at the documentation but can't figure out.where I am going wrong.  A SIMPLE sample would be greatly appreciated.

**Comment by micjahn** [comment]
The extended code 39 support isn't included in the last release (0.16.2). But it is already inside master.
Please wait for the next release or build your own binary from the sources meanwhile.
