### ISSUE TITLE
Upgrade SkiaSharp - current version had Vulnerabilities

### ISSUE THREAD

**Issue by mathy-plutoflume** [micjahn/ZXing.Net#545]
Current `SkiaSharp` version used is `2.88.3`; which has vulnerabilities 
![image](https://github.com/micjahn/ZXing.Net/assets/101151855/c555015a-8a9c-4d7c-940a-926c898a89ef)

This need to upgrade to newer (or latest) version.

**Comment by micjahn** [comment]
It is available now.

**Comment by micjahn** [comment]
You have to use this one here:
https://www.nuget.org/packages/ZXing.Net.Bindings.SkiaSharp

**Comment by mathy-plutoflume** [comment]
My bad 🤦🏼‍♂️, i was looking at the wrong package link. Thanks! I am able to upgrade it now.
