### ISSUE TITLE
Upgrade SixLabors.ImageSharp - current version has vulnerabilities

### ISSUE THREAD

**Issue by RadtkeJCJ** [micjahn/ZXing.Net#560]
The current version used by ZXing.Net.Bindings.ImageSharp.V2 is flagged as having vulnerabilities on NuGet:
![image](https://github.com/micjahn/ZXing.Net/assets/22891417/4283b9ae-a7dd-46bc-8efe-db2d6df30d5d)
https://www.nuget.org/packages/SixLabors.ImageSharp/2.1.3
The latest 2.X version (2.1.7) looks to be the version it was resolved in. Looks like the 3.X series is similar.

**Comment by micjahn** [comment]
new versions are available at nuget.org.
