### ISSUE TITLE
The image for PLESSEY is vertically tiny.

### ISSUE THREAD

**Issue by dai-kanai** [micjahn/ZXing.Net#562]
I used ZXing.Windows.Compatibility.BarcodeWriter.Write.
It generates a vertically tiny image for the format PLESSEY.
![image](https://github.com/micjahn/ZXing.Net/assets/143141116/f279c03a-c1d5-4f1c-ab5f-0413c75615db)

**Comment by micjahn** [comment]
Can you please post a code snippet which shows how you generate the code?

**Comment by dai-kanai** [comment]
@micjahn 
Thank you for your reply.
I forgot to say the pasted image was the magnified image and I made a tiny code at that time, so it was so obvious.
Anyway, here is the test code project.
[BarcodeTest.zip](https://github.com/micjahn/ZXing.Net/files/14845994/BarcodeTest.zip)

I cut the source from our production, so maybe it is not optimized.

By the way, about PLESSEY, the text is also very small.

**Comment by dai-kanai** [comment]
@micjahn
I understood the size of the letters comes from the code specification.
How about the original issue, the height?
It always uses only around 1/3 of the height in the case of PLESSEY.

**Comment by micjahn** [comment]
It uses the requested height. But it has to extend the width of the resulting bitmap.
In the example the requested size of 600x400 pixels results in a size of 1845x400 pixels because the width is needed to get a bitmap with black and white bars in the correct ratio.

**Comment by dai-kanai** [comment]
Understood.
Thank you.
