### ISSUE TITLE
ZXing.Net.Bindings.CoreCompat.System.Drawing relies on version errors of zxing.net

### ISSUE THREAD

**Issue by maikebing** [micjahn/ZXing.Net#57]
The new version of 0.16.2 ZXing.Net.Bindings.CoreCompat.System.Drawing depends on Zxing.Net, but if Zxing.net is 0.16.2, BarcodeWriterExtensions.WriteAsBitmap (BW, st).Save (filename); will prompt the lack of assembly zxing.net 0.16.0, but if zxing.net will be downgraded to 0.16.0, it will be reported the following error

5>D:\\Works\\TCSOA\\TCS.LIC\\TCS.LIC.csproj: error NU1605: detects packet degradation: ZXing.Net degrades from 0.16.2 to 0.16.0. Reference packages directly from the project to select different versions.
D:\\Works\\TCSOA\\TCS.LIC\\TCS.LIC.csproj: error NU1605: TCS.LIC - > ZXing.Net.Bindings.CoreCompat.System.Drawing 0.16.3-beta - > ZXing.Net (> 0.16.2)
D:\\Works\\TCSOA\\TCS.LIC\\TCS.LIC.csproj: error NU1605: TCS.LIC - > ZXing.Net (> 0.16.0)

**Comment by maikebing** [comment]
.net core 2.0 Vs2017

**Comment by micjahn** [comment]
Should work now with version 0.16.4.0.

**Comment by maikebing** [comment]
谢谢你！
Thank you very much!
