### ISSUE TITLE
Upgrading to Magick.Net 13.7.0 breaks ZXing.Magick

### ISSUE THREAD

**Issue by flytzen** [micjahn/ZXing.Net#571]
The `ZXing.Magick` binding references `Magick.Net.Core` vs 12.3.0.

Consumers of `ZXing.Magick` have to reference `Magick.Net` themselves (which is a good thing). However, `MagickFormat` is an enum in `Magick.Net.Core` and it was changed in `Magick.Net` v 13.7.0.

This line:
https://github.com/micjahn/ZXing.Net/blob/45461597e3ef97ac00fb2b9f742612c9a69c8c0b/Source/Bindings/ZXing.Magick/MagickImageLuminanceSource.cs#L67

uses `MagickFormat.Gray` which has a value of 83 in `Magick.Net` 13.6.0 and earlier. However, in `Magick.Net` 13.7.0, `83` equals `Gradient`.

So, when a consumer of `ZXing.Magick` upgrades `Magick.Net` to 13.7.0, it will break `ZXing.Magick`.

The easiest fix for `ZXing` would be to upgrade to `Magick.Net` 13.7.0.

See also
- https://github.com/dlemstra/Magick.NET/issues/1627
- https://github.com/BrandonPotter/GoogleAuthenticator/pull/213

**Comment by micjahn** [comment]
Version 0.16.14 of the binding package is pushed to nuget.org. That version is built against version 13.8.0 of Magick.Net.
