### ISSUE TITLE
Cannot create GenericMultipleBarcodeReader from ZXing.OpenCV.BarcodeReader

### ISSUE THREAD

**Issue by blauertee** [micjahn/ZXing.Net#577]
Is there any Possibility to do the following?

```c#
var Reader = new ZXing.OpenCV.BarcodeReader();
var MuReader = new ZXing.Multi.GenericMultipleBarcodeReader(Reader);
```

(I can cast the ZXing.OpenCV.BarcodeReader into Reader but then the Multi-Reader does not allow an OpenCV Mat as Argument anymore)

Thanks in Advance!

**Comment by micjahn** [comment]
You can use it this way:

```
var Reader = new ZXing.OpenCV.BarcodeReader();
Reader.DecodeMultiple(...)
```

**Comment by micjahn** [comment]
You are right, the naming is somewhat misleading.
Background: "Reader", "GenericMultipleBarcodeReader", "QRCodeReader", "PDF417Reader" and so on are classes which are directly ported from the original java version. They can't be used with a bitmap or Mat instance directly. They need a BinaryBitmap instance which has to be created manually before.
"ZXing.BarcodeReader", "ZXing.OpenCV.BarcodeReader" and so on are additional classes which only exist in ZXing.Net.
That classes combine the separate calls to create a luminance source, a binary bitmap, automatic rotation and decoding of the binary bitmap into one call. BarcodeReader classes use the GenericMultipleBarcodeReader under the hood.

**Comment by blauertee** [comment]
Okay but if [this](https://stackoverflow.com/questions/27129312/can-zxing-net-read-multiple-qr-barcodes-in-same-image) is right this is only applicable to read multiple QR-Codes from the same Image. Is there any way to read all recognizable optical codes of different types on an image, using an OpenCv Mat as Input?

**Comment by micjahn** [comment]
The method "DecodeMultiple" works for different types of codes as stated in my comment at stackoverflow:

> The BarcodeReader class implements two interfaces: IBarcodeReader and IMultipleBarcodeReader. The IMultipleBarcodeReader interface supports the method DecodeMultiple. If you set the Property PossibleFormats only to QR_CODE the BarcodeReader uses internally the QRCodeMultiReader implementation if DecodeMultiple is called. If you look for other barcode types it uses the GenericMultipleBarcodeReader.

**Comment by blauertee** [comment]
Then this is probably more related to #423 then to not beeing able to detect different code types than qr. Thank' for the quick response and for explaning what my misunderstanding was!
