### ISSUE TITLE
QR code Scanning doesn't work on some android phones

### ISSUE THREAD

**Issue by trampster** [micjahn/ZXing.Net#580]
QR code scanning doesn't work on the following android phones:

- Motorola G84 5G
- Sonim XP9900
- Oppo A54

The camera view shows but it never detects the QR code.

The preloaded camera app on these phones can scan these code successfully. And the same QR code can be scanned by ZXing.Net.Maui on other android and iOS phone models.

![QRCode](https://github.com/user-attachments/assets/be2017d6-8141-4b13-a5e1-dc37b07f5baf)

I have attached logs from trying to scan with the Oppo A54. There are logs from when the scan page is loaded but there is nothing apart from GC collection stats while its actually trying to scan.

[OPPO.A54.QR.code.scan.logs.txt](https://github.com/user-attachments/files/17053141/OPPO.A54.QR.code.scan.logs.txt)

We are using this through ZXing.Net.Maui and are not sure if the issue is with ZXing.Net.Maui or with ZXing.NET

Versions:
ZXing.Net version 0.16.9
ZXing.Net.Maui version 0.4.0
ZXing.Net.Maui.Controls version 0.4.0
net8.0
Maui version 8.0.80

**Comment by micjahn** [comment]
I cannot provide support for individual smartphone models. If ZXing.Net can read the QR code on other smartphones, the error will not be in ZXing.Net. Btw. I was able to successfully decode the QR code of the provided image with the Windows Forms test application.

**Comment by trampster** [comment]
No problem, I think the issue is with ZXing.Net.Maui anyway.
