### ISSUE TITLE
Memory leak while stop() is called in winforms C# [QRCode] Scanning

### ISSUE THREAD

**Issue by ahmedtalaat327** [micjahn/ZXing.Net#581]
**Describe the bug**
I cant end the thread even if uses : 
`SignalToStop()` func.

this is a piece of code 👍 

`   

> private void Exitcamera()
>         {
>             videoCaptureDevice.SignalToStop(); 
>             // FinalVideo.WaitForStop();  << marking out that one solved it
>             //videoCaptureDevice.Stop();
>             videoCaptureDevice.NewFrame -= new NewFrameEventHandler(VideoCaptureDevice_NewFrame); // as sugested
>             videoCaptureDevice = null;
>         }

`

**Expected behavior**
the thread must end but when I try to exit the window application the app still in processes 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Visual studio x64

screens:
![Screenshot 2024-10-13 001447](https://github.com/user-attachments/assets/76b6596d-e75b-4829-9a41-5bad2952e976)
![Screenshot 2024-10-13 001421](https://github.com/user-attachments/assets/9918caec-2cca-4677-966b-ed0e1b290aa8)

**Comment by micjahn** [comment]
In my opinion this is not an error inside ZXing.Net itself.
If I am wrong, please reopen the issue and provide more details about the location within ZXing.net where you suspect the memory leak.
