### ISSUE TITLE
powershell barcode decoder

### ISSUE THREAD

**Issue by geojaya** [micjahn/ZXing.Net#62]
PS C:\>Add-Type -Path <place the path to the zxing.dll here>\zxing.dll
PS C:\>$reader = New-Object -TypeName ZXing.BarcodeReader
PS C:\>$bitmap = [System.Drawing.Bitmap]::FromFile("<path to your bitmap image file>")
PS C:\>$result = $reader.Decode($bitmap)
PS C:\>$bitmap.Dispose()
PS C:\>$result.Text

Went through the powershell scripts, did not a result from a 3 of 9  barcode  in  .bmp file . powershell version 5.1 on Windows 7  sp1

**Comment by geojaya** [comment]
did not get barcode value

**Comment by micjahn** [comment]
What version of zxing do you use?
Please provide the image file for testing.
Did you really use the following line
`PS C:>$bitmap = [System.Drawing.Bitmap]::FromFile("")`
or did you manually remove the file name from inside the FromFile call before posting that issue?

**Comment by geojaya** [comment]
I have attached the jpeg version of the file.
![testbar](https://user-images.githubusercontent.com/4351259/33238296-cb2ade4e-d23f-11e7-86f8-b30c89545f0a.jpg)

**Comment by geojaya** [comment]
using  version 0.16.2  of Xzing.net  dll.

had the reference to the file with proper path  in FromFile call  when I tested with Powershell

**Comment by micjahn** [comment]
The problem is the quiet area at the left and right side of the barcode. It is to small.
Please try the attached, modified version of the barcode.
![wikipedia-code39](https://user-images.githubusercontent.com/3475026/33286502-cb550c92-d3b5-11e7-8313-e781570ff249.PNG)

**Comment by geojaya** [comment]
That works fine and also tested few other   code 3 of 9

However slight problem -  If the Barcode Orientation is not 0 degree -I do not get any result- any hint I can pass on the Decode() method call.

**Comment by geojaya** [comment]
I see dubstylee has suggested to pass TRY_HARDER  hint. When I called the method, with this parameter, -feedback method not overloaded.  How will I pass this Hint

**Comment by micjahn** [comment]
I updated the wiki page.
`PS C:\>$reader.Options.TryHarder = 1`

**Comment by geojaya** [comment]
I tried this which is having 35 degree orientation and did get any result. All other barcodes which is vertical and horizontal reads fine

For this one I tried with  try harder option of 1 , 2  6 etc, and still did not work, barcode was not read

![testbar4](https://user-images.githubusercontent.com/4351259/33471372-e53679e8-d621-11e7-964a-79e633080e91.JPG)
