### ISSUE TITLE
Reading 39 barcode using powershell

### ISSUE THREAD

**Issue by geojaya** [micjahn/ZXing.Net#65]
I tried this which is having 35 degree orientation and did get any result. All other barcodes which is vertical and horizontal reads fine

For this one I tried with try harder option of 1 , 2 6 etc, and still did not work, barcode was not read

![testbar4](https://user-images.githubusercontent.com/4351259/33471535-afb08772-d622-11e7-8eaa-f4aa64b0625b.JPG)

**Comment by micjahn** [comment]
The reader works horizontally line by line. There is no perspective correction for 1D barcodes. If you take a lineal you will see that you can't draw a line from the left to the right which includes all bars of the code. Less rotation or longer bars can fix it or someone implements a correction algorithm which rotates the image correctly. Feel free to provide a PR.
