### ISSUE TITLE
Generated barcode cannot be scanned / read or is read incorrectly

### ISSUE THREAD

**Issue by Hypnodude** [micjahn/ZXing.Net#69]
Hi,

We're generating datamatrix barcodes on Windows using the COM Interop wrapper.
On the whole, things are working nicely, but we have a few scenarios where things do not behave as expected.

1. *AHJGJ:IAGH
2. *AHJGJ;JA;FH

Item 1 above - the barcode generated from this string cannot be read using any of the readers / scanners we tried including the various Android apps or commercial barcode products.
Item 2 above - this barcode scans but the value read is different to the string actually encrypted. when the barcode for this string is scanned, it reads it as ***AH'q57'68H**

Thanx,
Alon

**Comment by anilroychoudhry** [comment]
Yes, i encountered the same.  A commercial library I trialled didn;t seem to have the issue.  All characters are part of the Latin Character set - ISO-8859-1

**Comment by micjahn** [comment]
Which version of ZXing.Net do you use?
I tried it with the current release 0.16.2 and the WindowsFormsDemoClient. I can't reproduce that issue.
Everything worked as expected.

**Comment by Hypnodude** [comment]
Hi Michael,

I'm still using 0.16.0.0
I'll try it with the updated DLL and see if that resolves the issue or not, 
then get backto you and let you know.

Thanx,
Alon

----------------------------------------

**Comment by Hypnodude** [comment]
Hi Michael,

I get the same result with the latest source (0.16.2.0)
Using the WindowsFormsDemo app (zxing.net for .Net 4.0) I do the following:

1. On the Encoder form, I put the string to encode into the Content field: *AHJGJ:IAGH
2. I select DATA_MATRIX from the drop-down for Type
3. I click the 'Encode' button and the barcode is rendered in the picturebox
4. Save this to a png file on disk
5. On the Decoder tab, click the elipses to select the Barcode Image file just saved and select it from the file system - this loads the image into the picturebox
6. Click the Decode button directly below the elipses - the Content shows 'No barcode recognized'

I tried this with both pieces of text - the same result for both.

If I click on the Decode button from the Encoder tab, it takes me to the Decoder tab with the picturebox displaying the barcode and the content correctly reflecting the encoded text, but it doesn't seem to work when deciding from a file.

Typically, we are generating small barcodes - 10 x 10, but for this test I left the default barcode size (188 x 214) as well as trying 10 x 10 - the same results each time.

Thanx,
Alon

**Comment by Hypnodude** [comment]
![bad1 10](https://user-images.githubusercontent.com/31230652/34241622-f15ca946-e66a-11e7-84e9-a2c87118eaf1.png)
![bad1](https://user-images.githubusercontent.com/31230652/34241623-f1869ec2-e66a-11e7-8263-58b47b1266e0.png)
![bad2](https://user-images.githubusercontent.com/31230652/34241624-f1af045c-e66a-11e7-968b-d0ae67323b71.png)

**Comment by Hypnodude** [comment]
The above barcodes are ones generated - the top is as per the example described above, the 2nd is the same, but encoded as 10x10.
The 3rd is the second string encoded as 10x10

**Comment by Hypnodude** [comment]
The barcodes DO scan correctly in other apps and using my phone - they do generate correctly!

**Comment by micjahn** [comment]
The "Decode" button at the encoder page uses the decoding hint "PureBarcode". With that hint zxing uses another detector for synthetic images (images which are not taken by a camera with normal noise in the picture). In your case the default detector has some trouble to find the correct edges of the data matrix code. That can happen but in normal real worlds scenarios it should be very rare.
