### ISSUE TITLE
Building the Unity DLL

### ISSUE THREAD

**Issue by motionsmith** [micjahn/ZXing.Net#7]
How can I rebuild the zxing.unity.dll? So far, I have:

1. Added the UNITY compiler directive to the .NET 3.5 version of ZXing.NET
2. Rebuilt the .NET 3.5 project.

At that point, I get errors wherever unity classes/namespaces are used (Color32, UnityEngine, etc).

Thanks,
Eric

**Comment by micjahn** [comment]
I'm really not sure what you tried out. If you grab the sources from the repository and open the solution it should be buildable out of the box. Did you add the sources manually to another project?

**Comment by motionsmith** [comment]
Hey @micjahn. Thanks for your help. In `BarcodeReader.cs` there is a a line that says `using UnityEngine;`. This only compiles if the `UNITY` compiler directive is specified. When I add that directive, the project then needs access to that namespace. I imagine that the Unity binaries are not included in the ZXing project, so including this namespace would fail (which I have found to be the case).

**Comment by micjahn** [comment]
The Unity binaries are in the 3rdParty directory. So if you use the sources and project files directly from the repository it should be buildable out of the box.

**Comment by micjahn** [comment]
All solutions and projects are building fine, dependencies are included in the repository. I can't see an open issue here and will close it for now.
