### ISSUE TITLE
Problem decoding QRCode image generated from ZXing

### ISSUE THREAD

**Issue by StanleyTso** [micjahn/ZXing.Net#70]
Code encoded and unable to decode: uNpsg6u2uMMVt1VJi0MYDaIpYsPNiiX66BW13bfI77j7AN1eQi

Anyone has idea?

Online demo works: https://zxing.org/w/decode.jspx 

I believe it should be just happening from .NET library
![4727658b-17f5-4e9d-990a-33ac9babdb93](https://user-images.githubusercontent.com/34806657/34325025-b70526fc-e83a-11e7-82fc-24e04ba34abf.png)

Problem is when I have enabled ERROR_CORRECTION

options.Hints.Add(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);

if I removed this code, the QRCode is good. 

Thank you

Stan

**Comment by micjahn** [comment]
I tried your sample image with the WinFormsDemo client from version 0.16.2.0 of ZXing.Net and doesn't have any problems.
Can you show a more complete code snippet of your encoding and decoding methods?

**Comment by StanleyTso** [comment]
The problem exists when we apply the ErrorCorrectionLevel to High.


        options.Hints.Add(EncodeHintType.ERROR_CORRECTION,
ErrorCorrectionLevel.H);

Thanks Micjahn

**Comment by micjahn** [comment]
As a said before, without more detailed information I can't help here.
Your sample works for me. It doesn't matter which error correction level is selected.
I can successfully decode the image which you attached here.
Please try the current WindowsFormsDemo from the 0.16.2 release.
https://github.com/micjahn/ZXing.Net/releases/download/zxing.net-0.16.2.0/ZXing.Net.DemoClients.0.16.2.0.zip
