### ISSUE TITLE
Unable to decode maxicode

### ISSUE THREAD

**Issue by clayzzzzzzzzzz** [micjahn/ZXing.Net#71]
Dear micjahn

I got one problem with decoding maxicode.Hope Someone can help me.
Here is my code:
                MultiFormatReader br = new MultiFormatReader();
                LuminanceSource sr = new BitmapLuminanceSource(newBitmap);
                HybridBinarizer hybrid = new HybridBinarizer(sr);
                BinaryBitmap bb = new BinaryBitmap(hybrid);
                Result result = br.decode(bb);
newBitmap is a maxicode Bitmap;
The result will be null;
This code will work ,if newBitmap is code128 or QRcode.

Best Regards

Clayz

**Comment by micjahn** [comment]
The maxicode support of zxing is very limited.
It works only with pure barcode images. A fully working detector is missing.
You can read your sample with the following snippet:
```
var reader = new BarcodeReader();
reader.Options.PureBarcode = true; // most important line
var result = reader.Decode(hybrid);
```

Feel free to open the issue again with a PR which adds the missing detector.
