### ISSUE TITLE
Picture artifact

### ISSUE THREAD

**Issue by Karamouchka** [micjahn/ZXing.Net#72]
I notice that if the picture start with black area and or finish with black area, the bar-code cannot be read.
![0 - copy](https://user-images.githubusercontent.com/35288708/34760271-a7e4f8f2-f611-11e7-8017-6caf92a5b509.jpg)

**Comment by micjahn** [comment]
The quiet zone at the left is to small. You should extend the white area at the left so that it fits the specifications.

**Comment by Karamouchka** [comment]
And where can I find information about that specification?

**Comment by micjahn** [comment]
The official specification are in ANSI MH 10.8 M-1983 and MIL-STD-1189.
Or you can try a little search
[https://www.google.de/search?q=specification+code+39+quiet+zone](https://www.google.de/search?q=specification+code+39+quiet+zone)
