### ISSUE TITLE
ZXing.BarcodeReader or ZXing.QrCode.QRCodeReader not decode

### ISSUE THREAD

**Issue by maxpower80** [micjahn/ZXing.Net#73]
Hello everyone, I have tried to use zxing (version 0.16.2.0 for .net 3.5) and I can not decode this QR image, I have searched for other similar errors and I have tried solutions such as setting TRY_HARDER or PURE_BARCODE parameters but the result is the same: decode function returns null. I have tried in the online application https://zxing.org/w/decode.jspx to attach the image and there if decoding is achieved. Please, could you tell me what may be happening? Thank you very much and greetings.

![a](https://user-images.githubusercontent.com/35295921/34779695-40e62ed6-f621-11e7-84da-8d0f83c786be.jpg)

**Comment by micjahn** [comment]
ZXing.Net has some troubles with the top-left finder pattern. There is some noise at the square which looks like some kind of reflection. If you remove it (make it black) the code can be sucessfully decoded.
I looked through the code but I can't find any difference between the java and the .net version. I can't help here with an improvement in the source code. Feel free to reopen the issue with a PR.
