### ISSUE TITLE
Sometimes pop out decoded string from nothing by webcam

### ISSUE THREAD

**Issue by RickyKuo** [micjahn/ZXing.Net#74]
When I continue scan on a white paper completely without any barcode on it, but sometimes it has result return suddenly. the return string usually EAN8, EAN13 or 2 character string. The version is .net 0.16.0.0

**Comment by micjahn** [comment]
Really, I need more information.
Please save the image when the reader returns a result and attach it here.

**Comment by RickyKuo** [comment]
@micjahn thanks for your help.
I got the result with a white paper from webcam as attach.
The result text is 12441834 UPC_E.

Image
![barcodetest 2](https://user-images.githubusercontent.com/18573361/34856064-1ba72efa-f77e-11e7-9f6c-091bc941f903.jpg)

Result
![message](https://user-images.githubusercontent.com/18573361/34856142-7281a9c6-f77e-11e7-9b1c-4f8d757ece4f.png)

**Comment by micjahn** [comment]
Thats not a white paper in my eyes. It's more like white noise. It's possible that there is a short black and white sequence within the noise which can be decoded as a barcode. I don't see any chance to fix it. You should try to get a clearer signal from you webcam.
