### ISSUE TITLE
.Net Standard

### ISSUE THREAD

**Issue by gmarbury** [micjahn/ZXing.Net#78]
Please update the projects (including samples) to build .NET Standard preferably 2.0.

**Comment by micjahn** [comment]
I'm not sure why this should be necessary. .Net Standard 1.0, 1.1 and 1.3 are supported with specific builds because of some classes which are used by ZXing.Net. As far as I know you can use all three versions with .Net Standard 2.0 projects. There is no benefit if I would add an additional 2.0 version.
Did I miss something?

**Comment by fahadabdulaziz** [comment]
Hi,

There is two benefits from targeting .Net Standard 2.
1. Lower the dependencies were needed in prior versions but no longer needed with ver. 2
2. There are some issues in .Net Framework 4.7.1  when referencing .Net standard libraries would be resolved when the library targets .Net Standard 2.

You may refer to:
https://github.com/dotnet/standard/issues/481
https://github.com/JamesNK/Newtonsoft.Json/issues/1423
https://github.com/Azure/diagnostics-eventflow/issues/155
https://github.com/mysql-net/MySqlConnector/issues/421

**Comment by gmarbury** [comment]
It's not possible to create a new Xamarin project in VS2017 with PCL anymore.  And if you open a PCL from VS2015 you get this nice message every time you go to the project properties 

> .NETStandard is the recommended method for sharing code between applications targeting different platforms

Some UWP projects don't build.  For example I can't get the Sample.Forms app in https://github.com/Redth/ZXing.Net.Mobile to build and run FormsSample.WindowsUniversal in VS2017 at all. I think it because the newer UWP projects that comes with VS 2017 out the box requires a different profile than what your ZXing.portable  was compiled on. What's even weirder is when I try to enable the "Windows Universal 10.0" target on Zxing.portable it will not save and unchecks itself.

**Comment by micjahn** [comment]
Please don't mix up ZXing.Net with ZXing.Net.Mobile. That are two different projects. ZXing.Net.Mobile uses ZXing.Net under the hood but it is not maintained by me. And ZXing.Net supports .Net Standard up from version 1.0. I only have to make sure that it is really necessary to build it against .Net Standard 2.0. As far as I understand the other issues there are some workarounds for the problems with .Net Standard 2.0 and the .Net Framework 4.6/4.7.

**Comment by gmarbury** [comment]
First both of you have done a great job. I respect  that a lot. Saving me a lot of time. I know they are different, that's why I provided the link to the other repo.  But that sample is a good example of a client using your PCL. There isn't a project in ZXing.Net  that builds .Net Standard in VS2017 because the old project.json isn't supported any more which I see you have an output of .Net Standard. I believe you need a cproj that builds .NET standard just like ZXing.portable builds a PCL.. Again thank you for your time. Great job.

**Comment by gmarbury** [comment]
Any more thought to this @micjahn? Maybe I can assist if you point me in the right direction.

**Comment by corneliu-serediuc** [comment]
Xamarin.iOS referencing a NET Standard 2.0.1 Library in Visual Studio for Mac:
```
Error MT2101: Can't resolve the reference 'ZXing.Common.BitMatrix', referenced from the method 'System.Byte[] 
BarcodeGenerator::Generate(System.String,System.Int32,System.Int32)' in 'zxing, Version=0.16.2.0, Culture=neutral, PublicKeyToken=4e88037ac681fe60'. (MT2101)
```

**Comment by micjahn** [comment]
@gmarbury I think I will add a .Net Standard 2.0 version. But I have to switch to VS 2017 before. This will take a little more time.

**Comment by corneliu-serediuc** [comment]
Perfect! Looking forward to it! Thanks!

**Comment by gmarbury** [comment]
The community edition of VS2017 is free and has everything you need.

**Comment by corneliu-serediuc** [comment]
Any updates ?

**Comment by micjahn** [comment]
Sorry, I'm a little bit busy last weeks. Hopefully get it done this week...

**Comment by corneliu-serediuc** [comment]
Thank you @micjahn! Is it also available via NuGet ?

**Comment by micjahn** [comment]
not at the moment.

**Comment by irowbin** [comment]
@micjahn Any progress? 😆

**Comment by CHLINDE** [comment]
I permanently get the error message "Could not load assembly 'zxing, Version=0.16.2.0..." on Xamarin Forms.
I installed the package via NuGet-Package administration tool and only added the following:

`using ZXing;`

 and 

`IBarcodeReader reader = new BarcodeReader();`

Is there any solution to fix this problem?

**Comment by micjahn** [comment]
version 0.16.4.0 with .net standard 2.0 support is out. Sorry for long delay.

**Comment by 2Elemental** [comment]
Is it possible to also release a .net standard 2.0 version with Unity support, given that Unity now fully embraces .net standard 2.0?

**Comment by micjahn** [comment]
I can try it. The binary packages of ZXing.Net contain a .Net 2.0 standard version already. Doesn't it work out of the box? What is missing?

**Comment by 2Elemental** [comment]
All of the Color32 supporting classes are missing, like Color32Renderer, Color32LuminanceSource and the inherited classes of BarcodeReader and BarcodeWriter to support Color32
