### ISSUE TITLE
Zxing on .Net framework 4.3 for gadgeeter

### ISSUE THREAD

**Issue by FrancescoPolitano** [micjahn/ZXing.Net#8]
Hi, I'm stuck with a problem i hope u can help me to solve.
I want to use your incredible good library on my FEZ SPIDER using 4.3 version of .net framework but i can't build it! How can I use your lib with this versione of the fw?
Thank you so much

**Comment by micjahn** [comment]
There is a ZXing.Net repository for .Net MF:
https://github.com/micjahn/ZXing.Net-NETMF
Did you try the sample within the repo?

**Comment by FrancescoPolitano** [comment]
Yes i found the repo but i don't know how to include that in my gadgeteer project on VS, this is not in form of a tipical library, sorry I'm a newbie!
