### ISSUE TITLE
How can I extract byte[] of image from luminanceSource?

### ISSUE THREAD

**Issue by ysmoradi** [micjahn/ZXing.Net#80]
I've CVPixelBufferBGRA32LuminanceSource and I'd like to extract my row image from that. How can I do that? Thanks in advance.

**Comment by micjahn** [comment]
The class CVPixelBufferBGRA32LuminanceSource is part of the project [ZXing.Net.Mobile](https://github.com/Redth/ZXing.Net.Mobile). But as far as I understand the source code you can't get the raw image data from that luminance source. The image is converted to grayscale on the fly. The original data isn't available after construction of the object.

**Comment by ysmoradi** [comment]
Thanks for your answer.
If the image is grayscale, it's far better for me. How can I extract that grayscale image anyway? (I submitted my issue there first, but no one answered me)
https://github.com/Redth/ZXing.Net.Mobile/issues/672

**Comment by ysmoradi** [comment]
No matter where is the source code of my LuminanceSource, at the end of story, it's passed to decode method of barcode scanner class which is located in this repository. How do you extract barcode from that source?

**Comment by micjahn** [comment]
If you have access to the LuminanceSource instance you can get the grayscale values from the Matrix property.
The luminance values are later converted to a b/w image via a binarizer. The barcode reader looks for the specific patterns of the barcodes types inside the binarized data.

**Comment by ysmoradi** [comment]
Could you please provide me any sample source code? Thanks for your information (: 👍

**Comment by micjahn** [comment]
I looked trough the code of ZXingScannerView and the OutputRecorder class of the ZXing.Net.Mobile project. As far as I can tell there is no chance to get the LuminanceSource instance. I think you can't grab the raw image. But I'm not very familar with the sources. Perhaps anyone else knows a way.

**Comment by ysmoradi** [comment]
Yeah! They've done a lot of things to make their code impossible to extend!
But I've found a way to get a reference to that LuminanceSource instance.
The thing I'm not aware of that, is how can I extract image from that source?

**Comment by ysmoradi** [comment]
This's my code:

```csharp

public class ScannerViewRenderer : ZXingScannerViewRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<ZXing.Net.Mobile.Forms.ZXingScannerView> e)
        {
            base.OnElementChanged(e);

            if (Element.IsScanning)
            {
                OutputRecorder outputRecorder = (OutputRecorder)Control.GetType().GetField("outputRecorder", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(Control);
                FieldInfo handleImageField = outputRecorder.GetType().GetField("HandleImage", BindingFlags.Instance | BindingFlags.NonPublic);
                Func<LuminanceSource, bool> originalHandleSource = (Func<LuminanceSource, bool>)handleImageField.GetValue(outputRecorder);
                Func<LuminanceSource, bool> newHandleSource = (source) =>
                {
                    bool hadResult = originalHandleSource(source);

                    if (hadResult == false)
                    {
                        ((FormsScannerView)Element).CheckRawImageIfInternalScannerImplementationFoundNothing?.Invoke(File.ReadAllBytes(Path.Combine(NSBundle.MainBundle.BundlePath, "1.png")));
                    }

                    return hadResult;
                };

                handleImageField.SetValue(outputRecorder, newHandleSource);
            }
        }
    }

```

**Comment by micjahn** [comment]
The following should work. Not sure, I didn't compile and test it.

```
                Func<LuminanceSource, bool> newHandleSource = (source) =>
                {
                    var rawGrayscaleImageBytes = source.Matrix;
                    bool hadResult = originalHandleSource(source);

                    if (hadResult == false)
                    {
                        ((FormsScannerView)Element).CheckRawImageIfInternalScannerImplementationFoundNothing?.Invoke(File.ReadAllBytes(Path.Combine(NSBundle.MainBundle.BundlePath, "1.png")));
                    }

                    return hadResult;
                };
```

**Comment by ysmoradi** [comment]
Sorry, that was test code. It works, but it's not what I'm looking for. I've read that code with my wishes! See the code again

**Comment by ysmoradi** [comment]
Yeah, I've seen that matrix property. And it looks good. But what's stored in that byte[] ? I tried to save that in a file, but I wasn't able to see something meaningful

**Comment by micjahn** [comment]
That are the raw luminance values (grayscale) without any format informations. Every byte is a single pixel.

**Comment by ysmoradi** [comment]
Now I think I understand the conceptual side of the story and I'm thankful about that. As I'm not a image processing pro, I've no idea that even my question is right or night. Anyway, could you please provide me some snippet code to save that data in a png file for example? I think my OCR library needs complete image with format information.

On my side, I try to make OCR work with existing data, but any help is come in handy here :-)

**Comment by ysmoradi** [comment]
Finally! I managed to extract image from that array

```
byte[] grayscale_image = source.Matrix;
                using (System.Drawing.Bitmap currentImageBitmap = new System.Drawing.Bitmap(source.Width, source.Height, System.Drawing.Imaging.PixelFormat.Format8bppIndexed))
                {
                    System.Drawing.Imaging.BitmapData currentImageBitmapData = currentImageBitmap.LockBits(new System.Drawing.Rectangle(0, 0, currentImageBitmap.Width, currentImageBitmap.Height),
                                     System.Drawing.Imaging.ImageLockMode.WriteOnly, currentImageBitmap.PixelFormat);

                    System.Runtime.InteropServices.Marshal.Copy(grayscale_image, 0, currentImageBitmapData.Scan0, grayscale_image.Length);

                    currentImageBitmap.UnlockBits(currentImageBitmapData);
                }

```
But images are very ugly! There are some options at MobileBarcodeScanningOptions. How can we set those options to get less affected image?

**Comment by gregt1234** [comment]
I'm looking to capture the image that is processed by ZXing on iOS so that i can run additional processing on it. Seems like you have been able to achieve this ? I'm not very familiar with the ZXing library yet, can you share a little bit more on the overall solution ?
