### ISSUE TITLE
Problem with "Code 39" barcodes

### ISSUE THREAD

**Issue by vebaspect** [micjahn/ZXing.Net#82]
_ZXing.Net_ does not recognize the following _Code 39_ barcodes:

![code-39_dka455773](https://user-images.githubusercontent.com/7981915/36467847-0008271c-16e1-11e8-9b53-35b46f37c1b3.png)
![code-39_rtpl00335062](https://user-images.githubusercontent.com/7981915/36467850-01a08fe2-16e1-11e8-85c2-843b61082c64.png)

_ZXing Decoder Online_ recognizes them correctly.

**Comment by micjahn** [comment]
I tested your sample images with the current version and it works without problems. ZXing.Net gives the
same results like the online decoder.
