### ISSUE TITLE
Problem with "Code 39" barcodes 

### ISSUE THREAD

**Issue by rchmielorz** [micjahn/ZXing.Net#83]
ZXing.Net does not recognize Code 39 barcodes in such invoice:
![example](https://user-images.githubusercontent.com/18697092/37141529-9d6c36d0-22b5-11e8-9acf-3e3fd7d1096e.png)

ZXing Decoder Online recognizes them correctly.

**Comment by micjahn** [comment]
WinFormsDemo successfully decodes the barcode. You should set the TryHarder option to true.

**Comment by rchmielorz** [comment]
Thank you, it really helped.
