### ISSUE TITLE
[Question] README for building the project

### ISSUE THREAD

**Issue by ronneke1996** [micjahn/ZXing.Net#86]
Hello, 

I'm trying to build to project, but I'm not sure if I'm doing the right things. I want the ZXing.unity.dll to build for me.

I'm using VS2017 and opened the vs2017.sln. After that I clicked on build > Build ZXing.NET. This first time I tried that it asked for a private key, so I change the dummy-private key to private and after that I only have 2 builds:
- netstandard
- netstandard2.0
These build are in the Source\lib folder.

Am I doing something wrong with building or can't I build the unity dll in VS2017?

Maybe writing a small README for building the project would help.

**Comment by ronneke1996** [comment]
Alright, I was able to build the project with VS2015 after downloading that.

**Comment by micjahn** [comment]
I wrote a little wiki article:
https://github.com/micjahn/ZXing.Net/wiki/How-to-build
