### ISSUE TITLE
[Question] License model

### ISSUE THREAD

**Issue by FireDragonGameStudio** [micjahn/ZXing.Net#87]
Hy, what kind of licensing model are you using? Is it GPL, MIT or something else? Is it ok to use this library for commercial projects?

Best regards :)

**Comment by micjahn** [comment]
Apache 2.0, look at 
https://github.com/micjahn/ZXing.Net/blob/master/COPYING

**Comment by micjahn** [comment]
and yes, you can use it in commercial projects. And of course I would be very happy if you contribute to this project or make a donation.
