### ISSUE TITLE
How to calculate character limit in 8-bit encode mode

### ISSUE THREAD

**Issue by ianchiu28** [micjahn/ZXing.Net#88]
Hi Sir,

I can't figure it out how to calculate character limit in 8-bit encode mode.
Here is my code:
```
string text = "龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘12"; // 40 Chinese words + 2 numbers
Bitmap bmpQRCode = null;

QrCodeEncodingOptions options = new QrCodeEncodingOptions();
options.CharacterSet = "UTF-8";
options.QrVersion = 7;
options.ErrorCorrection = ErrorCorrectionLevel.M;
options.Margin = 0;
options.Width = 45;
options.Height = 45;

BarcodeWriter writer = new BarcodeWriter();
writer.Format = BarcodeFormat.QR_CODE;
writer.Options = options;

bmpQRCode = writer.Write(text);
```

My input is a string with 40 Chinese words + 2 numbers.
Then I use [UTF8 encoder online](https://www.browserling.com/tools/utf8-encode) to encode and I get 122 bytes.

> \xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\x31\x32

According to this [web](http://www.qrcode.com/en/about/version.html), we know that QR Code can encode 122 bytes in version 7 and ECL M.
But I got `ZXing.WriterException: Data too big for requested version`.
If I remove the last number.
`string text = "龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘龘1";`
> \xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\xe9\xbe\x98\x31

Then it works well.
Is something that I miss?

**Comment by micjahn** [comment]
If you use another character encoding than ISO-8859-1 zxing automatically adds an ECI segment.
If you disable ECI than your content will fit:
```
         options.DisableECI = true;
```

**Comment by ianchiu28** [comment]
Thank you very much for your help!
