### ISSUE TITLE
Some questions when I using Shift_JIS and Mode.Byte to generate a QR Code.

### ISSUE THREAD

**Issue by ianchiu28** [micjahn/ZXing.Net#89]
Hi Sir,

I have some questions when I using Shift_JIS and Mode.Byte to generate a QR Code.
Here is my code:

```
string text = "いきちにひみりイキシチニヒミういきちにひみりイキシチニ https://zh.wikipedia.org/wiki/Shift_JIS"; // 27 Japanese words + 40 alphanumeric words
Bitmap bmpQRCode = null;

QrCodeEncodingOptions options = new QrCodeEncodingOptions();
options.CharacterSet = "Shift_JIS";
options.QrVersion = 7;
options.ErrorCorrection = ErrorCorrectionLevel.M;
options.DisableECI = true;
options.Margin = 0;
options.Width = 45;
options.Height = 45;

BarcodeWriter writer = new BarcodeWriter();
writer.Format = BarcodeFormat.QR_CODE;
writer.Options = options;

bmpQRCode = writer.Write(text);
```
My input is a string with 27 Japanese words + 40 alphanumeric words
And it will use Mode.BYTE as its encode mode.

But I get the `KeyNotFoundException` when I use "Shift_JIS" and Mode.BYTE
Does it mean that I can't use Shift_JIS and Mode.BYTE to generate QR Code?

**Comment by micjahn** [comment]
Sorry, no workaround. You have to wait for the next release which fixes it.

**Comment by micjahn** [comment]
Not true, little mistake. You can try "SJIS" instead of "Shift_JIS

**Comment by ianchiu28** [comment]
Thank you very much for your help
It work perfectly after I tried.
