### ISSUE TITLE
Unity (Android) Implementation

### ISSUE THREAD

**Issue by nkarampi** [micjahn/ZXing.Net#90]
Hello,
I am having a strange issue. I want to parse my result when the Result is a QR_CODE. 
I am parsing it using ResultParser from Client.Result.
Everything is working fine in Unity Editor but when I run on Android I get this:

``System.TypeInitializationException: An exception was thrown by the type initializer for ZXing.Client.Result.ResultParser ---> System.TypeInitializationException: An exception was thrown by the type initializer for ZXing.Client.Result.EmailDoCoMoResultParser ---> System.ArgumentOutOfRangeException: Argument is out of range.
 ``
``
 : Parameter name: options
 :   at System.Text.RegularExpressions.Regex.validate_options (RegexOptions options) [0x00000] in <filename unknown>:0 
 :   at System.Text.RegularExpressions.Regex..ctor (System.String pattern, RegexOptions options) [0x00000] in <filename unknown>:0 
 :   at ZXing.Client.Result.EmailDoCoMoResultParser..cctor () [0x00000] in <filename unknown>:0 
 :   --- End of inner exception stack trace ---
 :   at ZXing.Client.Result.ResultParser..cctor () [0x00000] in <filename unknown>:0 
 :   --- End of inner exception stack trace ---
 :   at BarcodeScanner.Parser.ZXingParser.Decode (UnityEngine.Color32[] colors, Int32 width, Int32 height) [0x00000] in <filename unknown>:0 
  ``

**Comment by nkarampi** [comment]
I found the solution. It wasn't an issue from the plugin.

The solution for anyone having the same problem is: 
Change API Compatibility Level from .NET 2.0 Subset to .NET 2.0 in Player Settings

**Comment by micjahn** [comment]
Hm, I think I shouldn't use the option RegexOptions.Compiled. I think it isn't supported by .Net 2.0 subset.
