### ISSUE TITLE
stride argument of WriteableBitmap.WritePixels()

### ISSUE THREAD

**Issue by kzmi** [micjahn/ZXing.Net#96]
In WriteableBitmapRenderer.Presentation.cs, WriteableBitmap.WritePixels() takes bmp.BackBufferStride as "stride" argument.

```c#
bmp.WritePixels(new Int32Rect(0, 0, width, height), pixels, bmp.BackBufferStride, 0);
```

But I'm wondering that the "stride" argument should be a stride of "source" buffer, "width * sizeof(int)" in this case.

```c#
bmp.WritePixels(new Int32Rect(0, 0, width, height), pixels, width * sizeof(int), 0);
```

I have checked the souece of .NET Framework 4.7.
WritePixels() calls WritePixelsImpl() internally, and the "stride" value is passed as "sourceBufferStride" argument of WritePixelsImpl().

**Comment by micjahn** [comment]
Thanks for reporting it. I fixed it but I think it doesn't have any effect as long as int has a size of 4 and BGRA32 too.
