### ISSUE TITLE
Error compiling Unity Project for Hololens

### ISSUE THREAD

**Issue by RaulLlanoF** [micjahn/ZXing.Net#97]
Hello im trying to add the funcionality of reading QR codes to my app so I downloaded the last repository version and take the zxing.unity dll and the BarCodeCam.cs, added it to my project and it works really good (in the editor) but when i trying to compile the project i get this errors 

![errorqrscanner](https://user-images.githubusercontent.com/23524863/38357826-f1f81baa-38c3-11e8-8627-4378658be1a7.PNG)

Any idea? 
thanks in advance!

**Comment by micjahn** [comment]
I'm not sure but I think you have to switch to another .net framework target. As far as I know there is only a subset target active by default. Using the full api set of the .net framework should fix it.
Perhaps it would be a better solution if you can get rid of the Thread object.
